### PR TITLE
help: link base and overlay terrains in terrain help pages (#9456)

### LINKED ISSUE #9456: Terrain Description doesn't show overlay help_topic_text
### Game and System Information

The Battle for Wesnoth version 1.19.4+dev (f79e8b444cc-Modified) x86_64

Libraries
=========

Boost:             1.75
Lua:               5.4.6
OpenSSL/libcrypto: 3.0.0h-dev (runtime 3.0.0h-dev)
libcurl:           8.0.1 (runtime 8.0.1)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.50.4 (runtime 1.50.4)
SDL:               2.30.8 (runtime 2.30.8)
SDL_image:         2.8.2 (runtime 2.8.2)
SDL_mixer:         2.8.0 (runtime 2.8.0)

Current video settings
======================

SDL video drivers:        [x11] wayland KMSDRM offscreen dummy evdev
Window size:              2234x1453
Game canvas size:         1117x726
Final render target size: 2234x1453
Screen refresh rate:      60
Screen dpi:               162.56x161.36
Renderer:                 opengl (hw)
Maximum texture size:     32768x32768
VSync:                    on

Installed add-ons
=================

No add-ons installed.

### Description of the bug

Checking the terrain description of a hex on the map does not display the `help_topic_text` if there is a terrain overlay.  For base layer, this is a minor bug bug because there are likely other hexes with that base terrain.  But there is never an overlay terrain floating over nothing, so "Terrain Description" never shows that text.  It is in there if you go looking for it, but you'll never see it naturally.
Terrain_help_issue-bridge
(I know the UI is getting a lot of work, the text getting cut off is probably just growing pains.)

### Steps to reproduce the behavior

Start a scenario, check terrain description of something with an overlay, like a bridge over water.  Then navigate around the topic tree to find the bridge by itself.

### Expected behavior

Either show all available `help_topic_text` or link to the standalone terrains, like how the basic terrains are linked to.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #9456 by linking the help pages for Base and Overlay terrain for composite terrains.

Screenshot from 2025-02-23 16-20-28

### CODE REVIEW

**Comment by babaissarkar** [comment]
FYI @doofus-01

File: src/gui/dialogs/help_browser.cpp [hunk 1]
```diff
@@ -17,20 +17,15 @@
...
-#include "gui/widgets/settings.hpp"
-#include "gui/widgets/text_box.hpp"
 #include "gui/widgets/toggle_button.hpp"
 #include "gui/widgets/tree_view.hpp"
 #include "gui/widgets/tree_view_node.hpp"
 #include "gui/widgets/window.hpp"
-#include "log.hpp"
 #include "video.hpp"
 
 #ifdef GUI2_EXPERIMENTAL_LISTBOX
```
Comment (Vultraz) [inline src/gui/dialogs/help_browser.cpp:31]: Since you're cleaning up includes, get rid of this conditional as well. `GUI2_EXPERIMENTAL_LISTBOX` is long dead.

File: src/help/help_topic_generators.cpp [hunk 2]
```diff
@@ -189,6 +196,20 @@ std::string terrain_topic_generator::operator()() const {
...
+		ss << markup::make_link(base_t.editor_name(), terrain_prefix + base_t.id());
+		ss << ", ";
+		ss << "Overlay terrain: ";
+		const auto& overlay = t_translation::terrain_code(t_translation::NO_LAYER, type_.number().overlay);
+		const auto& overlay_t = tdata->get_terrain_info(overlay);
+		ss << markup::make_link(overlay_t.editor_name(), (overlay_t.hide_help() ? "." : "") + terrain_prefix + overlay_t.id());
+		ss << "\n";
+	}
+
+
```
Comment (Vultraz) [inline src/help/help_topic_generators.cpp:212]: Excess space.

Comment (babaissarkar) [reply src/help/help_topic_generators.cpp]: removed one linebreak.

File: src/gui/dialogs/help_browser.cpp (hunk 1 above)
Comment (babaissarkar) [reply src/gui/dialogs/help_browser.cpp]: Removed.

File: src/help/help_topic_generators.cpp [hunk 3]
```diff
@@ -189,6 +196,20 @@ std::string terrain_topic_generator::operator()() const {
 		return ss.str();
 	}
 
+	if (type_.is_combined()) {
+		ss << "Base terrain: ";
+		const auto& base = t_translation::terrain_code(type_.number().base, t_translation::NO_LAYER);
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/help/help_topic_generators.cpp]: Got rid of the refs and removed one local variable. Not using the brace initializer because somebody might complain it's unreadable. :(

**Review by Vultraz — APPROVED** [review]
