### PR TITLE
Editor: Move scenario components when resizing scenario's map

### LINKED ISSUE #10520: Units and items are not moved when resizing the map.
### Game and System Information

- **Version:1.18.3 portable version but irrelevant
- **OS:Windows 11

### Description of the bug

When you resize the map in the scenario editor, the terrain coordinates are shifted but not the item and unit ones.

### Steps to reproduce the behavior

1. Open the editor
2. New Scenario
3. Place an item and an unit
4. Resize in a way that change the coordinates of the terrains
5. Units and items have move wrt the terrains

Image
Image

### Expected behavior

Unit are not shifted wrt the terrain, their coordinates are modified instead

### Additional context

If there is an event generator in the 1.19 editor, this should also apply to events.

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #10520

**TODO**
- [x] Move unit (undoable)
- [x] avoid unit suddenly showing idle animation after move
- [x] Move items
- [x] Move labels (undoable)
- [x] make item moving undoable (needs a new editor action)
- [x] move Time Areas

**NOTE**
Due to the way map coordinates work in hex grid, visual adjacency after resizing is not guaranteed.

Before:
Screenshot from 2025-09-20 21-44-32
After resize (add 1 to width):
Screenshot from 2025-09-20 21-44-40

### CODE REVIEW

**Comment by rodolphecombe** [comment]
I assume that if you resize by a multiple of 2 adjacency is preserved

Edit: is this not smth that could be solved?

**Comment by gfgtdf** [comment]
> Due to the way map coordinates work in hex grid, visual adjacency after resizing is not guaranteed.

when resizing a map like that, does it only mess up the units or also the map itself? Like if there was for example a hill tile at the position of the dwarf would the hill also be not-adjacent to the water tile?

**Comment by gfgtdf** [comment]
also, i'd expect this implementation to not work with editor undoing since its not part of the editor action.

**Comment by babaissarkar** [comment]
> also, i'd expect this implementation to not work with editor undoing since its not part of the editor action.

It does, I used unit replace action.

**Comment by babaissarkar** [comment]
> > Due to the way map coordinates work in hex grid, visual adjacency after resizing is not guaranteed.
> 
> when resizing a map like that, does it only mess up the units or also the map itself? Like if there was for example a hill tile at the position of the dwarf would the hill also be not-adjacent to the water tile?

It may, in some cases, but the effect for terrain isn't very obvious. Notice the cobbles below.

Screenshot from 2025-09-21 06-31-20
Screenshot from 2025-09-21 06-31-12

**Comment by gfgtdf** [comment]
> It may, in some cases, but the effect for terrain isn't very obvious. Notice the cobbles below.

i wonder whether we shoudl just fix his too, currenly itjust adds a fixed value to the coodinates, like if we had before
```
/A \__
\__/B \
/C \__/
\__/D \
   \__/
```
And add 1 column to the left we get
```
/  \__/B \
\__/A \__/
/  \__/D \
\__/C \__/
   \__/
```
which messes up the like you descirbed above, alternativley we could for example just automaticially add one to the height to make it preserve the map, so that it would become
```
/  \__/  \
\__/A \__/
/  \__/B \
\__/C \__/
/  \__/D \
\__/  \__/
   \__/
```

imo this is more closeley to what one would expect, i don't really see usecases for the current behviour (this is unrelated to unitstho)

File: src/editor/map/context_manager.cpp [hunk 1]
```diff
@@ -628,8 +634,48 @@ void context_manager::resize_map_dialog()
...
+		for (const auto& u : units) {
+			map_location l{u.get_location().x - x_offset, u.get_location().y - y_offset};
+			chain->append_action(std::make_unique<editor_action_unit_replace>(u.get_location(), l));
+		}
+
+		// TODO make this undoable
+		chain->append_action(std::make_unique<editor_action_item_move_all>(x_offset, y_offset));
+
+		map_labels& labels = get_map_context().get_labels();
+		get_map_context().map().for_each_loc([&](const map_location& loc) {
```
Comment (babaissarkar) [inline src/editor/map/context_manager.cpp:650]: @Vultraz Need help trying to simplify this block. It works but adds way too many actions to the chain.

**Comment by gfgtdf** [comment]
are [time_area]s also moved properly?

**Comment by gfgtdf** [comment]
also: does it still work when units/labels etc are in a location that would be removed by the resizing operation?

**Comment by babaissarkar** [comment]
@gfgtdf I'll check and let you know. I'm fairly busy so may take a while.

**Comment by babaissarkar** [comment]
> also: does it still work when units/labels etc are in a location that would be removed by the resizing operation?

I don't think that should cause an issue as everything is moved inwards usually AFAIK. If you have a specific test case I can try that.

Also, no it doesn’t support time areas it seems.

**Comment by babaissarkar** [comment]
> are [time_area]s also moved properly?

Implemented in https://github.com/wesnoth/wesnoth/pull/10568/commits/5ea86550bce413fd1b072fc74bde0a2ad4661d3a.

**Comment by gfgtdf** [comment]
> I don't think that should cause an issue as everything is moved inwards usually AFAIK. If you have a specific test case I can try that.


I'd think just use the resizing dialog to shrink the map (new size smaller than old size)

**Comment by babaissarkar** [comment]
> > I don't think that should cause an issue as everything is moved inwards usually AFAIK. If you have a specific test case I can try that.
> 
> I'd think just use the resizing dialog to shrink the map (new size smaller than old size)

What would be the expected correct behavior?

**Comment by gfgtdf** [comment]
> What would be the expected correct behavior?

Hmm not sure, i guess either those elements vanishing or them being cramped at the border of the map.

But more importantly, that the code doesnt run into assertions or other bugs later because elements are out of map.
Also undoing bringing these elements back correctly.

**Comment by rodolphecombe** [comment]
> Also undoing bringing these elements back correctly.

I would not expect that to work TBH, so, IMHO, it not working should not prevent the PR from being merged.

**Comment by babaissarkar** [comment]
I understand that this needs further refinements, but since it serves the basic purpose of the original issue, I'll merge this and further refinements can be done in future PRs.
