### PR TITLE
Fix duplicate mod ids breaking mod selection

### LINKED ISSUE #6780: Multiplayer Modification Checklist Bug
### Game and System Information

- **Version:** 1.14.17 & 1.16.3
- **Downloaded from:** Steam
- **Build info:** No custom build. Downloaded through Steam, swapped between beta 1.14.x (stable) and current 1.16.3 in Steam Betas option in game properties. Since info and log files are long I uploaded both below.
- **OS:** Windows 10 21H2
[1.14.17 Build Info.txt](https://github.com/wesnoth/wesnoth/files/8943258/1.14.17.Build.Info.txt)
[1.14.17 Log.txt](https://github.com/wesnoth/wesnoth/files/8943259/1.14.17.Log.txt)
[1.16.3 Build Info.txt](https://github.com/wesnoth/wesnoth/files/8943260/1.16.3.Build.Info.txt)
[1.16.3 Log.txt](https://github.com/wesnoth/wesnoth/files/8943263/1.16.3.Log.txt)

### Description of the bug

When checking or unchecking mods in the multiplayer window the game freezes or hangs for a second and does one of the following:
1. Checks/Unchecks the selected mod only. (On rare occasion it's smooth with no hanging).
2. Checks/Unchecks up to 5+ other mods randomly, does nothing to the mod selected for some reason.
3. Checks/Unchecks the mod selected and another two spaces up or down.
4. When "3." occurs and I try to checking the selected mod again after unchecking both, the same mod two spaces up checks first, when clicking again the selected mod checks. Seems to happen in a weird sequence.

### Steps to reproduce the behavior

1. Download addons for 1.14.17 and 1.16.3, ideally the same addons updated for both versions.
2. Open multiplayer, select any map.
3. Check/Uncheck mods.

### Expected behavior

Checking and unchecking mods only does so for the selected mod and doesn't automatically do so for random mods in the list.

### Additional context

It's possible I messed something up having multiple installs of different versions of Wesnoth on Steam and two installed locally on two different drives causing unexpected bugs.

### PR DESCRIPTION
**Pull request by Pentarctagon**
Error string left as untranslatable for now due to string freeze.

Fixes #6780

### CODE REVIEW

File: src/game_initialization/create_engine.cpp [hunk 1]
```diff
@@ -791,11 +793,15 @@ void create_engine::init_extras(const MP_EXTRA extra_type)
...
 			else {
-				//TODO: use a more visible error message.
 				ERR_CF << "found " << extra_name << " with id=" << extra["id"] << " twice";
+				duplicates.emplace_back(extra["id"].str());
 			}
 		}
 	}
+
+	if(duplicates.size() > 0) {
+		gui2::show_error_message("Found multiple modifications with the same id:\n"+utils::join(duplicates, "\n"));
```
Comment (stevecotton) [inline src/game_initialization/create_engine.cpp:803]: I think this should be translatable, even in 1.18.

There's two ways of looking at the string freeze, either measure it by what's in the PO files, or by the situations that cause English text to be shown to users. IMO the situation is serious enough to justify showing the string to the user, but if we're showing the string to the user anyway then there's no reason not to make it translatable.

Comment (ProditorMagnus) [reply src/game_initialization/create_engine.cpp:803]: It is serious issue without this PR, but just debug info afterwards.

Comment (stevecotton) [reply src/game_initialization/create_engine.cpp:803]: That's good, but then it doesn't justify a GUI error dialog.

Comment (Pentarctagon) [reply src/game_initialization/create_engine.cpp]: Removed then.

Comment (soliton-) [reply src/game_initialization/create_engine.cpp]: How does this PR accomplish making duplicate IDs not an error?

Comment (ProditorMagnus) [reply src/game_initialization/create_engine.cpp]: I understand that after this change, when toggling duplicate option then all options with that id will be toggled, instead of random modification with different id.

Comment (soliton-) [reply src/game_initialization/create_engine.cpp]: And how is that not an error?

Comment (ProditorMagnus) [reply src/game_initialization/create_engine.cpp]: Maybe is maybe not, needs testing when next version is uploaded.

Comment (stevecotton) [reply src/game_initialization/create_engine.cpp]: In that case I think an error dialog is the right way to go, and it should also identify which add-ons are providing those modifications.

Comment (Pentarctagon) [reply src/game_initialization/create_engine.cpp]: It would enable whichever modification with that id it happens to find first. The thing fixed is that it doesn't make the UI behave in weird ways anymore.

Comment (stevecotton) [reply src/game_initialization/create_engine.cpp]: That sounds like a recipe for OOS :(

Comment (Pentarctagon) [reply src/game_initialization/create_engine.cpp]: The only way to possibly avoid the OOS risk would be to not display any of the modifications with duplicate IDs, making them unselectable and unusable.
