### PR TITLE
Move command line processing before logger initialization

### LINKED ISSUE #9111: Assert at start when logging is enabled
### Game and System Information

- **Version:**1.19.1dev+
- **OS:**windows10

### Description of the bug

when i try to start game with https://github.com/wesnoth/wesnoth/commit/4f40c9deb5453e7cc99da4495251f60cb30436a0 commit it return "Attempted to access userdata location before userdata initialization!" window and i can't fix that without replace assert(!user_data_dir.empty() && "Attempted to access userdata location before userdata initialization!");by old code in filesystem.cpp line789.

### Steps to reproduce the behavior

try to start game.

Read error windows

Same if a change part name of Wesnoth1.19 userdata folder, it's same issue too with sippress of preference file.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pentarctagon**
Log files goes in the userdata folder so they therefore need the userdata to be initialized before that.

Fixes #9111

---

This does at least fix #9111, though obviously more is needed before it can be merged.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
when ubuntu check will be fixed, it will fine.

**Comment by soliton-** [comment]
Looks like some fallout from the unchecked value calls introduced in #9107.

**Comment by Vultraz** [comment]
Should these errors be silenced, or are they genuine issues?

**Comment by Pentarctagon** [comment]
Looks like the issue it's running into here (at least for the schema validation failures) is that `game_config::path` is getting set to `/usr/local/share/wesnoth` rather than my actual git repository location, so it tries to schema validate `/usr/local/share/wesnoth/data/schema/game_config.cfg` which doesn't exist, so it returns `std::nullopt`.

**Comment by Pentarctagon** [comment]
I think this is basically done, though I'm not sure what exception handling needs to be done around the command line option processing now.

File: src/commandline_options.hpp [hunk 1]
```diff
@@ -239,6 +239,18 @@ class commandline_options
...
 	/** True if --with-replay was given on the command line. Shows replay of the loaded file. */
 	bool with_replay;
+	/** True if --wnoconsole was given on the command line. Controls whether to write to a command prompt on Windows. */
+	bool no_console;
+	/** True if --no-log-sanitize was given on the command line. Prevents removal of OS user from file paths in log files. */
+	bool no_log_sanitize;
+	/** True if --log-to-file was given on the command line. Results in logs not being redirected to a log file. */
+	bool log_to_file;
+	/**
+	 * True if --no-log-to-file was given on the command line. Forces output to be written to a log file. Takes priority over any arguments that implicitly prevent logging to file.
```
Comment (Vultraz) [inline src/commandline_options.hpp:249]: Is this comment correct?

Comment (Pentarctagon) [reply src/commandline_options.hpp]: Nope, got it backwards.

File: src/commandline_options.cpp [hunk 2]
```diff
@@ -510,6 +515,14 @@ commandline_options::commandline_options(const std::vector<std::string>& args)
 		windowed = true;
 	if(vm.count("with-replay"))
 		with_replay = true;
+	if(vm.count("wnoconsole"))
```
Comment (CelticMinstrel) [inline src/commandline_options.cpp:518]: I thought this was only supported on Windows?

File: src/commandline_options.hpp [hunk 3]
```diff
@@ -239,6 +239,19 @@ class commandline_options
 	bool windowed;
 	/** True if --with-replay was given on the command line. Shows replay of the loaded file. */
 	bool with_replay;
+	/** True if --wnoconsole was given on the command line. Controls whether to write to a command prompt on Windows. */
```
Comment (CelticMinstrel) [inline src/commandline_options.hpp:242]: I think this should be phrased differently, perhaps more along the lines of "Prevents logs from being written to the console window if Wesnoth is launched from the command prompt on Windows". Not entirely happy with that either, but…

File: src/wesnoth.cpp [hunk 4]
```diff
@@ -267,10 +267,46 @@ static int handle_validate_command(const std::string& file, abstract_validator&
...
+			&& !cmdline_opts.simple_version
+			&& !cmdline_opts.userdata_path
+			&& !cmdline_opts.version
+			&& !cmdline_opts.do_diff
+			&& !cmdline_opts.do_patch
+			&& !cmdline_opts.preprocess
+			&& !cmdline_opts.render_image
+			&& !cmdline_opts.screenshot
+			&& !cmdline_opts.headless_unit_test
+			&& !cmdline_opts.any_validation_option();
```
Comment (CelticMinstrel) [inline src/wesnoth.cpp:307]: This is clearly incorrect. The `--validate-addon` option shouldn't turn it into a CLI program, and I think `--validate-core` probably shouldn't either. These are "validate as you play" options. Only `--validate` and `--validate-schema` are intended for CLI use. (The fifth one, `--use-schema`, is only an auxiliary to `--validate` and meaningless without it.)

**Comment by CelticMinstrel** [comment]
What happens when Boost.ProgramOptions fails to parse the arguments? With command-line parsing occurring before the log and/or console is set up, I have a feeling the errors might be getting swallowed up, especially on Windows.

**Comment by Pentarctagon** [comment]
I'd assume it needs to do `catch(const boost::program_options::error& e)` (and remove that catch block from where it is currently in `main()`, and then just print to `std::cerr` directly.

File: src/commandline_options.cpp (hunk 2 above)
Comment (Pentarctagon) [reply src/commandline_options.cpp:518]: `--wconsole` got removed a while ago in the logging overhaul.

**Comment by CelticMinstrel** [comment]
> I'd assume it needs to do `catch(const boost::program_options::error& e)` (and remove that catch block from where it is currently in `main()`, and then just print to `std::cerr` directly.

That sounds mostly right, but I think that could still get swallowed up on Windows when launching from the command-line – it probably needs to set up console redirection just to print that message.

File: src/commandline_options.cpp (hunk 2 above)
Comment (CelticMinstrel) [reply src/commandline_options.cpp:523]: How does that make sense? Right now, `--wconsole` is redundant if launched from the command line, because it already connects to the console if nothing is specified (if I'm understanding the code correctly). But what if you want to make a shortcut that launches Wesnoth with a console?

**Comment by Pentarctagon** [comment]
> It would also be nice if it could use the SDL message box function if for whatever reason it detects there's no console to write to

That would require SDL to be initialized before logging is available though.

**Comment by CelticMinstrel** [comment]
…why exactly is that an issue?

**Comment by Pentarctagon** [comment]
Then we're back in the same situation if SDL initialization fails.

**Comment by CelticMinstrel** [comment]
Is it even possible for SDL initialization to fail? Assuming that none of the subsystems are initialized (so, no graphics or audio or anything like that).

**Comment by Pentarctagon** [comment]
If graphics aren't initialized, how would it show a message box?

**Comment by Pentarctagon** [comment]
Though apparently https://wiki.libsdl.org/SDL2/SDL_ShowSimpleMessageBox doesn't actually require SDL to be initialized to use.

File: src/commandline_options.cpp (hunk 2 above)
Comment (Pentarctagon) [reply src/commandline_options.cpp:523]: It doesn't need an option for that. It attempts to attach to the parent process for its console and if that fails it creates its own.

**Comment by CelticMinstrel** [comment]
> If graphics aren't initialized, how would it show a message box?

It doesn't use the graphics subsystem though. It uses WinAPI or X11 to spawn an OS-native message box.

**Comment by Pentarctagon** [comment]
Well, I don't think it makes sense for me to try to guess at that or remote troubleshoot someone else testing that, especially given how rare it would likely be for anyone to be running Wesnoth from a terminal on Windows and also have a command line option error occur. So I will leave it to someone on Windows to figure that out, if it's something they thing is overly annoying.

Also 1.19.2 is supposed to be released this weekend, so I intend to merge this later today and then tag 1.19.2.

**Comment by CelticMinstrel** [comment]
> So I will leave it to someone on Windows to figure that out, if it's something they think is overly annoying.

Well, at least it's less annoying than _not getting any feedback at all_, which is what I suspect might happen otherwise. Though it also might not – I'm really not sure. Windows is confusing.
