### PR TITLE
Fix dragging labels in editor (fixes #3302)

### LINKED ISSUE #3302: Moving labels in editor causes back to titlescreen
To move a label, use drag and drop:
move_a_label

### PR DESCRIPTION
**Pull request by seanyeh**
https://github.com/wesnoth/wesnoth/issues/3302

Currently in the scenario editor, dragging a label causes a crash. I rewrote the dragging functionality to be similar to how we do it with units, hope that's ok

### CODE REVIEW

File: src/editor/action/action_label.cpp [hunk 1]
```diff
@@ -88,4 +88,42 @@ void editor_action_label_delete::perform_without_undo(map_context& mc) const
...
 }
 
+IMPLEMENT_ACTION(label_replace)
+
+editor_action* editor_action_label_replace::perform(map_context& mc) const
+{
+	editor_action_ptr undo(new editor_action_label_replace(new_loc_, loc_));
+
+	perform_without_undo(mc);
+	return undo.release();
```
Comment (stevecotton) [inline src/editor/action/action_label.cpp:98]: A task for a separate PR, but this method should be returning the std::unique_ptr instead of returning an owning raw pointer.

File: src/editor/action/action_label.hpp [hunk 2]
```diff
@@ -97,4 +97,27 @@ class editor_action_label_delete : public editor_action_location
...
+
+	/** Inherited from editor_action, implemented by IMPLEMENT_ACTION. */
+	editor_action_label_replace* clone() const;
+
+	editor_action* perform(map_context& mc) const;
+
+	void perform_without_undo(map_context& mc) const;
+
+	/** Inherited from editor_action, implemented by IMPLEMENT_ACTION. */
+	const std::string& get_name() const;
```
Comment (stevecotton) [inline src/editor/action/action_label.hpp:117]: The four const methods can and should all have the `override` keyword too.

File: src/editor/action/action_label.cpp [hunk 3]
```diff
@@ -88,4 +88,42 @@ void editor_action_label_delete::perform_without_undo(map_context& mc) const
...
+{
+	const terrain_label* old_label = mc.get_labels().get_label(loc_);
+
+	// Do nothing if label does not exist in original location
+	if (!old_label) {
+		return;
+	}
+
+	// Move label to new location by creating one in the new location
+	// with the same properties and clearing the old location
```
Comment (stevecotton) [inline src/editor/action/action_label.cpp:111]: This doesn't undo correctly.

* Create labels 'a' and 'b'
* Drag 'a' on top of 'b'
* Try to undo

The result is that 'a' moves back to where it originally was, but 'b' doesn't reappear.

**Review by stevecotton — COMMENTED** [review]
The build failure was just an unrelated build breakage from changes in campaignd that were merged into master.

File: src/editor/action/action_label.cpp (hunk 3 above)
Comment (seanyeh) [reply src/editor/action/action_label.cpp]: Thanks, you're right, this is something I completely overlooked. I was still having some trouble understanding how these editor actions worked, but I think I have a better understanding now. I've changed my approach to be simpler and similar to the original approach, but moving the logic to `drag_end_left` (when the drag is released).

File: src/editor/action/mouse/mouse_action_map_label.cpp [hunk 4]
```diff
@@ -108,6 +90,47 @@ editor_action* mouse_action_map_label::up_right(editor_display& disp, int x, int
...
+		.get_label(clicked_on_);
+
+	// Return nullptr if the dragged label doesn't exist
+	if (!dragged_label) {
+		return nullptr;
+	}
+
+	// Create action chain to:
+	// 1. Delete label in initial hex
+	// 2. Delete label in target hex
```
Comment (stevecotton) [inline src/editor/action/mouse/mouse_action_map_label.cpp:114]: Please say something on this line like "... if it exists, will be a no-op if it doesn't"

**Comment by stevecotton** [comment]
+1, Looks good to me.

I think the editor_action framework should be updated to use std::unique_ptr in place of raw pointers, but that's a separate task.

**Comment by Vultraz** [comment]
@stevecotton if you've confirmed this works can be merged
