### PR TITLE
Fix invalid WFL crashes Wesnoth

### LINKED ISSUE #9249: invalid WFL crashes Wesnoth
### Game and System Information

- **Version:**1.18.0

### Description of the bug

Invalid formula in weapon special crahes Wesnoth, when evaluated.

### Steps to reproduce the behavior

1. Into Lua console:
```
wesnoth.units.to_map({ type = "Elvish Archer",side=1 }, 10, 10)
u = wesnoth.units.get({10,10})
wesnoth.units.add_modification(u, "object",{
  {
    "effect",{
      apply_to="attack",
      range="ranged", {
        "set_specials",{
          mode="append",{
            "damage",{
              id="sample",
              name="sample",
              apply_to="self", {
                "filter_self",{
                  formula="()"
                }
              }
            }
          }
        }
      }
    }
  }
})
```
2. Select the unit
3. Enjoy your OS screen ;D

### Expected behavior

Maybe not crashing?

### Additional context

None

### PR DESCRIPTION
**Pull request by Mahoyomu**
### Goal of the PR
- Resolves #9249.
### How does the PR work?
- By adding try-catch to finish a todo in filter.cpp, it catches formula error when evaluating formula.
### Does it resolve any reported issue?
- #9249
### If not a bug fix, why is this PR needed? What use cases does it solve?
- This is a bug fix. Also, there's a case in formula evaluating that the formula will undoubtly be an empty expression and don't need to call itself again to find out the error, the pr also makes changes on it.

## To do

Adjust possibly missed related method, delete some redundant description.

This PR is Ready for Review.

## How to test
Compile and run, see the test video I might be uploading soon, or see changes in the src. (personally have tested it and it works)

### CODE REVIEW

File: src/formula/formula.cpp [hunk 1]
```diff
@@ -1329,9 +1332,16 @@ expression_ptr parse_expression(const tk::token* i1, const tk::token* i2, functi
 	}
 
 	if(op == nullptr) {
-		if(i1->type == tk::token_type::lparens && (i2-1)->type == tk::token_type::rparens) {
+		// There's a situation when i1+1 equals i2-1 (meanwhile iter length is 2, like `()`)
+		// Resulting in empty expression.
+		if(i1->type == tk::token_type::lparens && (i2 - 1)->type == tk::token_type::rparens) {
+			if(i1 + 1 == i2 - 1) {
+				ERR_WML << "Syntax error: no expression between brackets, reset to empty";
```
Comment (soliton-) [inline src/formula/formula.cpp:1339]: Seems confusing to print syntax error but not treat it like a syntax error.

File: src/units/filter.cpp [hunk 2]
```diff
@@ -666,8 +666,15 @@ void unit_filter_compound::fill(vconfig cfg)
...
-				//TODO: catch syntax error.
-				return wfl::formula(c, new wfl::gamestate_function_symbol_table());
+				try {
+					return wfl::formula(c, new wfl::gamestate_function_symbol_table());
+				} catch(const wfl::formula_error& e) {
+					lg::log_to_chat() << "Formula error while evaluating formula in unit filter, reset to empty: " << e.type << " at "
+									  << e.filename << ':' << e.line << ")\n";
+					ERR_WML << "Formula error while evaluating formula in unit filter, reset to empty: " << e.type << " at "
+							<< e.filename << ':' << e.line << ")";
+					return wfl::formula("", new wfl::gamestate_function_symbol_table());
```
Comment (CelticMinstrel) [inline src/units/filter.cpp:676]: Why does this say "reset to empty"? I get that you're returning an "empty" formula as part of the error, but that doesn't seem like something worth stating in the error message.

(Is returning an empty formula fine, by the way?)

Comment (CelticMinstrel) [reply src/units/filter.cpp:676]: > In my test, weapon special with empty formula seems to be ignored currently, only err msg like "Pango-critical" come out. Besides, if the error is caught here, it has to return a value. Considering the ignoring behavior of empty formula, I can't think of a better value than empty personally.

It's a little tricky since it returns a formula rather than a value, but I think `"null()"` might be appropriate here.

Comment (CelticMinstrel) [reply src/units/filter.cpp:676]: Also, there's no point in adding `new wfl::gamestate_function_symbol_table()` here when the formula is a literal string that doesn't even need that function table. I think the function table argument is optional. If not, I'm pretty sure you can pass `nullptr`.

**Comment by stevecotton** [comment]
I did a rebuilt and confirmed that the tests pass (it was just a timeout from a build being slow).

@soliton- and @CelticMinstrel, is there anything more to do before merging?

**Comment by Pentarctagon** [comment]
@CelticMinstrel any issues with this getting merged?
