### PR TITLE
Prevent wesnoth from crashing after campaign credits

### LINKED ISSUE #7395: Game crash or closes when the game ends
### Game and System Information

The Battle for Wesnoth version 1.17.13 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

Game paths
==========

Data dir:        D:\SteamLibrary\steamapps\common\wesnoth
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.17
User data dir:   C:\Users\USER\Documents\My Games\Wesnoth1.17
Saves dir:       C:\Users\USER\Documents\My Games\Wesnoth1.17\saves
Add-ons dir:     C:\Users\USER\Documents\My Games\Wesnoth1.17\data\add-ons
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.17\cache
Logs dir:        C:\Users\USER\Documents\My Games\Wesnoth1.17\logs

Libraries
=========

Boost:             1.80
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1s (runtime 1.1.1s)
Cairo:             1.17.6 (runtime 1.17.6)
Pango:             1.50.11 (runtime 1.50.11)
SDL:               2.24.1 (runtime 2.24.1)
SDL_image:         2.6.2 (runtime 2.6.2)
SDL_mixer:         2.6.2 (runtime 2.6.2)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers:        [windows] dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Screen refresh rate:      60
Screen dpi:               96.00x96.00
Renderer:                 direct3d (hw)
Maximum texture size:     16384x16384
VSync:                    on

Current audio settings
======================

SDL audio drivers:  [wasapi] directsound
Number of channels: 2
Output rate:        48000 Hz
Sample format:      signed 16 bit little-endian
Sample size:        4096 bytes

Installed add-ons
=================

A_New_Order:                    1.4.1
Advance_Wesnoth_Wars_fork:      1.17.12.2
Akladian_Music:                 1.0.1
An_Orcish_Incursion:            1.0.3
Dead_Bodies:                    1.3.3
Dead_Bodies_terrain:            1.0.2
Eastern_Invasion_Dalas:         2.0.1
Era_of_Magic:                   4.0.0
Era_of_Magic_Resources:         2.0.0
Gui_Debug_Tools:                0.10.2
Legend_of_the_Invincibles_beta: 3.2.7.118gf514925
Non_Fatal_Wounds_Extended:      3.2
Reflection:                     1.2.0
To_Lands_Unknown:               3.7.0
To_Lands_Unknown_Resources_1:   2.1.0
To_Lands_Unknown_Resources_2:   2.0.0
Unitmarker:                     1.0.6
combat-info-theme:              0.0.7

### Description of the bug

Epilogues of:
To Lands Unknown, Secrets of the Ancients > APPCRASH
Under the Burning Suns,The Hammer of Thursagan > Game closes

If I exit pressing ESC, it returns to the menu correctly and this crash can be avoided

imagen

### Steps to reproduce the behavior

- See any epilogue
- Wait to the end (dont push ESC)
- Crash or game closes

### Expected behavior

When the Epilogue ends, the game returns to the menu automatically

### Additional context

This happens on 1.17.12 too, this isn't a new bug
The log file is completely clean, nothing relevant

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #7395

### CODE REVIEW

**Comment by gfgtdf** [comment]
looks good to me

File: src/gui/widgets/window.hpp [hunk 1]
```diff
@@ -221,8 +221,8 @@ class window : public panel, public top_level_drawable
 	/**
 	 * Requests to close the window.
 	 *
-	 * At the moment the request is always honored but that might change in the
-	 * future.
+	 * This request is not always honored, and so callers must account for the window remaining open.
```
Comment (stevecotton) [inline src/gui/widgets/window.hpp:224]: Is it "not always honored" or "not always honored immediately"? As in, is one call always enough to close the window, although it might take time for it to be processed?

Comment (Pentarctagon) [reply src/gui/widgets/window.hpp:224]: Well, the close the campaign credits window does close on its own with this PR applied, so I suppose it's "not always honored immediately".

Comment (Pentarctagon) [reply src/gui/widgets/window.hpp]: Updated.

**Review by stevecotton — APPROVED** [review]
