### PR TITLE
Editor enhancements

### LINKED ISSUE #8445: Loyal Units in Editor Tool
### Game and System Information

- **Version: Windows**
- **Downloaded from: Steam**
- **Build info:**
- **OS:**

### Description of the bug

They didn't work (Polish verion language). You can't click them and they didn't have the gold little thing next to head

### Steps to reproduce the behavior

1. Start Editor
2. Create New Scenario
3. Add a unit
4. Right-click on unit
5. Select 'Loyal' from the menu
6. Observe no change to the unit and right-clicking again indicates no apparent change in the loyal status

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #8910: editor: Save into addon when saving a scenario
### Describe the desired feature

When creating a scenario in the editor it asks for an addon but when then saving the scenario the save dialog starts out at editor/scenarios in userdata and not in the chosen addon.

### LINKED ISSUE #8911: editor: Pick proper dir and filename in Save Map/Scenario As dialog
### Describe the desired feature

1) Enter editor
2) New Scenario
3) Save Scenario As
4) Type in some name and save
5) Save Map As
Now you get the previous scenario filename in the dialog and if you do save you overwrite your scenario.

Similarly you get the map file name if you save as map first.

This is confusing and can lead to data loss if the user is not careful. Even if you change the filename you're saving to the wrong dir.

The save dialog should pick the proper dir to start with and even then it might be good to give an explicit warning if someone saves a map as .cfg or a scenario as .map and/or when they save them in the wrong dir (as much as the editor can tell, so just if the dir is named maps/scenarios). The wrong extension could perhaps even be completely forbidden.

### LINKED ISSUE #9024: Improve or remove file saving on F5 in the editor
### Describe the desired feature

I don't see how it's any useful and it has weird behavior of saving all open scenarios/maps under unexpected paths.

https://github.com/wesnoth/wesnoth/blob/e67a91caf22429c56cd2012e324cd8ee212b5481/src/editor/controller/editor_controller.cpp#L804-L808

https://github.com/wesnoth/wesnoth/blob/e67a91caf22429c56cd2012e324cd8ee212b5481/src/editor/map/context_manager.cpp#L807-L832

### PR DESCRIPTION
**Pull request by babaissarkar**
Contains various enhancements mostly to the Time Schedule Editor that I couldn't manage to add in #8066. It also contains a few other things in the Map Editor itself. There are also changes to the Unit Type Editor that are related to the new features in the Schedule Editor. The File Dialog has also been redesigned.

### Map Editor
* Rename `Load Map` to `Load Map/Scenario` (since it can load both), `Edit Scenario` to `Edit Scenario Settings`, `Save Map` to just `Save`.
* Rearrange menu order
* Add icon for the preferences menu item (used the preexisting settings.png icon)
* Open folder correctly at Add-on's scenario directory instead of `editor/scenarios`. (Resolves #8910)
* Show `Save Scenario As` only for Scenarios
* Use the `settings.png` icon for `Preferences` menu item
* Add functionality to "Loyal" checkbox (Unit tool -> Place unit -> Right click menu) (Resolves #8445)
* Do not allow maps to be saved in scenarios folder or vice versa (Resolves #8911)
* Unit List moved to Units menu from File menu to reduce some pressure from the latter. (2e1c3f25d95fbb9ae642e79eeafcb5988c0f0bfa)
* Status Table menu item disabled since it does nothing. Should be reenabled once the functionality has been added. (See 2e1c3f25d95fbb9ae642e79eeafcb5988c0f0bfa)
* Improve reload functionality in Editor (F5). Reload happens directly from memory and no temp files are needed. Also, the undo/redo stacks will be preserved. (Resolves #9024)

**Map Mode:**
Screenshot from 2024-05-25 17-52-50

**Scenario Mode:**
Screenshot from 2024-05-25 17-53-03

### Time Schedule Editor
* Browse buttons now set wesnoth style paths instead of just pasting the absolute path returned by the file dialog
* Change text boxes from inactive to uneditable.
* Code generation improvements
* Add copyright notice to `tod_new_schedule` (missed in #8066)
* Confirmation messages
* New icons for the preview button (2 sets : preview image and preview sound)
* Preview buttons for image and sound files
Screenshot from 2024-05-24 12-48-36

### Unit Type Editor
The last four entries above :
* Confirmation messages
* New icons for the preview button (2 sets : preview image and preview sound)

### Add-on menu
* Two new items for (1) opening the select add-on dialog, (2) opening the add-on folder
Screenshot from 2024-05-25 17-54-24

The open add-on folder option shows a GUI2 file dialog at the add-on's folder which can be used to open any file. If it is a loadable map/scenario it will be opened in the editor, otherwise the OS's default application for that file will be opened.

### File Dialog
* Redesigned with new icons
* New `Open External` button that opens selected file/folder in the platform's default application (independently of what pressing `Open` would do). This could be used to quickly open a folder or preview the file before actually selecting it.
* Extension checking and filename validation. (See https://github.com/wesnoth/wesnoth/issues/8911#issuecomment-2180708634) (Resolves #8911)

Screenshot from 2024-05-28 11-09-16

### CODE REVIEW

File: src/gui/dialogs/editor/custom_tod.cpp [hunk 1]
```diff
@@ -168,17 +169,52 @@ void custom_tod::select_file(const std::string& default_dir)
...
 		} else if(data.first == "sound") {
-			times_[current_tod_].sounds = dn;
+			times_[current_tod_].sounds = to_wesnoth_path(dn, "sounds");
 		}
 	}
 
 	update_selected_tod_info();
 }
 
+std::string custom_tod::to_wesnoth_path(std::string abs_path, std::string asset_type, bool copy_if_outside)
```
Comment (soliton-) [inline src/gui/dialogs/editor/custom_tod.cpp:183]: This seems like a more generic function that shouldn't be in a dialog. If the name contains something about addons/editor and assets and the else case throws an exception or returns an invalid optional or something instead, I think it could go into filesystem.

In the else case it's odd that it asks the user to copy and then possibly doesn't do it anyway regardless what the user decided.

File: src/gui/dialogs/editor/custom_tod.cpp [hunk 2]
```diff
@@ -167,39 +167,45 @@ void custom_tod::select_file(const std::string& default_dir)
...
+
+	if (!addon_id_.empty()) {
+		addon_asset_dir = filesystem::get_current_editor_dir(addon_id_) + "/" + asset_type;
+		is_in_addon_dir = (abs_path.find(addon_asset_dir) != std::string::npos);
+	}
+
+	if (is_in_core_dir) {
+		rel_path = abs_path.erase(0, core_asset_dir.size()+1);
+	} else if (is_in_addon_dir) {
+		rel_path = abs_path.erase(0, addon_asset_dir.size()+1);
```
Comment (CelticMinstrel) [inline src/gui/dialogs/editor/custom_tod.cpp:200]: …doesn't this need to add a prefix to the path as well?

File: src/gui/dialogs/editor/custom_tod.cpp [hunk 3]
```diff
@@ -197,12 +199,19 @@ std::string custom_tod::to_wesnoth_path(std::string abs_path, std::string asset_
 	} else if (is_in_addon_dir) {
 		rel_path = abs_path.erase(0, addon_asset_dir.size()+1);
 	} else {
-		// image outside wesnoth's directories
-		// copy to addon's images directory
+		// file outside, ask the user if they want to copy
+		const std::string& message
+			= _("File outside Wesnoth's data dirs. Do you wish to copy it in your add-on?");
```
Comment (CelticMinstrel) [inline src/gui/dialogs/editor/custom_tod.cpp:204]: "into your add-on"

Maybe also "This file is outside".

**Comment by CelticMinstrel** [comment]
> * Rename `Load Game` to `Load Game/Scenario` (since it can load both)

I'm not sure how you got this wrong, but it's Map, not Game.

**Comment by babaissarkar** [comment]
What do you mean by "prefix"? It converts an absolute path to something
like "misc/some-image.png" (the same as what is supported by image widget's
label)

File: src/gui/dialogs/editor/custom_tod.cpp (hunk 1 above)
Comment (CelticMinstrel) [reply src/gui/dialogs/editor/custom_tod.cpp:183]: > In the else case it's odd that it asks the user to copy and then possibly doesn't do it anyway regardless what the user decided.

What do you mean…? As far as I can tell that's only the case if the addon ID is empty, which shouldn't happen if I understand correctly.

Side note: This is minor, but it might be nice to allow the user to specify a subdirectory to copy it to. For example, if they type in "scenery/" then it will be copied to "$addondir/images/scenery/".

**Comment by CelticMinstrel** [comment]
Hmm, I think I'm getting confused between asset paths and WML paths actually. Never mind.

File: src/gui/dialogs/editor/custom_tod.cpp (hunk 1 above)
Comment (soliton-) [reply src/gui/dialogs/editor/custom_tod.cpp:183]: If either `copy_if_outside` is false or `addon_id_` is empty the user is asked and then nothing is done.

Comment (babaissarkar) [reply src/gui/dialogs/editor/custom_tod.cpp:183]: > This seems like a more generic function that shouldn't be in a dialog. If the name contains something about addons/editor and assets and the else case throws an exception or returns an invalid optional or something instead, I think it could go into filesystem.

Good idea. But can the gui part (the confirm dialog) go into filesystem? (Because I need it most of the time)

Comment (CelticMinstrel) [reply src/gui/dialogs/editor/custom_tod.cpp:183]: > But can the gui part (the confirm dialog) go into filesystem?

I'm not really sure what you mean by this…? It's just the standard confirm dialog, right?

Comment (babaissarkar) [reply src/gui/dialogs/editor/custom_tod.cpp:183]: > I'm not really sure what you mean by this…? It's just the standard confirm dialog, right?
Yes, it's a standard dialog, but I though it is a convention to not have gui related stuff in fliesystem.cpp. I wonder if we can make an exception for this. Perhaps @soliton- can clarify.

Comment (CelticMinstrel) [reply src/gui/dialogs/editor/custom_tod.cpp:183]: I see… I'm not sure about that, then.

File: src/gui/dialogs/editor/custom_tod.cpp (hunk 3 above)
Comment (babaissarkar) [reply src/gui/dialogs/editor/custom_tod.cpp]: Added.

File: src/gui/dialogs/editor/custom_tod.cpp (hunk 1 above)
Comment (soliton-) [reply src/gui/dialogs/editor/custom_tod.cpp]: > > This seems like a more generic function that shouldn't be in a dialog. If the name contains something about addons/editor and assets and the else case throws an exception or returns an invalid optional or something instead, I think it could go into filesystem.
> 
> Good idea. But can the gui part (the confirm dialog) go into filesystem? (Because I need it most of the time) Otherwise I might still need wrapper here to show the gui.

No, hence "the else case throws an exception or returns an invalid optional or something instead". The GUI part would stay in the dialog.

Comment (babaissarkar) [reply src/gui/dialogs/editor/custom_tod.cpp]: Moved to `filesystem` in ee87304efde70de15eb3cb10c1416efb378b26c9.

File: src/editor/map/context_manager.hpp [hunk 4]
```diff
@@ -25,11 +25,11 @@ class game_config_view;
 
 namespace editor
 {
+using context_ptr = std::unique_ptr<map_context>;
```
Comment (Vultraz) [inline src/editor/map/context_manager.hpp:28]: Remove this alias and just use the unique_ptr type directly. And replace the instances of `new map_context` in `context_manager` with `std::make_unique<map_context>`.

File: src/editor/map/map_context.hpp [hunk 5]
```diff
@@ -62,9 +62,6 @@ struct editor_team_info {
 class map_context : public display_context
 {
 public:
-	map_context(const map_context&) = delete;
```
Comment (Vultraz) [inline src/editor/map/map_context.hpp:65]: Add these back, please.

File: src/gui/dialogs/editor/custom_tod.cpp [hunk 6]
```diff
@@ -251,8 +294,7 @@ void custom_tod::update_tod_display()
 	// The display handles invaliding whatever tiles need invalidating.
 	disp->update_tod(&get_selected_tod());
 
-	// NOTE: revert to invalidate_layout if necessary to display the ToD mask image.
-	get_window()->queue_redraw();
+	get_window()->invalidate_layout();
```
Comment (Vultraz) [inline src/gui/dialogs/editor/custom_tod.cpp:297]: Why this change?

File: src/gui/dialogs/editor/custom_tod.cpp [hunk 7]
```diff
@@ -287,9 +329,13 @@ void custom_tod::update_selected_tod_info()
 	update_tod_display();
 }
 
-void custom_tod::copy_to_clipboard_callback(tod_attribute_getter getter)
+void custom_tod::copy_to_clipboard_callback(std::pair<std::string, tod_attribute_getter> data)
 {
+	std::string type = data.first;
```
Comment (Vultraz) [inline src/gui/dialogs/editor/custom_tod.cpp:334]: Perfect usecase for structured bindings:
```cpp
auto& [type, getter] = data;
```

File: src/editor/map/context_manager.cpp [hunk 8]
```diff
@@ -52,10 +52,12 @@
 
 #include <memory>
 #include <boost/algorithm/string.hpp>
+#include <boost/filesystem.hpp>
 
 namespace editor {
 
-static std::vector<std::string> saved_windows_;
+static std::vector<context_ptr> saved_contexts_;
+static int last_context_ = 0;
```
Comment (Vultraz) [inline src/editor/map/context_manager.cpp:60]: Put these and the static functions in an anonymous namespace.

**Review by Vultraz — CHANGES_REQUESTED** [review]

File: src/gui/dialogs/editor/custom_tod.cpp (hunk 6 above)
Comment (babaissarkar) [reply src/gui/dialogs/editor/custom_tod.cpp:297]: When there is no ToD selected, if the user selects an image using the browse button, the image won't be reloaded unless `invalidate_layout` is used.

File: src/editor/map/context_manager.cpp (hunk 8 above)
Comment (babaissarkar) [reply src/editor/map/context_manager.cpp]: Moved.

File: src/editor/map/map_context.hpp (hunk 5 above)
Comment (babaissarkar) [reply src/editor/map/map_context.hpp]: Added.

File: src/editor/map/context_manager.hpp (hunk 4 above)
Comment (babaissarkar) [reply src/editor/map/context_manager.hpp]: moved the alias back to where it originally was. Faced segfaults while replacing the `new map_context`-s.

File: src/editor/map/map_context.cpp [hunk 9]
```diff
@@ -123,15 +123,18 @@ map_context::map_context(const map_context&& ctxt)
 	, game_classification_(ctxt.game_classification_)
 	, music_tracks_(ctxt.music_tracks_)
 {
-	for (size_t i = 0; i < ctxt.undo_stack_.size(); i++) {
-		undo_stack_.push_back(std::move(undo_stack_.front()));
-		undo_stack_.pop_front();
+	for(auto& a : ctxt.undo_stack_) {
+		undo_stack_.push_back(a->clone());
```
Comment (CelticMinstrel) [inline src/editor/map/map_context.cpp]: Why would you need to clone if this is a _move_ constructor? Cloning is for copying. In a move constructor you can just steal ownership of the pointer.

Comment (babaissarkar) [reply src/editor/map/map_context.cpp]: Remove that ctor, since it wasn't needed, but yes, that was bad. (My understanding of move semantics is very limited.)

File: src/editor/map/context_manager.hpp (hunk 4 above)
Comment (Vultraz) [reply src/editor/map/context_manager.hpp]: Suggest removing the alias in the class as well. It makes it clearer to have consistent usage. As for the segfaults, that really shouldn’t happen… Do you know exactly where it was crashing?

File: src/editor/map/context_manager.cpp (hunk 8 above)
Comment (Vultraz) [reply src/editor/map/context_manager.cpp]: 👍 You don’t need to add the extra level of indent, though. Also you can keep the anon namespace inside the `editor` namespace.

File: src/editor/map/context_manager.hpp (hunk 4 above)
Comment (babaissarkar) [reply src/editor/map/context_manager.hpp]: Fixed in d9b695289fc80de68f97f224bbc41fa4cab8b4cf

**Review by Vultraz — APPROVED** [review]

**Comment by babaissarkar** [comment]
TODO, WIP:
- [ ] Segfault when reloading maps with labels.
