### PR TITLE
Editor/Edit Side: don't add/write game default base_income

### LINKED ISSUE #10123: Income slider increases by 2 after saving map in editor
### Game and System Information

- **Version:** 1.18.4  (& 1.14)
- **OS:** windows (both)

### Description of the bug

After saving a self-made multiplayer scenario in the editor the income set for each side is increased by 2.

- It shows when loading the scenario again in the editor 

### Steps to reproduce the behavior

- Open a self-made scenario in the editor

- Check income slider in 'edit side' 

- Change something randomly to save the scenario + save

- Exit to menu > reopen the editor > load the scenario

- Check income slider(s) again - it is increased by 2

Image

- After the second time the bug occurs it also shows in the mp screen when createing a game with that scenario

- STARTING a mp game ofc adds the game’s default base_income=2 (from [game_config]) additionally on top

### Expected behavior

- The first increase by 2 just shows in the map editor (in 'edit side') - it does not transfer to the file or to the mp match screen

- Starting with the second time this happens (on *save+exit editor*) the file and consequently the mp screen also have increased income by 2. It goes on to stack +2 in the file and the mp screen every time on *save+exit editor* 

- This leads to the income being shown in the map editor is always 2 higher than in the file

Image

### Additional context

- This bug has been spotted by several map makers - one saw it back in 1.14.X. (income increased by 2 after saving scenario in editor) the other one in 1.18.4

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #10123

Reasoning given in https://github.com/wesnoth/wesnoth/issues/10123#issuecomment-2991271494, quoted here:

> 
> This is where the `+2` comes from:
> https://github.com/wesnoth/wesnoth/blob/a1d3e10e75b6695dc8466360168525a1bb47d743/src/team.hpp#L183
> 
> (game's base income is `2`, which gets added to the value loaded from the file)
> 
> `base_income()`'s retval is used for the `editor_team_info` constructor here:
> https://github.com/wesnoth/wesnoth/blob/a1d3e10e75b6695dc8466360168525a1bb47d743/src/editor/map/map_context.cpp#L46
> 
> Which in turn gets used in the Edit Side dialog, so when you save it it's income from saved scenario file + base income of game.

### CODE REVIEW

File: src/editor/map/map_context.cpp [hunk 1]
```diff
@@ -495,7 +496,7 @@ void map_context::load_scenario()
 			teams_.back().set_recruits(utils::split_set(side["recruit"].str(), ','));
 		}
 	}
-
+
```
Comment (Vultraz) [inline src/editor/map/map_context.cpp]: Whitespace.

**Review by Vultraz — CHANGES_REQUESTED** [review]
`set_base_income` in the same file assumes that the input *does* include the `game_config` adjustment, since it subtracts that value before setting `info_.base_income`. If you store `editor_team_info` without said adjustment, the input to `set_base_income` will be wrong.

That being said, I think it would be better to add a direct getter (and maybe a setter) for `team_info::income` that doesn't adjust for the `game_config::base_income`. The fact that it's adjusted is an implementation detail that we shouldn't be handling in the UI code.

(Also, please move the implementation of the functions that access `game_config` into the cpp file and remove the `game_config.hpp` include from `team.hpp`)

File: src/editor/map/map_context.cpp (hunk 1 above)
Comment (babaissarkar) [reply src/editor/map/map_context.cpp]: Removed.

**Comment by babaissarkar** [comment]
> (Also, please move the implementation of the functions that access `game_config` into the cpp file and remove the `game_config.hpp` include from `team.hpp`)

@Vultraz you mean moving into `team.cpp`, right? To confirm, that'd just move the `game_config` include from `team.hpp` into `team.cpp`, along with the two method implementations.

**Comment by Vultraz** [comment]
Yes.

**Comment by babaissarkar** [comment]
@Vultraz the include move causes a lot of files to fail compilation.

File: src/team.hpp [hunk 2]
```diff
@@ -180,7 +179,8 @@ class team
 	int side() const { return info_.side; }
 	int gold() const { return info_.gold; }
 	int start_gold() const { return info_.start_gold; }
-	int base_income() const { return info_.income + game_config::base_income; }
+	int raw_income() const { return info_.income; }
```
Comment (Vultraz) [inline src/team.hpp:186]: Could you add a doc comment to these four functions (the two getters and setters) in order to clarify their expected input and return values.

File: src/team.cpp [hunk 3]
```diff
@@ -411,6 +412,16 @@ void team::write(config& cfg) const
...
 }
 
+int team::base_income() const
+{
+	return info_.income + game_config::base_income;
+}
+
+void team::set_base_income(int amount)
+{
+	info_.income = amount - game_config::base_income;
```
Comment (Vultraz) [inline src/team.cpp]: Can be defined in terms of `set_raw_income`.

File: src/team.cpp [hunk 4]
```diff
@@ -411,6 +412,16 @@ void team::write(config& cfg) const
 	cfg["action_bonus_count"] = action_bonus_count_;
 }
 
+int team::base_income() const
+{
+	return info_.income + game_config::base_income;
```
Comment (Vultraz) [inline src/team.cpp]: Can be defined with `raw_income`

**Comment by gfgtdf** [comment]
> (Also, please move the implementation of the functions that access `game_config` into the cpp file and remove the `game_config.hpp` include from `team.hpp`)

These were at some point explicitly moved out of the cpp file though https://github.com/wesnoth/wesnoth/commit/72eb8633020719aae1efa7672f381c0371b71f23 . It seems that it was dont fo perfomance (i doubt that it really makes a difference though)

File: src/team.hpp (hunk 2 above)
Comment (babaissarkar) [reply src/team.hpp:186]: Done.
