### PR TITLE
Keep laurel decorations consistent with difficulty level

### LINKED ISSUE #8442: Laurels shown when changing difficulty mid campaign are always golden
### Game and System Information

- **Version:** 1.17.26
- **Downloaded from:** Steam
- **OS:** Windows 10

### Description of the bug

See title. :D

### Steps to reproduce the behavior

1. Select a scenario start file.
2. Check the 'change difficulty box'
change difficulty
3. Load the save
4. Observe the options shown, each completed difficulty shows as a gold laurel.
wrong laurels

### Expected behavior

I expected that the laurels would be the same as shown in the campaign dialog when selecting the difficulty.
right laurels

For me that would make more sense, but if it's an intentional decision, that's fine by me too. It feels like an oversight though.

### Additional context
[DW-Epilogue.gz](https://github.com/wesnoth/wesnoth/files/14373477/DW-Epilogue.gz)
Makes it easiest to confirm, as loading the save with a difficulty selected automatically gives the campaign completion.

### PR DESCRIPTION
**Pull request by Wedge009**
Still feels a bit clunky, but I'm following the pattern already used here:
https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/src/gui/dialogs/campaign_selection.cpp#L98-L110

This works for me, at least. Thanks to @CelticMinstrel for pointing me in the right direction. If there's a better way than just relying on the count of difficulties, please advise.

Resolves #8442. Should be back-ported to 1.18 branch, I think 1.16 as well unless there's absolutely no way there's going to be another release for it.

image

### CODE REVIEW

**Comment by Wedge009** [comment]
Not sure why the checks are failing.

**Comment by Pentarctagon** [comment]
```
src/gui/dialogs/campaign_difficulty.cpp:105:20: error: the compiler can assume that the address of 'widget' will never be NULL [-Werror=address]
  105 |                 if(&widget) {
      |                    ^~~~~~~
```
which means you don't need that if-check.

**Comment by Wedge009** [comment]
Thanks. What's the copyright check about?

**Comment by Pentarctagon** [comment]
Vultraz still needs to fix that - you can ignore it.

**Comment by CelticMinstrel** [comment]
That warning is a result of using the version of `find_widget` that throws an exception if the element is not found… which is probably fine in this case.

**Comment by Wedge009** [comment]
I wasn't sure which one to use. Originally I had it working with a direct dynamic cast to `styled_widget *` but you suggested I should use `find_widget` so I did.

File: src/gui/dialogs/campaign_difficulty.cpp [hunk 1]
```diff
@@ -99,10 +101,29 @@ void campaign_difficulty::pre_show(window& window)
...
+		styled_widget& widget = find_widget<styled_widget>(&grid, "victory", false);
+		if(preferences::is_campaign_completed(campaign_id_, d["define"])) {
+			// Use different laurels according to the difficulty level, following the
+			// pre-existing convention established in campaign_selection class.
+			// Assumes ascending order of difficulty.
+			if(difficulty_count == 0) {
+				widget.set_label(game_config::images::victory_laurel_easy);
+			}
+
+			else if(difficulty_count + 1 >= difficulty_max) {
```
Comment (soliton-) [inline src/gui/dialogs/campaign_difficulty.cpp:113]: The line spacing for the else blocks looks a bit odd here and below. Is there a reason for that?

File: src/gui/dialogs/campaign_difficulty.cpp [hunk 2]
```diff
@@ -99,10 +101,29 @@ void campaign_difficulty::pre_show(window& window)
...
 
-		widget* widget = grid.find("victory", false);
-		if(widget && !preferences::is_campaign_completed(campaign_id_, d["define"])) {
-			widget->set_visible(widget::visibility::hidden);
+		styled_widget& widget = find_widget<styled_widget>(&grid, "victory", false);
+		if(preferences::is_campaign_completed(campaign_id_, d["define"])) {
+			// Use different laurels according to the difficulty level, following the
+			// pre-existing convention established in campaign_selection class.
+			// Assumes ascending order of difficulty.
+			if(difficulty_count == 0) {
```
[the remark this answers is not in the document]
Comment (Wedge009) [reply src/gui/dialogs/campaign_difficulty.cpp:109]: Yes, you're right. Will clarify this because I didn't notice that.

File: src/gui/dialogs/campaign_difficulty.cpp (hunk 1 above)
Comment (Wedge009) [reply src/gui/dialogs/campaign_difficulty.cpp:113]: No particular reason other than I haven't really done C++ development in a long time, mostly Python recently, and I'm probably influence by its 'sparse is better than dense mandate. If it was up to me, I would put the opening brace on its own line but I was at least trying to follow existing convention there. Since the rest of the code here uses dense formatting, I'll follow that.

**Comment by Wedge009** [comment]
If no further concerns, I plan to merge and back-port this soon - within the next day or so.

**Comment by Wedge009** [comment]
Oops, forgot to squash...
