### PR TITLE
Fix assertion when opening the gamestate inspector while disabled events haven't been cleaned up

### LINKED ISSUE #3257: Using :inspect after remove_event shows assertion failure
After removing event with wesnoth.wml_actions.remove_event{id="AE_arc_stone_repetrify_advance"} from lua console and using inspect, I get https://vgy.me/kECBVs.png, when pressing ignore, game and inspect continues working.

Log has
20180616 01:18:42 error gui/layout: grid [] place: Failed to place a grid, we have 301,49 space but we need 318,49 space. This happened at a grid with the id '' in a 'N4gui214tree_view_nodeE' with the id '' in a 'N4gui29tree_viewE' with the id 'stuff_list' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'gamestate_inspector'.

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Fixes #3257

### CODE REVIEW

File: src/game_events/manager.cpp [hunk 1]
```diff
@@ -178,7 +178,7 @@ void manager::write_events(config& cfg, bool include_nonserializable) const
 		// have been flagged as disabled by this point (such events are disabled before their
 		// actions are run). If a disabled event is encountered outside an event context,
 		// however, assert. That means something went wrong with event list cleanup.
```
Comment (stevecotton) [inline src/game_events/manager.cpp:180]: This comment needs an extra sentence explaining the `include_nonserializable`.

The code change itself seems good giving the timing (I approve of getting it into tonight's build), but IIUC it's a hack of "we know that only the inspector uses this, and it makes sense to allow `[inspect]` at odd times, so avoid the assert".

**Review by stevecotton — APPROVED** [review]
