### PR TITLE
Make the adhoc add-on download check more detailed.

### LINKED ISSUE #6383: Addons can't be updated from the multiplayer server menu
### Game and System Information
 - What version of the game are you running? Tried 1.16.0 and 1.16.1
 - Where did you download it from? flatpak and custom build from 1.16.0 tag
 - What OS are you running? Ubuntu 20

### Describe the bug
When someone is hosting a game which required some addon and you have an outdated version of this addon, the game proposes to update the addon (if you click OK). In 1.16 it does nothing. Only manual updating through Main Menu > Add-ons works.

### To Reproduce
1. Host a multiplayer game in one Wesnoth instance
2. Launch another one with an outdated version of the addon
3. Try to update the addon with this menu 
изображение

Not all addons require all users to have the same latest version to play. Addons for which this behaviour was observed: Era of Magic, The Great Steppe Era
### Expected behavior
The addon updates successfully and you can join the game

### PR DESCRIPTION
**Pull request by Pentarctagon**
Originally this simply checked for whether the add-on's directory existed to avoid downloading the same add-on multiple times when migrating from one major release to another. However this then causes add-ons to not get updated when joining a multiplayer game where to person joining has the add-on (so the directory exists) but needs an updated version of it.

Fixes #6383

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Tested locally:
* Host has add-on, joining player doesn't -> joining player prompted to download and then is able to join.
* Host has add-on, joining player has outdated version -> joining player prompted to download and then is able to join.
* Host has older version than joining player -> joining player is unable to join and is given a prompt suggesting they tell the host they need to update.

**Comment by ProditorMagnus** [comment]
Reminder to test where one or more involved players are addon authors.

**Comment by Pentarctagon** [comment]
It looks like that wouldn't be an issue. If the add-on versions aren't compatible and it is required, then it's not possible to join (a popup gets shown saying the host needs to update). If the add-on isn't required, then it wouldn't be checked for whether an update is needed in the first place.

File: src/addon/manager_ui.cpp [hunk 1]
```diff
@@ -38,6 +39,7 @@ static lg::log_domain log_filesystem("filesystem");
 static lg::log_domain log_addons_client("addons-client");
 
 #define ERR_CFG LOG_STREAM(err,   log_config)
+#define INFO_CFG LOG_STREAM(info,   log_config)
```
Comment (stevecotton) [inline src/addon/manager_ui.cpp:42]: Either make the `log_config` line up with the line above, or don't add the extra spaces.

File: src/addon/manager_ui.cpp [hunk 2]
```diff
@@ -276,8 +278,29 @@ bool ad_hoc_addon_fetch_session(const std::vector<std::string>& addon_ids)
...
+				if(filesystem::file_exists(info_cfg)) {
+					game_config::config_cache& cache = game_config::config_cache::instance();
+					config info;
+					cache.get_config(info_cfg, info);
+					version_info installed_addon_version(info.child_or_empty("info")["version"]);
+
+					// if the installed version is outdated, download the most recent version from the add-ons server
+					if(installed_addon_version < addon.current_version) {
+						addons_client::install_result res = client.install_addon_with_checks(addons, addon);
+						return_value = return_value && (res.outcome == addons_client::install_outcome::success);
```
Comment (stevecotton) [inline src/addon/manager_ui.cpp:301]: The contents of this conditional block are the same as the contents of the next conditional block, it would be nice to merge them.

The logic above has already used a `continue` to avoid an unnecessary download, so I think the logic here should use `continue` too.

File: src/addon/manager_ui.cpp (hunk 1 above)
Comment (Pentarctagon) [reply src/addon/manager_ui.cpp]: Done.

File: src/addon/manager_ui.cpp (hunk 2 above)
Comment (Pentarctagon) [reply src/addon/manager_ui.cpp]: Did the first part, though I'm not sure what you mean about the `continue`?

Comment (stevecotton) [reply src/addon/manager_ui.cpp]: I mean that the logic could do this:
```
if(...)
    continue;
if(...)
    continue;
addons_client::install_stuff();
```
or it could do this:
```
bool do_update=true;
if(...)
    do_update=false;
if(...)
    do_update=false;
if(do_update==false)
    addons_client::install_stuff();
```
but please choose one or the other without mixing them.

Comment (Pentarctagon) [reply src/addon/manager_ui.cpp]: The point of it is simply to short circuit things when there is no chance of doing either an install or an update. I could add a `do_nothing` variable and then change the if-checks that come after it to also check that variable, but that would then also mean the last part of the current logic - where it displays any add-ons which needed an install/update but weren't found on the add-ons server - would never trigger anymore.

Comment (stevecotton) [reply src/addon/manager_ui.cpp]: Maybe I'm missing something - I'm not seeing why you do this:
```
// if the installed version is outdated, download the most recent version from the add-ons server
if(installed_addon_version < addon.current_version) {
    do_update = true;
}
```
instead of doing
```
// if the installed version is already up-to-date, skip downloading a new copy from the add-ons server
if(installed_addon_version >= addon.current_version) {
    continue;
}
```

Comment (Pentarctagon) [reply src/addon/manager_ui.cpp]: Removing `do_update` and using `continue` would mean that the check immediately below it would be just:
```
if(!filesystem::file_exists(info_cfg)) {
	addons_client::install_result res = client.install_addon_with_checks(addons, addon);
	return_value = return_value && (res.outcome == addons_client::install_outcome::success);
}
```
which then wouldn't do an update for an outdated but existing add-on. Unless you mean getting rid of that if-check altogether?

Comment (stevecotton) [reply src/addon/manager_ui.cpp]: AFAICS, that if-check can be removed.

Comment (Pentarctagon) [reply src/addon/manager_ui.cpp]: Alright, updated.

File: src/addon/manager_ui.cpp [hunk 3]
```diff
@@ -276,11 +278,31 @@ bool ad_hoc_addon_fetch_session(const std::vector<std::string>& addon_ids)
...
+
+				// if _info.cfg exists, compare the local vs remote add-on versions to determine whether a download is needed
+				if(filesystem::file_exists(info_cfg)) {
+					game_config::config_cache& cache = game_config::config_cache::instance();
+					config info;
+					cache.get_config(info_cfg, info);
+					version_info installed_addon_version(info.child_or_empty("info")["version"]);
+
+					// if the installed version is outdated, download the most recent version from the add-ons server
+					if(installed_addon_version < addon.current_version) {
```
Comment (stevecotton) [inline src/addon/manager_ui.cpp:298]: The logic has reversed, this should be a `>=` test now.

Comment (Pentarctagon) [reply src/addon/manager_ui.cpp]: Updated.
