### PR TITLE
Error handling for campaigns without id (fixes #4664)

### LINKED ISSUE #4664: Attempting to start a campaign with no id starts a different campaign instead
### Game and System Information
wesnoth 1.14.9 from debian unstable

### Describe the bug
If there's no id in the `[campaign]` tag, the campaign will still show up in the menu, but it will load whatever campaign was previously selected in the campaign menu. It will also retain the description and image of the previously selected campaign. Only the icon and name are displayed correctly.

wesnoth -c errors out properly, thankfully, but that was a very confusing issue.

### To Reproduce
1. Make a copy of a campaign, or create a new one
1. Delete the id from the campaign tag
1. Run wesnoth, try to select and play the campaign.

### Expected behavior
Ideally, the faulty campaign should display an error instead of loading, as it does with preprocessor errors. It also shouldn't display the image and description of another campaign. Alternatively, I could live with the campaign not showing up in the menu, so long as wesnoth --log-debug engine shows something useful.

### PR DESCRIPTION
**Pull request by stevecotton**
Can be cleanly cherry-picked between 1.14 and master, and tested on both. Sample output:
```
20191229 18:22:08 error config: Found a [campaign] with neither a name nor an id attribute, ignoring it
20191229 18:25:18 error config: Ignoring a [campaign] with no id attribute, but name 'Tactics Puzzles'
```

### CODE REVIEW

File: src/game_initialization/create_engine.cpp [hunk 1]
```diff
@@ -727,6 +727,15 @@ void create_engine::init_all_levels()
 	// Campaigns.
 	for(const config& data : game_config_.child_range("campaign"))
 	{
+		if(!data.has_attribute("id") || data["id"].empty()) {
+			if(!data.has_attribute("name") || data["name"].empty()) {
```
Comment (gfgtdf) [inline src/game_initialization/create_engine.cpp]: technicailly `!data.has_attribute("name")` imples `data["name"].empty()` so this can be simplified

Comment (stevecotton) [reply src/game_initialization/create_engine.cpp]: Thanks - I missed that data was already `const`; will do the simplification.

The build error is something about the macOS setup, not this change.
