### PR TITLE
Extend case-insensitive filtering beyond ASCII characters

### LINKED ISSUE #9328: Search filter is case-insensitive only for ASCII characters
### Game and System Information

- **Version:** 1.18.2
- **OS:** Ubuntu 20.04

### Description of the bug

When you search for a save by its name, in English it's case-insensitive. Which is very logical. But for some reason in Russian it requires a verbatim inclusion, strictly case-sensitive

### Steps to reproduce the behavior

image
Here I search for Spartan with a different case of English letters and for Ход (it means "Turn" in Russian). It finds it when verbatim
image
now for ход (the first letter not capitalized) it finds nothing

### Expected behavior

Search is case-insensitive for all languages that have a notion of a letter case

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Wedge009**
Attempt to resolve #9328.

Caveats:
1. This is based purely on the discussion from the linked issue. I don't know if I've covered all the details discussed therein.
2. This seems to work for me, but at present I don't have non-ASCII characters in my saved game names, so I can't properly test this.
3. The game load dialogue isn't the only place where case-insensitive searching is limited to ASCII characters. If this change is accepted, then potentially it could be applied to other searches:

https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/gui/dialogs/addon/manager.cpp#L68-L77

https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/menu_events.cpp#L1393-L1397

https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/game_initialization/lobby_data.cpp#L503-L506

https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/serialization/string_utils.cpp#L664-L669

Also, given this is an improvement at least for players using non-ASCII translations, it could possibly be back-ported.

### CODE REVIEW

**Comment by Wedge009** [comment]
I got thrown by the example given for [npos](https://en.cppreference.com/w/cpp/string/basic_string/npos), where it compares against `s.npos`. It sort of makes sense though, but I can change it to `std::string::npos`.

**Comment by soliton-** [comment]
> I don't see any non-ASCII characters in the add-ons list for fields that seem to be searched: name, version, author. So maybe add-on manager can be left alone.

Translation stuff is checked with `translation::ci_search` which looks like it should work fine.

> I'm not sure where the label search in `menu_events.cpp` are used, but potentially that might be useful for users.

It's used when you search with `/` in-game. So create a label with `Ö` for example and search for `ö`.

**Comment by Wedge009** [comment]
> It's used when you search with `/` in-game. So create a label with `Ö` for example and search for `ö`.

I meant for my [reply](https://github.com/wesnoth/wesnoth/issues/9328#issuecomment-2342338094) to go here, but it probably helps to put it in the issue discussion.

**Comment by Wedge009** [comment]
Draft because this doesn't look like it will actually fix the issue.

**Comment by Vultraz** [comment]
Why do you say that?

**Comment by soliton-** [comment]
Actually would still not hurt to do it properly for the addon manager case as well since there is no requirement to use only ASCII characters. Not sure if we require to use English (would certainly make sense on the official server) but even then you can use Unicode characters that are not just a single byte.

**Review by soliton- — APPROVED** [review]

**Comment by Wedge009** [comment]
I mainly left it because I don't have a means to test it. But I updated it as well, just made it consistent with the second loop that already uses `ci_search`.

**Review by Vultraz — APPROVED** [review]

File: src/menu_events.cpp [hunk 1]
```diff
@@ -1389,22 +1389,17 @@ void menu_handler::do_search(const std::string& new_search)
 		if(!gui_->shrouded(loc)) {
 			const terrain_label* label = gui_->labels().get_label(loc);
 			if(label) {
-				std::string label_text = label->text().str();
-				if(std::search(label_text.begin(), label_text.end(), last_search_.begin(), last_search_.end(),
-						   utils::chars_equal_insensitive)
-						!= label_text.end()) {
-					found = true;
-				}
+				const std::string& label_text = label->text().str();
```
Comment (Vultraz) [inline src/menu_events.cpp:1392]: Not worth changing but does this `str()` return a reference here? If not it should still be a copy.
