### PR TITLE
Make it possible to use the "unit description" command in replay mode on fogged/shrouded units.

### LINKED ISSUE #3687: When "Point of view" is "Full map", can't view descriptions of would-be shrouded enemy units
During replay of a scenario that has an enemy unit under shroud, change "Point of view" to "Full map". The enemy unit is then shown, but the `d` hotkey ("Unit Description") does not work on it. This is because https://github.com/wesnoth/wesnoth/blob/64cb83d4579f7ba7cbfd9832ce1c511e2c02ea0d/src/hotkey/hotkey_handler.cpp#L360-L361 calls https://github.com/wesnoth/wesnoth/blob/64cb83d4579f7ba7cbfd9832ce1c511e2c02ea0d/src/menu_events.cpp#L635-L645 which does not pass `see_all=true`.

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #3687

### CODE REVIEW

File: src/menu_events.cpp [hunk 1]
```diff
@@ -649,13 +649,14 @@ void menu_handler::rename_unit()
 unit_map::iterator menu_handler::current_unit()
 {
 	const mouse_handler& mousehandler = pc_.get_mouse_handler_base();
+	const bool see_all = pc_.is_replay() && dynamic_cast<playsingle_controller&>(pc_).get_replay_controller()->see_all();
```
Comment (jostephd) [inline src/menu_events.cpp]: Is this `dynamic_cast` good? Should I add a `virtual replay_controller * play_controller::get_replay_controller() { return nullptr; }` and have `playsingle_controller::get_replay_controller` override it?

Comment (soliton-) [reply src/menu_events.cpp]: Yes, I think you should move `get_replay_controller()` up to `play_controller`. I'd also move the `replay_controller` member up so you can make sure in code that if `is_replay()` is true there is a valid `replay_controller`.

Comment (jostephd) [reply src/menu_events.cpp]: I've moved get_replay_controller up. I didn't understand what you mean by moving the data member, though. Is the code good as it is now or should I make further changes?

Comment (soliton-) [reply src/menu_events.cpp]: Using `get_replay_controller()` in `play_controller::is_replay()` like you did works as well. Now you can remove `playsingle_controller::is_replay()` since it does the same thing.

Comment (jostephd) [reply src/menu_events.cpp]: I already have, haven't I? Thanks for the review.

Comment (soliton-) [reply src/menu_events.cpp]: Ah, indeed I missed that, my bad.
