### PR TITLE
Use a proper struct for lightmap adjustments

### LINKED ISSUE #10101: Cannot build from source on Xcode 16.3
### Game and System Information

- **Version:** dev @ `c1093c5dfe365350d778c0429379f0d96c1c9b90` \
(I cannot verify whether 1.18 is affected too because I do not want to lose my existing 1.18 build)
- **OS:** macOS Sequoia 15.4

### Description of the bug

Attempting to build Wesnoth on the newly-released Xcode 16.3 results in the following error:

```
CompileC /Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Build/Intermediates.noindex/The\ Battle\ for\ Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/hash.o /Users/iris/Projects/wesnoth/src/hash.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'wesnothd' from project 'The Battle for Wesnoth')
    cd /Users/iris/Projects/wesnoth/projectfiles/Xcode
    
    Using response file: /Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Build/Intermediates.noindex/The Battle for Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp
    
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -ivfsstatcache /Users/iris/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/macosx15.4-24E241-88b860576fb364319593bd8fb30666b0.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -Wno-trigraphs -Wmissing-field-initializers -Wmissing-prototypes -Wunreachable-code -Wnon-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -index-store-path /Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Index.noindex/DataStore -Wall -Wno-shorten-64-to-32 @/Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Build/Intermediates.noindex/The\ Battle\ for\ Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -MMD -MT dependencies -MF /Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Build/Intermediates.noindex/The\ Battle\ for\ Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/hash.d --serialize-diagnostics /Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Build/Intermediates.noindex/The\ Battle\ for\ Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/hash.dia -c /Users/iris/Projects/wesnoth/src/hash.cpp -o /Users/iris/Library/Developer/Xcode/DerivedData/The_Battle_for_Wesnoth-gvcieigqfnvlbvdaxanimpkfsprs/Build/Intermediates.noindex/The\ Battle\ for\ Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/hash.o -index-unit-output-path /The\ Battle\ for\ Wesnoth.build/Debug/wesnothd.build/Objects-normal/arm64/hash.o

In file included from /Users/iris/Projects/wesnoth/src/hash.cpp:16:
In file included from /Users/iris/Projects/wesnoth/src/hash.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/string:648:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/string_view:300:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned char>'
  300 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
      |                                          ^
/Users/iris/Projects/wesnoth/src/hash.cpp:47:26: note: in instantiation of template class 'std::basic_string_view<unsigned char>' requested here
   47 |         utils::byte_string_view view{bytes.data(), len};
      |                                 ^
In file included from /Users/iris/Projects/wesnoth/src/hash.cpp:16:
In file included from /Users/iris/Projects/wesnoth/src/hash.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/string:621:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/__string/char_traits.h:45:8: note: template is declared here
   45 | struct char_traits;
      |        ^
1 error generated.

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/string_view:300:42: Implicit instantiation of undefined template 'std::char_traits<unsigned char>'
```

This did not occur with Xcode 16.2.

From some searching around I believe this may result from this change mentioned in the [Xcode 16.3 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16_3-release-notes#Resolved-Issues):

> The base template for std::char_traits has been removed. If you are using std::char_traits with types other than char, wchar_t, char8_t, char16_t, char32_t or a custom character type for which you specialized std::char_traits, your code will stop working. The Standard does not mandate that a base template is provided, and such a base template is bound to be incorrect for some types, which could previously cause unexpected behavior while going undetected.

### Steps to reproduce the behavior

yes

### Expected behavior

build

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vultraz**
Resolves #10101. I'm not entirely sure about the approach I've taken here, so any thoughts are welcome.

### CODE REVIEW

File: src/display.cpp [hunk 1]
```diff
@@ -1033,7 +1033,9 @@ void display::get_terrain_images(const map_location& loc, const std::string& tim
 {
 	terrain_image_vector_.clear();
 
-	std::vector<image::light_adjust> lighting;
+	static std::vector<image::light_adjust> lighting;
+	lighting.clear();
```
Comment (soliton-) [inline src/display.cpp:1037]: What‘s the point of this?

Comment (Vultraz) [reply src/display.cpp:1037]: We already keep a permanent vector in the class for terrain images (`terrain_image_vector_`). I figured it was a safe bet to keep a static vector for lightmap data, since this function is called so often. But I can do more extensive testing.
