### PR TITLE
Fix #8460 [effect] apply_to=variation

### LINKED ISSUE #8460: Effect ``apply_to=hitpoints`` ``heal_full=yes`` doesn't work
### Game and System Information

- **Version:** built from 40fc9a8be70bbbf4108303f9034392e38e63081b

### Description of the bug

[Bug_with_heal_full.zip](https://github.com/wesnoth/wesnoth/files/14397875/Bug_with_heal_full.zip)

Here is the test scenario. It uses RECRUIT_UNIT_VARIATIONS macro to allow recruit either usual zombies or troll zombies. Troll zombies have 21 max hp. 

The code of the macro includes the following to heal units. In 1.16 it works fine, in the recent version it doesn't
```
                   [effect]
                        apply_to=hitpoints
                        heal_full=yes
                    [/effect]
```

изображение

### Steps to reproduce the behavior

1. Install the scenario above
2. Start the game
3. Recruit zombies until you get a troll zombie, it would have 18 out of 21 hp

### Expected behavior

Full hp troll zombies

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gfgtdf**
Previously the code would apply the variation effects last, so that codes like
```
[effect]
  apply_to=variation
  ..
[/effect]
[effect]
  apply_to=hitpoints
  heal_full=yes
[/effect]
```
Would not set the unit hitpoints to the new variations hitpoints because the variation effect was applied after the healing effect.

In 1.16 this worked becasue healign was applied a little too often but that lead  also to bugs like #8324

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Why are there parts related to poison removed too?

**Comment by gfgtdf** [comment]
> Why are there parts related to poison removed too?

Becasue they were only there to fix other problems of variations being applied last.

**Comment by gfgtdf** [comment]
This is intended to be backported btw since its fixes a regression from 1.16

File: src/units/unit.cpp [hunk 1]
```diff
@@ -2442,14 +2442,20 @@ void unit::add_modification(const std::string& mod_type, const config& mod, bool
...
+	config* target = nullptr;
+
 	if(no_add == false) {
-		modifications_.add_child(mod_type, mod);
+		target = &modifications_.add_child(mod_type, mod);
+		target->remove_children("effect");
 	}
 
-	bool set_poisoned = false; // Tracks if the poisoned state was set after the type or variation was changed.
 	config type_effect, variation_effect;
```
Comment (stevecotton) [inline src/units/unit.cpp:2452]: These two configs seem to be unused now.

I haven't managed to understand the code yet, when are the variations now applied?

Comment (gfgtdf) [reply src/units/unit.cpp:2452]: in order, like other effects, as part of the loop here.

**Comment by stevecotton** [comment]
This PR seems to do what it says it does (see below), the code looks smaller, still haven't understood why the parts of the effect are temporarily removed.

```
#textdomain wesnoth-test

#####
# API(s) being tested: [effect]apply_to=variation,[effect]heal_full=yes
##
# Actions:
# Turn Bob into a walking corpse (18 max hp)
# Turn Bob into a drake walking corpse (23 max hp)
# Apply a full heal
##
# Expected end state:
# Bob's current hp is 23
#####
{GENERIC_UNIT_TEST "effect_type_variation_full_heal" (
    [event]
        name=side 1 turn 1

        [object]
            silent=yes
            [filter]
                id=bob
            [/filter]
            [effect]
                apply_to=type
                name="Walking Corpse"
            [/effect]
            [effect]
                apply_to=variation
                name="drake"
            [/effect]
            [effect]
                apply_to=hitpoints
                heal_full=yes
            [/effect]
        [/object]

        {ASSERT (
            [have_unit]
                id=bob
                formula="self.hitpoints=23"
            [/have_unit]
        )}

        {SUCCEED}
    [/event]
)}

#####
# API(s) being tested: [effect]apply_to=variation,[effect]heal_full=yes
##
# Actions:
# Turn Bob into a walking corpse (18 max hp)
# Turn Bob into a drake walking corpse (23 max hp)
##
# Expected end state:
# Bob's current hp is 18
#####
{GENERIC_UNIT_TEST "effect_type_variation_no_heal" (
    [event]
        name=side 1 turn 1

        [object]
            silent=yes
            [filter]
                id=bob
            [/filter]
            [effect]
                apply_to=type
                name="Walking Corpse"
            [/effect]
            [effect]
                apply_to=variation
                name="drake"
            [/effect]
        [/object]

        {ASSERT (
            [have_unit]
                id=bob
                formula="self.hitpoints=18"
            [/have_unit]
        )}

        {SUCCEED}
    [/event]
)}
```

**Comment by gfgtdf** [comment]
So that the [effect]s after the variation effect arent applied twice.

**Comment by stevecotton** [comment]
It's still got no unit test. Please either take the one from my comment or write one yourself.

**Comment by stevecotton** [comment]
Who is handling the backport?

**Comment by Pentarctagon** [comment]
Done.
