### PR TITLE
Multiply help portait scaling by the pixel multiplier.

### LINKED ISSUE #8275: Image scaling regression
### Game and System Information

- **Version:**
- v1.17.24+dev (d9aa71ac867)
- **Downloaded from:**
- here
- **Build info:**
- scons
- **OS:**
Linux

### Description of the bug

Something has gone wrong with the scaling recently (maybe last couple weeks?)  It's more noticeable in sloppier portrait images, but it shows on mainline too.  I compare it to 1.16 here (need to click the image, don't just glance at the preview)
Screenshot_20240121_scaling

### Steps to reproduce the behavior

start wesnoth, go to help browser and look up units with both M/F versions

### Expected behavior

_No response_

### Additional context

I'm going to call this a blocker because it looks worse than the current stable version, and lot of work went into the graphics/display for upcoming version.  This would undercut that rollout.

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #8275

------

Current:
without

With this PR:
with1
with2

### CODE REVIEW

File: src/help/help_topic_generators.cpp [hunk 1]
```diff
@@ -324,6 +324,9 @@ std::string unit_topic_generator::operator()() const {
 		sz = 400;
 	}
 
+	// otherwise scaling down (SCALE_INTO below) and then scaling back up due to the pixel multiplier leads to ugly results
```
Comment (CelticMinstrel) [inline src/help/help_topic_generators.cpp:327]: This "otherwise" appears to be referring back to a nonexistent antecedent. Did you miss part of the comment?

Comment (Pentarctagon) [reply src/help/help_topic_generators.cpp]: Clarified the comment.

Comment (CelticMinstrel) [reply src/help/help_topic_generators.cpp]: Better,  but "without" is one word.

**Comment by Wedge009** [comment]
So the portrait images are scaled according to the current pixel multiplier setting? Just wondering about the size difference between the before and after samples.

**Comment by Pentarctagon** [comment]
Correct.
