### PR TITLE
label inline link mechanism code simplification

### LINKED ISSUE #8915: URL hitboxes on centered text are left-aligned
### Game and System Information

- **Version:** 1.18.0+dev (f4a1d25d3f4cb0d1b02bf2ad3926ce4d92f469de), 1.19+dev
- **OS:** Linux (Debian testing distro, X11 session started 11 days ago)
- **libc6** 2.38-11
- **libcairo2** 1.18.0-3+b1
- **libfontconfig1** 2.15.0-1.1
- **libgcc-s1** 14-20240330-1
- **libglib2.0-0t64** 2.80.2-1
- **libpango-1.0-0** 1.52.2+ds-1
- **libpangocairo-1.0-0** 1.52.2+ds-1
- **libsdl2-2.0-0** 2.30.2+dfsg-1
- **libsdl2-image-2.0-0** 2.8.2+dfsg-1+b1
- **libsdl2-mixer-2.0-0** 2.8.0+dfsg-1+b2

### Description of the bug

The red areas are (approximately) where the cursor changes and clicking opens a confirmation dialog to open the link. The non-red areas are just text, and clicking there does nothing. Screenshot is from a 1.19+dev build with work in progress on PR #8905, but the same issue is reproducible on the current 1.18 branch at commit f4a1d25d3f4cb0d1b02bf2ad3926ce4d92f469de.

image

The areas are approximate (drew on top of a screenshot rather than having a way to see the exact area), and on 1.18 the right edges of the hitbox are slightly further left. On 1.18 the left edges seem to be in the same x coordinate for both texts, however on 1.19 the left edge of the area is, as shown in the screenshot, a few pixels further right for the longer piece of text.

### Steps to reproduce the behavior

1. From the title screen, open the language selection
2. Hover over the links

### Expected behavior

_No response_

### Additional context

The UI that shows this bug is a new feature that's added to 1.18.1 but wasn't in 1.18.0.

### PR DESCRIPTION
**Pull request by babaissarkar**
Also fixes non-left aligned inline links having wrong link click bounds. (resolves #8915)

Note: I came upon the solution accidentally while doing some cleanup. Fix is:
https://github.com/wesnoth/wesnoth/blob/4976f0a3f8cb6d5d10f608fbcb220fa36cabffce/src/gui/widgets/styled_widget.cpp#L560-L567

### CODE REVIEW

File: src/font/text.cpp [hunk 1]
```diff
@@ -241,51 +241,38 @@ std::size_t pango_text::get_maximum_length() const
...
-	std::string d(delim);
 
-	if (index < 0 || (static_cast<std::size_t>(index) >= txt.size()) || d.find(txt.at(index)) != std::string::npos) {
+	if (index < 0 || (static_cast<std::size_t>(index) >= txt.size()) || delim.find(txt.at(index)) != std::string::npos) {
 		return ""; // if the index is out of bounds, or the index character is a delimiter, return nothing
 	}
 
 	std::size_t l = index;
-	while (l > 0 && (d.find(txt.at(l-1)) == std::string::npos)) {
+	while (l > 0 && (delim.find(txt.at(l-1)) == std::string::npos)) {
```
Comment (babaissarkar) [inline src/font/text.cpp:256]: Can these be simplified to for loops?

Comment (Wedge009) [reply src/font/text.cpp:256]: It looks that way to me, but I suppose it might look odd that the loop would contain nothing. Also it might be done this way for scope reasons, since `l` and `r` (I really prefer fully spelled-out variable names...) are used for the `substr` call at the end.

Comment (Vultraz) [reply src/font/text.cpp:256]: I agree, it would look weird to have an empty loop. Seems an appropriate place for a while loop.

File: src/font/text.cpp [hunk 2]
```diff
@@ -328,8 +315,11 @@ int pango_text::xy_to_index(const point& position) const
 
 	// Get the index of the character.
 	int index, trailing;
-	pango_layout_xy_to_index(layout_.get(), position.x * PANGO_SCALE,
-		position.y * PANGO_SCALE, &index, &trailing);
+	if(!pango_layout_xy_to_index(layout_.get(), position.x * PANGO_SCALE,
+		position.y * PANGO_SCALE, &index, &trailing))
```
Comment (Vultraz) [inline src/font/text.cpp:319]: Just put this whole condition on one line.

**Comment by Vultraz** [comment]
Besides the two small style things, good to go.

File: src/gui/widgets/styled_widget.cpp [hunk 3]
```diff
@@ -557,14 +552,18 @@ void styled_widget::signal_handler_notify_remove_tooltip(const event::ui_event e
...
 
-std::string styled_widget::get_label_link(const point & position) const
+std::string styled_widget::get_label_link(const point& position) const
 {
-	return renderer_.get_link(position);
+	// Without the following line, bounds for links in the case of non-left aligned text
+	// are incorrectly calculated. See issue #8915.
+	get_best_text_size(point(0, 0), get_size());
+
+	return renderer_.get_link(position - get_origin());
```
Comment (Vultraz) [inline src/gui/widgets/styled_widget.cpp:566]: This means `get_link` expected coordinates relative to the origin? Why so?

Comment (babaissarkar) [reply src/gui/widgets/styled_widget.cpp:566]: > This means `get_link` expected coordinates relative to the origin? Why so?

We create a text texture and blit it inside the location inside the widget in canvas. Text renderer has no idea of the text's origin. To it everything starts at 0,0.

Comment (Vultraz) [reply src/gui/widgets/styled_widget.cpp:566]: Ahh, it's a matter of viewports. Could you add a comment to that effect?

File: src/font/text.cpp (hunk 2 above)
Comment (babaissarkar) [reply src/font/text.cpp]: Moved to one line.

File: src/gui/widgets/styled_widget.cpp (hunk 3 above)
Comment (babaissarkar) [reply src/gui/widgets/styled_widget.cpp:569]: Comment added.

**Comment by babaissarkar** [comment]
One more small change: we're using the `pango_text::xy_to_index` wrapper at one other place (`get_column_line()`), and it now also returns the trailing index.

**Review by Vultraz — APPROVED** [review]
