### PR TITLE
filesystem: simplify to_asset_path

### LINKED ISSUE #9579: time schedule editor strange behavior
### Game and System Information

- **Version: BfW 1.19.5:**
- **OS: Windows 10:**

### Description of the bug

adding a sound from the Wesnoth data file in the times schedule editor causes the sound file to be moved into the data file instead of the proper add-on file.

### Steps to reproduce the behavior

1. open **Editor** -> **new scenario** -> **time schedule editor** -> add **sound** -> choose a sound from mainline data file
2. a warning about copying the sound file into the scenario file. choose **yes** 
3. **save**
4. go to **..\wesnoth 1.19\** 
5. you will find the sound file moved from sounds to data 

### Expected behavior

the sound file should not be moved if it is from mainline  files already. And it should be copied if it is from another addon file

### Additional context

This behavior only tested in Windows 10.
I changed the data file from Battle-for-Wesnoth-developpement-version.zip to Wesnoth.1.19

### PR DESCRIPTION
**Pull request by babaissarkar**
Uses `boost::filesystem::path` and the `filesystem::is_prefix` method to improve the `filesystem::to_asset_path` method, hopefully improving cross-platform compatibility.

Resolves #9579

### CODE REVIEW

File: src/filesystem.cpp [hunk 1]
```diff
@@ -1431,36 +1432,35 @@ std::string normalize_path(const std::string& fpath, bool normalize_separators,
 
 bool to_asset_path(std::string& path, const std::string& addon_id, const std::string& asset_type)
 {
-	std::string rel_path = "";
-	std::string core_asset_dir = get_dir(game_config::path + "/data/core/" + asset_type);
-	std::string addon_asset_dir;
+	// datadir is absoulute path to where wesnoth's data is installed
+	// Case 1 example: datadir/data/core/images/misc/image.png -> misc/images
+	bfs::path core_asset_dir = get_dir(game_config::path + "/data/core/" + asset_type);
```
Comment (soliton-) [inline src/filesystem.cpp:1437]: Not new here but why does this use `get_dir` (or why in the world does a function with that name create a directory)?

`get_dir` looks pretty weird. It seems to be quite specific to the use in `get_cache_dir`.

File: src/filesystem.cpp [hunk 2]
```diff
@@ -17,6 +17,7 @@
  * @file
  * File-IO
  */
+#include <boost/filesystem/operations.hpp>
```
Comment (soliton-) [inline src/filesystem.cpp:20]: This should be moved down to the other bfs includes.

File: src/filesystem.cpp (hunk 1 above)
Comment (babaissarkar) [reply src/filesystem.cpp]: Removed, turned out to be unnecessary.

File: src/filesystem.cpp (hunk 2 above)
Comment (babaissarkar) [reply src/filesystem.cpp]: Remove, turned out to be an include my ide auto-added, but wasn't needed.

**Comment by babaissarkar** [comment]
> I think it would help to add some unit tests for this function. It's meant to be somewhat of a reverse of `get_binary_file_location`, yes?

If by "complete path" it means absolute path, then yes.

File: src/filesystem.cpp [hunk 3]
```diff
@@ -1431,36 +1431,42 @@ std::string normalize_path(const std::string& fpath, bool normalize_separators,
...
+		}
+
+		if(!found) {
 			// Not found in either core or addons dirs,
 			// return a possible path where the asset could be copied.
-			std::string filename = boost::filesystem::path(path).filename().string();
-			std::string asset_path = addon_asset_dir + "/" + filename;
-			rel_path = filename;
-			found = false;
+			path = (addon_asset_dir / bfs::path(path).filename()).string();
```
Comment (soliton-) [inline src/filesystem.cpp:1466]: I think this is something the caller should do. It isn't mentioned in the description of `Helper function to convert absolute path to wesnoth relative path` and doesn't really fit.

Comment (soliton-) [reply src/filesystem.cpp:1466]: Current usage is confusing to me. If `false` is returned the asset is possibly copied to the addon and the full path is used instead of the `wesnoth relative path`.

File: src/filesystem.cpp [hunk 4]
```diff
@@ -1431,36 +1431,42 @@ std::string normalize_path(const std::string& fpath, bool normalize_separators,
...
-		addon_asset_dir = get_current_editor_dir(addon_id) + "/" + asset_type;
-		is_in_addon_dir = (path.find(addon_asset_dir) != std::string::npos);
-		if (is_in_addon_dir) {
-			rel_path = path.erase(0, addon_asset_dir.size()+1);
-			found = true;
-		} else {
+
+	if(is_prefix(path, core_asset_dir)) {
+		// Case 1: remove leading datadir/asset_type from given absolute path
+		// For example: given datadir/images/misc/image.png, returns misc/image.png
```
Comment (soliton-) [inline src/filesystem.cpp:1443]:
```suggestion
		// Case 1: remove leading datadir/data/core/asset_type from given absolute path
		// For example: given datadir/data/core/images/misc/image.png, returns misc/image.png
```

File: src/filesystem.cpp [hunk 5]
```diff
@@ -1431,36 +1431,42 @@ std::string normalize_path(const std::string& fpath, bool normalize_separators,
...
+		path = bfs::relative(path, core_asset_dir).string();
+		found = file_exists(core_asset_dir / path);
+	} else if(is_prefix(path, data_asset_dir)) {
+		// Case 2: remove leading datadir/data/core/asset_type from given absolute path
+		// For example: given datadir/data/core/images/misc/image.png, returns misc/image.png
```
Comment (soliton-) [inline src/filesystem.cpp:1448]:
```suggestion
		// Case 2: remove leading datadir/asset_type from given absolute path
		// For example: given datadir/images/misc/image.png, returns misc/image.png
```

File: src/filesystem.cpp (hunk 4 above)
Comment (babaissarkar) [reply src/filesystem.cpp]: Updated.

File: src/filesystem.cpp (hunk 5 above)
Comment (babaissarkar) [reply src/filesystem.cpp]: Updated.

File: src/gui/dialogs/editor/custom_tod.cpp [hunk 6]
```diff
@@ -173,32 +173,35 @@ void custom_tod::select_file(const std::string& default_dir)
...
+		const auto optional_path = filesystem::to_asset_path(path, addon_id, type);
+
+		if(optional_path.has_value()) {
+			return optional_path.value();
+		} else if (gui2::show_message(_("Confirm"), message, message::yes_no_buttons) == gui2::retval::OK) {
+			boost::filesystem::path output_path = filesystem::get_current_editor_dir(addon_id);
+			output_path /= type;
+			output_path /= boost::filesystem::path(path).filename();
+			filesystem::copy_file(path, output_path.string());
+			return output_path.filename().string();
```
Comment (soliton-) [inline src/gui/dialogs/editor/custom_tod.cpp:192]: Shouldn't this return a shortened path as well?

File: src/filesystem.hpp [hunk 7]
```diff
@@ -378,9 +378,9 @@ std::string normalize_path(const std::string& path,
 						   bool resolve_dot_entries = false);
 
 /** Helper function to convert absolute path to wesnoth relative path */
-bool to_asset_path(std::string& abs_path,
-                   const std::string& addon_id,
-                   const std::string& asset_type);
+utils::optional<std::string> to_asset_path(const std::string& abs_path,
```
Comment (soliton-) [inline src/filesystem.hpp:381]: The return type change is not reflected in the implementation.

Comment (babaissarkar) [reply src/filesystem.hpp:381]: Fixed.

File: src/gui/dialogs/editor/custom_tod.cpp (hunk 6 above)
Comment (babaissarkar) [reply src/gui/dialogs/editor/custom_tod.cpp:192]: The file is being copied to `~add-ons/MyAddon/images/test.png`, so the relative path is just `test.png`, which is what it returns.

Comment (soliton-) [reply src/gui/dialogs/editor/custom_tod.cpp:192]: Ah yes, it returns just the filename.

File: src/filesystem.cpp [hunk 8]
```diff
@@ -1429,39 +1430,39 @@ std::string normalize_path(const std::string& fpath, bool normalize_separators,
 	}
 }
 
-bool to_asset_path(std::string& path, const std::string& addon_id, const std::string& asset_type)
+utils::optional<std::string> to_asset_path(std::string& path, const std::string& addon_id, const std::string& asset_type)
```
[the remark this answers is not in the document]
Comment (soliton-) [reply src/filesystem.cpp:1433]: And you need a different local variable for `path`.

[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/filesystem.cpp]: Done.

**Comment by babaissarkar** [comment]
Can someone test this on Windows?

**Comment by soliton-** [comment]
An interesting test would be a file with the same path on two drives because I'm not sure if `is_prefix` considers the drive letter. So incoming path `D:\...\image.png` with `C:\...\image.png` also existing and being in the wesnoth dir.
