### PR TITLE
Respect lua_next constraints

### LINKED ISSUE #2171: Segmentation fault in Lua completion
Got a segmentation fault for wesnoth v1.13.10+dev (8279602d-Clean):
```
Thread 1 "wesnoth" received signal SIGSEGV, Segmentation fault.
0x000055555646a955 in luaH_next (L=0x7fffe219fe38, t=0x55555f4002a0, key=0x7fffe1f236a0) at src/lua/ltable.cpp:196
196	src/lua/ltable.cpp: No such file or directory.
(gdb)
```


```
(gdb) bt      
#0  0x000055555646a955 in luaH_next(lua_State*, Table*, lua_TValue*) (L=0x7fffe219fe38, t=0x55555f4002a0, key=0x7fffe1f236a0) at src/lua/ltable.cpp:196
#1  0x000055555644cbe9 in lua_next(lua_State*, int) (L=0x7fffe219fe38, idx=1) at src/lua/lapi.cpp:1128
#2  0x0000555555b0e204 in lua_kernel_base::get_attribute_names(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffe185a010, input="test_unit.") at src/scripting/lua_kernel_base.cpp:916
#3  0x0000555555fa4526 in gui2::dialogs::lua_interpreter::lua_model::get_attribute_names(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555e352c20, s="test_unit.") at src/gui/dialogs/lua_interpreter.cpp:179
#4  0x0000555555fa2a0d in gui2::dialogs::lua_interpreter::controller::tab() (this=0x55555afae210) at src/gui/dialogs/lua_interpreter.cpp:622
#5  0x0000555555fa1a97 in gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, int, gui2::window&) (this=0x55555afae210, handled=@0x7fffffffb516: false, halt=@0x7fffffffb517: false, key=9, window=...) at src/gui/dialogs/lua_interpreter.cpp:527
#6  0x0000555555fa86b5 in std::__invoke_impl<void, void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int, gui2::window&>(std::__invoke_memfun_deref, void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int&&, gui2::window&) (__f=
    @0x55555dc4a1f0: (void (gui2::dialogs::lua_interpreter::controller::*)(gui2::dialogs::lua_interpreter::controller * const, bool &, bool &, int, gui2::window &)) 0x555555fa18e6 <gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, int, gui2::window&)>, __t=@0x55555dc4a208: 0x55555afae210, __args#0=@0x7fffffffb516: false, __args#1=@0x7fffffffb517: false, __args#2=@0x7fffffffb468: 9, __args#3=...) at /usr/include/c++/7.2.0/bits/invoke.h:73
#7  0x0000555555fa80f5 in std::__invoke<void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int, gui2::window&>(void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int&&, gui2::window&) (__fn=
    @0x55555dc4a1f0: (void (gui2::dialogs::lua_interpreter::controller::*)(gui2::dialogs::lua_interpreter::controller * const, bool &, bool &, int, gui2::window &)) 0x555555fa18e6 <gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, int, gui2::window&)>, __args#0=@0x55555dc4a208: 0x55555afae210, __args#1=@0x7fffffffb516: false, __args#2=@0x7fffffffb517: false, __args#3=@0x7fffffffb468: 9, __args#4=...) at /usr/include/c++/7.2.0/bits/invoke.h:95
#8  0x0000555555fa7a3d in std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)>::__call<void, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, 0ul, 1ul, 2ul, 3ul, 4ul>(std::tuple<gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (this=0x55555dc4a1f0, __args=...) at /usr/include/c++/7.2.0/functional:467
#9  0x0000555555fa6eb4 in std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)>::operator()<gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void>(gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555dc4a1f0, __args#0=..., __args#1=@0x7fffffffb46c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffb516: false, __args#3=@0x7fffffffb517: false, __args#4=@0x7fffffffb468: 9, __args#5=@0x7fffffffb4c0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/functional:551
#10 0x0000555555fa63cc in std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__functor=..., __args#0=..., __args#1=@0x7fffffffb46c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffb516: false, __args#3=@0x7fffffffb517: false, __args#4=@0x7fffffffb468: 9, __args#5=@0x7fffffffb4c0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/bits/std_function.h:316
#11 0x0000555555ef2633 in std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x55555dc49f10, __args#0=..., __args#1=gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffb516: false, __args#3=@0x7fffffffb517: false, __args#4=9, __args#5=KMOD_NONE, __args#6="")
    at /usr/include/c++/7.2.0/bits/std_function.h:706
#12 0x0000555555eed6d1 in gui2::event::implementation::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, event_chain=std::vector of length 1, capacity 1 = {...}, dispatcher=0x55555e080d00, w=0x55555cffd1f0, params#0=@0x7fffffffb690: 9, params#1=@0x7fffffffb684: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:433
#13 0x0000555555eea716 in gui2::event::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, d=0x55555e080d10, w=0x55555cffd1f0, params#0=@0x7fffffffb690: 9, params#1=@0x7fffffffb684: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:505
#14 0x0000555555ee8609 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555e080d10, event=gui2::event::SDL_KEY_DOWN, target=..., key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/dispatcher.cpp:154
#15 0x0000555555f06870 in gui2::event::distributor::signal_handler_keyboard_internal<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const---Type <return> to continue, or q <return> to quit---
&>(gui2::event::ui_event, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555f716fa0, evt=gui2::event::SDL_KEY_DOWN, p1=@0x7fffffffb764: 9, p2=@0x7fffffffb760: KMOD_NONE, p3="") at src/gui/core/event/distributor.cpp:661
#16 0x0000555555f0474e in gui2::event::distributor::signal_handler_sdl_key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555f716fa0, key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/distributor.cpp:713
#17 0x0000555555f0fffb in std::__invoke_impl<void, void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__invoke_memfun_deref, void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__f=
    @0x55555efeab50: (void (gui2::event::distributor::*)(gui2::event::distributor * const, int, SDL_Keymod, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x555555f04718 <gui2::event::distributor::signal_handler_sdl_key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, __t=@0x55555efeab60: 0x55555f716fa0, __args#0=@0x7fffffffba68: 9, __args#1=@0x7fffffffbac0: KMOD_NONE, __args#2="") at /usr/include/c++/7.2.0/bits/invoke.h:73
#18 0x0000555555f0f62e in std::__invoke<void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__fn=
    @0x55555efeab50: (void (gui2::event::distributor::*)(gui2::event::distributor * const, int, SDL_Keymod, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x555555f04718 <gui2::event::distributor::signal_handler_sdl_key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, __args#0=@0x55555efeab60: 0x55555f716fa0, __args#1=@0x7fffffffba68: 9, __args#2=@0x7fffffffbac0: KMOD_NONE, __args#3="") at /usr/include/c++/7.2.0/bits/invoke.h:95
#19 0x0000555555f0e963 in std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::__call<void, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, 0ul, 1ul, 2ul, 3ul>(std::tuple<gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x55555efeab50, __args=...) at /usr/include/c++/7.2.0/functional:467
#20 0x0000555555f0ce1e in std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()<gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void>(gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555efeab50, __args#0=..., __args#1=@0x7fffffffba6c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffbb16: false, __args#3=@0x7fffffffbb17: false, __args#4=@0x7fffffffba68: 9, __args#5=@0x7fffffffbac0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/functional:551
#21 0x0000555555f0aa35 in std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__functor=..., __args#0=..., __args#1=@0x7fffffffba6c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffbb16: false, __args#3=@0x7fffffffbb17: false, __args#4=@0x7fffffffba68: 9, __args#5=@0x7fffffffbac0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/bits/std_function.h:316
#22 0x0000555555ef2633 in std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x55555efeab20, __args#0=..., __args#1=gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffbb16: false, __args#3=@0x7fffffffbb17: false, __args#4=9, __args#5=KMOD_NONE, __args#6="")
    at /usr/include/c++/7.2.0/bits/std_function.h:706
#23 0x0000555555eed6d1 in gui2::event::implementation::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, event_chain=std::vector of length 1, capacity 1 = {...}, dispatcher=0x55555e080d00, w=0x55555e080d00, params#0=@0x7fffffffbc90: 9, params#1=@0x7fffffffbc84: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:433
#24 0x0000555555eea716 in gui2::event::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, d=0x55555e080d10, w=0x55555e080d00, params#0=@0x7fffffffbc90: 9, params#1=@0x7fffffffbc84: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:505
#25 0x0000555555ee8609 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555e080d10, event=gui2::event::SDL_KEY_DOWN, target=..., key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/dispatcher.cpp:154
#26 0x00005555558e7c32 in gui2::event::sdl_event_handler::key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x555557c60c80, key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/handler.cpp:758
#27 0x00005555558e7925 in gui2::event::sdl_event_handler::key_down(SDL_Event const&) (this=0x555557c60c80, event=...) at src/gui/core/event/handler.cpp:715
#28 0x00005555558e64d7 in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) (this=0x555557c60c80, event=...) at src/gui/core/event/handler.cpp:413
#29 0x000055555661aa47 in events::pump() () at src/events.cpp:616
---Type <return> to continue, or q <return> to quit---
#30 0x0000555555a22e81 in gui2::window::show(bool, unsigned int) (this=0x55555e080d00, restore=false, auto_close_timeout=0) at src/gui/widgets/window.cpp:612
#31 0x000055555590aff0 in gui2::dialogs::modal_dialog::show(CVideo&, unsigned int) (this=0x7fffffffc220, video=..., auto_close_time=0) at src/gui/dialogs/modal_dialog.cpp:89
#32 0x0000555555fa3190 in gui2::dialogs::lua_interpreter::display(CVideo&, lua_kernel_base*) (video=..., lk=0x7fffe185a010) at src/gui/dialogs/lua_interpreter.cpp:689
#33 0x0000555555fa3230 in gui2::dialogs::lua_interpreter::display(CVideo&, gui2::dialogs::lua_interpreter::WHICH_KERNEL) (video=..., which=gui2::dialogs::lua_interpreter::GAME)
    at src/gui/dialogs/lua_interpreter.cpp:697
#34 0x0000555556648a75 in hotkey::command_executor_default::lua_console() (this=0x555557db01a0) at src/hotkey/command_executor.cpp:680
#35 0x0000555556646d4d in hotkey::command_executor::execute_command(hotkey::hotkey_command const&, int, bool) (this=0x555557db01a0, cmd=..., press=true)
    at src/hotkey/command_executor.cpp:334
#36 0x00005555563de3cf in play_controller::hotkey_handler::execute_command(hotkey::hotkey_command const&, int, bool) (this=0x555557db01a0, cmd=..., index=-1, press=true)
    at src/hotkey/hotkey_handler.cpp:263
#37 0x0000555556647ee7 in hotkey::execute_command(hotkey::hotkey_command const&, hotkey::command_executor*, int, bool) (command=..., executor=0x555557db01a0, index=-1, press=true)
    at src/hotkey/command_executor.cpp:533
#38 0x0000555556647dce in hotkey::event_execute(SDL_Event const&, hotkey::command_executor*) (event=..., executor=0x555557db01a0) at src/hotkey/command_executor.cpp:524
#39 0x0000555556647cc3 in hotkey::key_event(SDL_Event const&, hotkey::command_executor*) (event=..., executor=0x555557db01a0) at src/hotkey/command_executor.cpp:508
#40 0x0000555555dc3c6e in controller_base::handle_event(SDL_Event const&) (this=0x7fffffffce80, event=...) at src/controller_base.cpp:62
#41 0x000055555661aa47 in events::pump() () at src/events.cpp:616
#42 0x0000555555dc488c in controller_base::play_slice(bool) (this=0x7fffffffce80, is_delay_enabled=true) at src/controller_base.cpp:239
#43 0x00005555561b6fb0 in play_controller::play_slice_catch() (this=0x7fffffffce80) at src/play_controller.cpp:1062
#44 0x00005555561bc9a6 in playmp_controller::play_human_turn() (this=0x7fffffffce80) at src/playmp_controller.cpp:172
#45 0x00005555561c246b in playsingle_controller::play_side_impl() (this=0x7fffffffce80) at src/playsingle_controller.cpp:396
#46 0x00005555561bc1d9 in playmp_controller::play_side_impl() (this=0x7fffffffce80) at src/playmp_controller.cpp:86
#47 0x00005555561b7730 in play_controller::play_side() (this=0x7fffffffce80) at src/play_controller.cpp:1155
#48 0x00005555561b79ec in play_controller::play_turn() (this=0x7fffffffce80) at src/play_controller.cpp:1193
#49 0x00005555561c0985 in playsingle_controller::play_scenario_main_loop() (this=0x7fffffffce80) at src/playsingle_controller.cpp:190
#50 0x00005555561c130c in playsingle_controller::play_scenario(config const&) (this=0x7fffffffce80, level=...) at src/playsingle_controller.cpp:279
#51 0x0000555555ec3c10 in campaign_controller::playmp_scenario(end_level_data&) (this=0x7fffffffd530, end_level=...) at src/game_initialization/playcampaign.cpp:225
#52 0x0000555555ec3f49 in campaign_controller::play_game() (this=0x7fffffffd530) at src/game_initialization/playcampaign.cpp:288
#53 0x00005555558dec06 in game_launcher::launch_game(game_launcher::RELOAD_GAME_DATA) (this=0x5555573591c0, reload=game_launcher::RELOAD_DATA) at src/game_launcher.cpp:949
#54 0x00005555558474d8 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=std::vector of length 1, capacity 1 = {...}) at src/wesnoth.cpp:832
#55 0x0000555555847e2a in main(int, char**) (argc=1, argv=0x7fffffffe498) at src/wesnoth.cpp:1066
(gdb)
```


```
(gdb) bt full
#0  0x000055555646a955 in luaH_next(lua_State*, Table*, lua_TValue*) (L=0x7fffe219fe38, t=0x55555f4002a0, key=0x7fffe1f236a0) at src/lua/ltable.cpp:196
        i = 0
#1  0x000055555644cbe9 in lua_next(lua_State*, int) (L=0x7fffe219fe38, idx=1) at src/lua/lapi.cpp:1128
        t = 0x7fffe1f23690
        more = -1
#2  0x0000555555b0e204 in lua_kernel_base::get_attribute_names(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffe185a010, input="test_unit.") at src/scripting/lua_kernel_base.cpp:916
        top = 1
        obj = 1
        ret = std::vector of length 0, capacity 0
        base_path = "test_unit"
        last_dot = 9
        partial_name = ""
        load = "return test_unit"
        L = 0x7fffe219fe38
        save_stack = 0
        result = 0
#3  0x0000555555fa4526 in gui2::dialogs::lua_interpreter::lua_model::get_attribute_names(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555e352c20, s="test_unit.") at src/gui/dialogs/lua_interpreter.cpp:179
#4  0x0000555555fa2a0d in gui2::dialogs::lua_interpreter::controller::tab() (this=0x55555afae210) at src/gui/dialogs/lua_interpreter.cpp:622
        text = "test_unit."
        prefix = ""
        prefix_end_pos = 18446744073709551615
        static_matches = 
          std::vector of length 17, capacity 17 = {"and", "break", "else", "elseif", "end", "false", "for", "function", "local", "nil", "not", "repeat", "return", "then", "true", "until", "while"}
        matches = std::vector of length 0, capacity 0
#5  0x0000555555fa1a97 in gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, int, gui2::window&) (this=0x55555afae210, handled=@0x7fffffffb516: false, halt=@0x7fffffffb517: false, key=9, window=...) at src/gui/dialogs/lua_interpreter.cpp:527
        __PRETTY_FUNCTION__ = "void gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, SDL_Keycode, gui2::window&)"
#6  0x0000555555fa86b5 in std::__invoke_impl<void, void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int, gui2::window&>(std::__invoke_memfun_deref, void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int&&, gui2::window&) (__f=
    @0x55555dc4a1f0: (void (gui2::dialogs::lua_interpreter::controller::*)(gui2::dialogs::lua_interpreter::controller * const, bool &, bool &, int, gui2::window &)) 0x555555fa18e6 <gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, int, gui2::window&)>, __t=@0x55555dc4a208: 0x55555afae210, __args#0=@0x7fffffffb516: false, __args#1=@0x7fffffffb517: false, __args#2=@0x7fffffffb468: 9, __args#3=...) at /usr/include/c++/7.2.0/bits/invoke.h:73
#7  0x0000555555fa80f5 in std::__invoke<void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int, gui2::window&>(void (gui2::dialogs::lua_interpreter::controller::*&)(bool&, bool&, int, gui2::window&), gui2::dialogs::lua_interpreter::controller*&, bool&, bool&, int&&, gui2::window&) (__fn=
    @0x55555dc4a1f0: (void (gui2::dialogs::lua_interpreter::controller::*)(gui2::dialogs::lua_interpreter::controller * const, bool &, bool &, int, gui2::window &)) 0x555555fa18e6 <gui2::dialogs::lua_interpreter::controller::input_keypress_callback(bool&, bool&, int, gui2::window&)>, __args#0=@0x55555dc4a208: 0x55555afae210, __args#1=@0x7fffffffb516: false, __args#2=@0x7fffffffb517: false, __args#3=@0x7fffffffb468: 9, __args#4=...) at /usr/include/c++/7.2.0/bits/invoke.h:95
#8  0x0000555555fa7a3d in std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)>::__call<void, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, 0ul, 1ul, 2ul, 3ul, 4ul>(std::tuple<gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (this=0x55555dc4a1f0, __args=...) at /usr/include/c++/7.2.0/functional:467
#9  0x0000555555fa6eb4 in std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)>::operator()<gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void>(gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555dc4a1f0, __args#0=..., __args#1=@0x7fffffffb46c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffb516: false, __args#3=@0x7fffffffb517: false, __args#4=@0x7fffffffb468: 9, __args#5=@0x7fffffffb4c0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/functional:551
#10 0x0000555555fa63cc in std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allo---Type <return> to continue, or q <return> to quit---
cator<char> > const&), std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__functor=..., __args#0=..., __args#1=@0x7fffffffb46c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffb516: false, __args#3=@0x7fffffffb517: false, __args#4=@0x7fffffffb468: 9, __args#5=@0x7fffffffb4c0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/bits/std_function.h:316
#11 0x0000555555ef2633 in std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x55555dc49f10, __args#0=..., __args#1=gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffb516: false, __args#3=@0x7fffffffb517: false, __args#4=9, __args#5=KMOD_NONE, __args#6="")
    at /usr/include/c++/7.2.0/bits/std_function.h:706
#12 0x0000555555eed6d1 in gui2::event::implementation::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, event_chain=std::vector of length 1, capacity 1 = {...}, dispatcher=0x55555e080d00, w=0x55555cffd1f0, params#0=@0x7fffffffb690: 9, params#1=@0x7fffffffb684: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:433
        func = 
          @0x55555dc49f10: {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555dc4a1f0, _M_const_object = 0x55555dc4a1f0, _M_function_pointer = 0x55555dc4a1f0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555dc4a1f0, this adjustment 93825133748008}, _M_pod_data = "\360\241\304]UU\000\000(\237\304]UU\000"}, _M_manager = 0x555555fa63e0 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555fa6313 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}
        __for_range = 
            std::__cxx11::list = {[0] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555dc4a1f0, _M_const_object = 0x55555dc4a1f0, _M_function_pointer = 0x55555dc4a1f0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555dc4a1f0, this adjustment 93825133748008}, _M_pod_data = "\360\241\304]UU\000\000(\237\304]UU\000"}, _M_manager = 0x555555fa63e0 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555fa6313 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}, [1] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x555562320e20, _M_const_object = 0x555562320e20, _M_function_pointer = 0x555562320e20, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x555562320e20}, _M_pod_data = " \016\062bUU\000\000\000\000\000\000\000\000\000"}, _M_manager = 0x555555a10ee3 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::text_box_base::*(gui2::text_box_base*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>))(gui2::event::ui_event, bool&, int, SDL_Keymod)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555a10e16 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::text_box_base::*(gui2::text_box_base*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>))(gui2::event::ui_event, bool&, int, SDL_Keymod)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}}
        __for_begin = 
  {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555dc4a1f0, _M_const_object = 0x55555dc4a1f0, _M_function_pointer = 0x55555dc4a1f0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555dc4a1f0, this adjustment 93825133748008}, _M_pod_data = "\360\241\304]UU\000\000(\237\304]UU\000"}, _M_manager = 0x555555fa63e0 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555fa6313 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}
        __for_end = 
---Type <return> to continue, or q <return> to quit---
  {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x2, _M_const_object = 0x2, _M_function_pointer = 0x2, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x2, this adjustment 93825208028600}, _M_pod_data = "\002\000\000\000\000\000\000\000\270\r2bUU\000"}, _M_manager = 0x555562320db8}, _M_invoker = 0x0}
        signal = 
          @0x555562320d88: {pre_child = empty std::__cxx11::list, child = std::__cxx11::list = {[0] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555dc4a1f0, _M_const_object = 0x55555dc4a1f0, _M_function_pointer = 0x55555dc4a1f0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555dc4a1f0, this adjustment 93825133748008}, _M_pod_data = "\360\241\304]UU\000\000(\237\304]UU\000"}, _M_manager = 0x555555fa63e0 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555fa6313 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::dialogs::lua_interpreter::controller::*(gui2::dialogs::lua_interpreter::controller*, boost::arg<3>, boost::arg<4>, boost::arg<5>, std::reference_wrapper<gui2::window>))(bool&, bool&, int, gui2::window&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}, [1] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x555562320e20, _M_const_object = 0x555562320e20, _M_function_pointer = 0x555562320e20, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x555562320e20}, _M_pod_data = " \016\062bUU\000\000\000\000\000\000\000\000\000"}, _M_manager = 0x555555a10ee3 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::text_box_base::*(gui2::text_box_base*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>))(gui2::event::ui_event, bool&, int, SDL_Keymod)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555a10e16 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::text_box_base::*(gui2::text_box_base*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>))(gui2::event::ui_event, bool&, int, SDL_Keymod)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}}, post_child = empty std::__cxx11::list}
        __PRETTY_FUNCTION__ = "bool gui2::event::implementation::fire_event(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event> >&, gui2::widget*, gui2::widget*, F&& ...) [with T = std::function<void("...
        handled = false
        halt = false
#13 0x0000555555eea716 in gui2::event::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, d=0x55555e080d10, w=0x55555cffd1f0, params#0=@0x7fffffffb690: 9, params#1=@0x7fffffffb684: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:505
        __PRETTY_FUNCTION__ = "bool gui2::event::fire_event(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, F&& ...) [with T = std::function<void(gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, "...
        dispatcher_w = 0x55555e080d00
        event_chain = std::vector of length 1, capacity 1 = {{first = 0x55555e080d00, second = gui2::event::SDL_KEY_DOWN}}
#14 0x0000555555ee8609 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555e080d10, event=gui2::event::SDL_KEY_DOWN, target=..., key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/dispatcher.cpp:154
        __PRETTY_FUNCTION__ = "bool gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, SDL_Keycode, SDL_Keymod, const string&)"
#15 0x0000555555f06870 in gui2::event::distributor::signal_handler_keyboard_internal<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555f716fa0, evt=gui2::event::SDL_KEY_DOWN, p1=@0x7fffffffb764: 9, p2=@0x7fffffffb760: KMOD_NONE, p3="") at src/gui/core/event/distributor.cpp:661
        control = 0x55555cffd1f0
#16 0x0000555555f0474e in gui2::event::distributor::signal_handler_sdl_key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555f716fa0, key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/distributor.cpp:713
#17 0x0000555555f0fffb in std::__invoke_impl<void, void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__invoke_memfun_deref, void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__f=
    @0x55555efeab50: (void (gui2::event::distributor::*)(gui2::event::distributor * const, int, SDL_Keymod, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x555555f04718 <gui2::event::distributor::signal_handler_sdl_key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, __t=@0x55555efeab60: 0x55555f716fa0, __args#0=@0x7fffffffba68: 9, __args#1=@0x7fffffffbac0: KMOD_NONE, __args#2="") at /usr/include/c++/7.2.0/bits/invoke.h:73
---Type <return> to continue, or q <return> to quit---
#18 0x0000555555f0f62e in std::__invoke<void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(void (gui2::event::distributor::*&)(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), gui2::event::distributor*&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__fn=
    @0x55555efeab50: (void (gui2::event::distributor::*)(gui2::event::distributor * const, int, SDL_Keymod, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x555555f04718 <gui2::event::distributor::signal_handler_sdl_key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, __args#0=@0x55555efeab60: 0x55555f716fa0, __args#1=@0x7fffffffba68: 9, __args#2=@0x7fffffffbac0: KMOD_NONE, __args#3="") at /usr/include/c++/7.2.0/bits/invoke.h:95
#19 0x0000555555f0e963 in std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::__call<void, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, 0ul, 1ul, 2ul, 3ul>(std::tuple<gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x55555efeab50, __args=...) at /usr/include/c++/7.2.0/functional:467
#20 0x0000555555f0ce1e in std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()<gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void>(gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555efeab50, __args#0=..., __args#1=@0x7fffffffba6c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffbb16: false, __args#3=@0x7fffffffbb17: false, __args#4=@0x7fffffffba68: 9, __args#5=@0x7fffffffbac0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/functional:551
#21 0x0000555555f0aa35 in std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__functor=..., __args#0=..., __args#1=@0x7fffffffba6c: gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffbb16: false, __args#3=@0x7fffffffbb17: false, __args#4=@0x7fffffffba68: 9, __args#5=@0x7fffffffbac0: KMOD_NONE, __args#6="") at /usr/include/c++/7.2.0/bits/std_function.h:316
#22 0x0000555555ef2633 in std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x55555efeab20, __args#0=..., __args#1=gui2::event::SDL_KEY_DOWN, __args#2=@0x7fffffffbb16: false, __args#3=@0x7fffffffbb17: false, __args#4=9, __args#5=KMOD_NONE, __args#6="")
    at /usr/include/c++/7.2.0/bits/std_function.h:706
#23 0x0000555555eed6d1 in gui2::event::implementation::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, event_chain=std::vector of length 1, capacity 1 = {...}, dispatcher=0x55555e080d00, w=0x55555e080d00, params#0=@0x7fffffffbc90: 9, params#1=@0x7fffffffbc84: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:433
        func = 
          @0x55555efeab20: {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555efeab50, _M_const_object = 0x55555efeab50, _M_function_pointer = 0x55555efeab50, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555efeab50, this adjustment 93825133719632}, _M_pod_data = "P\253\376^UU\000\000P0\304]UU\000"}, _M_manager = 0x555555f0aa49 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555f0a97c <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}
        __for_range = 
            std::__cxx11::list = {[0] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555efeab50, _M_const_object = 0x55555efeab50, _M_function_pointer = 0x55555efeab50, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555efeab50, this adjustment 93825133719632}, _M_pod_data = "P\253\376^UU\000\000P0\304]UU\000"}, _M_manager = 0x555555f0aa49 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555f0a97c <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}, [1] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55556238b050, _M_const_object = 0x55556238b050, _M_function_pointer = 0x555562---Type <return> to continue, or q <return> to quit---
38b050, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55556238b050, this adjustment 93825154593912}, _M_pod_data = "P\260\070bUU\000\000x\264\002_UU\000"}, _M_manager = 0x555555a2f512 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::window::*(gui2::window*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>, bool))(gui2::event::ui_event, bool&, int, SDL_Keymod, bool)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555a2f445 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::window::*(gui2::window*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>, bool))(gui2::event::ui_event, bool&, int, SDL_Keymod, bool)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}}
        __for_begin = 
  {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555efeab50, _M_const_object = 0x55555efeab50, _M_function_pointer = 0x55555efeab50, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555efeab50, this adjustment 93825133719632}, _M_pod_data = "P\253\376^UU\000\000P0\304]UU\000"}, _M_manager = 0x555555f0aa49 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555f0a97c <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}
        __for_end = 
  {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x2, _M_const_object = 0x2, _M_function_pointer = 0x2, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x2, this adjustment 93825208463264}, _M_pod_data = "\002\000\000\000\000\000\000\000\240\257\070bUU\000"}, _M_manager = 0x55556238afa0}, _M_invoker = 0x1}
        signal = 
              @0x55555efeaab8: {pre_child = empty std::__cxx11::list, child = std::__cxx11::list = {[0] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555efeab50, _M_const_object = 0x55555efeab50, _M_function_pointer = 0x55555efeab50, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555efeab50, this adjustment 93825133719632}, _M_pod_data = "P\253\376^UU\000\000P0\304]UU\000"}, _M_manager = 0x555555f0aa49 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555f0a97c <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::event::distributor::*(gui2::event::distributor*, boost::arg<5>, boost::arg<6>, boost::arg<7>))(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}, [1] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55556238b050, _M_const_object = 0x55556238b050, _M_function_pointer = 0x55556238b050, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55556238b050, this adjustment 93825154593912}, _M_pod_data = "P\260\070bUU\000\000x\264\002_UU\000"}, _M_manager = 0x555555a2f512 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::window::*(gui2::window*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>, bool))(gui2::event::ui_event, bool&, int, SDL_Keymod, bool)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555a2f445 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::window::*(gui2::window*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>, bool))(gui2::event::ui_event, bool&, int, SDL_Keymod, bool)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}}, post_child = std::__cxx11::list = {[0] = {<std::_Maybe_unary_or_binary_function<void, gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55556238afe0, _M_const_object = 0x55556238afe0, _M_function_pointer = 0x55556238afe0, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55556238afe0, this adjustment 93825147571632}, _M_pod_data = "\340\257\070bUU\000\000\260\215\227^UU\000"}, _M_manager = 0x555555a2f512 <std::_Function_base::_Base_manager<std::_Bind<void (gui2::window::*(gui2::window*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>, bool))(gui2::event::ui_event, bool&, int, SDL_Keymod, bool)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555a2f445 <std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::_Bind<void (gui2::window::*(gui2::window*, boost::arg<2>, boost::arg<3>, boost::arg<5>, boost::arg<6>, bool))(gui2::event::ui_event, bool&, int, SDL_Keymod, bool)> >::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, int&&, SDL_Keymod&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>}}}
        __PRETTY_FUNCTION__ = "bool gui2::event::implementation::fire_event(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event> >&, gui2::widget*, gui2::widget*, F&& ...) [with T = std::function<void("...
        handled = false
        halt = false
---Type <return> to continue, or q <return> to quit---
#24 0x0000555555eea716 in gui2::event::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, int const&, SDL_Keymod const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (event=gui2::event::SDL_KEY_DOWN, d=0x55555e080d10, w=0x55555e080d00, params#0=@0x7fffffffbc90: 9, params#1=@0x7fffffffbc84: KMOD_NONE, params#2="") at src/gui/core/event/dispatcher_private.hpp:505
        __PRETTY_FUNCTION__ = "bool gui2::event::fire_event(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, F&& ...) [with T = std::function<void(gui2::widget&, gui2::event::ui_event, bool&, bool&, int, SDL_Keymod, "...
        dispatcher_w = 0x55555e080d00
        event_chain = std::vector of length 1, capacity 1 = {{first = 0x55555e080d00, second = gui2::event::SDL_KEY_DOWN}}
#25 0x0000555555ee8609 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555e080d10, event=gui2::event::SDL_KEY_DOWN, target=..., key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/dispatcher.cpp:154
        __PRETTY_FUNCTION__ = "bool gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, SDL_Keycode, SDL_Keymod, const string&)"
#26 0x00005555558e7c32 in gui2::event::sdl_event_handler::key_down(int, SDL_Keymod, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x555557c60c80, key=9, modifier=KMOD_NONE, unicode="") at src/gui/core/event/handler.cpp:758
        dispatcher = 0x55555e080d10
#27 0x00005555558e7925 in gui2::event::sdl_event_handler::key_down(SDL_Event const&) (this=0x555557c60c80, event=...) at src/gui/core/event/handler.cpp:715
        hk = std::shared_ptr (count 1, weak 0) 0x5555621b3340
        done = false
#28 0x00005555558e64d7 in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) (this=0x555557c60c80, event=...) at src/gui/core/event/handler.cpp:413
#29 0x000055555661aa47 in events::pump() () at src/events.cpp:616
        handler = 0x555557c60c80
        __for_range = std::__cxx11::list = {[0] = 0x555557c60c80}
        __for_begin = 0x555557c60c80
        __for_end = 0x1
        event = 
          @0x5555623086f0: {type = 768, common = {type = 768, timestamp = 122811052}, window = {type = 768, timestamp = 122811052, windowID = 2, event = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 43, data2 = 9}, key = {type = 768, timestamp = 122811052, windowID = 2, state = 1 '\001', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_TAB, sym = 9, mod = 0, unused = 32767}}, edit = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>, start = 0, length = 0}, text = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>}, motion = {type = 768, timestamp = 122811052, windowID = 2, which = 1, state = 43, x = 9, y = -291569664, xrel = 32767, yrel = 0}, button = {type = 768, timestamp = 122811052, windowID = 2, which = 1, button = 43 '+', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 9, y = -291569664}, wheel = {type = 768, timestamp = 122811052, windowID = 2, which = 1, x = 43, y = 9, direction = 4003397632}, jaxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, jball = {type = 768, timestamp = 122811052, which = 2, ball = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 43, yrel = 0}, jhat = {type = 768, timestamp = 122811052, which = 2, hat = 1 '\001', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 768, timestamp = 122811052, which = 2}, caxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, cbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 768, timestamp = 122811052, which = 2}, adevice = {type = 768, timestamp = 122811052, which = 2, iscapture = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 768, timestamp = 122811052}, user = {type = 768, timestamp = 122811052, windowID = 2, code = 1, data1 = 0x90000002b, data2 = 0x7fffee9f0000 <_XimForwardEventCallback+16>}, syswm = {type = 768, timestamp = 122811052, msg = 0x100000002}, tfinger = {type = 768, timestamp = 122811052, touchId = 4294967298, fingerId = 38654705707, x = -2.46040583e+28, y = 4.59163468e-41, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, dTheta = 6.0255834e-44, dDist = 1.26116862e-44, x = -2.46040583e+28, y = 4.59163468e-41, numFingers = 0, padding = 0}, dgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, gestureId = 38654705707, numFingers = 4003397632, error = 4.59163468e-41, x = 0, y = 0}, drop = {type = 768, timestamp = 122811052, file = 0x100000002 <error: Cannot access memory at address 0x100000002>, windowID = 43}, padding = "\000\003\000\000\254\362Q\a\002\000\000\000\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 25 times>}
        info = {resize_dimensions = {first = 0, second = 0}, ticks_ = 0}
        last_mouse_down = 120830884
        last_click_x = 310
        last_click_y = 984
        temp_event = 
          {type = 768, common = {type = 768, timestamp = 122811052}, window = {type = 768, timestamp = 122811052, windowID = 2, event = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 43, data2 = 9}, key = {type = 768, timestamp = 122811052, windowID = 2, state = 1 '\001', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_TAB, sym = 9, mod = 0, unused = 32767}}, edit = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>, start = 0, length = 0}, text = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>}, motion = {type = 768, timestamp = 122811052, windowID = 2, which = 1, state = 43, x = 9, y = -291569664, xrel = 32767, yrel = 0}, button = {type = 768, timest---Type <return> to continue, or q <return> to quit---
amp = 122811052, windowID = 2, which = 1, button = 43 '+', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 9, y = -291569664}, wheel = {type = 768, timestamp = 122811052, windowID = 2, which = 1, x = 43, y = 9, direction = 4003397632}, jaxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, jball = {type = 768, timestamp = 122811052, which = 2, ball = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 43, yrel = 0}, jhat = {type = 768, timestamp = 122811052, which = 2, hat = 1 '\001', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 768, timestamp = 122811052, which = 2}, caxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, cbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 768, timestamp = 122811052, which = 2}, adevice = {type = 768, timestamp = 122811052, which = 2, iscapture = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 768, timestamp = 122811052}, user = {type = 768, timestamp = 122811052, windowID = 2, code = 1, data1 = 0x90000002b, data2 = 0x7fffee9f0000 <_XimForwardEventCallback+16>}, syswm = {type = 768, timestamp = 122811052, msg = 0x100000002}, tfinger = {type = 768, timestamp = 122811052, touchId = 4294967298, fingerId = 38654705707, x = -2.46040583e+28, y = 4.59163468e-41, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, dTheta = 6.0255834e-44, dDist = 1.26116862e-44, x = -2.46040583e+28, y = 4.59163468e-41, numFingers = 0, padding = 0}, dgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, gestureId = 38654705707, numFingers = 4003397632, error = 4.59163468e-41, x = 0, y = 0}, drop = {type = 768, timestamp = 122811052, file = 0x100000002 <error: Cannot access memory at address 0x100000002>, windowID = 43}, padding = "\000\003\000\000\254\362Q\a\002\000\000\000\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 25 times>}
        poll_count = 4
        begin_ignoring = 0
        events = 
            std::vector of length 4, capacity 4 = {{type = 32769, common = {type = 32769, timestamp = 122811039}, window = {type = 32769, timestamp = 122811039, windowID = 4139793888, event = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 4443, data2 = 0}, key = {type = 32769, timestamp = 122811039, windowID = 4139793888, state = 0 '\000', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = 4443, sym = 0, mod = 0, unused = 0}}, edit = {type = 32769, timestamp = 122811039, windowID = 4139793888, text = "\000\000\000\000[\021", '\000' <repeats 14 times>, "\350\303\006\000\000\000\000\000h\004\062\066", start = 0, length = -155173408}, text = {type = 32769, timestamp = 122811039, windowID = 4139793888, text = "\000\000\000\000[\021", '\000' <repeats 14 times>, "\350\303\006\000\000\000\000\000h\004\062\066"}, motion = {type = 32769, timestamp = 122811039, windowID = 4139793888, which = 0, state = 4443, x = 0, y = 0, xrel = 0, yrel = 443368}, button = {type = 32769, timestamp = 122811039, windowID = 4139793888, which = 0, button = 91 '[', state = 17 '\021', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 32769, timestamp = 122811039, windowID = 4139793888, which = 0, x = 4443, y = 0, direction = 0}, jaxis = {type = 32769, timestamp = 122811039, which = -155173408, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 4443, padding4 = 0}, jball = {type = 32769, timestamp = 122811039, which = -155173408, ball = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 4443, yrel = 0}, jhat = {type = 32769, timestamp = 122811039, which = -155173408, hat = 0 '\000', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 32769, timestamp = 122811039, which = -155173408, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 32769, timestamp = 122811039, which = -155173408}, caxis = {type = 32769, timestamp = 122811039, which = -155173408, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 4443, padding4 = 0}, cbutton = {type = 32769, timestamp = 122811039, which = -155173408, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 32769, timestamp = 122811039, which = -155173408}, adevice = {type = 32769, timestamp = 122811039, which = 4139793888, iscapture = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 32769, timestamp = 122811039}, user = {type = 32769, timestamp = 122811039, windowID = 4139793888, code = 0, data1 = 0x115b, data2 = 0x0}, syswm = {type = 32769, timestamp = 122811039, msg = 0xf6c03de0}, tfinger = {type = 32769, timestamp = 122811039, touchId = 4139793888, fingerId = 4443, x = 0, y = 0, dx = 6.21290898e-40, dy = 0, pressure = 2.65266317e-06}, mgesture = {type = 32769, timestamp = 122811039, touchId = 4139793888, dTheta = 6.22596908e-42, dDist = 0, x = 0, y = 0, numFingers = 50152, padding = 6}, dgesture = {type = 32769, timestamp = 122811039, touchId = 4139793888, gestureId = 4443, numFingers = 0, error = 0, x = 6.21290898e-40, y = 0}, drop = {type = 32769, timestamp = 122811039, file = 0xf6c03de0 <error: Cannot access memory at address 0xf6c03de0>, windowID = 4443}, padding = "\001\200\000\000\237\362Q\a\340=\300\366\000\000\000\000[\021", '\000' <repeats 14 times>, "\350\303\006\000\000\000\000\000h\004\062\066\000\000\000\000\340=\300\366\377\177\000"}, {type = 513, common = {type = 513, timestamp = 122811052}, window = {type = 513, timestamp = 122811052, windowID = 1464838448, event = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 513, timestamp = 122811052, windowID = 1464838448, state = 85 'U', repeat = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 513, timestamp = 122811052, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>, start = 0, length = 0}, text = {type = 513, timestamp = 122811052, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>}, motion = {type = 513, timestamp = 122811052, windowID = 1464838448, which = 21845, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 513, timestamp = 122811052, windowID = 1464838448, which = 21845, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 513, timestamp = 122811052, windowID = 1464838448, which = 21845, x = 0, y = 0, direction = 0}, jaxis = {type = 513, timestamp = 122811052, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 513, timestamp = 122811052, which = 1464838448, ball = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 513, timestamp = 122811052, which = 1464838448, hat = 85 'U', value = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 513, timestamp = 122811052, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 513, timestamp = 122811052, which = 1464838448}, caxis = {type = 513, timestamp = 122811052, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 513, timestamp = 122811052, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 513, timestamp = 122811052, which = 1464838448}, adevice = {type = 513, timestamp = 122811052, which = 1464838448, iscapture = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 513, timestamp = 122811052}, user = {type = 513, timestamp = 122811052, windowID = 1464838448, code = 21845, data1 = 0x0, data2 = 0x0}, syswm = {type = 513, timestamp = 122811052, msg = 0x5555574fa930}, tfinger = {type = 513, timestamp = 122811052, touchId = 93825025419568, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 513, timestamp = 122811052, touchId = 93825025419568, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 513, timestamp = 122811052, touchId = 93825025419568, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 513, timestamp = 122811052, file = 0x5555574fa930 "\002", windowID = 0}, padding = "\001\002\000\000\254\362Q\a0\251OWUU", '\000' <repeats 41 times>}, {type = 768, common = {type = 768, timestamp = 122811052}, window = {type = 768, timestamp = 122811052, windowID = 2, event = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 43,---Type <return> to continue, or q <return> to quit---
 data2 = 9}, key = {type = 768, timestamp = 122811052, windowID = 2, state = 1 '\001', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_TAB, sym = 9, mod = 0, unused = 32767}}, edit = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>, start = 0, length = 0}, text = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>}, motion = {type = 768, timestamp = 122811052, windowID = 2, which = 1, state = 43, x = 9, y = -291569664, xrel = 32767, yrel = 0}, button = {type = 768, timestamp = 122811052, windowID = 2, which = 1, button = 43 '+', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 9, y = -291569664}, wheel = {type = 768, timestamp = 122811052, windowID = 2, which = 1, x = 43, y = 9, direction = 4003397632}, jaxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, jball = {type = 768, timestamp = 122811052, which = 2, ball = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 43, yrel = 0}, jhat = {type = 768, timestamp = 122811052, which = 2, hat = 1 '\001', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 768, timestamp = 122811052, which = 2}, caxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, cbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 768, timestamp = 122811052, which = 2}, adevice = {type = 768, timestamp = 122811052, which = 2, iscapture = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 768, timestamp = 122811052}, user = {type = 768, timestamp = 122811052, windowID = 2, code = 1, data1 = 0x90000002b, data2 = 0x7fffee9f0000 <_XimForwardEventCallback+16>}, syswm = {type = 768, timestamp = 122811052, msg = 0x100000002}, tfinger = {type = 768, timestamp = 122811052, touchId = 4294967298, fingerId = 38654705707, x = -2.46040583e+28, y = 4.59163468e-41, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, dTheta = 6.0255834e-44, dDist = 1.26116862e-44, x = -2.46040583e+28, y = 4.59163468e-41, numFingers = 0, padding = 0}, dgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, gestureId = 38654705707, numFingers = 4003397632, error = 4.59163468e-41, x = 0, y = 0}, drop = {type = 768, timestamp = 122811052, file = 0x100000002 <error: Cannot access memory at address 0x100000002>, windowID = 43}, padding = "\000\003\000\000\254\362Q\a\002\000\000\000\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 25 times>}, {type = 32771, common = {type = 32771, timestamp = 122811051}, window = {type = 32771, timestamp = 122811051, windowID = 0, event = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 32771, timestamp = 122811051, windowID = 0, state = 0 '\000', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 32771, timestamp = 122811051, windowID = 0, text = '\000' <repeats 20 times>, "\350\303\006\000\000\000\000\000\065!\353\066", start = 0, length = -155173408}, text = {type = 32771, timestamp = 122811051, windowID = 0, text = '\000' <repeats 20 times>, "\350\303\006\000\000\000\000\000\065!\353\066"}, motion = {type = 32771, timestamp = 122811051, windowID = 0, which = 0, state = 0, x = 0, y = 0, xrel = 0, yrel = 443368}, button = {type = 32771, timestamp = 122811051, windowID = 0, which = 0, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 32771, timestamp = 122811051, windowID = 0, which = 0, x = 0, y = 0, direction = 0}, jaxis = {type = 32771, timestamp = 122811051, which = 0, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 32771, timestamp = 122811051, which = 0, ball = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 32771, timestamp = 122811051, which = 0, hat = 0 '\000', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 32771, timestamp = 122811051, which = 0, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 32771, timestamp = 122811051, which = 0}, caxis = {type = 32771, timestamp = 122811051, which = 0, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 32771, timestamp = 122811051, which = 0, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 32771, timestamp = 122811051, which = 0}, adevice = {type = 32771, timestamp = 122811051, which = 0, iscapture = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 32771, timestamp = 122811051}, user = {type = 32771, timestamp = 122811051, windowID = 0, code = 0, data1 = 0x0, data2 = 0x0}, syswm = {type = 32771, timestamp = 122811051, msg = 0x0}, tfinger = {type = 32771, timestamp = 122811051, touchId = 0, fingerId = 0, x = 0, y = 0, dx = 6.21290898e-40, dy = 0, pressure = 7.00741157e-06}, mgesture = {type = 32771, timestamp = 122811051, touchId = 0, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 50152, padding = 6}, dgesture = {type = 32771, timestamp = 122811051, touchId = 0, gestureId = 0, numFingers = 0, error = 0, x = 6.21290898e-40, y = 0}, drop = {type = 32771, timestamp = 122811051, file = 0x0, windowID = 0}, padding = "\003\200\000\000\253\362Q\a", '\000' <repeats 24 times>, "\350\303\006\000\000\000\000\000\065!\353\066\000\000\000\000\340=\300\366\377\177\000"}}
        ev_it = 
  {type = 768, common = {type = 768, timestamp = 122811052}, window = {type = 768, timestamp = 122811052, windowID = 2, event = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 43, data2 = 9}, key = {type = 768, timestamp = 122811052, windowID = 2, state = 1 '\001', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_TAB, sym = 9, mod = 0, unused = 32767}}, edit = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>, start = 0, length = 0}, text = {type = 768, timestamp = 122811052, windowID = 2, text = "\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>}, motion = {type = 768, timestamp = 122811052, windowID = 2, which = 1, state = 43, x = 9, y = -291569664, xrel = 32767, yrel = 0}, button = {type = 768, timestamp = 122811052, windowID = 2, which = 1, button = 43 '+', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 9, y = -291569664}, wheel = {type = 768, timestamp = 122811052, windowID = 2, which = 1, x = 43, y = 9, direction = 4003397632}, jaxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, jball = {type = 768, timestamp = 122811052, which = 2, ball = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 43, yrel = 0}, jhat = {type = 768, timestamp = 122811052, which = 2, hat = 1 '\001', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 768, timestamp = 122811052, which = 2}, caxis = {type = 768, timestamp = 122811052, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 43, padding4 = 0}, cbutton = {type = 768, timestamp = 122811052, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 768, timestamp = 122811052, which = 2}, adevice = {type = 768, timestamp = 122811052, which = 2, iscapture = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 768, timestamp = 122811052}, user = {type = 768, timestamp = 122811052, windowID = 2, code = 1, data1 = 0x90000002b, data2 = 0x7fffee9f0000 <_XimForwardEventCallback+16>}, syswm = {type = 768, timestamp = 122811052, msg = 0x100000002}, tfinger = {type = 768, timestamp = 122811052, touchId = 4294967298, fingerId = 38654705707, x = -2.46040583e+28, y = 4.59163468e-41, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, dTheta = 6.0255834e-44, dDist = 1.26116862e-44, x = -2.46040583e+28, y = 4.59163468e-41, numFingers = 0, padding = 0}, dgesture = {type = 768, timestamp = 122811052, touchId = 4294967298, gestureId = 38654705707, numFingers = 4003397632, error = 4.59163468e-41, x = 0, y = 0}, drop = {type = 768, timestamp = 122811052, file = 0x100000002 <error: Cannot access memory at address 0x100000002>, windowID = 43}, ---Type <return> to continue, or q <return> to quit---
padding = "\000\003\000\000\254\362Q\a\002\000\000\000\001\000\000\000+\000\000\000\t\000\000\000\000\000\237\356\377\177", '\000' <repeats 25 times>}
        ev_end = 
  {type = 0, common = {type = 0, timestamp = 0}, window = {type = 0, timestamp = 0, windowID = 129, event = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = -206284040, data2 = 32767}, key = {type = 0, timestamp = 0, windowID = 129, state = 0 '\000', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = 4088683256, sym = 32767, mod = 0, unused = 32767}}, edit = {type = 0, timestamp = 0, windowID = 129, text = "\000\000\000\000\370Z\264\363\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000x\207\060b", start = 21845, length = 1647347576}, text = {type = 0, timestamp = 0, windowID = 129, text = "\000\000\000\000\370Z\264\363\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000x\207\060b"}, motion = {type = 0, timestamp = 0, windowID = 129, which = 0, state = 4088683256, x = 32767, y = 0, xrel = 32767, yrel = 0}, button = {type = 0, timestamp = 0, windowID = 129, which = 0, button = 248 '\370', state = 90 'Z', clicks = 180 '\264', padding1 = 243 '\363', x = 32767, y = 0}, wheel = {type = 0, timestamp = 0, windowID = 129, which = 0, x = -206284040, y = 32767, direction = 0}, jaxis = {type = 0, timestamp = 0, which = 129, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 23288, padding4 = 62388}, jball = {type = 0, timestamp = 0, which = 129, ball = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 23288, yrel = -3148}, jhat = {type = 0, timestamp = 0, which = 129, hat = 0 '\000', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 0, timestamp = 0, which = 129, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 0, timestamp = 0, which = 129}, caxis = {type = 0, timestamp = 0, which = 129, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 23288, padding4 = 62388}, cbutton = {type = 0, timestamp = 0, which = 129, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 0, timestamp = 0, which = 129}, adevice = {type = 0, timestamp = 0, which = 129, iscapture = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 0, timestamp = 0}, user = {type = 0, timestamp = 0, windowID = 129, code = 0, data1 = 0x7ffff3b45af8 <main_arena+88>, data2 = 0x7fff00000000}, syswm = {type = 0, timestamp = 0, msg = 0x81}, tfinger = {type = 0, timestamp = 0, touchId = 129, fingerId = 140737282071288, x = 0, y = 4.59163468e-41, dx = 0, dy = 0, pressure = 8.14097127e+20}, mgesture = {type = 0, timestamp = 0, touchId = 129, dTheta = -2.85784454e+31, dDist = 4.59163468e-41, x = 0, y = 4.59163468e-41, numFingers = 0, padding = 0}, dgesture = {type = 0, timestamp = 0, touchId = 129, gestureId = 140737282071288, numFingers = 0, error = 4.59163468e-41, x = 0, y = 0}, drop = {type = 0, timestamp = 0, file = 0x81 <error: Cannot access memory at address 0x81>, windowID = 4088683256}, padding = "\000\000\000\000\000\000\000\000\201\000\000\000\000\000\000\000\370Z\264\363\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000x\207\060bUU\000\000x\207\060bUU\000"}
        resize_found = false
        first_draw_event = 
  {type = 32771, common = {type = 32771, timestamp = 122811051}, window = {type = 32771, timestamp = 122811051, windowID = 0, event = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 32771, timestamp = 122811051, windowID = 0, state = 0 '\000', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 32771, timestamp = 122811051, windowID = 0, text = '\000' <repeats 20 times>, "\350\303\006\000\000\000\000\000\065!\353\066", start = 0, length = -155173408}, text = {type = 32771, timestamp = 122811051, windowID = 0, text = '\000' <repeats 20 times>, "\350\303\006\000\000\000\000\000\065!\353\066"}, motion = {type = 32771, timestamp = 122811051, windowID = 0, which = 0, state = 0, x = 0, y = 0, xrel = 0, yrel = 443368}, button = {type = 32771, timestamp = 122811051, windowID = 0, which = 0, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 32771, timestamp = 122811051, windowID = 0, which = 0, x = 0, y = 0, direction = 0}, jaxis = {type = 32771, timestamp = 122811051, which = 0, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 32771, timestamp = 122811051, which = 0, ball = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 32771, timestamp = 122811051, which = 0, hat = 0 '\000', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 32771, timestamp = 122811051, which = 0, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 32771, timestamp = 122811051, which = 0}, caxis = {type = 32771, timestamp = 122811051, which = 0, axis = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 32771, timestamp = 122811051, which = 0, button = 0 '\000', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 32771, timestamp = 122811051, which = 0}, adevice = {type = 32771, timestamp = 122811051, which = 0, iscapture = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 32771, timestamp = 122811051}, user = {type = 32771, timestamp = 122811051, windowID = 0, code = 0, data1 = 0x0, data2 = 0x0}, syswm = {type = 32771, timestamp = 122811051, msg = 0x0}, tfinger = {type = 32771, timestamp = 122811051, touchId = 0, fingerId = 0, x = 0, y = 0, dx = 6.21290898e-40, dy = 0, pressure = 7.00741157e-06}, mgesture = {type = 32771, timestamp = 122811051, touchId = 0, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 50152, padding = 6}, dgesture = {type = 32771, timestamp = 122811051, touchId = 0, gestureId = 0, numFingers = 0, error = 0, x = 6.21290898e-40, y = 0}, drop = {type = 32771, timestamp = 122811051, file = 0x0, windowID = 0}, padding = "\003\200\000\000\253\362Q\a", '\000' <repeats 24 times>, "\350\303\006\000\000\000\000\000\065!\353\066\000\000\000\000\340=\300\366\377\177\000"}
#30 0x0000555555a22e81 in gui2::window::show(bool, unsigned int) (this=0x55555e080d00, restore=false, auto_close_timeout=0) at src/gui/widgets/window.cpp:612
        mouse_button_state_initialized = true
        scope_logging_object__ = 
          {ticks_ = {<boost::date_time::base_time<boost::posix_time::ptime, boost::date_time::counted_time_system<boost::date_time::counted_time_rep<boost::posix_time::millisec_posix_time_system_config> > >> = {<boost::operators_impl::less_than_comparable<boost::posix_time::ptime, boost::operators_impl::equality_comparable<boost::posix_time::ptime, boost::posix_time::ptime, boost::operators_impl::operators_detail::empty_base<boost::posix_time::ptime>, boost::operators_impl::operators_detail::false_t>, boost::operators_impl::operators_detail::empty_base<boost::posix_time::ptime>, boost::operators_impl::operators_detail::true_t>> = {<boost::operators_impl::less_than_comparable1<boost::posix_time::ptime, boost::operators_impl::equality_comparable<boost::posix_time::ptime, boost::posix_time::ptime, boost::operators_impl::operators_detail::empty_base<boost::posix_time::ptime>, boost::operators_impl::operators_detail::false_t> >> = {<boost::operators_impl::equality_comparable<boost::posix_time::ptime, boost::posix_time::ptime, boost::operators_impl::operators_detail::empty_base<boost::posix_time::ptime>, boost::operators_impl::operators_detail::false_t>> = {<boost::operators_impl::equality_comparable1<boost::posix_time::ptime, boost::operators_impl::operators_detail::empty_base<boost::posix_time::ptime> >> = {<boost::operators_impl::operators_detail::empty_base<boost::posix_time::ptime>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, time_ = {time_count_ = {value_ = 9223372036854775806}}}, <No data fields>}, output_ = 0x0, str_ = ""}
        __func__ = "show"
---Type <return> to continue, or q <return> to quit---
        __PRETTY_FUNCTION__ = "int gui2::window::show(bool, unsigned int)"
        draw_interval_setter = {interval_ = 0}
#31 0x000055555590aff0 in gui2::dialogs::modal_dialog::show(CVideo&, unsigned int) (this=0x7fffffffc220, video=..., auto_close_time=0) at src/gui/dialogs/modal_dialog.cpp:89
        push_window_stack = {local_window = std::unique_ptr<gui2::window> containing 0x55555e080d00}
        __PRETTY_FUNCTION__ = "bool gui2::dialogs::modal_dialog::show(CVideo&, unsigned int)"
#32 0x0000555555fa3190 in gui2::dialogs::lua_interpreter::display(CVideo&, lua_kernel_base*) (video=..., lk=0x7fffe185a010) at src/gui/dialogs/lua_interpreter.cpp:689
#33 0x0000555555fa3230 in gui2::dialogs::lua_interpreter::display(CVideo&, gui2::dialogs::lua_interpreter::WHICH_KERNEL) (video=..., which=gui2::dialogs::lua_interpreter::GAME)
    at src/gui/dialogs/lua_interpreter.cpp:697
#34 0x0000555556648a75 in hotkey::command_executor_default::lua_console() (this=0x555557db01a0) at src/hotkey/command_executor.cpp:680
#35 0x0000555556646d4d in hotkey::command_executor::execute_command(hotkey::hotkey_command const&, int, bool) (this=0x555557db01a0, cmd=..., press=true)
    at src/hotkey/command_executor.cpp:334
#36 0x00005555563de3cf in play_controller::hotkey_handler::execute_command(hotkey::hotkey_command const&, int, bool) (this=0x555557db01a0, cmd=..., index=-1, press=true)
    at src/hotkey/hotkey_handler.cpp:263
        command = hotkey::LUA_CONSOLE
        prefixlen = 9
#37 0x0000555556647ee7 in hotkey::execute_command(hotkey::hotkey_command const&, hotkey::command_executor*, int, bool) (command=..., executor=0x555557db01a0, index=-1, press=true)
    at src/hotkey/command_executor.cpp:533
        __PRETTY_FUNCTION__ = "void hotkey::execute_command(const hotkey::hotkey_command&, hotkey::command_executor*, int, bool)"
#38 0x0000555556647dce in hotkey::event_execute(SDL_Event const&, hotkey::command_executor*) (event=..., executor=0x555557db01a0) at src/hotkey/command_executor.cpp:524
        hk = std::shared_ptr (count 2, weak 0) 0x7fffe051e910
        press = true
#39 0x0000555556647cc3 in hotkey::key_event(SDL_Event const&, hotkey::command_executor*) (event=..., executor=0x555557db01a0) at src/hotkey/command_executor.cpp:508
#40 0x0000555555dc3c6e in controller_base::handle_event(SDL_Event const&) (this=0x7fffffffce80, event=...) at src/controller_base.cpp:62
        new_event = 
          {type = 4294952192, common = {type = 4294952192, timestamp = 32767}, window = {type = 4294952192, timestamp = 32767, windowID = 1449260204, event = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = -15040, data2 = 32767}, key = {type = 4294952192, timestamp = 32767, windowID = 1449260204, state = 85 'U', repeat = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = 4294952256, sym = 32767, mod = 42688, unused = 21845}}, edit = {type = 4294952192, timestamp = 32767, windowID = 1449260204, text = "UU\000\000@\305\377\377\377\177\000\000\300\246\316WUU\000\000 \305\377\377\377\177\000\000t\330aV", start = 21845, length = -15040}, text = {type = 4294952192, timestamp = 32767, windowID = 1449260204, text = "UU\000\000@\305\377\377\377\177\000\000\300\246\316WUU\000\000 \305\377\377\377\177\000\000t\330aV"}, motion = {type = 4294952192, timestamp = 32767, windowID = 1449260204, which = 21845, state = 4294952256, x = 32767, y = 1473160896, xrel = 21845, yrel = -15072}, button = {type = 4294952192, timestamp = 32767, windowID = 1449260204, which = 21845, button = 64 '@', state = 197 '\305', clicks = 255 '\377', padding1 = 255 '\377', x = 32767, y = 1473160896}, wheel = {type = 4294952192, timestamp = 32767, windowID = 1449260204, which = 21845, x = -15040, y = 32767, direction = 1473160896}, jaxis = {type = 4294952192, timestamp = 32767, which = 1449260204, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = -15040, padding4 = 65535}, jball = {type = 4294952192, timestamp = 32767, which = 1449260204, ball = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', xrel = -15040, yrel = -1}, jhat = {type = 4294952192, timestamp = 32767, which = 1449260204, hat = 85 'U', value = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 4294952192, timestamp = 32767, which = 1449260204, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 4294952192, timestamp = 32767, which = 1449260204}, caxis = {type = 4294952192, timestamp = 32767, which = 1449260204, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = -15040, padding4 = 65535}, cbutton = {type = 4294952192, timestamp = 32767, which = 1449260204, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 4294952192, timestamp = 32767, which = 1449260204}, adevice = {type = 4294952192, timestamp = 32767, which = 1449260204, iscapture = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 4294952192, timestamp = 32767}, user = {type = 4294952192, timestamp = 32767, windowID = 1449260204, code = 21845, data1 = 0x7fffffffc540, data2 = 0x555557cea6c0}, syswm = {type = 4294952192, timestamp = 32767, msg = 0x55555661f4ac <__gnu_cxx::__aligned_membuf<events::sdl_handler*>::_M_ptr()+24>}, tfinger = {type = 4294952192, timestamp = 32767, touchId = 93825009841324, fingerId = 140737488340288, x = 4.54431162e+14, y = 3.0611365e-41, dx = -nan(0x7fc520), dy = 4.59163468e-41, pressure = 6.20799438e+13}, mgesture = {type = 4294952192, timestamp = 32767, touchId = 93825009841324, dTheta = -nan(0x7fc540), dDist = 4.59163468e-41, x = 4.54431162e+14, y = 3.0611365e-41, numFingers = 50464, padding = 65535}, dgesture = {type = 4294952192, timestamp = 32767, touchId = 93825009841324, gestureId = 140737488340288, numFingers = 1473160896, error = 3.0611365e-41, x = -nan(0x7fc520), y = 4.59163468e-41}, drop = {type = 4294952192, timestamp = 32767, file = 0x55555661f4ac <__gnu_cxx::__aligned_membuf<events::sdl_handler*>::_M_ptr()+24> "\311\303UH\211\345H\203\354\020H\211}\370H\211u\360H\213E\370H\211\307\350l\231#\377H\213\020H+U\360H\211\020\220\311ÐUH\211\345H\211}\370H\211u\360H\213E\370H\213U\360H\211\020\220]\303UH\211\345H\211}\370]\303UH\211\345H\203\354 H\211}\370H\211u\360H\211U\350H\215U\360H\215E\370H\211\326H\211\307\350_\314\377\377\204\300t!H\213U\370H\215E\350H\211\326H\211\307\350`\027", windowID = 4294952256}, padding = "\000\305\377\377\377\177\000\000\254\364aVUU\000\000@\305\377\377\377\177\000\000\300\246\316WUU\000\000 \305\377\377\377\177\000\000t\330aVUU\000\000@\305\377\377\377\177\000"}
        quit_hotkey = 
            @0x555557696c20: {id = hotkey::HOTKEY_QUIT_GAME, command = "quit", description = {val_ = std::shared_ptr (count 1, weak 0) 0x5555575abdd0}, hidden = false, toggle = false, scope = std::bitset = {[1] = 1, [2] = 1}, category = hotkey::HKCAT_GENERAL, tooltip = {val_ = std::shared_ptr (count 1, weak 0) 0x5555575abe70}}
        mh_base = 
          @0x7fffffffcfb0: {_vptr.mouse_handler_base = 0x555557221b70 <vtable for events::mouse_handler+16>, simple_warp_ = false, minimap_scrolling_ = false, dragging_left_ = false, draggin---Type <return> to continue, or q <return> to quit---
g_started_ = false, dragging_right_ = false, drag_from_x_ = 966, drag_from_y_ = 465, drag_from_hex_ = {x = 11, y = 5}, last_hex_ = {x = 15, y = 3}, show_menu_ = false, scroll_start_x_ = 0, scroll_start_y_ = 0, scroll_started_ = false}
#41 0x000055555661aa47 in events::pump() () at src/events.cpp:616
        handler = 0x7fffffffce80
        __for_range = 
          std::__cxx11::list = {[0] = 0x7fffffffce80, [1] = 0x7fffe20e36c8, [2] = 0x55555b9a9a00, [3] = 0x55555c988fc0, [4] = 0x55555e740ad0, [5] = 0x555562288210, [6] = 0x55555aaee9d0, [7] = 0x555562335ec0, [8] = 0x555561cfeaa0, [9] = 0x55555cb378a0, [10] = 0x55555fdd61b0}
        __for_begin = 0x7fffffffce80
        __for_end = 0xb
        event = 
          @0x555561fcd820: {type = 771, common = {type = 771, timestamp = 121903337}, window = {type = 771, timestamp = 121903337, windowID = 2, event = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 771, timestamp = 121903337, windowID = 2, state = 96 '`', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020", start = -401652093, length = 1463149600}, text = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020"}, motion = {type = 771, timestamp = 121903337, windowID = 2, which = 96, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 771, timestamp = 121903337, windowID = 2, which = 96, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 771, timestamp = 121903337, windowID = 2, which = 96, x = 0, y = 0, direction = 0}, jaxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 771, timestamp = 121903337, which = 2, ball = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 771, timestamp = 121903337, which = 2, hat = 96 '`', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 771, timestamp = 121903337, which = 2}, caxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 771, timestamp = 121903337, which = 2}, adevice = {type = 771, timestamp = 121903337, which = 2, iscapture = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 771, timestamp = 121903337}, user = {type = 771, timestamp = 121903337, windowID = 2, code = 96, data1 = 0x0, data2 = 0x0}, syswm = {type = 771, timestamp = 121903337, msg = 0x6000000002}, tfinger = {type = 771, timestamp = 121903337, touchId = 412316860418, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 9.86153169e-29}, mgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 771, timestamp = 121903337, file = 0x6000000002 <error: Cannot access memory at address 0x6000000002>, windowID = 0}, padding = "\003\003\000\000\351\030D\a\002\000\000\000`", '\000' <repeats 28 times>, "\005\372\020\203F\017\350 \344\065WUU\000"}
        info = {resize_dimensions = {first = 0, second = 0}, ticks_ = 0}
        last_mouse_down = 120830884
        last_click_x = 310
        last_click_y = 984
        temp_event = 
          {type = 771, common = {type = 771, timestamp = 121903337}, window = {type = 771, timestamp = 121903337, windowID = 2, event = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 771, timestamp = 121903337, windowID = 2, state = 96 '`', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020", start = -401652093, length = 1463149600}, text = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020"}, motion = {type = 771, timestamp = 121903337, windowID = 2, which = 96, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 771, timestamp = 121903337, windowID = 2, which = 96, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 771, timestamp = 121903337, windowID = 2, which = 96, x = 0, y = 0, direction = 0}, jaxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 771, timestamp = 121903337, which = 2, ball = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 771, timestamp = 121903337, which = 2, hat = 96 '`', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 771, timestamp = 121903337, which = 2}, caxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 771, timestamp = 121903337, which = 2}, adevice = {type = 771, timestamp = 121903337, which = 2, iscapture = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 771, timestamp = 121903337}, user = {type = 771, timestamp = 121903337, windowID = 2, code = 96, data1 = 0x0, data2 = 0x0}, syswm = {type = 771, timestamp = 121903337, msg = 0x6000000002}, tfinger = {type = 771, timestamp = 121903337, touchId = 412316860418, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 9.86153169e-29}, mgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 771, timestamp = 121903337, file = 0x6000000002 <error: Cannot access memory at address 0x6000000002>, windowID = 0}, padding = "\003\003\000\000\351\030D\a\002\000\000\000`", '\000' <repeats 28 times>, "\005\372\020\203F\017\350 \344\065WUU\000"}
        poll_count = 3
        begin_ignoring = 0
        events = 
---Type <return> to continue, or q <return> to quit---
            std::vector of length 3, capacity 4 = {{type = 513, common = {type = 513, timestamp = 121903337}, window = {type = 513, timestamp = 121903337, windowID = 1464838448, event = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 513, timestamp = 121903337, windowID = 1464838448, state = 85 'U', repeat = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 513, timestamp = 121903337, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>, start = 0, length = 0}, text = {type = 513, timestamp = 121903337, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>}, motion = {type = 513, timestamp = 121903337, windowID = 1464838448, which = 21845, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 513, timestamp = 121903337, windowID = 1464838448, which = 21845, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 513, timestamp = 121903337, windowID = 1464838448, which = 21845, x = 0, y = 0, direction = 0}, jaxis = {type = 513, timestamp = 121903337, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 513, timestamp = 121903337, which = 1464838448, ball = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 513, timestamp = 121903337, which = 1464838448, hat = 85 'U', value = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 513, timestamp = 121903337, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 513, timestamp = 121903337, which = 1464838448}, caxis = {type = 513, timestamp = 121903337, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 513, timestamp = 121903337, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 513, timestamp = 121903337, which = 1464838448}, adevice = {type = 513, timestamp = 121903337, which = 1464838448, iscapture = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 513, timestamp = 121903337}, user = {type = 513, timestamp = 121903337, windowID = 1464838448, code = 21845, data1 = 0x0, data2 = 0x0}, syswm = {type = 513, timestamp = 121903337, msg = 0x5555574fa930}, tfinger = {type = 513, timestamp = 121903337, touchId = 93825025419568, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 513, timestamp = 121903337, touchId = 93825025419568, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 513, timestamp = 121903337, touchId = 93825025419568, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 513, timestamp = 121903337, file = 0x5555574fa930 "\002", windowID = 0}, padding = "\001\002\000\000\351\030D\a0\251OWUU", '\000' <repeats 41 times>}, {type = 768, common = {type = 768, timestamp = 121903337}, window = {type = 768, timestamp = 121903337, windowID = 2, event = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 53, data2 = 96}, key = {type = 768, timestamp = 121903337, windowID = 2, state = 1 '\001', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_GRAVE, sym = 96, mod = 0, unused = 32767}}, edit = {type = 768, timestamp = 121903337, windowID = 2, text = "\001\000\000\000\065\000\000\000`\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>, start = 0, length = 0}, text = {type = 768, timestamp = 121903337, windowID = 2, text = "\001\000\000\000\065\000\000\000`\000\000\000\000\000\237\356\377\177", '\000' <repeats 13 times>}, motion = {type = 768, timestamp = 121903337, windowID = 2, which = 1, state = 53, x = 96, y = -291569664, xrel = 32767, yrel = 0}, button = {type = 768, timestamp = 121903337, windowID = 2, which = 1, button = 53 '5', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 96, y = -291569664}, wheel = {type = 768, timestamp = 121903337, windowID = 2, which = 1, x = 53, y = 96, direction = 4003397632}, jaxis = {type = 768, timestamp = 121903337, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 53, padding4 = 0}, jball = {type = 768, timestamp = 121903337, which = 2, ball = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 53, yrel = 0}, jhat = {type = 768, timestamp = 121903337, which = 2, hat = 1 '\001', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 768, timestamp = 121903337, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 768, timestamp = 121903337, which = 2}, caxis = {type = 768, timestamp = 121903337, which = 2, axis = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 53, padding4 = 0}, cbutton = {type = 768, timestamp = 121903337, which = 2, button = 1 '\001', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 768, timestamp = 121903337, which = 2}, adevice = {type = 768, timestamp = 121903337, which = 2, iscapture = 1 '\001', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 768, timestamp = 121903337}, user = {type = 768, timestamp = 121903337, windowID = 2, code = 1, data1 = 0x6000000035, data2 = 0x7fffee9f0000 <_XimForwardEventCallback+16>}, syswm = {type = 768, timestamp = 121903337, msg = 0x100000002}, tfinger = {type = 768, timestamp = 121903337, touchId = 4294967298, fingerId = 412316860469, x = -2.46040583e+28, y = 4.59163468e-41, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 768, timestamp = 121903337, touchId = 4294967298, dTheta = 7.42688186e-44, dDist = 1.34524653e-43, x = -2.46040583e+28, y = 4.59163468e-41, numFingers = 0, padding = 0}, dgesture = {type = 768, timestamp = 121903337, touchId = 4294967298, gestureId = 412316860469, numFingers = 4003397632, error = 4.59163468e-41, x = 0, y = 0}, drop = {type = 768, timestamp = 121903337, file = 0x100000002 <error: Cannot access memory at address 0x100000002>, windowID = 53}, padding = "\000\003\000\000\351\030D\a\002\000\000\000\001\000\000\000\065\000\000\000`\000\000\000\000\000\237\356\377\177", '\000' <repeats 25 times>}, {type = 771, common = {type = 771, timestamp = 121903337}, window = {type = 771, timestamp = 121903337, windowID = 2, event = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 771, timestamp = 121903337, windowID = 2, state = 96 '`', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020", start = -401652093, length = 1463149600}, text = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020"}, motion = {type = 771, timestamp = 121903337, windowID = 2, which = 96, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 771, timestamp = 121903337, windowID = 2, which = 96, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 771, timestamp = 121903337, windowID = 2, which = 96, x = 0, y = 0, direction = 0}, jaxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 771, timestamp = 121903337, which = 2, ball = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 771, timestamp = 121903337, which = 2, hat = 96 '`', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 771, timestamp = 121903337, which = 2}, caxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 771, timestamp = 121903337, which = 2}, adevice = {type = 771, timestamp = 121903337, which = 2, iscapture = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 771, timestamp = 121903337}, user = {type = 771, timestamp = 121903337, windowID = 2, code = 96, data1 = 0x0, data2 = 0x0}, syswm = {type = 771, timestamp = 121903337, msg = 0x6000000002}, tfinger = {type = 771, timestamp = 121903337, touchId = 412316860418, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 9.86153169e-29}, mgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 771, timestamp = 121903337, file = 0x6000000002 <error: Cannot access memory at address 0x6000000002>, windowID = 0}, padding = "\003\003\000\000\351\030D\a\002\000\000\000`", '\000' <repeats 28 times>, "\005\372\020\203F\017\350 \344\065WUU\000"}}
        ev_it = 
---Type <return> to continue, or q <return> to quit---
  {type = 771, common = {type = 771, timestamp = 121903337}, window = {type = 771, timestamp = 121903337, windowID = 2, event = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 771, timestamp = 121903337, windowID = 2, state = 96 '`', repeat = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020", start = -401652093, length = 1463149600}, text = {type = 771, timestamp = 121903337, windowID = 2, text = "`", '\000' <repeats 28 times>, "\005\372\020"}, motion = {type = 771, timestamp = 121903337, windowID = 2, which = 96, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 771, timestamp = 121903337, windowID = 2, which = 96, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 771, timestamp = 121903337, windowID = 2, which = 96, x = 0, y = 0, direction = 0}, jaxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 771, timestamp = 121903337, which = 2, ball = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 771, timestamp = 121903337, which = 2, hat = 96 '`', value = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 771, timestamp = 121903337, which = 2}, caxis = {type = 771, timestamp = 121903337, which = 2, axis = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 771, timestamp = 121903337, which = 2, button = 96 '`', state = 0 '\000', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 771, timestamp = 121903337, which = 2}, adevice = {type = 771, timestamp = 121903337, which = 2, iscapture = 96 '`', padding1 = 0 '\000', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 771, timestamp = 121903337}, user = {type = 771, timestamp = 121903337, windowID = 2, code = 96, data1 = 0x0, data2 = 0x0}, syswm = {type = 771, timestamp = 121903337, msg = 0x6000000002}, tfinger = {type = 771, timestamp = 121903337, touchId = 412316860418, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 9.86153169e-29}, mgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 771, timestamp = 121903337, touchId = 412316860418, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 771, timestamp = 121903337, file = 0x6000000002 <error: Cannot access memory at address 0x6000000002>, windowID = 0}, padding = "\003\003\000\000\351\030D\a\002\000\000\000`", '\000' <repeats 28 times>, "\005\372\020\203F\017\350 \344\065WUU\000"}
        ev_end = 
  {type = 513, common = {type = 513, timestamp = 121902431}, window = {type = 513, timestamp = 121902431, windowID = 1464838448, event = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 513, timestamp = 121902431, windowID = 1464838448, state = 85 'U', repeat = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 513, timestamp = 121902431, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>, start = 0, length = 0}, text = {type = 513, timestamp = 121902431, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>}, motion = {type = 513, timestamp = 121902431, windowID = 1464838448, which = 21845, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 513, timestamp = 121902431, windowID = 1464838448, which = 21845, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 513, timestamp = 121902431, windowID = 1464838448, which = 21845, x = 0, y = 0, direction = 0}, jaxis = {type = 513, timestamp = 121902431, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 513, timestamp = 121902431, which = 1464838448, ball = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 513, timestamp = 121902431, which = 1464838448, hat = 85 'U', value = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 513, timestamp = 121902431, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 513, timestamp = 121902431, which = 1464838448}, caxis = {type = 513, timestamp = 121902431, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 513, timestamp = 121902431, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 513, timestamp = 121902431, which = 1464838448}, adevice = {type = 513, timestamp = 121902431, which = 1464838448, iscapture = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 513, timestamp = 121902431}, user = {type = 513, timestamp = 121902431, windowID = 1464838448, code = 21845, data1 = 0x0, data2 = 0x0}, syswm = {type = 513, timestamp = 121902431, msg = 0x5555574fa930}, tfinger = {type = 513, timestamp = 121902431, touchId = 93825025419568, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 513, timestamp = 121902431, touchId = 93825025419568, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 513, timestamp = 121902431, touchId = 93825025419568, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 513, timestamp = 121902431, file = 0x5555574fa930 "\002", windowID = 0}, padding = "\001\002\000\000_\025D\a0\251OWUU", '\000' <repeats 41 times>}
        resize_found = false
        first_draw_event = 
  {type = 513, common = {type = 513, timestamp = 121902431}, window = {type = 513, timestamp = 121902431, windowID = 1464838448, event = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 513, timestamp = 121902431, windowID = 1464838448, state = 85 'U', repeat = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 0, unused = 0}}, edit = {type = 513, timestamp = 121902431, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>, start = 0, length = 0}, text = {type = 513, timestamp = 121902431, windowID = 1464838448, text = "UU", '\000' <repeats 29 times>}, motion = {type = 513, timestamp = 121902431, windowID = 1464838448, which = 21845, state = 0, x = 0, y = 0, xrel = 0, yrel = 0}, button = {type = 513, timestamp = 121902431, windowID = 1464838448, which = 21845, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 0}, wheel = {type = 513, timestamp = 121902431, windowID = 1464838448, which = 21845, x = 0, y = 0, direction = 0}, jaxis = {type = 513, timestamp = 121902431, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 513, timestamp = 121902431, which = 1464838448, ball = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 513, timestamp = 121902431, which = 1464838448, hat = 85 'U', value = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 513, timestamp = 121902431, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 513, timestamp = 121902431, which = 1464838448}, caxis = {type = 513, timestamp = 121902431, which = 1464838448, axis = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 513, timestamp = 121902431, which = 1464838448, button = 85 'U', state = 85 'U', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 513, timestamp = 121902431, which = 1464838448}, adevice = {type = 513, timestamp = 121902431, which = 1464838448, iscapture = 85 'U', padding1 = 85 'U', padding2 = 0 '\000', padding3 = 0 '\000'}, quit = {type = 513, timestamp = 121902431}, user = {type = 513, timestamp = 121902431, windowID = 1464838448, code = 21845, data1 = 0x0, data2 = 0x0}, syswm = {type = 513, timestamp = 121902431, msg = 0x5555574fa930}, tfinger = {type = 513, timestamp = 121902431, touchId = 93825025419568, fingerId = 0, x = 0, y = 0, dx = 0, dy = 0, pressure = 0}, mgesture = {type = 513, timestamp = 121902431, touchId = 93825025419568, dTheta = 0, dDist = 0, x = 0, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 513, timestamp = 121902431, touchId = 938250254195---Type <return> to continue, or q <return> to quit---
68, gestureId = 0, numFingers = 0, error = 0, x = 0, y = 0}, drop = {type = 513, timestamp = 121902431, file = 0x5555574fa930 "\002", windowID = 0}, padding = "\001\002\000\000_\025D\a0\251OWUU", '\000' <repeats 41 times>}
#42 0x0000555555dc488c in controller_base::play_slice(bool) (this=0x7fffffffce80, is_delay_enabled=true) at src/controller_base.cpp:239
        key = {key_list = 0x7ffff6c02f0a ""}
        m = 0x7fffffffc770
        a = 0x7fffffffcf00
        str_vec = Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 
Python Exception <class 'OverflowError'> int too big to convert: 

          std::vector of length -1466015322895, capacity 1 = {"", "\240\311\377\377\377\177\000\000\246\311\033VUU\000\000\340l^\340\001\177\000\000\200\316\377\377\377\177\000\000\240\310\377\377\377\177\000\000\000\000\000\000\000\000\000\000\200\310\377\377\377\177\000\000\000\317\377\377\377\177\000\000p\310\377\377\377\177\000\000\t\000\000\000\000\000\000\000turn_bell\000^\340\377\177\000\000\240\310\377\377\377\177\000\000\211O\227UUU\000\000\300\310\377\377\377\177\000\000\320\310\377\377\377\177\000\000\240\311\377\377\377\177\000\000r)\034VUU\000\000\340\310\377\377\377\177\000\000\200\316\377\377\377\177\000\000\340l^\340\377\177\000\000\000\005\372\020\203F\017\350\376\377\377\377\377\377\377\177\000\000\000\000\000\000\000\000\360\310\377\377\377\177\000\000"..., "", "0\312\377\377\377\177\000\000k$\034VUU\000\000\300\311\377\377\377\177\000\000\200\316\377\377\377\177\000\000turn_changed\000U\000\000\340\311\377\377\377\177\000\000\f\000\000\000\000\000\000\000Turn changed\000U\000\000\240\212\276WUU\000\000\030\000\000\000\000\000\000\000.\000\000\000\000\000\000\000yM\033VUU\000\000p\327\377\377\377\177\000\000\000\005\372\020\203F\017\350\210l^\340\377\177\000\000\210l^\340\377\177\000\000P\312\377\377\377\177\000\000\331\301\033VUU\000\000\001\000\000\000\001\000\000\000\200\316\377\377\377\177\000\000\220\312\377\377\377\177\000\000\060w\033VUU\000\000\220\312\377\377\377\177\000\000"..., "", "turn_bell", "\240\311\377\377\377\177\000\000r)\034VUU\000\000\340\310\377\377\377\177\000\000\200\316\377\377\377\177\000\000\340l^\340\377\177\000\000\000\005\372\020\203F\017\350\376\377\377\377\377\377\377\177\000\000\000\000\000\000\000\000\360\310\377\377\377\177", '\000' <repeats 11 times>, "\311\377\377\377\177\000\000\000\005\372\020\203F\017\350 \311\377\377\377\177\000\000\212\245\250UUU\000\000p\311\377\377\377\177\000\000`\311\377\377\377\177\000\000\240\311\377\377\377\177\000\000f\202aVUU\000\000P\311\377\377\001\000\000\000\210l^\340\377\177\000\000`\311\377\377\377\177\000\000\362\342\255U\001\000\000\000\330l^\340\377\177\000\000\200+\355\341\377\177\000\000\340l^\340\377\177\000\000"..., "0\312\377\377\377\177\000\000k$\034VUU\000\000\300\311\377\377\377\177\000\000\200\316\377\377\377\177\000\000turn_changed\000U\000\000\340\311\377\377\377\177\000\000\f\000\000\000\000\000\000\000Turn changed\000U\000\000\240\212\276WUU\000\000\030\000\000\000\000\000\000\000.\000\000\000\000\000\000\000yM\033VUU\000\000p\327\377\377\377\177\000\000\000\005\372\020\203F\017\350\210l^\340\377\177\000\000\210l^\340\377\177\000\000P\312\377\377\377\177\000\000\331\301\033VUU\000\000\001\000\000\000\001\000\000\000\200\316\377\377\377\177\000\000\220\312\377\377\377\177\000\000\060w\033VUU\000\000\220\312\377\377\377\177\000\000"..., , "", "\240\311\377\377\377\177\000\000f\202aVUU\000\000P\311\377\377\001\000\000\000\210l^\340\377\177\000\000`\311\377\377\377\177\000\000\362\342\255U\001\000\000\000\330l^\340\377\177\000\000\200+\355\341\377\177\000\000\340l^\340\377\177\000\000\330l^\340\377\177\000\000\340l^\340\377\177\000\000\330l^\340\377\177\000\000\240\311\377\377\377\177\000\000\000\005\372\020\203F\017\350\210l^\340\377\177\000\000\250\326\377\377\377\177\000\000\060\312\377\377\377\177\000\000k$\034VUU\000\000\300\311\377\377\377\177\000\000\200\316\377\377\377\177\000\000turn_changed\000U\000\000\340\311\377\377\377\177\000\000\f\000\000\000\000\000\000\000Turn cha"..., "0\312\377\377\377\177\000\000k$\034VUU\000\000\300\311\377\377\377\177\000\000\200\316\377\377\377\177\000\000turn_changed\000U\000\000\340\311\377\377\377\177\000\000\f\000\000\000\000\000\000\000Turn changed\000U\000\000\240\212\276WUU\000\000\030\000\000\000\000\000\000\000.\000\000\000\000\000\000\000yM\033VUU\000\000p\327\377\377\377\177\000\000\000\005\372\020\203F\017\350\210l^\340\377\177\000\000\210l^\340\377\177\000\000P\312\377\377\377\177\000\000\331\301\033VUU\000\000\001\000\000\000\001\000\000\000\200\316\377\377\377\177\000\000\220\312\377\377\377\177\000\000\060w\033VUU\000\000\220\312\377\377\377\177\000\000"..., "\340l^\340\377\177\000\000\330l^\340\377\177\000\000\340l^\340\377\177\000\000\330l^\340\377\177\000\000\240\311\377\377\377\177\000\000\000\005\372\020\203F\017\350\210l^\340\377\177\000\000\250\326\377\377\377\177\000\000\060\312\377\377\377\177\000\000k$\034VUU\000\000\300\311\377\377\377\177\000\000\200\316\377\377\377\177\000\000turn_changed\000U\000\000\340\311\377\377\377\177\000\000\f\000\000\000\000\000\000\000Turn changed\000U\000\000\240\212\276WUU\000\000\030\000\000\000\000\000\000\000.\000\000\000\000\000\000\000yM\033VUU\000\000p\327\377\377\377\177\000\000\000\005\372\020\203F\017\350\210l^\340\377\177\000\000"..., "", , "P\312\377\377\377\177\000\000\331\301\033VUU\000\000\001\000\000\000\001\000\000\000\200\316\377\377\377\177\000\000\220\312\377\377\377\177\000\000\060w\033VUU\000\000\220\312\377\377\377\177\000\000\200\316\377\377\377\177\000\000\220\312\377\377\377\177\000\000\000\005\372\020\203F\017\350X\016\060WUU\000\000\001\000\000\000\000\000\000\000\300\312\377\377\377\177\000\000\354y\033VUU\000\000\300\312\377\377\377\177\000\000\200\316\377\377\377\177\000\000\360\344\340\341\377\177\000\000P\222\065WUU\000\000\200\313\377\377\377\177\000\000\205\t\034VUU\000\000\000\313\377\377\377\177\000\000\200\316\377\377\377\177\000\000\000\313\377\377\377\177\000\000\060(\256UUU\000\000\220ۄWUU\000\000"..., <error: Cannot access memory at address 0x6168635f6e727574>, <error: Cannot access memory at address 0x616863206e727554>, <error: Cannot access memory at address 0x2e>, "", "", "", "@", "", " \316\377\377\377\177\000\000\f\023\034VUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177", '\000' <repeats 26 times>, "\020\314\377\377\377\177\000\000 \314\377\377\377\177\000\000\324`dVUU\000\000\060\314\377\377\377\177\000\000hS\\WUU", '\000' <repeats 18 times>, "\020\314\377\377\377\177\000\000\000\000\000\000\000\000\000\000\060\314\377\377\377\177\000\000p'\222[UU\000\000\260O2[UU\000\000xP2[UU", '\000' <repeats 42 times>..., " \313\377\377\377\177\000\000\362\342\255UUU\000\000 لWUU\000\000\000\317\377\377\377\177\000\000@\313\377\377\377\177\000\000d\214\255UUU\000\000`\313\377\377\377\177\000\000\000\317\377\377\377\177\000\000`\313\377\377\377\177\000\000@f\255UUU", '\000' <repeats 11 times>, "\005\372\020\203F\017\350\200\313\377\377\377\177\000\000P\222\065WUU\000\000\250\326\377\377\377\177\000\000\000\000\000\000\000\000\000\000 \316\377\377\377\177\000\000\f\023\034VUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177", '\000' <repeats 26 times>, "\020\314\377\377\377\177\000\000 \314\377\377\377\177\000\000"..., "@\313\377\377\377\177\000\000d\214\255UUU\000\000`\313\377\377\377\177\000\000\000\317\377\377\377\177\000\000`\313\377\377\377\177\000\000@f\255UUU", '\000' <repeats 11 times>, "\005\372\020\203F\017\350\200\313\377\377\377\177\000\000P\222\065WUU\000\000\250\326\377\377\377\177\000\000\000\000\000\000\000\000\000\000 \316\377\377\377\177\000\000\f\023\034VUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177", '\000' <repeats 26 times>, "\020\314\377\377\377\177\000\000 \314\377\377\377\177\000\000\324`dVUU\000\000\060\314\377\377\377\177\000\000hS\\WUU\000\000\000\000\000\000\000\000\000\000"..., "`\313\377\377\377\177\000\000@f\255UUU", '\000' <repeats 11 times>, "\005\372\020\203F\017\350\200\313\377\377\377\177\000\000P\222\065WUU\000\000\250\326\377\377\377\177\000\000\000\000\000\000\000\000\000\000 \316\377\377\377\177\000\000\f\023\034VUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177", '\000' <repeats 26 times>, "\020\314\377\377\377\177\000\000 \314\377\377\377\177\000\000\324`dVUU\000\000\060\314\377\377\377\177\000\000hS\\WUU", '\000' <repeats 18 times>, "\020\314\377\377\377\177\000\000\000\000\000\000\000\000\000\000\060\314\377\377\377\177\000\000"..., "\200\313\377\377\377\177\000\000P\222\065WUU\000\000\250\326\377\377\377\177\000\000\000\000\000\000\000\000\000\000 \316\377\377\377\177\000\000\f\023\034VUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177", '\000' <repeats 26 times>, "\020\314\377\377\377\177\000\000 \314\377\377\377\177\000\000\324`dVUU\000\000\060\314\377\377\377\177\000\000hS\\WUU", '\000' <repeats 18 times>, "\020\314\377\377\377\177\000\000\000\000\000\000\000\000\000\000\060\314\377\377\377\177\000\000p'\222[UU\000\000\260O2[UU\000\000xP2[UU\000\000\000\000\000\000\000\000\000\000"..., " \316\377\377\377\177\000\000\f\023\034VUU\000\000(\227\065WUU\000\000\200\316\377\377\377\17---Type <return> to continue, or q <return> to quit---
7", '\000' <repeats 26 times>, "\020\314\377\377\377\177\000\000 \314\377\377\377\177\000\000\324`dVUU\000\000\060\314\377\377\377\177\000\000hS\\WUU", '\000' <repeats 18 times>, "\020\314\377\377\377\177\000\000\000\000\000\000\000\000\000\000\060\314\377\377\377\177\000\000p'\222[UU\000\000\260O2[UU\000\000xP2[UU", '\000' <repeats 42 times>..., "P\323\377\377\377\177\000\000\020<\354UUU\000\000\320\323\377\377\377\177\000\000\060\325\377\377\377\177\000\000\000\000\000\000\377\177\000\000`Z\222[UU\000\000\260\316\377\377\377\177\000\000\210\350\242UUU\000\000`Z\222[UU", '\000' <repeats 14 times>, "\377\177\000\000\000\005\372\020\203F\017\350\250 \"WUU\000\000\001\000rWUU\000\000\250\326\377\377\377\177\000\000\n/\300\366\377\177\000\000\000\000\000\000\000\177", '\000' <repeats 34 times>, "\210\"\"WUU\000\000@\376iVUU\000\000\340\312rWUU\000\000\061&\223UUU\000\000"..., "", '\000' <repeats 40 times>, "hS\\WUU", '\000' <repeats 26 times>, "\220\314\377\377\377\177\000\001\240\314\377\377\377\177\000\000\222^dVUU", '\000' <repeats 18 times>, "\260\314\377\377\377\177\000\000\202\027\265UUU", '\000' <repeats 18 times>, "\340\314\377\377\377\177\000\000\343\016\265UUU", '\000' <repeats 26 times>, "\310\314\377\377\377\177\000\000\310\314\377\377\377\177\000\000"..., "", '\000' <repeats 24 times>, "hS\\WUU", '\000' <repeats 26 times>, "\220\314\377\377\377\177\000\001\240\314\377\377\377\177\000\000\222^dVUU", '\000' <repeats 18 times>, "\260\314\377\377\377\177\000\000\202\027\265UUU", '\000' <repeats 18 times>, "\340\314\377\377\377\177\000\000\343\016\265UUU", '\000' <repeats 26 times>, "\310\314\377\377\377\177\000\000\310\314\377\377\377\177", '\000' <repeats 18 times>..., "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", "", "", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", "\200\315\377\377\377\177\000\000\262\246\033VUU\000\000\300\315\377\377\377\177\000\000\200\321\377\377\377\177\000\000\220\315\377\377\377\177\000\000\f\000\000\000\000\000\000\000sound_source\000\177\000\000\300\315\377\377\377\177\000\000\202\235\033VUU\000\000P \224[UU\000\000\300\066\016\342\377\177\000\000\020\316\377\377\377\177\000\000;\277\033VUU\000\000И5WUU\000\000p\327\377\377\377\177\000\000\250\326\377\377\377\177\000\000P\222\065WUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177\000\000P\222\065WUU\000\000\000\005\372\020\203F\017\350P\222\065WUU\000\000\250\326\377\377\377\177\000\000P\323\377\377\377\177\000\000"..., "\220\315\377\377\377\177\000\000\f\000\000\000\000\000\000\000sound_source\000\177\000\000\300\315\377\377\377\177\000\000\202\235\033VUU\000\000P \224[UU\000\000\300\066\016\342\377\177\000\000\020\316\377\377\377\177\000\000;\277\033VUU\000\000И5WUU\000\000p\327\377\377\377\177\000\000\250\326\377\377\377\177\000\000P\222\065WUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177\000\000P\222\065WUU\000\000\000\005\372\020\203F\017\350P\222\065WUU\000\000\250\326\377\377\377\177\000\000P\323\377\377\377\177\000\000\020<\354UUU\000\000\320\323\377\377\377\177\000\000\060\325\377\377\377\177\000\000\000\000\000\000\377\177\000\000"..., "sound_source", "\020\316\377\377\377\177\000\000;\277\033VUU\000\000И5WUU\000\000p\327\377\377\377\177\000\000\250\326\377\377\377\177\000\000P\222\065WUU\000\000(\227\065WUU\000\000\200\316\377\377\377\177\000\000P\222\065WUU\000\000\000\005\372\020\203F\017\350P\222\065WUU\000\000\250\326\377\377\377\177\000\000P\323\377\377\377\177\000\000\020<\354UUU\000\000\320\323\377\377\377\177\000\000\060\325\377\377\377\177\000\000\000\000\000\000\377\177\000\000`Z\222[UU\000\000\260\316\377\377\377\177\000\000\210\350\242UUU\000\000`Z\222[UU", '\000' <repeats 14 times>, "\377\177\000\000\000\005\372\020\203F\017\350\250 \"WUU\000\000"..., "P\222\065WUU\000\000\250\326\377\377\377\177\000\000P\323\377\377\377\177\000\000\020<\354UUU\000\000\320\323\377\377\377\177\000\000\060\325\377\377\377\177\000\000\000\000\000\000\377\177\000\000`Z\222[UU\000\000\260\316\377\377\377\177\000\000\210\350\242UUU\000\000`Z\222[UU", '\000' <repeats 14 times>, "\377\177\000\000\000\005\372\020\203F\017\350\250 \"WUU\000\000\001\000rWUU\000\000\250\326\377\377\377\177\000\000\n/\300\366\377\177\000\000\000\000\000\000\000\177", '\000' <repeats 34 times>, "\210\"\"WUU\000\000@\376iVUU\000\000"..., "\224S\336\367\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\260\326\377\377\377\177\000\000\260\326\377\377\377\177\000\000\000\000\000\000\000\000\000\000\224S\336\367\377\177\000\000\000\000\000\000\000\000\000\000\300\277)\340\377\177\000\000`_N\342\377\177\000\000\260\310)\340\377\177\000\000\031\000\000\000\000\000\000\000P\035\222\341\377\177\000\000`\272\222\341\377\177\000\000P\035\223\341\377\177\000\000\340\326\377\377\377\177\000\000\000\000\000\000\377\177\000\000@\bR\340\377\177\000\000\340\241\327\341\377\177\000\000\000\231\000\340\377\177\000\000\003\000\000\000\000\000\000\000\020L\327\341\377\177\000\000\220L\327\341\377\177\000\000\220L\327\341\377\177\000\000\240\310/WUU\000\000"..., , "\360\324\377\377\377\177\000\000I?\354UUU\000\000\000\000\000\000\377\177\000\000\060\325\377\377\377\177\000\000\360\324\377\377\377\177\000\000\177\265\217UUU\000\000\001\000\000\000\000\000\000\000И5WUU\000\000\300\323\377\377\377\177\000\000w̡UUU\000\001\300\221\065WUU\000\000\000\000\000\000\377\177\000\000\214\370\215UUU\000\000i\370\215UUU\000\000\030W\026WUU\000\000\000\000\000\000\000\000\000\000\001\001\000\001\001\001\001", '\000' <repeats 26 times>, "\324\377\377\377\177", '\000' <repeats 14 times>, "\377\177\000\000ȑ5WUU\000\000\060\324\377\377\377\177\000\000"..., <error: Cannot access memory at address 0x7fff00000000>, "", "\354:\334UUU\000\000\242Y\334UUU\000\000挎UUU\000\000\064Y\334UUU\000\000\362\214\216UUU\000\000\376\214\216UUU\000\000\n\215\216UUU\000\000\036\215\216UUU\000\000\060\215\216UUU\000\000\200\221aVUU\000\000\376\221aVUU\000\000d\223aVUU\000\000F\225aVUU\000\000j\227aVUU\000\000ИaVUU\000\000B\215\216UUU\000\000T\215\216UUU\000\000\340\277\033VUU\000\000\244\300\033VUU\000\000f\215\216UUU\000\000\232n\033VUU\000\000\272n\033VUU\000\000\004P\033VUU\000\000\214P\033VUU\000\000Zn\033VUU\000\000"..., "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "UH\211\345SH\203\354\070H\211}\330H\211uЉU\314dH\213\004%(\000\000\000H\211E\350\061\300\213Ẽ\370\001t2\203\370\001\177\006\205\300t\016\353|\203\370\002tB\203\370\003t\\\353pH\213E\330H\211\307\350\331#\362\377H\211\302H\215\005\067\070\203\001H\211\002\353UH\213E\330H\211\307\350\364a\000\000H\211\303H\213E\320H\211\307\350\272a\000\000H\211\003\353\065H\213U\320H\213E\330H\203\354\bAPH\211\326H\211\307\350\341a\000\000H\203\304\020\353\026H\213E\330H\203\354\bQH\211\307\350\023b\000\000H\203\304\020\220\270\000\000\000\000H\213M\350dH3\f%(\000\000\000t\006\377\025"..., "\200A\022WUU\000\000\210?\022WUU\000\000 \242\200`UU\000\000 \242\200`UU\000\000(\242\200`UU\000\000\030\374\377\377\030\374\377\377*\000\000\000\000\000\000\000C\351&+\000\000\000\000\245cCI\000\000\000\000\351o\223\370\000\000\000\000乾y\000\000\000\000_m?\307\000\000\000\000\352Yf\275\000\000\000\000\267\332\"H\000\000\000\000\362\242֝\000\000\000\000\331\035\062T\000\000\000\000\246\272v\345\000\000\000\000\001B\365\222\000\000\000\000h\335\372i\000\000\000\000C\364\201\313\000\000\000\000\276\206\300\334\000\000\000\000\203\335\065\002\000\000\000\000\353!z\254\000\000\000\000\265w\311]\000\000\000\000\245\061\233L\000\000\000\000"..., "\001\000\000\000UU\000\000\240 \316WUU", '\000' <repeats 18 times>, "\200E\030\\UU\000\000\v\000\000\000\000\000\000\000description\000UU\000\000\000\000\000\000UU\000\000\370\303\311WUU\000\000\340\262hWUU\000\000PN\243WUU\000\000\000\000\000\000\000\000\000\000\021\t", '\000' <repeats 30 times>, "I~\213\377M\204\220\377@y\206\377U\214\230\377D}\214\377O\203\220\377>u\203\377Fz\207\377/gw\377>r\203\377U\212\226\377G}\212\377", '\000' <repeats 16 times>..., "", "", "", , <error: Cannot access memory at address 0x1d1000003c6>, "", , "\017\000\000\000\003\000\000\000\016\000\000\000\004\000\000\000\r\000\000\000\004\000\000\000\f\000\000\000\005\000\000\000\v\000\000\000\005\000\000\000\n\000\000\000\006\000\000\000\v\000\000\000\a\000\000\000!\000\000\000\000\000\000\000\027\000\000\000 \000\000\000p\274\354\377\377\377\377\377\002\000\000\000\000\000\000\000Q\000\000\000\000\000\000\000`ȉ\340\377\177\000\000\260ȉ\340\377\177\000\000\020Ή\340\377\177\000\000`Ή\340\377\177\000\000\240\260X\340\377\177\000\000\360\260X\340\377\177\000\000images/\000p\026\310WUU\000\000P\000\000\000\000\000\000\000q\000\000\000\000\000\000\000\001\000\000\000\377\177\000\000 Ѐ^UU\000\000\340\356\200WUU\000\000"..., , "\001\000\000\000UU\000\000P\320\377\377\377\177", '\000' <repeats 18 times>, "\v\000\000\000\005\000\000\000\001\000\000\000\000\000\000\000@\000\000\000\000\000\000\000a\000\000\000\000\000\000\000`\372\334]UU\000\000\024\001\000_\372\363\b\337\061\000\000\000\000\000\000\000halo/thunderer/smoke-se-ranged-kill[1~11].png:100\000\000\000\000\000\000\000`\000\000\000\000\000\000\000!\000\000\000\000\000\000\000\000\061\065\060\071\070\070\064\063\071\067\000\000\000\000\000\020\240\205\341\377\177\000\000!\000\000\000\000\000\000\000\000\346!aUU\000\000"..., "\n\000\000\000\003\000\000\000\v\000\000\000\003\000\000\000\000\000\000\000\n\000\000\000\004\000\000\000\v\000\000\000\004\000\000\000\000\000\000\000\n\000\000\000\005\000\000\000\v\000\000\000\004\000\000\000\000\000\000\000\n\000\000\000\006\000\000\000\v\000\000\000\005\000\000\000\000\000\000\000\v\000\000\000\000\000\000\000\f\000\000\000\001---Type <return> to continue, or q <return> to quit---
\000\000\000\000\000\000\000\v\000\000\000\001\000\000\000\f\000\000\000\001\000\000\000\000\000\000\000\v\000\000\000\002\000\000\000\f\000\000\000\003\000\000\000\000\000\000\000\v\000\000\000\003\000\000\000\f\000\000\000\004\000\000\000\001\000\000\000\v\000\000\000\004\000\000\000\f\000\000\000\004\000\000\000\001\000\000\000\v\000\000\000\005\000\000\000\f\000\000\000\005\000\000\000\001\000\000\000"..., <error: Cannot access memory at address 0x100000001>, "", "Command:", "", , <incomplete sequence \324>, <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "\000\274\036WUU\000\000\340\274\036WUU\000\000\001\000\016\342\000\000\000\000\210l^\340\377\177\000\000 \214\353\341\377\177\000\000p\233\067\340\377\177\000\000 \337\n\342\377\177\000\000 an even\000\000\000\000ndle\000\000\000\000\000\000\000\000\000\067\016\342\377\177\000\000\000\067\016\342\377\177\000\000\000\000\000\000\000\000\000\000И5WUU\000\000\000\000\000\000\000\000\000\000\001wh\340", '\000' <repeats 12 times>, "(\003\026WUU\000\000`7\016\342\377\177\000\000\v\000\000\000\000\000\000\000theme_reset\000e\000un", '\000' <repeats 24 times>..., "", "", <error: Cannot access memory at address 0x1>, "", "", "@\322\377\377\377\177\000\000@\322\377\377\377\177\000\000\020\066\226\366\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000h\355\201WUU\000\000h\355\201WUU\000\000\000\000\000\000\000\000\000\000v\a\000\000\031\000\000\000\000\000\000\000(", '\000' <repeats 11 times>, "\230\355\201WUU\000\000\230\355\201WUU", '\000' <repeats 34 times>, "\061\000\000\000\000\000\000\000\000\061\065\060\071\067\071\071\065\066\066\000UU\000\000\000W\231[UU\000\000pvY_UU\000\000\060\000\000\000\000\000\000\000!\000\000\000\000\000\000\000\260H\017WUU\000\000"..., "", "", <error: Cannot access memory at address 0xd>, "\000\000\000\000\000\000\000\000p\245\316WUU\000\000!\000\000\000\000\000\000\000\220l7WUU\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000A\000\000\000\000\000\000\000Ελληνικά (Ellinika)\000e/wesnoth/data/langu@\000\000\000\000\000\000\000A\000\000\000\000\000\000\000\260oRWUU\000\000\004\002\000\006\234\206\203\326\000\000\000\000\000\000\000\000format\000\000\000\340\000\000\324\366\000\000\001\000\000\000\000\000\000\000@\000\000\000\000\000\000\000\341\000\000\000\000\000\000\000PZRWUU\000\000#\000\000\000\000\000\000\000"..., "", "\000\274\036WUU\000\000\340\274\036WUU\000\000\001\000\016\342\000\000\000\000\210l^\340\377\177\000\000 \214\353\341\377\177\000\000p\233\067\340\377\177\000\000 \337\n\342\377\177\000\000 an even\000\000\000\000ndle\000\000\000\000\000\000\000\000\000\067\016\342\377\177\000\000\000\067\016\342\377\177\000\000\000\000\000\000\000\000\000\000И5WUU\000\000\000\000\000\000\000\000\000\000\001wh\340", '\000' <repeats 12 times>, "(\003\026WUU\000\000`7\016\342\377\177\000\000\v\000\000\000\000\000\000\000theme_reset\000e\000un", '\000' <repeats 24 times>..., "\000\000\000\000\000\000\000\000@\300\064WUU\000\000\360\324\377\377\377\177\000\000I?\354UUU\000\000\000\000\000\000\377\177\000\000\060\325\377\377\377\177\000\000\360\324\377\377\377\177\000\000\177\265\217UUU\000\000\001\000\000\000\000\000\000\000И5WUU\000\000\300\323\377\377\377\177\000\000w̡UUU\000\001\300\221\065WUU\000\000\000\000\000\000\377\177\000\000\214\370\215UUU\000\000i\370\215UUU\000\000\030W\026WUU\000\000\000\000\000\000\000\000\000\000\001\001\000\001\001\001\001", '\000' <repeats 26 times>, "\324\377\377\377\177", '\000' <repeats 14 times>, "\377\177\000\000"..., <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", <error: Cannot access memory at address 0x1>, "", "", "", <error: Cannot access memory at address 0x7fff00000000>, <error: Cannot access memory at address 0x7fff00000001>, "UH\211\345H\203\354\020H\211}\370H\213E\370H\211\307\350\064\001\000\000H\211\307\350\227\361\377\377\220\311\303UH\211\345SH\203\354\070H\211}\330H\211uЉU\314dH\213\004%(\000\000\000H\211E\350\061\300\213Ẽ\370\001t2\203\370\001\177\006\205\300t\016\353|\203\370\002tB\203\370\003t\\\353pH\213E\330H\211\307\350~Q\367\377H\211\302H\215\005\264O\210\001H\211\002\353UH\213E\330H\211\307\350\353\000\000\000H\211\303H\213E\320H\211\307\350\261\000\000\000H\211\003\353\065H\213U\320H\213E\330H\203\354\bAPH\211\326H\211\307\350\330\000\000\000H\203\304\020\353\026H\213E\330H\203\354\bQ"..., "\300\221\065WUU\000\000\000\000\000\000\377\177\000\000\214\370\215UUU\000\000i\370\215UUU\000\000\250\326\377\377\000\177\000\000\000\005\372\020\203F\017\350\320\325\377\377\377\177\000\000\000\000\000\000\000\000\000\000\250\326\377\377\377\177\000\000\330\327\377\377\377\177\000\000\240\341\377\377\377\177\000\000\330t\204UUU\000\000hX\n\366\377\177\000\000`\342\377\377\377\177\000\000\001\001\000\000\000\000\000\000\377\377\377\377P\001\000\000\000\000\000\000\377\177\000\000\300\221\065WUU\000\000\360٢\340\377\177\000\000@\271\242\340\377\177\000\000@\326\377\377\377\177\000\000\200 \243\340\377\177\000\000\360٢\340\377\177\000\000\000\000\000\000\000\000\000\000 ٢\340\377\177\000\000"..., "\300\221\065WUU\000\000\000\000\000\000\377\177\000\000\214\370\215UUU\000\000i\370\215UUU\000\000\250\326\377\377\000\177\000\000\000\005\372\020\203F\017\350\320\325\377\377\377\177\000\000\000\000\000\000\000\000\000\000\250\326\377\377\377\177\000\000\330\327\377\377\377\177\000\000\240\341\377\377\377\177\000\000\330t\204UUU\000\000hX\n\366\377\177\000\000`\342\377\377\377\177\000\000\001\001\000\000\000\000\000\000\377\377\377\377P\001\000\000\000\000\000\000\377\177\000\000\300\221\065WUU\000\000\360٢\340\377\177\000\000@\271\242\340\377\177\000\000@\326\377\377\377\177\000\000\200 \243\340\377\177\000\000\360٢\340\377\177\000\000\000\000\000\000\000\000\000\000 ٢\340\377\177\000\000"..., <error: Cannot access memory at address 0x16>, , "", <error: Cannot access memory at address 0xffffd538>, "", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", , "", "", <error: Cannot access memory at address 0x7fff00000000>, "", "", "\020\245}WUU\000\000\000\000\000\000\000\000\000\000\240\023\257WUU\000\000Q\000\000\000\000\000\000\000\200\330\330WUU\000\000\r\000\000\000\000\000\000\000\004\000\000Add Friend\000\000\000\240\330\330WUU", '\000' <repeats 11 times>, "\311\377\377\377\177\000\000\n\311\377\377\377\177\000\000\000\000\000\000\001\000\000\000!\000\000\000\000\000\000\000`\224\353\341\377\177\000\000\220\240\060WUU\000\000\200\316\377\377\377\177\000\000Q\000\000\000\000\000\000\000\200\344\330WUU\000\000c\000\000\000\000\000\000\000c\000\000\000\000\000\000\000\000\311\377\377\377\177\000\000\020\331\330WUU", '\000' <repeats 11 times>, "\311\377\377\377\177\000\000"..., "`K\017WUU\000\000\001\000\000\000\001\000\000\000\000\000png\000\000\000A\000\000\000\000\000\000\000\330$\017WUU\000\000\001\000\000\000\001\000\000\000P'\017WUU\000\000\360\314\312\\UU\000\000\060\315\312\\UU\000\000\060\315\312\\UU\000\000ole\000\000\000\000\000\061\000\000\000\000\000\000\000H%\017WUU\000\000\001\000\000\000\001\000\000\000xB\026WUU\000\000\001\000\000\000\000\000\000\000HC}]UU\000\000\061\000\000\000\000\000\000\000H%\017WUU\000\000\001\000\000\000\001\000\000\000xB\026WUU", '\000' <repeats 11 times>, "\223\027^UU\000\000\061\000\000\000\000\000\000\000H%\017WUU\000\000"..., "", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", "", "\000\000", "EM})}\n\000\071\265\f\000\000\000\000\000\000\024\000\000\000\377\177\000\000\024\000\000\000\377\177\000\000\bG\017WUU\000\000\320p\340\341\377\177\000\000\070q\340\341\377\177\000\000\070q\340\341\377\177\000\000@q\340\341\377\177\000\000\030\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000\f\000\000\000\000\000\000\000\bG\017WUU", '\000' <repeats 26 times>, " M\327\341\377\177", '\000' <repeats 11 times>, "M\327\341\377\177\000\000\005\000\000\000\000\000\000\000@M\327\341\377\177", '\000' <repeats 11 times>, "M\327\341\377\177\000\000\004\000\000\000\000\000\000\000\330F\017WUU\000\000"..., "exit", "play_multiplayer\000command_line\000titlescreen\000exit\000titlescreen_music\000music\000\000\000\000\000\000\000The wesnoth built-in timeout feature has been removed.\n\000Please use a platform-specific script which will kill the overtime "..., "", "@\330\377\377\377\177", '\000' <repeats 11 times>, "\377\377\377\377\377\377\377\000\000\000\000\001\000\000\000\000\000\000\363\377\177\000\000\300\221\065WUU\000\000\000\000\000\000\000\000\000\000\001\332\377\377\377\177\000\000\361\325\377\377\377\177\000\000\000\000\000\000\377\177\000\000\360\250\255WUU\000\000\020\023\230WUU\000\000\360\250\255WUU\000\000\002\000\000\000\000\000\000\000\360\330\377\377\377\177\000\000\000\000\000\000\060\000\000\000\240\022\230WUU\000\000\240\022\230WUU\000\000\240\022\230WUU\000\000\001\000\000\000\000\000\000\000\340\330\377\377\377\177\000\000\v\000\000\000\000\000\000\000titlescreen\000\000\000\000\000\000\331\377\377\377\177\000\000"..., "", "", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "\001\000\000\000UU\000\000x\330\377\377\377\177\000\000\020\023\230WUU", '\000' <repeats 11 times>, "\211\322WUU\000\000\020\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000p\000\000\000\000\000\000\000\220ԋWUU\000\000P\250\255WUU\000\000\225\026\205UUU\000\000W\026\205UUU\000\000`\251\255WUU\000\000a\000\000\000\000\000\000\000 \230\307WUU\000\000\024\002\001\363\062\352@\316\063\000\000\000\000\000\000\000Invalid context for %s: expected nil, side, or unit\000UU\000\000`\000\000\000\000\000\000\000"..., "", "\001", <error: Cannot access memory at address 0x726373656c746974>, "$", "", "\000\000\000\000\000\000\000---Type <return> to continue, or q <return> to quit---
\000\320*3WUU", '\000' <repeats 18 times>, "\060=3WUU\000\000\f\000\000\000\000\000\000\000chose_random", '\000' <repeats 12 times>, "Q", '\000' <repeats 15 times>, "\260\070\063WUU", '\000' <repeats 18 times>, "\240=3WUU\000\000\020\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "!\000\000\000\000\000\000\000disallow_shuffle\000\000\000\000\000\000\000\000Q", '\000' <repeats 15 times>..., "", "", "", , <error: Cannot access memory at address 0x7e1>, <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", "", "\002\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000 \343\377\377\377\177\000\000\000\343\377\377\377\177\000\000\340\230/WUU\000\000\340\230/WUU\000\000\030\000\000\000\060\000\000\000\000\341\377\377\377\177\000\000\000\340\377\377\377\177", '\000' <repeats 18 times>, "n\000\000\000[\000\000\000|\000\000\000w\000\000\000\000\343\377\377\377\177\000\000\020\343\377\377\377\177\000\000`\333\377\377\377\177\000\000틅UUU\000\000\360T3WUU\000\000\000\000\205UUU\000\000\000\343\377\377\377\177\000\000\020\343\377\377\377\177\000\000\023\000\000\000\000\000\000\000\000\005\372\020\203F\017\350\000\000\000\000UU\000\000"..., , "", '\000' <repeats 16 times>, "\240,3WUU\000", "", "", "\000U3WUU\000\000\003\000\000\000\000\000\000\000zoc", '\000' <repeats 21 times>, "!\000\000\000\000\000\000\000 w1WUU", '\000' <repeats 18 times>, "a\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\030\256/WUU", '\000' <repeats 18 times>, "pU3WUU\000\000\001\000\000\000\000\000\000\000_", '\000' <repeats 15 times>, " V3WUU\000\000(V3WUU\000\000(V3WUU\000\000\201", '\000' <repeats 31 times>..., , " \334\377\377\377\177\000\000\000\000\035\364\377\177\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000 \334\377\377\377\177\000\000\225\327\210UUU\000\000\"\000\000\000\000\000\000\000\000\343\377\377\377\177\000\000\360T3WUU\000\000\300\242/WUU\000\000@\000\000\000\000\000\000\000\000T3WUU\000\000\000\343\377\377\377\177\000\000\"\000\000\000\000\000\000\000P\334\377\377\377\177\000\000=\022\336\367\377\177\000\000P\334\377\377\377\177\000\000\000\000\000\000\000\000\000\000\060\313Q\367\377\177", '\000' <repeats 11 times>, "z\373\367\377\177\000\000\000\027\336\367\377\177\000\000]\000\000\000\000\000\000\000@\357Q\367\377\177\000\000\000z\373\367\377\177\000\000"..., '\000' <repeats 129 times>, "lvVUU\000\000\000\005\372\020\203F\017\350\000\000\000\000\000\000\000\000`@\204UUU\000\000\000lvVUU\000\000jO{\363\377\177\000\000\250\344\377\377\377\177\000\000\230\344\377\377\377\177\000\000\000\000\000\000\001\000\000\000"..., <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", <error: Cannot access memory at address 0x40>, "", "", "", "", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "\240\376\372\367\377\177\000\000\220\331\377\367\377\177", '\000' <repeats 11 times>, "\341\377\367\377\177\000\000\000p\373\367\377\177\000\000\000u\373\367\377\177\000\000\000z\373\367\377\177\000\000\360~\373\367\377\177\000", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, <error: Cannot access memory at address 0xfffffffffffff001>, <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "\000r=hUU\000\000\000=4`UU\000\000@w\333^UU\000\000\260\342z]UU\000\000`\002\251\\UU\000\000\060\021\366bUU\000\000\060:4`UU\000\000 g\\^UU\000\000\340h\001]UU\000\000PB\262^UU\000\000Э\314\\UU\000\000\260V\337^UU\000\000\020wN]UU\000\000ps\335^UU\000\000\000=4`UU\000\000\000=4`UU\000\000h[\264\363\377\177\000\000h[\264\363\377\177\000\000x[\264\363\377\177\000\000x[\264\363\377\177\000\000\210[\264\363\377\177\000\000\210[\264\363\377\177\000\000\230[\264\363\377\177\000\000\230[\264\363\377\177\000\000\300:4`UU\000\000"..., <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, "", "", "", <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, <error: Cannot access memory at address 0xfbad8001>, "3\000\000\000\061\000\000\000\000\000\000\000(#\017WUU\000\000(\340\064WUU", '\000' <repeats 26 times>, "\201\000\000\000\000\000\000\000p\350H\365\377\177\000\000X\340\064WUU\000\000\002\000\000\000\000\000\000\000-e", '\000' <repeats 14 times>, "x\340\064WUU\000\000\006\000\000\000\000\000\000\000editor\000\000\000\000\000\000\000\000\000\000\300\340\064WUU\000\000b\000\000\000\000\000\000\000b", '\000' <repeats 15 times>, "@\333\064WUU\000\000\060\341\064WUU\000\000q\000\000\000\000\000\000\000starts the i"..., "", "", "", "", "", "", "", "", "", "/opt/wesnoth-1.13-debug/bin/wesnoth", "", <error: Cannot access memory at address 0x2800000050>, "", "\000\000\000\000\000\000\000\000!", '\000' <repeats 31 times>, "\061\000\000\000\000\000\000\000p\200\065WUU\000\000\020\207\065WUU\000\000\020\210\065WUU\000\000\260\220\065WUU\000\000\000\000\000\000\000\000\000\000Q\000\000\000\000\000\000\000\060\317\066WUU\000\000D\370\243\356\377\177\000\000\203\000\000\000\000\000\000\000\060\317\066WUU\000\000G\025\244\356\377\177\000\000V\000\000\000\377\177\000\000`\356\237\356\377\177\000\000@N5WUU\000\000\000\000\000\000\000\000\000\000\221\000\000\000\000\000\000\000 \210\065WUU", '\000' <repeats 18 times>..., "", <error: Cannot access memory at address 0x2800000050>, ""...}
        was_scrolling = false
        values = {first = 6.9533558071227593e-310, second = 6.9533295886405374e-310}
        joystickx = 6.9533558071203878e-310
        joysticky = 4.6355708241889969e-310
        mousex = -14512
        mousey = 32767
        mouse_flags = 0 '\000'
        highlighted_hex = {x = 1437427264, y = 21845}
        window = 0x7fffffffc790
#43 0x00005555561b6fb0 in play_controller::play_slice_catch() (this=0x7fffffffce80) at src/play_controller.cpp:1062
        __PRETTY_FUNCTION__ = "void play_controller::play_slice_catch()"
#44 0x00005555561bc9a6 in playmp_controller::play_human_turn() (this=0x7fffffffce80) at src/playmp_controller.cpp:172
        __PRETTY_FUNCTION__ = "virtual void playmp_controller::play_human_turn()"
        timer = std::unique_ptr<countdown_clock> containing 0x0
#45 0x00005555561c246b in playsingle_controller::play_side_impl() (this=0x7fffffffce80) at src/playsingle_controller.cpp:396
#46 0x00005555561bc1d9 in playmp_controller::play_side_impl() (this=0x7fffffffce80) at src/playmp_controller.cpp:86
#47 0x00005555561b7730 in play_controller::play_side() (this=0x7fffffffce80) at src/play_controller.cpp:1155
#48 0x00005555561b79ec in play_controller::play_turn() (this=0x7fffffffce80) at src/play_controller.cpp:1193
#49 0x00005555561c0985 in playsingle_controller::play_scenario_main_loop() (this=0x7fffffffce80) at src/playsingle_controller.cpp:190
#50 0x00005555561c130c in playsingle_controller::play_scenario(config const&) (this=0x7fffffffce80, level=...) at src/playsingle_controller.cpp:279
        is_victory = false
        end_level = 
---Type <return> to continue, or q <return> to quit---
            @0x5555575c5368: {prescenario_save = false, replay_save = false, proceed_to_next_level = false, is_victory = false, transient = {carryover_report = false, linger_mode = false, reveal_map = false}}
        end_music = <error reading variable: Cannot access memory at address 0x8>
        __PRETTY_FUNCTION__ = "LEVEL_RESULT playsingle_controller::play_scenario(const config&)"
#51 0x0000555555ec3c10 in campaign_controller::playmp_scenario(end_level_data&) (this=0x7fffffffd530, end_level=...) at src/game_initialization/playcampaign.cpp:225
        playcontroller = Python Exception <class 'ValueError'> Cannot find type std::__cxx11::list<config, std::allocator<config> >::_Node: 

          {<playsingle_controller> = {<play_controller> = {<controller_base> = {<video2::draw_layering> = {<events::sdl_handler> = {_vptr.sdl_handler = 0x5555572220a8 <vtable for playmp_controller+16>, has_joined_ = true, has_joined_global_ = false}, <No data fields>}, game_config_ = @0x7fffffffd6a8, key_ = {key_list = 0x7ffff6c02f0a ""}, scrolling_ = false, scroll_up_ = false, scroll_down_ = false, scroll_left_ = false, scroll_right_ = false, joystick_manager_ = {joysticks_ = std::vector of length 0, capacity 0, joystick_area_ = 0, counter_ = 0}}, <events::observer> = {_vptr.observer = 0x555557222288 <vtable for playmp_controller+496>}, <quit_confirmation> = {static blockers_ = {<std::_Vector_base<quit_confirmation*, std::allocator<quit_confirmation*> >> = {_M_impl = {<std::allocator<quit_confirmation*>> = {<__gnu_cxx::new_allocator<quit_confirmation*>> = {<No data fields>}, <No data fields>}, _M_start = 0x555557cfc2f0, _M_finish = 0x555557cfc2f8, _M_end_of_storage = 0x555557cfc2f8}}, <No data fields>}, static open_ = false, prompt_ = {<std::_Maybe_unary_or_binary_function<bool>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x55555669fe40 <quit_confirmation::default_prompt()>, _M_const_object = 0x55555669fe40 <quit_confirmation::default_prompt()>, _M_function_pointer = 0x55555669fe40 <quit_confirmation::default_prompt()>, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x55555669fe40 <quit_confirmation::default_prompt()>, this adjustment 93825027721952}, _M_pod_data = "@\376iVUU\000\000\340\312rWUU\000"}, _M_manager = 0x555555932631 <std::_Function_base::_Base_manager<bool (*)()>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x555555932612 <std::_Function_handler<bool (), bool (*)()>::_M_invoke(std::_Any_data const&)>}}, ticks_ = 11029, tdata_ = std::shared_ptr (count 2, weak 0) 0x7fffe11cf640, gamestate_ = std::unique_ptr<game_state> containing 0x7fffe05e57b0, level_ = {static invalid = {static invalid = <same as static member of an already seen type>, static diff_track_attribute = 0x555556891e93 "__diff_track", values_ = std::map with 0 elements, children_ = std::map with 0 elements, ordered_children = std::vector of length 0, capacity 0}, static diff_track_attribute = 0x555556891e93 "__diff_track", values_ = std::map with 7 elements = {["description"] = {value_ = {which_ = 0, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "\370\303\311WUU\000\000\340\262hWUU\000\000PN\243WUU\000\000\000\000\000\000\000\000\000", align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}, ["disallow_recall"] = {value_ = {which_ = 0, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "X\002\000\000\310\000\000\000\020!\316WUU", '\000' <repeats 17 times>, align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}, ["experience_modifier"] = {value_ = {which_ = 3, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "<\000\000\000\302\001\000\000\240\003\333WUU", '\000' <repeats 17 times>, align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}, ["name"] = {value_ = {which_ = 7, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "@k\217[UU\000\000\220\366\276WUU\000\000PN\243WUU\000\000\000\000\000\000\000\000\000", align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}, ["remove_from_carryover_on_defeat"] = {value_ = {which_ = 0, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "\306\002\000\000\370\000\000\000\240\001\333WUU", '\000' <repeats 17 times>, align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}, ["require_scenario"] = {value_ = {which_ = 0, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "\306\002\000\000\370\000\000\000@\000\333WUU", '\000' <repeats 17 times>, align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}, ["victory_when_enemies_defeated"] = {value_ = {which_ = 0, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32, 8>> = {data_ = {buf = "\200\a\000\000\030\004\000\000p\340\315WUU", '\000' <repeats 17 times>, align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}, static s_yes = <optimized out>, static s_no = <optimized out>, static s_true = <optimized out>, static s_false = <optimized out>}}, children_ = std::map with 0 elements, ordered_children = std::vector of length 0, capacity 0}, saved_game_ = @0x555557359250, tooltips_manager_ = std::unique_ptr<tooltips::manager> containing 0x7fffe3fd8130, whiteboard_manager_ = std::shared_ptr (count 3, weak 1) 0x7fffe0379b70, plugins_context_ = std::unique_ptr<plugins_context> containing 0x7fffe3fd79e0, labels_manager_ = {<No data fields>}, help_manager_ = {<No data fields>}, mouse_handler_ = {<events::mouse_handler_base> = {_vptr.mouse_handler_base = 0x555557221b70 <vtable for events::mouse_handler+16>, simple_warp_ = false, minimap_scrolling_ = false, dragging_left_ = false, dragging_started_ = false, dragging_right_ = false, drag_from_x_ = 966, drag_from_y_ = 465, drag_from_hex_ = {x = 11, y = 5}, last_hex_ = {x = 15, y = 3}, show_menu_ = false, scroll_start_x_ = 0, scroll_start_y_ = 0, scroll_started_ = false}, gui_ = 0x7fffe20e36c0, pc_ = @0x7fffffffce80, previous_hex_ = {x = 16, y = 4}, previous_free_hex_ = {x = 16, y = 4}, selected_hex_ = {x = -1000, y = -1000}, next_unit_ = {x = 15, y = 3}, current_route_ = {route = {steps = std::vector of length 0, capacity 7, move_cost = 4}, steps = std::vector of length 0, capacity 7, move_cost = @0x7fffffffd030, marks = std::map with 1 element = {[{x = 11, y = 5}] = {turns = 1, zoc = false, capture = false, invisible = false}}}, current_paths_ = {_vptr.paths = 0x555557126868 <vtable for pathfind::paths+16>, destinations = {<std::vector<pathfind::paths::step, std::allocator<pathfind::paths::step> >> = std::vector of length 77, capacity 77 = {{curr = {x = 10, y = 3}, prev = {x = 11, y = 3}, move_left = 0}, {curr = {x = 10, y = 4}, prev = {x = 11, y = 4}, move_left = 0}, {curr = {x = 10, y = 5}, prev = {x = 11, y = 4}, move_left = 0}, {curr = {x = 10, y = 6}, prev = {x = 11, y = 5}, move_left = 0}, {curr = {x = 11, y = 0}, prev = {x = 12, y = 1}, move_left = 0}, {curr = {x = 11, y = 1}, prev = {x = 12, y = 1}, move_left = 0}, {curr = {x = 11, y = 2}, prev = {x = 12, y = 3}, move_left = 0}, {curr = {x = 11, y = 3}, prev = {x = 12, y = 4}, move_left = 1}, {curr = {x = 11, y = 4}, prev = {x = 12, y = 4}, move_left = 1}, {curr = {x = 11, y = 5}, prev = {x = 12, y = 5}, move_left = 1}, {curr = {x = 11, y = 6}, prev = {x = 11, y = 5}, move_left = 0}, {curr = {x = 12, y = 0}, prev = {x = 13, y = 0}, move_left = 0}, {curr = {x = 12, y = 1}, prev = {x = 13, y = 1}, move_left = 1}, {curr = {x = 12, y = 2}, prev = {x = 13, y = 2}, move_left = 1}, {curr = {x = 12, y = 3}, prev = {x = 13, y = 3}, move_left = 2}, {curr = {x = 12, y = 4}, prev = {x = 13, y = 3}, move_left = 2}, {curr = {x = 12, y = 5}, prev = {x = 13, y = 4}, move_left = 2}, {curr = {x = 12, y = 6}, prev = {x = 13, y = 5}, move_left = 1}, {curr = {x = 12, y = 7}, prev = {x = 13, y = 6}, move_left = 0}, {curr = {x = 13, y = 0}, prev = {x = 13, y = 1}, move_left = 1}, {curr = {x = 13, y = 1}, prev = {x = 14, y = 2}, move_left = 2}, {curr = {x = 13, y = 2}, prev = {x = 14, y = 3}, move_left = 3}, {curr = {x = 13, y = 3}, prev = {x = 14, y = 3}, move_left = 3}, {curr = {x = 13, y = 4}, prev = {x = 14, y = 4}, move_left = 3}, {curr = {x = 13,---Type <return> to continue, or q <return> to quit---
 y = 5}, prev = {x = 13, y = 4}, move_left = 2}, {curr = {x = 13, y = 6}, prev = {x = 14, y = 6}, move_left = 1}, {curr = {x = 13, y = 7}, prev = {x = 14, y = 7}, move_left = 0}, {curr = {x = 14, y = 0}, prev = {x = 15, y = 0}, move_left = 1}, {curr = {x = 14, y = 1}, prev = {x = 14, y = 2}, move_left = 2}, {curr = {x = 14, y = 2}, prev = {x = 14, y = 3}, move_left = 3}, {curr = {x = 14, y = 3}, prev = {x = 15, y = 3}, move_left = 4}, {curr = {x = 14, y = 4}, prev = {x = 15, y = 3}, move_left = 4}, {curr = {x = 14, y = 5}, prev = {x = 15, y = 4}, move_left = 3}, {curr = {x = 14, y = 6}, prev = {x = 15, y = 5}, move_left = 2}, {curr = {x = 14, y = 7}, prev = {x = 14, y = 6}, move_left = 1}, {curr = {x = 14, y = 8}, prev = {x = 14, y = 7}, move_left = 0}, {curr = {x = 15, y = 0}, prev = {x = 15, y = 1}, move_left = 2}, {curr = {x = 15, y = 1}, prev = {x = 15, y = 2}, move_left = 3}, {curr = {x = 15, y = 2}, prev = {x = 15, y = 3}, move_left = 4}, {curr = {x = 15, y = 3}, prev = {x = -1000, y = -1000}, move_left = 5}, {curr = {x = 15, y = 4}, prev = {x = 15, y = 3}, move_left = 4}, {curr = {x = 15, y = 5}, prev = {x = 15, y = 4}, move_left = 3}, {curr = {x = 15, y = 6}, prev = {x = 15, y = 5}, move_left = 2}, {curr = {x = 15, y = 7}, prev = {x = 15, y = 6}, move_left = 1}, {curr = {x = 15, y = 8}, prev = {x = 15, y = 7}, move_left = 0}, {curr = {x = 16, y = 0}, prev = {x = 15, y = 0}, move_left = 1}, {curr = {x = 16, y = 1}, prev = {x = 16, y = 2}, move_left = 2}, {curr = {x = 16, y = 2}, prev = {x = 15, y = 2}, move_left = 3}, {curr = {x = 16, y = 3}, prev = {x = 15, y = 3}, move_left = 4}, {curr = {x = 16, y = 4}, prev = {x = 15, y = 3}, move_left = 4}, {curr = {x = 16, y = 5}, prev = {x = 15, y = 4}, move_left = 3}, {curr = {x = 16, y = 6}, prev = {x = 16, y = 5}, move_left = 2}, {curr = {x = 16, y = 7}, prev = {x = 16, y = 6}, move_left = 1}, {curr = {x = 16, y = 8}, prev = {x = 16, y = 7}, move_left = 0}, {curr = {x = 17, y = 0}, prev = {x = 17, y = 1}, move_left = 1}, {curr = {x = 17, y = 1}, prev = {x = 17, y = 2}, move_left = 2}, {curr = {x = 17, y = 2}, prev = {x = 16, y = 3}, move_left = 3}, {curr = {x = 17, y = 3}, prev = {x = 16, y = 3}, move_left = 3}, {curr = {x = 17, y = 4}, prev = {x = 16, y = 4}, move_left = 3}, {curr = {x = 17, y = 5}, prev = {x = 17, y = 4}, move_left = 2}, {curr = {x = 17, y = 6}, prev = {x = 16, y = 6}, move_left = 1}, {curr = {x = 17, y = 7}, prev = {x = 17, y = 6}, move_left = 0}, {curr = {x = 18, y = 0}, prev = {x = 17, y = 0}, move_left = 0}, {curr = {x = 18, y = 1}, prev = {x = 18, y = 2}, move_left = 1}, {curr = {x = 18, y = 2}, prev = {x = 17, y = 2}, move_left = 2}, {curr = {x = 18, y = 3}, prev = {x = 17, y = 2}, move_left = 2}, {curr = {x = 18, y = 4}, prev = {x = 17, y = 4}, move_left = 2}, {curr = {x = 18, y = 5}, prev = {x = 17, y = 4}, move_left = 2}, {curr = {x = 18, y = 6}, prev = {x = 17, y = 5}, move_left = 1}, {curr = {x = 18, y = 7}, prev = {x = 18, y = 6}, move_left = 0}, {curr = {x = 19, y = 0}, prev = {x = 18, y = 1}, move_left = 0}, {curr = {x = 19, y = 1}, prev = {x = 18, y = 2}, move_left = 1}, {curr = {x = 19, y = 2}, prev = {x = 18, y = 2}, move_left = 1}, {curr = {x = 19, y = 3}, prev = {x = 18, y = 3}, move_left = 1}, {curr = {x = 19, y = 4}, prev = {x = 18, y = 4}, move_left = 1}, {curr = {x = 19, y = 5}, prev = {x = 18, y = 5}, move_left = 1}, {curr = {x = 19, y = 6}, prev = {x = 19, y = 5}, move_left = 0}}, <No data fields>}}, unselected_paths_ = true, unselected_reach_ = false, path_turns_ = 0, side_num_ = 1, over_route_ = true, reachmap_invalid_ = false, show_partial_move_ = false, static singleton_ = 0x7fffffffcfb0, preventing_units_highlight_ = false}, menu_handler_ = {<events::chat_handler> = {_vptr.chat_handler = 0x555557221a00 <vtable for events::menu_handler+16>}, gui_ = 0x7fffe20e36c0, pc_ = @0x7fffffffce80, game_config_ = @0x7fffffffd6a8, textbox_info_ = {box_ = std::unique_ptr<gui::textbox> containing 0x0, check_ = std::unique_ptr<gui::button> containing 0x0, mode_ = gui::TEXTBOX_NONE, label_string_ = "Command:", label_ = 466}, last_search_ = "", last_search_hit_ = {x = -1000, y = -1000}}, hotkey_handler_ = std::unique_ptr<play_controller::hotkey_handler> containing 0x555557db01a0, soundsources_manager_ = std::unique_ptr<soundsource::manager> containing 0x7fffe3fd7870, persist_ = {_vptr.persist_manager = 0x555557126908 <vtable for persist_manager+16>, in_transaction_ = true, contexts_ = std::map with 0 elements}, gui_ = std::unique_ptr<game_display> containing 0x7fffe20e36c0, xp_mod_ = std::unique_ptr<unit_experience_accelerator> containing 0x555557d8b760, statistics_context_ = std::unique_ptr<const statistics::scenario_context> containing 0x555557d4d690, replay_ = std::unique_ptr<replay> containing 0x555557b39d70, skip_replay_ = false, linger_ = false, init_side_done_now_ = false, map_start_ = {x = -1000, y = -1000}, victory_when_enemies_defeated_ = true, remove_from_carryover_on_defeat_ = true, victory_music_ = std::vector of length 0, capacity 0, defeat_music_ = std::vector of length 0, capacity 0, scope_ = {prev_scope_active_ = std::bitset = {[0] = 1}}, ignore_replay_errors_ = false, player_type_changed_ = false}, cursor_setter_ = {old_ = cursor::NORMAL}, textbox_info_ = {box_ = std::unique_ptr<gui::textbox> containing 0x0, check_ = std::unique_ptr<gui::button> containing 0x0, mode_ = gui::TEXTBOX_NONE, label_string_ = "", label_ = 0}, replay_sender_ = {obj_ = @0x555557b39d70, upto_ = 2}, network_reader_ = {data_ = std::__cxx11::list, next_ = {i_ = non-dereferenceable iterator for std::vector}, next_command_num_ = 0, network_reader_ = {<std::_Maybe_unary_or_binary_function<bool, config&>> = {<std::unary_function<config&, bool>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x7fffffffce80, _M_const_object = 0x7fffffffce80, _M_function_pointer = 0x7fffffffce80, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7fffffffce80, this adjustment 140737488343696}, _M_pod_data = "\200\316\377\377\377\177\000\000\220\322\377\377\377\177\000"}, _M_manager = 0x5555561c443e <std::_Function_base::_Base_manager<playsingle_controller::playsingle_controller(const config&, saved_game&, const config&, const ter_data_cache&, CVideo&, bool)::<lambda(config&)> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, _M_invoker = 0x5555561c4400 <std::_Function_handler<bool(config&), playsingle_controller::playsingle_controller(const config&, saved_game&, const config&, const ter_data_cache&, CVideo&, bool)::<lambda(config&)> >::_M_invoke(const std::_Any_data &, config &)>}}, turn_data_ = {replay_sender_ = @0x7fffffffd230, host_transfer_ = {_vptr.generic_event = 0x555557160328 <vtable for events::generic_event+16>, name_ = "host_transfer", observers_ = std::vector of length 1, capacity 1 = {0x7fffffffcec8}, change_handler_ = false, notify_active_ = false}, network_reader_ = @0x7fffffffd240}, end_turn_ = playsingle_controller::END_TURN_NONE, skip_next_turn_ = false, ai_fallback_ = false, replay_ = std::unique_ptr<replay_controller> containing 0x0}, <syncmp_handler> = {_vptr.syncmp_handler = 0x5555572222b0 <vtable for playmp_controller+536>}, network_processing_stopped_ = false, blindfold_ = {display_ = @0x7fffe20e36c0, blind = false}, mp_info_ = 0x0}
        res = {<enum_tag> = {<No data fields>}, v = 21845, static count = 4}
#52 0x0000555555ec3f49 in campaign_controller::play_game() (this=0x7fffffffd530) at src/game_initialization/playcampaign.cpp:288
        res = {<enum_tag> = {<No data fields>}, v = LEVEL_RESULT::VICTORY, static count = 4}
        end_level = 
            {prescenario_save = true, replay_save = true, proceed_to_next_level = false, is_victory = true, transient = {carryover_report = true, linger_mode = true, reveal_map = true}}
        game_type = {<enum_tag> = {<No data fields>}, v = game_classification::CAMPAIGN_TYPE::MULTIPLAYER, static count = 4}
#53 0x00005555558dec06 in game_launcher::launch_game(game_launcher::RELOAD_GAME_DATA) (this=0x5555573591c0, reload=game_launcher::RELOAD_DATA) at src/game_launcher.cpp:949
        ccontroller = 
          {video_ = @0x5555573598d0, state_ = @0x555557359250, game_config_ = @0x7fffffffd6a8, tdata_ = std::shared_ptr (count 2, weak 0) 0x7fffe11cf640, is_unit_test_ = false, is_replay_ = false, mp_info_ = 0x0}
        result = {<enum_tag> = {<No data fields>}, v = 32767, static count = 4}
        __PRETTY_FUNCTION__ = "void game_launcher::launch_game(game_launcher::RELOAD_GAME_DATA)"
---Type <return> to continue, or q <return> to quit---
#54 0x00005555558474d8 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=std::vector of length 1, capacity 1 = {...}) at src/wesnoth.cpp:832
        label_manager = {<No data fields>}
        should_reload = game_launcher::RELOAD_DATA
        dlg = 
    {<gui2::dialogs::modal_dialog> = {_vptr.modal_dialog = 0x555557166500 <vtable for gui2::dialogs::title_screen+16>, window_ = std::unique_ptr<gui2::window> containing 0x0, retval_ = 1, always_save_fields_ = false, fields_ = std::vector of length 0, capacity 0, focus_ = "", restore_ = false, allow_plugin_skip_ = false, show_even_without_video_ = false}, game_ = @0x5555573591c0, debug_clock_ = std::unique_ptr<gui2::dialogs::modeless_dialog> containing 0x0}
        cmdline_opts = 
            {bunzip2 = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\000\000\000\000\000\000\000 \337\377\377\377\177\000\000\002\000\000\000\000\000\000\000\320p\221\363\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, bzip2 = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "d\000\000\000\000\000\000\000-+\200\363\377\177\000\000\001\000\000\000\000\000\000\000\000\343\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, campaign = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\340\230/WUU\000\000\340\230/WUU\000\000\000\005\372\020\203F\017\350\220\331\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, campaign_difficulty = {<boost::optional_detail::optional_base<int>> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, campaign_scenario = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\220\340\377\377\377\177\000\000\030\000\000\000\000\000\000\000 \337\377\377\377\177\000\000\036n\221\363\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, clock = false, core_id = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\240\211\220\363\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, data_path = false, data_dir = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\324\336\377\377\377\177\000\000\341\a\000\000\000\000\000\000\n", '\000' <repeats 14 times>, aligner_ = {<No data fields>}}}}, <No data fields>}, debug = false, debug_lua = false, editor = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\360\332\377\377\377\177\000\000 \000\000\000\000\000\000\000\330\336\377\377\377\177\000\000\004\000\000\000UU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, fps = false, fullscreen = false, gunzip = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\004\000\000\000\000\000\000\000\000n\221\363\377\177\000\000\000\000\000\000\000\000\000\000\350\230/WUU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, gzip = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\220\332\377\377\377\177\000\000\004\237\210UUU\000\000\000\000\000\000\000\000\000\000\060,3WUU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, help = false, language = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\002\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000 \343\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, log = {<boost::optional_detail::optional_base<std::vector<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\340\230/WUU\000\000\340\230/WUU\000\000\030\000\000\000\060\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, log_strict_level = {<boost::optional_detail::optional_base<int>> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, load = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = '\000' <repeats 16 times>, "n\000\000\000[\000\000\000|\000\000\000w\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, logdomains = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\020\343\377\377\377\177\000\000`\333\377\377\377\177\000\000틅UUU\000\000\360T3WUU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, log_precise_timestamps = false, multiplayer = false, multiplayer_ai_config = {<boost::optional_detail::optional_base<std::vector<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\020\343\377\377\377\177\000\000\023\000\000\000\000\000\000\000\000\005\372\020\203F", <incomplete sequence \350>, aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_algorithm = {<boost::optional_detail::optional_base<std::vector<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\360T3WUU\000\000\260\333\377\377\377\177\000\000~`\205UUU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_controller = {<boost::optional_detail::optional_base<std::vector<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\023\343\377\377\377\177\000\000\020\343\377\377\377\177\000\000\360T3WUU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_era = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\005\372\020\203F\017\350\000\000\000\---Type <return> to continue, or q <return> to quit---
000\000\000\000\000\360T3WUU\000\000 \334\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_exit_at_end = false, multiplayer_ignore_map_settings = false, multiplayer_label = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = " \000\000\000\000\000\000\000 \334\377\377\377\177\000\000\225\327\210UUU\000\000\"\000\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_parm = {<boost::optional_detail::optional_base<std::vector<std::tuple<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::tuple<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\360T3WUU\000\000\300\242/WUU\000\000@\000\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_repeat = {<boost::optional_detail::optional_base<unsigned int>> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "UU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_scenario = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\"\000\000\000\000\000\000\000P\334\377\377\377\177\000\000=\022\336\367\377\177\000\000P\334\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_side = {<boost::optional_detail::optional_base<std::vector<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "0\313Q\367\377\177", '\000' <repeats 11 times>, "z\373\367\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, multiplayer_turns = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "]\000\000\000\000\000\000\000@\357Q\367\377\177\000\000\000z\373\367\377\177\000\000\370\334\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, max_fps = {<boost::optional_detail::optional_base<int>> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, noaddons = false, nocache = false, nodelay = false, nogui = false, nomusic = false, nosound = false, new_widgets = false, path = false, preprocess = false, preprocess_defines = {<boost::optional_detail::optional_base<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\030\317Q\367\377\177\000\000xX\235\366\377\177\000\000\366\062\254\237\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, preprocess_input_macros = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\000\000\000\000\000\000\000\320\335\377\377\377\177\000\000\300\335\377\377\377\177\000\000\370\334\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, preprocess_output_macros = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "@\000\000\000\000\000\000\000\300\066C\364\001\000\000\000\022\021\210\363\377\177\000\000\020\020\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, preprocess_path = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = " \004\000\000\000\000\000\000\371\202\201\363\377\177\000\000\000\000\000\000\000\000\000\000\025E\201\363\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, preprocess_target = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\320\064WUU\000\000\001\360\377\377\377\377\377\377\000\020\002\000\000\000\000\000\000\360\377\377\377\377\377\377", aligner_ = {<No data fields>}}}}, <No data fields>}, resolution = {<boost::optional_detail::optional_base<std::pair<int, int> >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\000\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, rng_seed = {<boost::optional_detail::optional_base<unsigned int>> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000U\373", <incomplete sequence \367>, aligner_ = {<No data fields>}}}}, <No data fields>}, server = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\240Z\264\363\377\177\000\000\370Z\264\363\377\177\000\000\020\020\000\000\000\000\000\000\000\020\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, username = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\000\000\000\000\000\000\000\341R\201\363\377\177\000\000\001\001\000\000\377\177\000\000\377\000\000\000\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, password = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\345\305\023\364\377\177\000\000\210\377\377\377\377\377\377\377\000z\373\367\377\177\000\000\300\066C\364\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, render_image = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "c\000\000\000p\000\000\000\b\000\000\000\000\000\000\000\001", '\000' <repeats 14 times>, aligner_ = {<No data fields>}}}}, <No data fields>}, render_image_dst = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\005\372\020\203F\017\350`\336\377\377\377\177\000\000`\336\377\377\377\177\000\000\220\337\377\377\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, screenshot = false, screenshot_map_file = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "@c\264\363\377\177\000\000a\003\221\363\377\177\000\000\257>\200\363\377\177\000\000\001\200\255\373\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, screenshot_output_file = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\005\340\064WUU\000\000\004\340\064WUU\000\000\004\340\064WUU\000\000\004\340\064WUU\000", aligner_ = {<No data fields>}}}}, <No data fields>}, script_file = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\004\340\064WUU\000\000\005\340\064WUU", '\000' <repeats 17 times>, aligner_ = {<No data fields>}}}}, <No data fields>}, plugin_file = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = '\000' <repeats 16 times>, "\002\000\000\000\062\060\061\067\000\00---Type <return> to continue, or q <return> to quit---
5\372\020\203F", <incomplete sequence \350>, aligner_ = {<No data fields>}}}}, <No data fields>}, script_unsafe_mode = false, strict_validation = false, test = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\003\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\060", '\000' <repeats 14 times>, aligner_ = {<No data fields>}}}}, <No data fields>}, unit_test = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\022\247\200\363\377\177\000\000$", '\000' <repeats 15 times>, "\003\000\000\000\060\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, headless_unit_test = false, timeout = {<boost::optional_detail::optional_base<unsigned int>> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "\000\000\000", aligner_ = {<No data fields>}}}}, <No data fields>}, noreplaycheck = false, mptest = false, userconfig_path = false, userconfig_dir = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "n\000\000\000[\000\000\000|\000\000\000w\000\000\000#\000\000\000\000\000\000\000\240Z\264\363\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, userdata_path = false, userdata_dir = {<boost::optional_detail::optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<boost::optional_detail::optional_tag> = {<No data fields>}, m_initialized = false, m_storage = {dummy_ = {data = "p\341\377\377\377\177\000\000\000\000\000\000\000\000\000\000\033\000\000\000\000\000\000\000\364j\201\363\377\177\000", aligner_ = {<No data fields>}}}}, <No data fields>}, validcache = false, version = false, report = false, windowed = false, with_replay = false, args_ = std::vector of length 0, capacity 0, args0_ = "/opt/wesnoth-1.13-debug/bin/wesnoth", all_ = {static m_default_line_length = 80, m_caption = "", m_line_length = 80, m_min_description_length = 40, m_options = std::vector of length 85, capacity 128 = {{px = 0x55555734ce10, pn = {pi_ = 0x55555734cf30}}, {px = 0x55555734d050, pn = {pi_ = 0x55555734d150}}, {px = 0x55555734d170, pn = {pi_ = 0x55555734d210}}, {px = 0x55555734d340, pn = {pi_ = 0x55555734d3e0}}, {px = 0x55555734d420, pn = {pi_ = 0x55555734d540}}, {px = 0x55555734d620, pn = {pi_ = 0x55555734d6c0}}, {px = 0x55555734d7a0, pn = {pi_ = 0x55555734d840}}, {px = 0x55555734d880, pn = {pi_ = 0x55555734d920}}, {px = 0x55555734d960, pn = {pi_ = 0x55555734da40}}, {px = 0x55555734da80, pn = {pi_ = 0x55555734db20}}, {px = 0x55555734e040, pn = {pi_ = 0x55555734e150}}, {px = 0x55555734e230, pn = {pi_ = 0x55555734e350}}, {px = 0x55555734e430, pn = {pi_ = 0x55555734e530}}, {px = 0x55555734e570, pn = {pi_ = 0x55555734e640}}, {px = 0x55555734e720, pn = {pi_ = 0x55555734e820}}, {px = 0x55555734e900, pn = {pi_ = 0x55555734e9a0}}, {px = 0x55555734e9e0, pn = {pi_ = 0x55555734eab0}}, {px = 0x55555734ed00, pn = {pi_ = 0x55555734edd0}}, {px = 0x55555734ee10, pn = {pi_ = 0x55555734eee0}}, {px = 0x55555734ef20, pn = {pi_ = 0x55555734eff0}}, {px = 0x55555734f030, pn = {pi_ = 0x55555734f100}}, {px = 0x55555734f140, pn = {pi_ = 0x55555734f220}}, {px = 0x55555734f300, pn = {pi_ = 0x55555734f470}}, {px = 0x55555734f550, pn = {pi_ = 0x55555734f6b0}}, {px = 0x55555734f6f0, pn = {pi_ = 0x55555734f800}}, {px = 0x55555734f8e0, pn = {pi_ = 0x55555734f9e0}}, {px = 0x55555734fac0, pn = {pi_ = 0x55555734fb60}}, {px = 0x55555734fc40, pn = {pi_ = 0x55555734fd30}}, {px = 0x55555734fd70, pn = {pi_ = 0x55555734fef0}}, {px = 0x555557350000, pn = {pi_ = 0x555557350100}}, {px = 0x5555573501e0, pn = {pi_ = 0x5555573502e0}}, {px = 0x5555573503c0, pn = {pi_ = 0x5555573504c0}}, {px = 0x555557350500, pn = {pi_ = 0x5555573505d0}}, {px = 0x555557350af0, pn = {pi_ = 0x555557350cb0}}, {px = 0x555557350cf0, pn = {pi_ = 0x555557350dd0}}, {px = 0x555557350eb0, pn = {pi_ = 0x555557351020}}, {px = 0x555557351060, pn = {pi_ = 0x555557351140}}, {px = 0x555557351180, pn = {pi_ = 0x555557351260}}, {px = 0x5555573512a0, pn = {pi_ = 0x555557351380}}, {px = 0x5555573513c0, pn = {pi_ = 0x5555573514a0}}, {px = 0x5555573515f0, pn = {pi_ = 0x5555573516e0}}, {px = 0x555557351800, pn = {pi_ = 0x5555573518a0}}, {px = 0x5555573519e0, pn = {pi_ = 0x555557351ac0}}, {px = 0x555557351b80, pn = {pi_ = 0x555557351c90}}, {px = 0x555557351d10, pn = {pi_ = 0x555557351db0}}, {px = 0x555557351ec0, pn = {pi_ = 0x555557351fb0}}, {px = 0x555557352040, pn = {pi_ = 0x5555573521c0}}, {px = 0x5555573522a0, pn = {pi_ = 0x5555573523a0}}, {px = 0x5555573523e0, pn = {pi_ = 0x555557352480}}, {px = 0x555557352590, pn = {pi_ = 0x5555573526a0}}, {px = 0x5555573527c0, pn = {pi_ = 0x555557352930}}, {px = 0x555557352a40, pn = {pi_ = 0x555557352b30}}, {px = 0x555557352c10, pn = {pi_ = 0x555557352d20}}, {px = 0x555557352e00, pn = {pi_ = 0x555557352f10}}, {px = 0x555557352f50, pn = {pi_ = 0x555557352ff0}}, {px = 0x555557353050, pn = {pi_ = 0x555557353160}}, {px = 0x555557353280, pn = {pi_ = 0x555557353380}}, {px = 0x555557353460, pn = {pi_ = 0x555557353560}}, {px = 0x555557353690, pn = {pi_ = 0x555557353790}}, {px = 0x555557353870, pn = {pi_ = 0x555557353950}}, {px = 0x555557353a20, pn = {pi_ = 0x555557353b00}}, {px = 0x555557353b40, pn = {pi_ = 0x555557353be0}}, {px = 0x555557353cf0, pn = {pi_ = 0x555557353db0}}, {px = 0x555557353e90, pn = {pi_ = 0x555557353f30}}, {px = 0x555557353fa0, pn = {pi_ = 0x555557354070}}, {px = 0x555557354150, pn = {pi_ = 0x555557354250}}, {px = 0x555557354330, pn = {pi_ = 0x555557354430}}, {px = 0x555557354510, pn = {pi_ = 0x555557354620}}, {px = 0x555557354700, pn = {pi_ = 0x5555573547e0}}, {px = 0x5555573548f0, pn = {pi_ = 0x555557354a00}}, {px = 0x555557354b50, pn = {pi_ = 0x555557354cf0}}, {px = 0x555557354d40, pn = {pi_ = 0x555557354e20}}, {px = 0x555557354f50, pn = {pi_ = 0x555557355040}}, {px = 0x555557355120, pn = {pi_ = 0x555557355270}}, {px = 0x5555573552b0, pn = {pi_ = 0x555557355390}}, {px = 0x5555573553d0, pn = {pi_ = 0x555557355470}}, {px = 0x5555573555b0, pn = {pi_ = 0x555557355730}}, {px = 0x555557355850, pn = {pi_ = 0x5555573559b0}}, {px = 0x555557355ac0, pn = {pi_ = 0x555557355b40}}, {px = 0x555557355c50, pn = {pi_ = 0x555557355e40}}, {px = 0x555557355e80, pn = {pi_ = 0x555557355f60}}, {px = 0x555557356080, pn = {pi_ = 0x555557356120}}, {px = 0x555557356230, pn = {pi_ = 0x5555573562e0}}, {px = 0x555557356410, pn = {pi_ = 0x5555573564f0}}, {px = 0x5555573565d0, pn = {pi_ = 0x5555573566b0}}}, belong_to_group = std::vector<bool> of length 85, capacity 128 = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, groups = std::vector of length 2, capacity 2 = {{px = 0x555557358070, pn = {pi_ = 0x555557358710}}, {px = 0x555557358810, pn = {pi_ = 0x5555573590b0}}}}, visible_ = {static m_default_line_length = 80, m_caption = "", m_line_length = 80, m_min_description_length = 40, m_options = std::vector of length 85, capacity 128 = {{px = 0x55555734ce10, pn = {pi_ = 0x55555734cf30}}, {px = 0x55555734d050, pn = {pi_ = 0x55555734d150}}, {px = 0x55555734d170, pn = {pi_ = 0x55555734d210}}, {px = 0x55555734d340, pn = {pi_ = 0x55555734d3e0}}, {px = 0x55555734d420, pn = {pi_ = 0x55555734d540}}, {px = 0x55555734d620, pn = {pi_ = 0x55555734d6c0}}, {px = 0x55555734d7a0, pn = {pi_ = 0x55555734d840}}, {px = 0x55555734d880, pn = {pi_ = 0x55555734d920}}, {px = 0x55555734d960, pn = {pi_ = 0x55555734da40}}, {px = 0x55555734da80, pn = {pi_ = 0x55555734db20}}, {px = 0x55555734e040, pn = {pi_ = 0x55555734e150}}, {px = 0x55555734e230, pn = {pi_ = 0x55555734e350}}, {px = 0x55555734e430, pn = {pi_ = 0x55555734e530}}, {px = 0x55555734e570, pn = {pi_ = 0x55555734e640}}, {px = 0x55555734e720, pn = {pi_ = 0x55555734e820}}, {px = 0x55555734e900, pn = {pi_ = 0x55555734e9a0}}, {px = 0x55555734e9e0, pn = {pi_ = 0x55555734eab0}}, {px = 0x55555734ed00, pn = {pi_ = 0x55555734edd0}}, {px = 0x55555734ee10, pn = {pi_ = 0x55555734eee0}}, {px = 0x55555734ef20, pn = {pi_ = 0x55555734eff0}}, {px = 0x55555734f030, pn = {pi_ = 0x55555734f100}}, {px = 0x55555734f140, pn = {pi_ = 0x55555734f220}}, {px = 0x55555734f300, pn = {pi_ = 0x55555734f470}}, {px = 0x55555734f550, pn = {pi_ = 0x55555734f6b0}}, {px = 0x55555734f6f0, pn = {pi_ = 0x55555734f800}}, {px = 0x55555734f8e0, pn = {pi_ = 0x55555734f9e0}}, {px = 0x55555734fac0, pn = {pi_ = 0x55555734fb60}}, {px = 0x55555734fc40, pn = {pi_ = 0x55555734fd30}}, {px = 0x55555734fd70, pn = {pi_ = 0x55555734fef0}}, {px = 0x555557350000, pn = {pi_ = 0x555557350100}}, {px = 0x5555573501e0, pn = {pi_ = 0x5555573502e0}}, {px = 0x5555573503c0, pn = {pi_ = 0x5555573504c0}}, {px = 0x555557350500, pn = {pi_ = 0x5555573505d0}}, {px = 0x555557350af0, pn = {pi_ = 0x555557350cb0}}, {px = 0x555557350cf0, pn = {pi_ = 0x555557350dd0}}, {px = 0x555557350eb0, pn = {pi_ = 0x555557351020}}, {px = 0x555557351060, pn = {pi_ = 0x555557351140}}, {px = 0x555557351180, pn = {pi_ = 0x555557351260}}, {px = 0x5555573512a0, pn = {pi_ = 0x555557351380}}, {px = 0x5555573513c0, pn = {pi_ = 0x5555573514a0}}, {px = 0x5555573515f0, pn = {pi_ = 0x5555573516e0}}, {px = 0x555557351800, pn = {pi_ = 0x5555573518a0}}, {px = 0x5555573519e0, pn = {pi_ = 0x555557351ac0}}, {px = 0x555557351b80, pn = {pi_ = 0x555557351c90}}, {px = 0x5---Type <return> to continue, or q <return> to quit---
55557351d10, pn = {pi_ = 0x555557351db0}}, {px = 0x555557351ec0, pn = {pi_ = 0x555557351fb0}}, {px = 0x555557352040, pn = {pi_ = 0x5555573521c0}}, {px = 0x5555573522a0, pn = {pi_ = 0x5555573523a0}}, {px = 0x5555573523e0, pn = {pi_ = 0x555557352480}}, {px = 0x555557352590, pn = {pi_ = 0x5555573526a0}}, {px = 0x5555573527c0, pn = {pi_ = 0x555557352930}}, {px = 0x555557352a40, pn = {pi_ = 0x555557352b30}}, {px = 0x555557352c10, pn = {pi_ = 0x555557352d20}}, {px = 0x555557352e00, pn = {pi_ = 0x555557352f10}}, {px = 0x555557352f50, pn = {pi_ = 0x555557352ff0}}, {px = 0x555557353050, pn = {pi_ = 0x555557353160}}, {px = 0x555557353280, pn = {pi_ = 0x555557353380}}, {px = 0x555557353460, pn = {pi_ = 0x555557353560}}, {px = 0x555557353690, pn = {pi_ = 0x555557353790}}, {px = 0x555557353870, pn = {pi_ = 0x555557353950}}, {px = 0x555557353a20, pn = {pi_ = 0x555557353b00}}, {px = 0x555557353b40, pn = {pi_ = 0x555557353be0}}, {px = 0x555557353cf0, pn = {pi_ = 0x555557353db0}}, {px = 0x555557353e90, pn = {pi_ = 0x555557353f30}}, {px = 0x555557353fa0, pn = {pi_ = 0x555557354070}}, {px = 0x555557354150, pn = {pi_ = 0x555557354250}}, {px = 0x555557354330, pn = {pi_ = 0x555557354430}}, {px = 0x555557354510, pn = {pi_ = 0x555557354620}}, {px = 0x555557354700, pn = {pi_ = 0x5555573547e0}}, {px = 0x5555573548f0, pn = {pi_ = 0x555557354a00}}, {px = 0x555557354b50, pn = {pi_ = 0x555557354cf0}}, {px = 0x555557354d40, pn = {pi_ = 0x555557354e20}}, {px = 0x555557354f50, pn = {pi_ = 0x555557355040}}, {px = 0x555557355120, pn = {pi_ = 0x555557355270}}, {px = 0x5555573552b0, pn = {pi_ = 0x555557355390}}, {px = 0x5555573553d0, pn = {pi_ = 0x555557355470}}, {px = 0x5555573555b0, pn = {pi_ = 0x555557355730}}, {px = 0x555557355850, pn = {pi_ = 0x5555573559b0}}, {px = 0x555557355ac0, pn = {pi_ = 0x555557355b40}}, {px = 0x555557355c50, pn = {pi_ = 0x555557355e40}}, {px = 0x555557355e80, pn = {pi_ = 0x555557355f60}}, {px = 0x555557356080, pn = {pi_ = 0x555557356120}}, {px = 0x555557356230, pn = {pi_ = 0x5555573562e0}}, {px = 0x555557356410, pn = {pi_ = 0x5555573564f0}}, {px = 0x5555573565d0, pn = {pi_ = 0x5555573566b0}}}, belong_to_group = std::vector<bool> of length 85, capacity 128 = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, groups = std::vector of length 8, capacity 8 = {{px = 0x555557356760, pn = {pi_ = 0x555557356aa0}}, {px = 0x555557356b20, pn = {pi_ = 0x555557357020}}, {px = 0x555557357040, pn = {pi_ = 0x555557357140}}, {px = 0x555557357160, pn = {pi_ = 0x555557357280}}, {px = 0x5555573572a0, pn = {pi_ = 0x555557357460}}, {px = 0x555557357d40, pn = {pi_ = 0x555557357e50}}, {px = 0x555557357e70, pn = {pi_ = 0x555557357f20}}, {px = 0x555557357f40, pn = {pi_ = 0x555557358050}}}}, hidden_ = {static m_default_line_length = 80, m_caption = "", m_line_length = 80, m_min_description_length = 40, m_options = std::vector of length 0, capacity 0, belong_to_group = std::vector<bool> of length 0, capacity 0, groups = std::vector of length 0, capacity 0}}
        finished = -1
        game = std::unique_ptr<game_launcher> containing 0x5555573591c0
        start_ticks = 336
        res = true
        cursor_manager = {<No data fields>}
        gui_event_manager = {<No data fields>}
        config_manager = Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth exceeded while getting the str of an object: 
Python Exception <class 'RecursionError'> maximum recursion depth excee
...
```

### PR DESCRIPTION
**Pull request by GregoryLundberg**
The key value returned by lua_next, on the Lua stack, cannot be modified.

Certain tests such as lua_isstring will convert the value.

The solution is, instead of testing if they key can be converted to a string, test if it actually is a string by using lua_type.

### CODE REVIEW

File: src/scripting/lua_common.cpp [hunk 1]
```diff
@@ -745,8 +745,9 @@ bool luaW_toconfig(lua_State *L, int index, config &cfg)
 	// Then convert the attributes (string indices).
 	for (lua_pushnil(L); lua_next(L, index); lua_pop(L, 1))
 	{
-		if (lua_isnumber(L, -2)) continue;
-		if (!lua_isstring(L, -2)) return_misformed();
+		int indextype = lua_type(L, -2);
+		if (indextype == LUA_TNUMBER) continue;
+		if (indextype != LUA_TSTRING) return_misformed();
```
Comment (CelticMinstrel) [inline src/scripting/lua_common.cpp]: I don't have a problem with this, but I do question its necessity? From what I understood, it was `lua_tostring` and `lua_tonumber` that modified the stack value, but not `lua_isstring` or `lua_isnumber`.

That said, I suppose the old way would have skipped over tags such as `[12345]`, which are technically legal WML (even though no-one actually uses such tags that I know of).

File: src/scripting/lua_formula_bridge.cpp [hunk 2]
```diff
@@ -70,7 +70,10 @@ class lua_callable : public formula_callable {
 		add_input(inputs, "__list");
 		add_input(inputs, "__map");
 		for(lua_pushnil(mState); lua_next(mState, table_i); lua_pop(mState,1)) {
-			if(lua_isstring(mState, -2) && !lua_isnumber(mState, -2)) {
+			lua_pushvalue(mState, -2);
+			bool t = (lua_type(mState, -1) == LUA_TSTRING) && !lua_isnumber(mState, -1);
+			lua_pop(mState, 1);
+			if (t) {
```
Comment (CelticMinstrel) [inline src/scripting/lua_formula_bridge.cpp]: I suspect the push+pop actually isn't necessary, unless I misread something in the Lua manual.

Also, using this method it's clearly redundant to test for both string and number. Perhaps it was also redundant in the old method, if `lua_isnumber` tests for convertability in the same way that `lua_isstring` does; I probably did this in some misguided attempt to work around the behaviour of `lua_isstring`. In any case, testing for string only should be sufficient.

**Comment by CelticMinstrel** [comment]
As a side note, I noticed the `__tab_enum` metafunction and wonder if any of Wesnoth's userdata types implement it; and if not, whether they should.

File: src/scripting/lua_common.cpp (hunk 1 above)
Comment (GregoryLundberg) [reply src/scripting/lua_common.cpp]: experimentation shows lua_isstring and lua_isnumber do the conversion to be able to tell is succeeded.

once bitten twice shy. If we had a problem with it one place, we probably just have not noticed it elsewhere.

File: src/scripting/lua_formula_bridge.cpp (hunk 2 above)
Comment (GregoryLundberg) [reply src/scripting/lua_formula_bridge.cpp]: I cannot change the index. So I push a copy and I need to clean that up, so a pop. Taht way, the lua_isnumber doesn't change the string "1" to the number 1 and cause a crash.

I decided to do this instead of lua_type because TSTRING implies !TNUMBER and so we must be doing the is-a-string-but-not-convertible-to-a-number thing for some reason.

**Comment by GregoryLundberg** [comment]
Dunno about missing metafunctions. My bend would be they should be there if they make sense. Most specifically, we want to ensure the metatable for Wesnoth userdata is immutable by Lua. But this is all a difference subject and requires more than a few moments consideration.

**Comment by CelticMinstrel** [comment]
Pretty sure the metatables for Wesnoth userdata _are_ immutable to Lua. As far as I know, all of them include a `__metatable` field which is returned instead of the actual table when calling `getmetatable` on the userdata.

File: src/scripting/lua_common.cpp (hunk 1 above)
Comment (CelticMinstrel) [reply src/scripting/lua_common.cpp]: Huh, that's pretty unexpected (and frankly kind of worrying, for a test to be mutating the data its testing), but alright.

File: src/scripting/lua_formula_bridge.cpp (hunk 2 above)
Comment (CelticMinstrel) [reply src/scripting/lua_formula_bridge.cpp]: Hmm. I'm not quite sure whether this is what I originally intended, or if I was trying to work around `lua_isstring` also accepting numbers. Thinking about it now though, it could (in rare cases) make sense to include strings that are convertible to numbers, as these could be valid WML keys.

**Comment by CelticMinstrel** [comment]
By the way, I think you mentioned you weren't sure how to test that this works as expected? I think what you'd need is to do something like this at the Lua console:

```
-- using compile instead of evaluate in case you want to test the formula on different inputs
test_f = wesnoth.compile_formula "dir(self)"
test_f{a=5, ['foo'] = 'bar', ['123'] = 'baz', 'qux', 'zzz'}
```

You could potentially expand the types of keys and values in the table passed to `test_f`, of course. (Actually, for the code you changed, only the keys should matter, as that function is the one that gets a list of all properties on a formula callable.) In that particular case, I would expect the result to be something like this `{'__list', '__map', 'a', 'foo', '123', 1, 2}`, though not necessarily in that order.

**Comment by GregoryLundberg** [comment]
As it stands, this PR fixes the problem with violating the constraint on the index for lua_next

Unfortunately, this does not effect the crash reported in #2171 .. that crash occurs inside lua_next, as well. But it appears to be related to the unit table having 21K indexed values and no hash table at all. lua_next assumes that there is at least an empty hash table and gets a segfault when accessing the first block of a table which was never allocated .. or something like that.

Anyway .. this is beginning to look like an issue in how the data  is marshaled from C++ to Lua.

The OP uses wesnoth.create_unit. I used wesnoth.get_unit and get the same crash.

Without this PR, if I use a Lua-constructed table {a="A","B",c="C") I get SIGABT when trying to step over "B" since the index (1) got converted to string ("1") and Lua caught it and was calling abort() after issuing a diagnostic message.

With this PR, my Lua-constructed table passes, offering just a and c and omitting [1] ("B") since it cannot be a named value. (Note we don't check the string is a valid variable name .. sigh.)

But that is SIGABT not SIGSEG!!!!

So, I'm presently stumped since the error is long before we call lua_next ..

**Comment by jyrkive** [comment]
If this pull request doesn't fix #2171, please edit the commit message accordingly.

File: src/scripting/lua_formula_bridge.cpp [hunk 3]
```diff
@@ -70,7 +70,10 @@ class lua_callable : public formula_callable {
 		add_input(inputs, "__list");
 		add_input(inputs, "__map");
 		for(lua_pushnil(mState); lua_next(mState, table_i); lua_pop(mState,1)) {
-			if(lua_isstring(mState, -2) && !lua_isnumber(mState, -2)) {
+			lua_pushvalue(mState, -2);
+			bool t = (lua_type(mState, -1) == LUA_TSTRING) && !lua_isnumber(mState, -1);
```
Comment (jyrkive) [inline src/scripting/lua_formula_bridge.cpp]: Please use a more descriptive variable name, e.g. `is_valid_key`.

File: src/scripting/lua_formula_bridge.cpp (hunk 2 above)
Comment (jyrkive) [inline src/scripting/lua_formula_bridge.cpp]: Please remove the space after the `if`.

File: src/scripting/lua_kernel_base.cpp [hunk 4]
```diff
@@ -178,7 +178,7 @@ static int intf_name_generator(lua_State *L)
 			if(lua_istable(L, 2)) {
 				std::map<std::string, std::vector<std::string>> data;
 				for(lua_pushnil(L); lua_next(L, 2); lua_pop(L, 1)) {
-					if(!lua_isstring(L, -2)) {
+					if (lua_type(L, -2) != LUA_TSTRING) {
```
Comment (jyrkive) [inline src/scripting/lua_kernel_base.cpp]: Remove the space after the `if`.

**Comment by GregoryLundberg** [comment]
@jyrkive #2171 exposes a major bug in Wesnoth's Lua interface. The fact that the specific error is a segmentation fault does not change the fact that the violation of constraints exists and causes an abort. I believe fixing the underlying segmentation fault would only lead to the abort this PR fixes.

As near as I can tell the segmentation fault is due to the marshaling of an instance the C++ unit class omits support for enumerating. Lua expects it to be a table or be table-like by adding a meta-method; both are omitted.

I could make the case that the segmentation fault is an upstream error. Lua should have recognized that userdata is not a table and should have aborted instead of hitting a segfault when the userdata fails to provide the proper meta-methods.

**Comment by jyrkive** [comment]
Well, my comment was only about this pull request. I can't merge the PR as long as its commit message says that it fixes a bug it doesn't actually fix.

I'm in favor of merging any PR that is an improvement, regardless of whether it achieves its ultimate goal.

File: src/scripting/lua_common.cpp (hunk 1 above)
Comment (GregoryLundberg) [reply src/scripting/lua_common.cpp]: As far as I can see, the only place Lua cares about the fact that data can be mutated is `lua_next` (in C++) and the `next(table, index)` Lua method.

One could argue the error is in the implementation of `lua_next` since the remainder of the language takes pains to ensure it does not matter. To be honest, I was amazed when I saw the constraints; I could understand them, once I saw them, but I expected Lua to be more resilient in this.

**Comment by GregoryLundberg** [comment]
Give me a bit and I'll clean up and decouple from the Issue.

Right now I'm trying to figure out why our userdata tested as TTABLE. There is a check in the Lua which should have aborted (SIGABT, with error message).

And, as @CelticMinstrel mentioned, there's a (missing?, Wesnoth-only?) meta-function which should have avoided the call to lua_next entirely.

**Comment by CelticMinstrel** [comment]
> Right now I'm trying to figure out why our userdata tested as TTABLE.

I think some custom Wesnoth data actually _is_ a table, rather than a userdata. No idea if that's actually relevant here, though.

And yes `__tab_enum` is Wesnoth-only.
