### PR TITLE
IntroWML code cleanup and fix for [image]scaled attribute

### LINKED ISSUE #5223: Does anyone want [story][part][image]scaled=yes ?
This is about the `[story][part][image]` tag, not the main `[image]` tag. This tag is documented on the IntroWML page, but is possibly only used by the macros `OLD_JOURNEY`, `NEW_JOURNEY`, `NEW_BATTLE`, etc.

My question is, does anyone want to keep its `scaled` attribute? This undocumented attribute defaults to false, but if you add `scaled=yes` then the image is scaled up to the width and height of the background - not to the same ratio as the background, but to the full size. So if you have a 1000 pixel wide background in an 800 pixel wide window, then `scaled=yes` means each journey-marker is an 800 pixel-wide blob.

The bug is already present in 1.14, haven't checked 1.12 yet. It would be easy to fix, but as no-one's noticed this bug then I'd prefer to just delete it.

Note: the `scaled` attribute doesn't control the positioning of the image. The x and y co-ordinates will still be scaled so that a journey marker that's meant to be on top of a map location is still correctly placed when the background image is scaled.

### PR DESCRIPTION
**Pull request by stevecotton**
Prior to this commit, the scaled= attribute was undocumented and had what I assume was a bug - when enabled the image was scaled up to the width and height of the background - not to the same ratio as the background, but to the full size. So if you had a 1000 pixel wide background in an 800 pixel wide window, then scaled=yes meant each journey-marker was an 800 pixel-wide blob.

However, if anyone was using it with background-size images as overlays then this commit will break that usage - that use case is still supported by having multiple [background_layer]s.

Closes #5223, which was a question about whether to fix or simply remove the scaled attribute. Given that [background_layer]scale= and [image]scaled= have different meanings (the background_layer one should and does cause it to be full-window), I've kept the 'd' on the end of 'scaled' too.

Use a loop instead of recursion. This cleanup is prompted by #5041 (drawing map labels in IntroWML), which will add more items to be drawn in this loop.  The old implementation would not have triggered tail-recursion optimisations, as the recursion site wasn't the final code in the function.

Correct documentation in the .hpp file about when the delay takes effect (this isn't a behavior change, just a documentation correction).

Review the schema, and remove attributes that aren't supported by the code.  Many of these attributes are supported for `background_layer` but not `image`.

### CODE REVIEW

File: src/gui/dialogs/story_viewer.cpp [hunk 1]
```diff
@@ -319,63 +319,52 @@ void story_viewer::display_part(window& window)
...
-	image["y"] = y_ss.str();
-	image["w"] = floating_image.autoscale() ? "(width)"  : "(image_width)";
-	image["h"] = floating_image.autoscale() ? "(height)" : "(image_height)";
-	image["name"] = floating_image.file();
+		std::ostringstream x_ss;
+		std::ostringstream y_ss;
 
-	// TODO: implement handling of the tiling options.
-	//image["resize_mode"] = "tile_centered"
+		// Floating images are scaled by the same factor as the background.
```
Comment (stevecotton) [inline src/gui/dialogs/story_viewer.cpp:332]: Just before creating this PR, I noticed that this should say "Floating image's locations are scaled ...". Hence opening it as a draft for now.

**Comment by stevecotton** [comment]
The two PRs that have autolinked above fix issues found by the schema changes. As part of my local build I'd checked some of the campaigns against the schema, but not all of them.

**Comment by CelticMinstrel** [comment]
Hmm, I'm kinda having second thoughts about this now. Based on #5223 it was clear that scaling an `[image]` wasn't useful with the current implementation, but I think it actually _is_ useful to be able to scale floating images on larger screens. The problem was that it was scaling to the same size as the background, which isn't correct - it should take the same scale factor that was used on the background and apply it to the image as well. If the background is scaled up 1.2x, then the floating image should also be scaled up 1.2x.

An example of a case where you might want to do this is if the background represents a _setting_ and the floating image is a _character_ that needs to move relative to the setting. Keeping the relative scale the same between background and floating seems correct for that case.

**Comment by stevecotton** [comment]
Thanks for the feedback, I've changed it to support the scaled= attribute.

**Comment by CelticMinstrel** [comment]
Seems good. It does seem a little weird for `[background_layer]` to support `scale=` while `[image]` supports `scaled=` though… should we maybe make it consistent?

**Comment by stevecotton** [comment]
[background_layer]scale= and [image]scaled= have different meanings, so I think it's better for them to have different names. The background_layer one should and does cause that layer to be full-window.

**Comment by CelticMinstrel** [comment]
Hmm, maybe, but those are still awfully similar names…

**Comment by stevecotton** [comment]
Maybe `resize_with_background` or just `resize`?

**Comment by CelticMinstrel** [comment]
Yeah, maybe something like that would help avoid confusion…

**Comment by stevecotton** [comment]
Planning to merge this today, if there are no more comments.

**Comment by stevecotton** [comment]
The wiki is currently down for maintenance - added this to the undocumented list as a reminder to myself.
