### PR TITLE
Solve bugs of [set_variables], closes #10977 closes #11081

### LINKED ISSUE #10977: [set_variables]  produces unexpected behavior and errors in certain cases
### Game and System Information

- **Version:** 1.19.20 from SourceForge
- **OS:** Win 11

### Description of the bug

[set_variables] has a few different errors it can produce, resulting in code producing unexpected results, or throwing an error & stopping. These appeared sometime in the 1.19 series.

see steps to reproduce.

### Steps to reproduce the behavior

the following code, which works in the latest 1.18 from steam:
(the arrays show up interleaved in gamestate inspector)

```
[event]

        name=start
        {VARIABLE index 0}
        [while]
            {VARIABLE_CONDITIONAL index numerical_not_equals 10}
            [do]
                [set_variables]
                    name=array[$index]
                    [value]
                        amount=$index
                    [/value]
                [/set_variables]
                [set_variables]
                    name=dupe_array[$index]
                    [value]
                        amount=$index
                    [/value]
                [/set_variables]
                {VARIABLE_OP index add 1}
            [/do]
        [/while]
        {VARIABLE new_index 5}
        {VARIABLE new_index_2 1}
        [set_variables]
            name=array[$new_index]
            to_variable=dupe_array[$new_index_2]
        [/set_variables]
    [/event]
```

produces the following errors in 1.19.20:
creates arrays of 18 members instead of the expected 10
and
the set_variables at the end with 'name' & 'to_variable' throws the following error to the log.
error wml: Error occured inside [set_variables]: lua/core/wml.lua:440: bad 'for' limit (number expected, got nil)

and
if you replace the final [set_variables] with:
```
        [set_variables]

            name=dupe_array[0]
            [value]
                amount=100
            [/value]
        [/set_variables]
```
1.18 works as expected, only setting the value of the first element, but in 1.19.20 it also wipes the rest of the array

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #11081: [set_variables] corrupts the destination
### Game and System Information

- **Version:** 1.19.21+dev @ `66432bc545f6a99d75552a30c91926cc0c8c4bcd`
- **OS:** macOS Sequoia 15.7.4

### Description of the bug

`[set_variables]` has unexpected behaviour which results in the target of a `mode=merge` operation being corrupted in unexpected ways under unclear circumstances. One example I'm currently tracking as a bug in my own campaign involves an array growing infinitely as a result of a `mode=merge` operation.

This bug report deals with a more basic manifestation of the bug wherein an array has its items incorrectly modified, and even mysteriously grows by one.

### Steps to reproduce the behavior

1. Patch Two Brothers scenario 1 with the following code in prestart below the line where Magrid is created:

```
        [store_unit]
            [filter]
                id=Arvith
            [/filter]
            mode=append
            variable=player_units
        [/store_unit]

        [store_unit]
            [filter]
                id=Alwyn
            [/filter]
            mode=append
            variable=player_units
        [/store_unit]

        [store_unit]
            [filter]
                id=Brent
            [/filter]
            mode=append
            variable=player_units
        [/store_unit]

        [inspect][/inspect]

        [set_variables]
            mode=merge
            name="player_units[0]"
            [value]
                x=1234
                y=1234
            [/value]
        [/set_variables]

        [set_variables]
            mode=merge
            name="player_units[1]"
            [value]
                x=5678
                y=5678
            [/value]
        [/set_variables]

        [set_variables]
            mode=merge
            name="player_units[2]"
            [value]
                x=9012
                y=9012
            [/value]
        [/set_variables]

        [inspect][/inspect]
```

2. Launch the scenario.
3. You will see a first gamestate inspector window where you can verify that the `player_units` array initially contains three items, these being the unit states for Arvith, Alwyn, and Brent. This is prior to the `[set_variables]` operations.
4. After dismissing the first inspector window, you'll see another where you'll observe that the `player_units` members have had their data completely cleared expect for the WML which was supposed to be merged, and it has also gained a fourth member which seems to be a clone of the second, even though the WML command sequence requests no such thing.

### Expected behavior

In step 4 above, the result should be identical to #3, except that the x,y values of each member should have been replaced with (1234,1234), (5678,5678), and (9012,9012), respectively. (Yes, these would be clearly invalid map coordinates, but the test case never unstores the units nor it's meant to. They are chosen solely to bring visibility to the data that's supposed to be merged.)

### Additional context

project-ethea/Invasion_from_the_Unknown#118 appears to be a specific manifestation of this bug resulting from a similar sequence, where the target array suddenly starts growing infinitely specifically on [line 404 of the scenario](https://github.com/project-ethea/Invasion_from_the_Unknown/blob/master/scenarios/23C_Broken_Heart.cfg#L404) for no obvious reason.

### PR DESCRIPTION
**Pull request by ProditorMagnus**
Solve bugs of [set_variables], closes #10977 closes #11081

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
I did not look #11081 since that needs specific campaign that I cant run with `lua wesnoth.require("wml-utils").handle_event_commands(wml.tovconfig(wml.load("~add-ons/EventLoader/action.cfg")))`

**Comment by ProditorMagnus** [comment]
I think test failures are real, but tests need to work with higher index for #10977 to be visible.

**Comment by newfrenchy83** [comment]
look at line 71 idx = idx + 1

File: data/lua/wml/set_variables.lua [hunk 1]
```diff
@@ -66,36 +67,53 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
...
+            wml.array_access.set(realvar, wml.child_array(merged, 'value'), variables)
+        else
+            local merged = wml.merge(merge_with, data, mode)
+            wml.array_access.set(realvar, wml.child_array(merged, 'value'), variables)
 		end
-		local merged = wml.merge(merge_with, data, mode)
-		-- If we started at a specific index, add back everything that came before and after
-		for i = 1, #head do
-			table.insert(merged, i, head[i])
+	elseif mode == "append" then
```
Comment (ProditorMagnus) [inline data/lua/wml/set_variables.lua:126]: documentation says explicit_idx has to be ignored for append

File: data/lua/wml/set_variables.lua [hunk 2]
```diff
@@ -66,36 +67,53 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
...
+            end
+            for i = 1, #data do
+                table.insert(merged, data[i])
+            end
+            for i = 1, #tail do
+                table.insert(merged, tail[i])
+            end
+            wml.array_access.set(realvar, wml.child_array(merged, 'value'), variables)
+        else
+            local merged = wml.merge(merge_with, data, mode)
```
Comment (ProditorMagnus) [inline data/lua/wml/set_variables.lua]: this might still be wrong, tests pass so have not focused on that use case

File: data/lua/wml/set_variables.lua [hunk 3]
```diff
@@ -66,36 +67,53 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
...
+                end
 			end
+			
 			if mode == "merge" then
 				-- For merge mode, all the values are merged together before being merged into the specific element
 				local data_merged = {}
 				for i = 1, #data do
 					data_merged = wml.merge(data_merged, data[i].contents, "append")
 				end
+                data_merged = wml.merge(merge_with[idx].contents, data_merged, "append") -- TODO really append?
```
Comment (ProditorMagnus) [inline data/lua/wml/set_variables.lua]: I do not understand how merge_explicit is expected to work. Test has
```
        [value]
            value=12
            [tag]
                __remove=yes
            [/tag]
            [tag]
            [/tag]
            [tag]
                core=splinter
            [/tag]
        [/value]
        [value]
            square=4096
            [tag]
                name=foo
            [/tag]
        [/value]
        [value]
            test=9
            [tag]
                name=bar
            [/tag]
        [/value]
```
and documentation has ` If given an explicit index, all the [value] and [literal] tags will be merged together into a single tag (as if with mode=append), and this resulting container will then be merged into the container at the specified element.`. First off, why append? That would produce multiple elements. Then my understanding is that since values first have to be merged, before merging to original data, then `__remove=yes` would remove tag with `name=foo`, not with `core=left` like test expects.

I disabled set_variables_merge_explicit test and created set_variables_replace_explicit_10977, and everything other than set_variables_merge_explicit is successful.

**Comment by ProditorMagnus** [comment]
AI code review of @CelticMinstrel Lua implementation: [11090.md](https://github.com/user-attachments/files/26144126/11090.md)

Review validation results (bulleted comments)

I asked code review from https://notebooklm.google.com/notebook/53343dd8-ee5a-4c68-8b13-7d62ff7100c6

1. The code calls wml.valid_var(name) multiple times to validate variable names. However, the wml module summary does not list a function named valid_var
    - need to update wiki, function actually exists

2. The rewrite retrieves child.contents.key but does not provide a fallback. If the key is missing in the WML, key_name will be nil.
    - need to adjust code so that child.contents.key defaults to 'value'

3. Misuse of wml.merge for Array Operations
The code attempts to use wml.merge(merge_with, data, mode) to handle the append and replace modes for arrays
The Bug: wml.merge is defined as a function that merges two WML tables (configs) recursively
It is intended to merge attributes and child tags within a single container.
Consequence: [set_variables] is an array-level tool. For mode=replace, the array should be cleared and entirely replaced by the new data
wml.merge with mode=replace will instead try to merge the contents of the first container in the array with the new data, which is not the standard WML behavior for replacing an array.
    - sounds plausible but not fully trusting

4. Index Syntax Applied to Wrong Modes
    - false positive, index is important for replace, merge, insert. Append is required to ignore index even if one is provided

5. Lua Type Error in insert Mode
    - false positive, Lua converts string to number automatically

6. Off-by-One and Indexing Logic
WML arrays are 0-indexed, while Lua tables are 1-indexed.
The Bug: In the insert block, the code uses table.insert(insert_into, idx + i, data[i]).
Consequence: If idx is 0 (the default), and i is 1 (the first element of data), it inserts at Lua index 1. This correctly places it at the front. However, if the user provides name=my_array[1], idx becomes "1". 1 + 1 = 2. In Lua, inserting at index 2 of an empty or 1-element table is fine, but if the intention was to match WML's 0-based logic perfectly across all modes, the inconsistent conversion of idx (only adding +1 for some modes but not insert) will lead to elements being placed in the wrong positions.
    - seems to work correctly already

7. Incorrect Iteration of to_split
In the [split] logic where no separator is provided, the code uses ipairs(to_split)
The Bug: to_split (from child.contents.list) is a string. ipairs only works on tables.
Consequence: To iterate over characters in a string in Wesnoth Lua, you should use stringx.iter_ranges or similar string-processing functions. ipairs on a string will simply do nothing (or error), resulting in an empty array.
    - AI should be correct, but wesnoth seems to accept it. ipairs() should reject strings `(bad argument #1 to 'ipairs' (table expected, got string))`, but in wesnoth Lua console it somehow works

**Comment by newfrenchy83** [comment]
the first case in https://github.com/wesnoth/wesnoth/issues/11081 isssue is solved, i tested that but you should replace space by tabulation

**Comment by newfrenchy83** [comment]
test fail :

 `
warning wml: Error (strict mode, strict_level = 1): wesnoth reported on channel warning wml

20260320 15:14:05 warning wml: The following conditional test unexpectedly failed:
	[variable]
		equals="right"
		name="test[2].tag[0].core"
	[/variable]
	
	Interpolated to:
	[variable]
		equals="right"
		name="test[2].tag[0].core"
	[/variable]
	
	Note: The variable test[2].tag[0].core currently has the value left.
BROKE STRICT (FAIL) (10): set_variables_merge_explicit
`

**Comment by gfgtdf** [comment]
> The code attempts to use wml.merge(merge_with, data, mode) to handle the append and replace modes for arrays

Whie it it coudl surely somehow work this is indeed for me the main thing that always puts me off of the current implementation. So if the current implementation has isues i'd suggest just to do what the old  implementation did like:(untested code)


```
if mode == "append" then
  idx = (idx or wml.variables[real_name .. ".length"]) + 1
  -- append means insert at end
  mode = "insert"
end
if mode == "repalce" then
  wml.variables[name] = nil
  -- implement replace as delete then insert
  mode = "insert"
end
if mode == "insert" then
-- the previous impleemntation taken form this pr
local insert_into = wml.array_access.get(realvar, variables)
		for i = 1, #data do
			table.insert(insert_into, idx + i, data[i])
		end
		wml.array_access.set(realvar, insert_into, variables);
elseif mode == "merge" then
  -- handle merge case only
else 
wml.error("unknown mode for [set_variables]: " .. cfg.mode)
end
```

File: data/lua/wml/set_variables.lua (hunk 3 above)
Comment (soliton-) [reply data/lua/wml/set_variables.lua]: > If given an explicit index, all the [value] and [literal] tags will be merged together into a single tag (as if with mode=append)

This is confusingly worded but means all `[value]` and `[literal]` tags are appended into one. So in this example that results in 5 `[tag]` tags.

> this resulting container will then be merged into the container at the specified element

That then means that those 5 tags will be merged with the 2 tags at index 2 (`core=left` and `core=right`). This results in the first tag (`core=left`) being removed, next left as is and the rest appended. So in the end there are 4 tags left satisfying the test conditions.

The tests were added before the switch to the lua implementation so should all have been run successfully with the C++ implementation.

Comment (ProditorMagnus) [reply data/lua/wml/set_variables.lua]: That is quite surprising, but it does explain why there is append. Now all tests pass

**Comment by newfrenchy83** [comment]
you should fix https://github.com/wesnoth/wesnoth/actions/runs/23353979697/job/67939896324?pr=11090

**Comment by ProditorMagnus** [comment]
Missing wml.valid_var documentation is the main blocker for merging now, once that is available it can be marked nondraft.

**Comment by newfrenchy83** [comment]
all check have passed

**Comment by ProditorMagnus** [comment]
added documentation

**Comment by ProditorMagnus** [comment]
After diff review (looks like new code is too long to give to notebook) I got more comments. Most are irrelevant, but I will need to investigate if one comment is real.

### 4. Boundary Check for `insert` Mode
The `insert` mode logic uses `table.insert(insert_into, idx + i, data[i])`.
*   **The Bug:** While Wesnoth's Lua handles the string-to-number coercion for `idx + i`, there is no check to ensure `idx` is within the bounds of the existing array.
*   **The Consequence:** WML documentation notes that if an invalid index is used, the engine should create empty containers before the insertion. Standard Lua `table.insert` will instead throw an error if you attempt to insert into a position significantly beyond the end of the table (e.g., index 10 in a 2-element table).

**Comment by ProditorMagnus** [comment]
Real.

**Comment by ProditorMagnus** [comment]
Next round
1. looks like important issue and needs testing
2. looks like comment that the use case is strange, but works as it should
3. could be optimized to not do for full replace, but probably performance is not important
4. is not in scope of this PR

Based on the sources, here are the remaining probable bugs and logic considerations in this new section:

### 1. Potential Crash on Out-of-Bounds `merge`
In the `explicit_idx` block for `mode == "merge"`, the code performs:
`data_merged = wml.merge(merge_with[idx].contents, data_merged, mode)`
*   **The Bug**: If a user attempts to merge into an index that does not exist (for example, using `name=arr` on an array with only 2 elements), **`merge_with[idx]` will be `nil`**. 
*   **Consequence**: Attempting to access `.contents` on a `nil` value will cause an immediate Lua runtime error.
*   **Recommendation**: You should check if the element exists and provide an empty table as a fallback, similar to how WML creates empty containers for invalid indices during insertion.
    ```lua
    local target_container = merge_with[idx] and merge_with[idx].contents or {}
    data_merged = wml.merge(target_container, data_merged, mode)
    ```

### 2. Logic Discrepancy: `replace` with Index
When an explicit index is used with `mode == "replace"`, your code removes the element at that index and inserts the entire `data` array in its place, while preserving the "tail" (elements after the index).
*   **The Consideration**: In standard WML, `mode=replace` without an index replaces the **entire array**. 
*   **The Status**: While the WML documentation focuses on the index syntax for `mode=insert`, your implementation treats `mode=replace` with an index as a "replace-element-and-shift" operation. If the intended behavior for `replace` at an index was to clear the *entire* array and start fresh at that index, your current logic (which keeps the `head` and `tail`) would be incorrect. However, for most use cases, your "sub-array replacement" logic is likely what a script writer would expect.

### 3. Efficiency of Double Wrapping/Unwrapping
Your code converts every element of `merge_with` and `data` into WML tags (`wml.tag.value`) and then later "unwraps" them with `wml.child_array`.
*   **The Consideration**: While this is functionally correct and allows you to use `wml.merge` for index-alignment, it involves significant table creation and iteration for large arrays (like a list of every location on a map). 
*   **The Status**: For small-to-medium arrays typical of unit variables or scenario settings, this is perfectly acceptable. For very large data sets, a manual loop calling `wml.merge` on raw container pairs might be more performant, but it would be significantly more complex to write.

### 4. Unaddressed `to_variable` for Containers
The `TODO` regarding `cfg.to_variable` remains.
*   **The Status**: Standard WML allows `to_variable` to point to a specific container (e.g., `my_unit.variables`). Because `wml.array_access.get` is designed for **arrays**, it may fail to correctly copy a single container if that is what the user provided in the `to_variable` attribute.

### Summary of Mode Alignment
*   **`insert`**: Successfully uses a `while` loop for boundary padding and `table.insert` for 1-based alignment. **(Resolved)**
*   **`append`**: Correctly retrieves the array and appends raw containers. **(Resolved)**
*   **`replace` (No Index)**: Correctly overwrites the target variable with the new data. **(Resolved)**
*   **`merge`**: Uses tag-wrapping to force `wml.merge` to align by index. **(Resolved logic, requires nil check)**

File: data/lua/wml/set_variables.lua [hunk 4]
```diff
@@ -66,38 +67,60 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
...
+					head[i] = merge_with[i]
+				end
+				if i > idx then
+					table.insert(tail, merge_with[i])
+				end
 			end
+
 			if mode == "merge" then
-				-- For merge mode, all the values are merged together before being merged into the specific element
+				-- For merge mode, all the values are merged (by append) together before being merged into the specific element
```
Comment (soliton-) [inline data/lua/wml/set_variables.lua]:
```suggestion
				-- For merge mode, all [value] and [literal] tags are joined together before being merged into the specific element
```
That's what I wrote on the wiki documentation now anyway. I hope that's clearer.

**Comment by newfrenchy83** [comment]
checks passed

**Comment by ProditorMagnus** [comment]
11081 is still solved?

**Comment by newfrenchy83** [comment]
> 11081 is still solved?

first case is still solved, but idon't know for second case

**Comment by ProditorMagnus** [comment]
I looked its comment, to_variable=test_source[0] is out of scope of this pr.

**Comment by newfrenchy83** [comment]
@ProditorMagnus uour PR, is megeable immedialtely or not, because next release planned for today

File: data/lua/wml/set_variables.lua [hunk 5]
```diff
@@ -16,7 +16,13 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
 				settings = wml.tostring(wml.literal(cfg))
 			}))
 		end
-		data = wml.array_access.get(cfg.to_variable, variables)
+		-- cfg.to_variable is allowed to refer to container variable (for example array element) instead of array, but wml.array_access.get does not support that
+		local variables_proxy = variables or wml.variables
```
Comment (ProditorMagnus) [inline data/lua/wml/set_variables.lua:20]: I did not expect variables as nil

File: data/lua/wml/set_variables.lua [hunk 6]
```diff
@@ -16,7 +16,13 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
...
+		if variables_proxy[cfg.to_variable .. ".length"] then
```
Comment (ProditorMagnus) [inline data/lua/wml/set_variables.lua:21]: length check should work

**Comment by newfrenchy83** [comment]
all check passed, is length check added to tests?

File: data/lua/wml/set_variables.lua (hunk 6 above)
Comment (gfgtdf) [reply data/lua/wml/set_variables.lua:21]: in theory this coudl break if the wml node contains an atribute "length", but good enough for now

File: data/lua/wml/set_variables.lua [hunk 7]
```diff
@@ -66,38 +72,68 @@ function wesnoth.wml_actions.set_variables(cfg, variables)
 		-- If specific index was specified, we start the operation at that index.
 		-- Thus, split the array into two parts such as that index is the first element of the second part
 		local head = {}
+		local tail = {}
 		if explicit_idx then
```
Comment (gfgtdf) [inline data/lua/wml/set_variables.lua:76]: i'm sure this whole block can be simplified quite a bit, but that's probably also something for after the next 1.19 release

File: data/lua/wml/set_variables.lua (hunk 6 above)
Comment (ProditorMagnus) [reply data/lua/wml/set_variables.lua:21]: It may be interesting to test whether proxy returns {VARIABLE node.length no} or array length, but I agree that there is no need to focus on such hacks.

File: data/lua/wml/set_variables.lua (hunk 7 above)
Comment (ProditorMagnus) [reply data/lua/wml/set_variables.lua:76]: I agree, and with replace and no idx there is no need to process existing variable data
