### PR TITLE
GUI2/Story Viewer: title text positioning support in [part]

### LINKED ISSUE #10616: Add "title_valignment" key to [part]
### Describe the desired feature

`[part]` supports the `text_alignment` key (left, center, right) and `text_layout` key (top, middle, bottom).

`[part]` also supports a horizontal alignment key, but no equivalent vertical alignment key. Having a `title_valignment` that functions identically to `text_layout` (but affecting the title instead of the text) would be helpful to display large, centered text without the need for workarounds.

Example that currently requires a workaround, and a crash that the workaround causes on small screens:
```
[part]
    #po: newlines at the beginning help to (depending on the screen size) center this vertically. The space at the end stops the last letter from getting cut off
    title=_"<span font_family='WesScript' size='90000'>


<i>The Deceiver’s Gambit </i></span>"
    title_alignment=center
[/part]
```
Image

Image

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #10616.
Introduces a new key `title_position` that allows for more positioning control of story screen title text. Syntax: `title_position = <X>,<Y>` or `title_position = centered`. X and Y must be one of the special values:
X : `left`, `right`, `center`
Y : `top`, `bottom`, `middle`

(Note: this won't afftect the alignment of the text, so `title_alignment` in conjunction with this may be needed.)

Example:
```ini
[part]
    title= _ "<i>The Legend of Wesmere</i>
Chapter One"
    title_position=centered
    title_alignment=center
[/part]
 ```
 
 Also, the title text will now *fade in/out* just like the part text.

### CODE REVIEW

**Comment by babaissarkar** [comment]
FYI @Dalas121 , I've changed the key name, and left `title_alignment` as it was. The latter is the alignment of the text itself like you would see on word processor while the support here is for positioning.

File: src/storyscreen/part.cpp [hunk 1]
```diff
@@ -1,100 +1,101 @@
...
+Part of the Battle for Wesnoth Project https://www.wesnoth.org/
+
+This program is free software; you can redistribute it and/or modify
+it under the terms of the GNU General Public License as published by
+the Free Software Foundation; either version 2 of the License, or
+(at your option) any later version.
+This program is distributed in the hope that it will be useful,
+but WITHOUT ANY WARRANTY.
+
+See the COPYING file for more details.
```
Comment (soliton-) [inline src/storyscreen/part.cpp]: Something went wrong here.

Comment (Wedge009) [reply src/storyscreen/part.cpp]: The indentation? Maybe something `wmlindent` requires?

Comment (babaissarkar) [reply src/storyscreen/part.cpp]: Something in vscode accidentally reindented this, I'll check.

Comment (babaissarkar) [reply src/storyscreen/part.cpp]: Should be fixed now.

Comment (Wedge009) [reply src/storyscreen/part.cpp]: Still looks like changed indentation in my GitHub view...

Comment (Vultraz) [reply src/storyscreen/part.cpp]: The cfg file indent has been fixed but the indent in the cpp file is still messed up (including the copyright notice).

Comment (babaissarkar) [reply src/storyscreen/part.cpp]: CPP file should also be fixed now.

**Comment by babaissarkar** [comment]
@Dalas121 would you like `title_font_size`/`title_color` keys, or do that using markup like now?

**Comment by Dalas121** [comment]
I'm fine using markup, unless there's a reason why that's not appropriate or less flexible.

File: data/gui/themes/default/dialogs/story_viewer.cfg [hunk 2]
```diff
@@ -276,25 +276,58 @@
...
+							[row]
+								grow_factor = 1
+								[column]
+									border = "all"
+									border_size = 10
+									grow_factor = 1
+									horizontal_grow = true
+									vertical_grow = true
+
+									[drawing]
```
Comment (Vultraz) [inline data/gui/themes/default/dialogs/story_viewer.cfg]: Since this is a stacked widget, we should be able to reuse the story_screen_title label definition rather than going directly for [drawing]. Expand it fully (horizontal_grow = true, vertical_grow = true) and handle the canvas stuff in the label definition itself.

Also please keep the spacing between tags consistent.

File: src/storyscreen/part.hpp [hunk 3]
```diff
@@ -319,6 +320,11 @@ class part : private story_parser
 		return title_alignment_;
 	}
 
+	/** Retrieves the percentage based position of the title text */
+	const point& title_position() {
```
Comment (Vultraz) [inline src/storyscreen/part.hpp]:
```suggestion
	const point& title_position() const
	{
```

File: src/storyscreen/part.cpp [hunk 4]
```diff
@@ -190,6 +192,48 @@ void part::resolve_wml(const vconfig& cfg)
 		text_alignment_ = cfg["text_alignment"].str();
 	}
 
+	auto decode_position = [loc = text_block_loc_](const std::string& pos_str, const bool vertical) -> int {
```
Comment (Vultraz) [inline src/storyscreen/part.cpp]: decode_position is only called once with vertical true and one with vertical false. Better to split these into two separate lambdas. Also the lambda declaration should be const, and no need for the trailing return type.

File: src/gui/dialogs/story_viewer.cpp [hunk 5]
```diff
@@ -486,6 +483,11 @@ void story_viewer::update()
 
 	unsigned short new_alpha = std::clamp<short>(fade_step_ * 25.5, 0, ALPHA_OPAQUE);
 	find_widget<scroll_label>("part_text").set_text_alpha(new_alpha);
+	drawing& title = find_widget<drawing>("title_text");
```
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp]: This will need to be adjusted back to a label if keep the custom label definition.

File: src/gui/dialogs/story_viewer.cpp [hunk 6]
```diff
@@ -235,24 +235,21 @@ void story_viewer::display_part()
...
+			auto& title_position = current_part_->title_position();
+			canv.set_variable("hperc", wfl::variant(title_position.x));
+			canv.set_variable("vperc", wfl::variant(title_position.y));
+			canv.set_variable("fade_alpha", wfl::variant(0));
+		}
 		title_label.set_label(title_text);
-	} else {
-		showing_title = false;
-
-		title_label.set_visible(widget::visibility::invisible);
```
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp:254]: What happened to hiding the title if we have no text?

**Review by Vultraz — CHANGES_REQUESTED** [review]

File: src/gui/dialogs/story_viewer.cpp (hunk 6 above)
Comment (babaissarkar) [reply src/gui/dialogs/story_viewer.cpp:254]: Did you miss this? `title_label.set_visible(showing_title);` It's the bool overload.

**Comment by babaissarkar** [comment]
@Vultraz all changes implemented.

File: src/gui/dialogs/story_viewer.cpp [hunk 7]
```diff
@@ -486,6 +484,12 @@ void story_viewer::update()
 
 	unsigned short new_alpha = std::clamp<short>(fade_step_ * 25.5, 0, ALPHA_OPAQUE);
 	find_widget<scroll_label>("part_text").set_text_alpha(new_alpha);
+	label& title = find_widget<label>("title_text");
+	title.set_text_alpha(new_alpha);
+	// for (auto& canv : title.get_canvases()) {
```
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp]: Commented-out code.

File: src/storyscreen/part.cpp [hunk 8]
```diff
@@ -190,6 +192,48 @@ void part::resolve_wml(const vconfig& cfg)
...
+		} else if (pos_str == "middle") {
+			return loc == BLOCK_MIDDLE ? 0 : 50;
+		} else if (pos_str == "bottom") {
+			return loc == BLOCK_BOTTOM ? 50 : 100;
+		} else {
+			return 0;
+		}
+	};
+
+	std::string hpos, vpos;
```
Comment (Vultraz) [inline src/storyscreen/part.cpp]: The hpos and vpos variables aren't used anywhere except the block below, so we should eliminate them or keep them in proper scope. Also, as-is, the code has potential out-of-bounds access on vals[0] if bad data is provided to `title_position`. Thoughts on this? (Is it useful to warn if more than 2 values are given? 🤔)

```cpp
	if(cfg["title_position"] == "centered") {
		title_perc_pos_ = {50, 50};
	} else {
		const auto vals = utils::split(cfg["title_position"]);
		switch(vals.size()) {
		case 0:
			// No values provided. Default to top-left
			title_perc_pos_ = {0, 0};
			break;

		case 1:
			// Singe horizontal and vertical value
			title_perc_pos_ = {decode_hposition(vals[0]), decode_vposition(vals[0])};
			break;
			
		default:
			// Separate horizontal and vertical values
			title_perc_pos_ = {decode_hposition(vals[0]), decode_vposition(vals[1])};
			break;
		}
	}
```

File: src/storyscreen/part.cpp [hunk 9]
```diff
@@ -190,6 +192,48 @@ void part::resolve_wml(const vconfig& cfg)
 		text_alignment_ = cfg["text_alignment"].str();
 	}
 
+	auto decode_hposition = [](const std::string& pos_str) {
```
Comment (Vultraz) [inline src/storyscreen/part.cpp]:
```suggestion
	const auto decode_hposition = [](const std::string& pos_str) {
```

File: src/storyscreen/part.cpp [hunk 10]
```diff
@@ -190,6 +192,48 @@ void part::resolve_wml(const vconfig& cfg)
...
+		} else if (pos_str == "center") {
+			return 50;
+		} else if (pos_str == "right") {
+			return 100;
+		} else {
+			return 0;
+		}
+	};
+
+	auto decode_vposition = [loc = text_block_loc_](const std::string& pos_str) {
```
Comment (Vultraz) [inline src/storyscreen/part.cpp]:
```suggestion
	const auto decode_vposition = [&loc = text_block_loc_](const std::string& pos_str) {
```

File: src/storyscreen/part.cpp [hunk 11]
```diff
@@ -21,6 +21,8 @@
 #include "storyscreen/part.hpp"
 
 #include "config.hpp"
+#include "log.hpp"
```
Comment (Vultraz) [inline src/storyscreen/part.cpp]: Are these two includes needed anymore?

File: src/gui/dialogs/story_viewer.cpp
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp]: Since we aren't using [drawing], please remove the include.

File: src/gui/dialogs/story_viewer.cpp [hunk 12]
```diff
@@ -486,6 +484,12 @@ void story_viewer::update()
 
 	unsigned short new_alpha = std::clamp<short>(fade_step_ * 25.5, 0, ALPHA_OPAQUE);
 	find_widget<scroll_label>("part_text").set_text_alpha(new_alpha);
+	label& title = find_widget<label>("title_text");
+	title.set_text_alpha(new_alpha);
```
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp]:
```suggestion
	find_widget<label>("title_text").set_text_alpha(new_alpha);
```

File: src/gui/dialogs/story_viewer.cpp (hunk 6 above)
Comment (Vultraz) [reply src/gui/dialogs/story_viewer.cpp:254]: I did miss it. My bad!

File: data/gui/themes/default/dialogs/story_viewer.cfg [hunk 13]
```diff
@@ -276,25 +276,40 @@
...
-				grow_factor = 1
+					[stacked_widget]
+						id = "background_stack"
+						[layer]
+							[row]
+								grow_factor = 1
+								[column]
+									border = "all"
+									border_size = 10
+									grow_factor = 1
```
Comment (Vultraz) [inline data/gui/themes/default/dialogs/story_viewer.cfg]:
```suggestion
```

File: data/gui/themes/default/dialogs/story_viewer.cfg [hunk 14]
```diff
@@ -276,25 +276,40 @@
...
+										use_markup = true
+									[/label]
+								[/column]
+							[/row]
+						[/layer]
+						[layer]
+							[row]
+								grow_factor = 1
+								[column]
+									grow_factor = 1
```
Comment (Vultraz) [inline data/gui/themes/default/dialogs/story_viewer.cfg]:
```suggestion
```

File: src/gui/dialogs/story_viewer.cpp [hunk 15]
```diff
@@ -235,24 +235,22 @@ void story_viewer::display_part()
...
-		title_label.set_visible(widget::visibility::visible);
-		title_label.set_text_alignment(title_text_alignment);
+	bool showing_title = current_part_->show_title() && !title_text.empty();
+	title_label.set_visible(showing_title);
+	if(showing_title) {
+		for(auto& canv : title_label.get_canvases()) {
+			auto& title_position = current_part_->title_position();
+			canv.set_variable("hperc", wfl::variant(title_position.x));
+			canv.set_variable("vperc", wfl::variant(title_position.y));
+			// canv.set_variable("fade_alpha", wfl::variant(0));
```
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp]:
```suggestion
```

File: src/gui/dialogs/story_viewer.cpp [hunk 16]
```diff
@@ -486,6 +484,12 @@ void story_viewer::update()
 
 	unsigned short new_alpha = std::clamp<short>(fade_step_ * 25.5, 0, ALPHA_OPAQUE);
 	find_widget<scroll_label>("part_text").set_text_alpha(new_alpha);
+	label& title = find_widget<label>("title_text");
+	title.set_text_alpha(new_alpha);
+	// for (auto& canv : title.get_canvases()) {
+	// 	canv.set_variable("fade_alpha", wfl::variant(new_alpha));
+	// }
```
Comment (Vultraz) [inline src/gui/dialogs/story_viewer.cpp]:
```suggestion
```

File: src/storyscreen/part.cpp (hunk 8 above)
Comment (Vultraz) [reply src/storyscreen/part.cpp]: Alternatively, if you prefer a more functional style:
```cpp
	title_perc_pos_ = std::invoke(
		[&, &position = cfg["title_position"]]() -> point {
			if(position == "centered") {
				return {50, 50};
			}

			const auto vals = utils::split(position);
			switch(vals.size()) {
			case 0:
				// No values provided. Default to top-left
				return {0, 0};

			case 1:
				// Singe horizontal and vertical value
				return {decode_hposition(vals[0]), decode_vposition(vals[0])};
				
			default:
				// Separate horizontal and vertical values
				return {decode_hposition(vals[0]), decode_vposition(vals[1])};
			}
		});

```

Comment (babaissarkar) [reply src/storyscreen/part.cpp]: > Also, as-is, the code has potential out-of-bounds access on vals[0] if bad data is provided to `title_position`.

Wouldn't the decoder functions return zero in that case? An example of bad value would be helpful.

Also, I'd borrow the first variant from here, thanks.

**Review by Vultraz — APPROVED** [review]
