### PR TITLE
Prevent program hang when compiled with relative path PREFERENCES_DIR

### LINKED ISSUE #2000: wesnoth --userconfig-dir is relative to home
Current:
` --userconfig-dir arg            sets the path of the user config directory to
                                  $HOME/<arg> or My Documents\My Games\<arg> 
                                  for Windows. You can specify also an absolute
                                  path outside the $HOME or My Documents\My 
                                  Games directory. Defaults to 
                                  $HOME/.config/wesnoth on X11 and to the 
                                  userdata-dir on other systems.
`
However, as processed with https://github.com/wesnoth/wesnoth/blob/master/src/wesnoth.cpp#L336 and https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_boost.cpp#L589, it does not call getenv("HOME").

So wesnoth --userdata-dir "wesnoth/userdata_1_12" --userconfig-dir "wesnoth/userdata_1_12" --server "server.wesnoth.org" results in
User configuration directory: wesnoth/userdata_1_12
User data directory: /home/ravana/wesnoth/userdata_1_12

### LINKED ISSUE #9007: Wesnoth (master) does not start
### Game and System Information

- **Version:**
- 6d6bb8d
- **OS:**
Linux

Libraries
=========

Boost:             1.75
Lua:               5.4.6
OpenSSL/libcrypto: 3.0.0h-dev (runtime 3.0.0h-dev)
libcurl:           8.0.1 (runtime 8.0.1)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.50.4 (runtime 1.50.4)
SDL:               2.30.3 (runtime 2.30.3)
SDL_image:         2.8.2 (runtime 2.8.2)
SDL_mixer:         2.8.0 (runtime 2.8.0)

Features
========

Lua console completion:       no
D-Bus notifications back end: yes

Current video settings
======================

SDL video drivers:        [x11] wayland KMSDRM offscreen dummy evdev
Window size:              1819x1110
Game canvas size:         1819x1110
Final render target size: 1819x1110
Screen refresh rate:      60
Screen dpi:               162.56x161.36
Renderer:                 opengl (hw)
Maximum texture size:     32768x32768
VSync:                    on

Current audio settings
======================

SDL audio drivers:  [pulseaudio] alsa pipewire dsp disk dummy
Number of channels: 2
Output rate:        44100 Hz
Sample format:      signed 16 bit little-endian
Sample size:        1024 bytes

Installed add-ons
=================

No add-ons installed.

### Description of the bug

Starting from CLI, wesnoth does not open a window to the main menu, it just hangs until process is canceled.
```
Battle for Wesnoth v1.19.0+dev (6d6bb8dc0c3-Modified) x86_64
Started on Sun Jun 16 17:50:28 2024

Automatically found a possible data directory at: /home/USER/West/dev/wesnoth
20240616 17:50:28 error deprecation: --userdata-dir=<relative path> has been deprecated and will be removed in version 1.17.0.; Use absolute paths. Relative paths are deprecated because they are interpreted relative to $HOME
20240616 17:50:28 error deprecation: --userdata-dir=<relative path> has been deprecated and will be removed in version 1.17.0.; Use absolute paths. Relative paths are deprecated because they are interpreted relative to $HOME
```

1809af8cdf8 works
ae8556a4c6 doesn't

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #2000
Fixes #9007

---

Draft still since I need to get the assert to not trigger on the various other non-boost tests.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
@soliton- FYI if you wanted to review/comment on this.

**Comment by Pentarctagon** [comment]
@doofus-01 Also FYI - this will make the workaround from #9007 how you permanently need to build wesnoth.

File: src/filesystem.cpp [hunk 1]
```diff
@@ -761,21 +756,17 @@ static bfs::path apple_userdata(const std::string& newprefdir)
...
 	// else make it relative to HOME if HOME is populated, otherwise make it relative to the current working directory
 	if(temp[0] == '/') {
 		dir = temp;
+		DBG_FS << "userdata using absolute path";
 	} else {
-		bfs::path home = home_str ? home_str : ".";
-		dir = home / temp;
+		dir = ".";
+		dir / temp;
+		DBG_FS << "unable to determine location to use for userdata, defaulting to current working directory";
```
Comment (soliton-) [inline src/filesystem.cpp:769]: Another confusing message that tells the user little and is a debug message. It needs to be clearly communicated to the user what is happening.

File: src/preferences/preferences.hpp [hunk 2]
```diff
@@ -752,8 +757,9 @@ class prefs
 		prefs(const prefs&& p) = delete;
 		prefs& operator=(const prefs&& p) = delete;
 
+		inline static bool no_preferences_save_ = false;
```
Comment (soliton-) [inline src/preferences/preferences.hpp:760]: Only member variables have a trailing underscore.

File: src/wesnoth.cpp [hunk 3]
```diff
@@ -309,6 +309,10 @@ static int process_command_args(const commandline_options& cmdline_opts)
 		return 0;
 	}
 
+	// earliest possible point to ensure the userdata directory is known
+	// if you're hitting the assertion in the preferences about the userdata not being initialized, it means you're trying to use the preferences before wesnoth knows where the preferences are
+	filesystem::get_user_data_dir();
```
Comment (soliton-) [inline src/wesnoth.cpp:314]: I would rather do the actual check here and assert in `get_user_data_path`.

**Review by soliton- — CHANGES_REQUESTED** [review]

File: src/SConscript [hunk 4]
```diff
@@ -42,9 +42,9 @@ for environ in [test_env, client_env, env]:
             environ.Append(CPPDEFINES = "LOCALEDIR='\"$localedirname\"'")
             if not os.path.isabs(env['localedirname']):
                 environ.Append(CPPDEFINES = "HAS_RELATIVE_LOCALEDIR")
-        if env['version_suffix'] and not env['prefsdir']:
-            environ['prefsdir'] = ".wesnoth$version_suffix"
         if environ['prefsdir']:
+            if env['version_suffix']:
+                environ['prefsdir'] += env['version_suffix']
```
Comment (soliton-) [inline src/SConscript:47]: Instead of changing how this works it should set prefsdir to `~/.wesnoth$version_suffix`.

File: src/wesnoth.cpp (hunk 3 above)
Comment (Pentarctagon) [reply src/wesnoth.cpp:314]: I don't understand what you mean. What check and what assert?

File: src/SConscript (hunk 4 above)
Comment (Pentarctagon) [reply src/SConscript:47]: I assume that wouldn't work on Windows?

File: src/wesnoth.cpp (hunk 3 above)
Comment (soliton-) [reply src/wesnoth.cpp:314]: I assume you call `get_user_data_dir` since that ends up at
https://github.com/wesnoth/wesnoth/blob/e67a91caf22429c56cd2012e324cd8ee212b5481/src/filesystem.cpp#L908-L910
So rather explicitly check here and call `set_user_data_dir` and convert the check in `get_user_data_path` into an assert.

Then we have one single point where the user data dir is set up and `get_user_data_path` asserts if any code requests the userdata dir too early instead of doing a potentially bogus setup.

File: src/SConscript (hunk 4 above)
Comment (soliton-) [reply src/SConscript:47]: If we support windows here then that should also keep doing what it does now. So it looks like replace `~`with the user's documents folder.

Comment (Pentarctagon) [reply src/SConscript:47]: I'd prefer that the person building wesnoth just says where they want the userdata folder to be.

File: src/wesnoth.cpp (hunk 3 above)
Comment (Pentarctagon) [reply src/wesnoth.cpp:314]: This will cause the boost unit tests to fail, since they directly create instances of objects that depend on the preferences without going through normal startup.

File: src/filesystem.cpp (hunk 1 above)
Comment (Pentarctagon) [reply src/filesystem.cpp]: Updated.

File: src/preferences/preferences.hpp (hunk 2 above)
Comment (Pentarctagon) [reply src/preferences/preferences.hpp]: Updated.

File: src/wesnoth.cpp (hunk 3 above)
Comment (soliton-) [reply src/wesnoth.cpp]: Why not fix that? Can you point to the code?

File: src/SConscript (hunk 4 above)
Comment (soliton-) [reply src/SConscript:47]: Well, then why mess with `prefsdir` at all? You can already set `prefsdir` and that is respected currently. This just changes all the logic around. Why is that desirable?

If the goal is to not have `version_suffix` provide a default for `prefsdir` then that is all that should be done. I still find that of dubious value.

The current, documented behavior seems quite reasonable. `suffix that will be added to default values of prefsdir, program_suffix and datadirname`

An easy way to get mostly independent builds for example for the stable and dev version. So you can use them concurrently.

File: src/filesystem.cpp [hunk 5]
```diff
@@ -691,20 +695,12 @@ static bfs::path windows_userdata(const std::string& newprefdir)
...
-			if (temp != PREFERENCES_DIR)
-#endif
-			{
-				// TRANSLATORS: translate the part inside <...> only
-				deprecated_message(_("--userdata-dir=<relative path that doesn't start with a period>"),
-					DEP_LEVEL::FOR_REMOVAL,
-					{1, 17, 0},
-					_("Use an absolute path, or a relative path that starts with a period and a backslash"));
-			}
+			ERR_FS << "relative path for userdata whose first path component doesn't start with '.' or '..' is not allowed: " << temp
```
Comment (soliton-) [inline src/filesystem.cpp:701]:
```suggestion
			ERR_FS << "relative path for userdata whose first path component is neither '.' or '..' is not allowed: " << temp
```

File: src/commandline_options.cpp [hunk 6]
```diff
@@ -205,9 +205,9 @@ commandline_options::commandline_options(const std::vector<std::string>& args)
...
 		("usercache-path", "prints the path of the cache directory and exits.")
-		("userconfig-dir", po::value<std::string>(), "sets the path of the user config directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory. Defaults to the userdata-dir.")
+		("userconfig-dir", po::value<std::string>(), "sets the path of the user config directory. You must specify an absolute path outside the $HOME or My Documents\\My Games directory. Defaults to the userdata-dir.")
 		("userconfig-path", "prints the path of the user config directory and exits.")
-		("userdata-dir", po::value<std::string>(), "sets the path of the userdata directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory.")
+		("userdata-dir", po::value<std::string>(), "sets the path of the userdata directory. You must specify an absolute path outside the $HOME or My Documents\\My Games directory.")
```
Comment (soliton-) [inline src/commandline_options.cpp:210]:
```suggestion
		("userdata-dir", po::value<std::string>(), "sets the path of the userdata directory. You must specify an absolute path.")
```

But this is not correct anyway is it? You can also specify a path starting with `.\` or `..\`.

File: src/commandline_options.cpp [hunk 7]
```diff
@@ -205,9 +205,9 @@ commandline_options::commandline_options(const std::vector<std::string>& args)
 		("unsafe-scripts", "makes the \'package\' package available to Lua scripts, so that they can load arbitrary packages. Do not do this with untrusted scripts! This action gives ua the same permissions as the Wesnoth executable.")
 		("usercache-dir", po::value<std::string>(), "sets the path of the cache directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory. Defaults to $HOME/.cache/wesnoth on X11 and to the userdata-dir on other systems.")
 		("usercache-path", "prints the path of the cache directory and exits.")
-		("userconfig-dir", po::value<std::string>(), "sets the path of the user config directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory. Defaults to the userdata-dir.")
+		("userconfig-dir", po::value<std::string>(), "sets the path of the user config directory. You must specify an absolute path outside the $HOME or My Documents\\My Games directory. Defaults to the userdata-dir.")
```
Comment (soliton-) [inline src/commandline_options.cpp:208]: Where is this requirement coming from?

**Review by soliton- — CHANGES_REQUESTED** [review]

File: src/wesnoth.cpp (hunk 3 above)
Comment (soliton-) [reply src/wesnoth.cpp]: To be clear this is an improvement no matter what. It's not crucial to get such an assert in in this PR.

File: src/commandline_options.cpp (hunk 7 above)
Comment (Pentarctagon) [reply src/commandline_options.cpp:208]: That's... what this PR is removing? The previously deprecated behavior was to default to the home or My Games directory when a relative path was provided.

File: src/SConscript (hunk 4 above)
Comment (Pentarctagon) [reply src/SConscript:47]: Because getting the Windows Documents folder location seems to be non-trivial and I don't want to have to add that to scons.

Comment (soliton-) [reply src/SConscript:47]: Why scons? wesnoth already does it. I just want to keep current functionality.

Comment (Pentarctagon) [reply src/SConscript:47]: I'm confused. These are scons options?

File: src/commandline_options.cpp (hunk 7 above)
Comment (soliton-) [reply src/commandline_options.cpp]: Maybe I'm missing something but nothing changes for the user config dir as far as I can tell.

Comment (Pentarctagon) [reply src/commandline_options.cpp]: I think I'm confused as well. The existing text seems just wrong? Since the user config directory setter has never had the same logic as the userdata directory setup to make it be relative to the home directory.

File: src/wesnoth.cpp (hunk 3 above)
Comment (Pentarctagon) [reply src/wesnoth.cpp]: I think this is something I'd prefer be done separately since getting past the assert then just give another error and I don't want to have to work through whatever changes are needed for the boost tests in order to get the assert working as part of this PR.

File: src/commandline_options.cpp (hunk 7 above)
Comment (soliton-) [reply src/commandline_options.cpp]: That's true nothing special is done so the part about $HOME and My Games etc is just wrong.

File: src/SConscript (hunk 4 above)
Comment (soliton-) [reply src/SConscript:47]: But interpreting a relative path (that does not start with . or ..) as relative to HOME etc is done by wesnoth. As such interpreting ~ instead as meaning HOME etc should be done by wesnoth as well and is already done for macos and linux. Windows might as well do the same and then scons can default to ~/... instead and it works the same as before.

File: src/commandline_options.cpp (hunk 7 above)
Comment (Pentarctagon) [reply src/commandline_options.cpp]: So... I think I changed this text for the wrong reason, but it ended up being the right outcome anyway since the existing text was already wrong.

Comment (soliton-) [reply src/commandline_options.cpp]: `You must specify an absolute path.` is incorrect though.

File: src/SConscript (hunk 4 above)
Comment (Pentarctagon) [reply src/SConscript:47]: So you're saying that on Windows, wesnoth should interpret `~` as pointing to My Games?

File: src/commandline_options.cpp (hunk 7 above)
Comment (Pentarctagon) [reply src/commandline_options.cpp]: Removed that sentence.

File: src/SConscript (hunk 4 above)
Comment (soliton-) [reply src/SConscript:47]: My Games under the user's documents folder, yes. Same behavior as now but explicitly requesting a path in the user's home dir which this basically is on windows.

Comment (Pentarctagon) [reply src/SConscript]: Updated.

File: src/SConscript [hunk 8]
```diff
@@ -42,8 +42,8 @@ for environ in [test_env, client_env, env]:
             environ.Append(CPPDEFINES = "LOCALEDIR='\"$localedirname\"'")
             if not os.path.isabs(env['localedirname']):
                 environ.Append(CPPDEFINES = "HAS_RELATIVE_LOCALEDIR")
-        if env['version_suffix'] and not env['prefsdir']:
-            environ['prefsdir'] = ".wesnoth$version_suffix"
+        if environ['version_suffix'] and not environ['prefsdir']:
```
[the remark this answers is not in the document]
Comment (Pentarctagon) [reply src/SConscript]: Nope, copy/paste error.

File: src/commandline_options.cpp [hunk 9]
```diff
@@ -170,7 +170,7 @@ commandline_options::commandline_options(const std::vector<std::string>& args)
 	general_opts.add_options()
 		("all-translations", "Show all translations, even incomplete ones.")
 		("clock", "Adds the option to show a clock for testing the drawing timer.")
-		("config-dir", po::value<std::string>(), "sets the path of the userdata directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory. DEPRECATED: use userdata-dir instead.")
+		("config-dir", po::value<std::string>(), "sets the path of the userdata directory. You must specify an absolute path. DEPRECATED: use userdata-dir instead.")
```
[the remark this answers is not in the document]
Comment (Pentarctagon) [reply src/commandline_options.cpp]: Updated.

File: src/commandline_options.cpp [hunk 10]
```diff
@@ -205,9 +205,9 @@ commandline_options::commandline_options(const std::vector<std::string>& args)
...
 		("usercache-path", "prints the path of the cache directory and exits.")
-		("userconfig-dir", po::value<std::string>(), "sets the path of the user config directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory. Defaults to the userdata-dir.")
+		("userconfig-dir", po::value<std::string>(), "sets the path of the user config directory. Defaults to the userdata-dir.")
 		("userconfig-path", "prints the path of the user config directory and exits.")
-		("userdata-dir", po::value<std::string>(), "sets the path of the userdata directory to $HOME/<arg> or My Documents\\My Games\\<arg> for Windows. You can specify also an absolute path outside the $HOME or My Documents\\My Games directory.")
+		("userdata-dir", po::value<std::string>(), "sets the path of the userdata directory. You must specify an absolute path.")
```
[the remark this answers is not in the document]
Comment (Pentarctagon) [reply src/commandline_options.cpp]: The one thing I'm still working through via trial an error on the CI is the macOS handling.

File: src/SConscript [hunk 11]
```diff
@@ -43,7 +43,7 @@ for environ in [test_env, client_env, env]:
             if not os.path.isabs(env['localedirname']):
                 environ.Append(CPPDEFINES = "HAS_RELATIVE_LOCALEDIR")
         if env['version_suffix'] and not env['prefsdir']:
-            environ['prefsdir'] = ".wesnoth$version_suffix"
+           environ['prefsdir'] = "~/.wesnoth$version_suffix"
```
Comment (soliton-) [inline src/SConscript:46]:
```suggestion
            environ['prefsdir'] = "~/.wesnoth$version_suffix"
```

**Comment by Pentarctagon** [comment]
Alright, I think this is good to go in.

**Comment by Pentarctagon** [comment]
@doofus-01 so at its current (hopefully final) state, you should be able to continue using just `version_suffix` by itself, the same as you were before.

File: src/filesystem.cpp [hunk 12]
```diff
@@ -689,44 +718,39 @@ static bfs::path windows_userdata(const std::string& newprefdir)
...
 		DBG_FS << "userdata relative to current working directory";
+	} else if(!temp.empty() && temp[0] == '~') {
+		std::optional<std::string> games_path = get_games_path();
+
+		if(games_path) {
+			dir = *games_path;
+		} else {
+			dir = get_cwd();
+		}
+		dir / temp.substr(1);
```
Comment (soliton-) [inline src/filesystem.cpp:729]: Does this somehow assign to `dir`?

File: src/filesystem.cpp [hunk 13]
```diff
@@ -759,23 +783,19 @@ static bfs::path apple_userdata(const std::string& newprefdir)
...
 	}
 
 	// if it's an absolute path, just use that
 	// else make it relative to HOME if HOME is populated, otherwise make it relative to the current working directory
 	if(temp[0] == '/') {
 		dir = temp;
+		DBG_FS << "userdata using absolute path: " << temp;
 	} else {
-		bfs::path home = home_str ? home_str : ".";
+		bfs::path home = home_str ? home_str : get_cwd();
```
Comment (soliton-) [inline src/filesystem.cpp:796]: Macos still falls back to HOME.

**Comment by soliton-** [comment]
It's unclear why this code is still so complicated. It really should be easy.

1) if new dir is empty check PREFERENCES_DIR
2) if still empty use default
3) handle ~

**Comment by soliton-** [comment]
I'll make a PR based on 1.18 when I find the time.

File: src/filesystem.cpp (hunk 13 above)
Comment (Pentarctagon) [reply src/filesystem.cpp:796]: It has to, since that's what it expects to do elsewhere (ie `migrate_apple_config_directory_for_unsandboxed_builds()`).

File: src/filesystem.cpp (hunk 12 above)
Comment (Pentarctagon) [reply src/filesystem.cpp:729]: Fixed in f1b90e91a976ea22990fbd75e85ed52cb8e1857a

**Comment by Pentarctagon** [comment]
Thanks, having someone who uses macOS is definitely preferable.

File: src/filesystem.cpp (hunk 13 above)
Comment (soliton-) [reply src/filesystem.cpp:796]: The migrate function expects the default dir. That should not change.

Comment (Pentarctagon) [reply src/filesystem.cpp:796]: Changed back in 2991c389550dd13dca8263adf9414b7876d4aabe then

Comment (soliton-) [reply src/filesystem.cpp:796]: I guess I didn't express what I wanted to say. As far as I can tell nothing changed so far. Whether the current dir is written as `.` or the absolute path of the current dir makes no difference besides cosmetics.

Perhaps it's not clear what that migrate function does. It doesn't really migrate anything. It makes a symlink from the location of a "normal" wesnoth to the location of a sandboxed wesnoth if that dir exists.
1) If HOME is not set this will not work at all. (Presumably there is a proper way to get the sandbox dir without using HOME but I don't think we need to care much.)
2) If the "normal" wesnoth is run first, it will not work either since it will create dirs as usual and if a sandboxed wesnoth is run later and then again a normal wesnoth it's too late to make a symlink.

It's also not really that important since I imagine it's rare for someone to run sandboxed and unsandboxed wesnoth of the same version interchangeably. Probably just going to happen for a dev.

Comment (Pentarctagon) [reply src/filesystem.cpp:796]: Well, the strange thing is that it seems (?) that despite the symlinks it's still actually setting the userdata dir to the non-sandboxed folder. Which never made sense to me since the sandboxing came later, so shouldn't it be writing to the sandboxed location instead of the non-sandboxed location? Also it's kind of weird that the sandboxing even allows that to work in the first place given the whole point of sandboxing is to prevent an application from accessing external locations/resources.

Comment (soliton-) [reply src/filesystem.cpp:796]: Presumably the sandboxing is implemented by diverting the standard location to the sandboxed one. Otherwise you'd have to rewrite every program.
