### PR TITLE
Bugfix visual (faulty hex offset) [LLM assisted]

### LINKED ISSUE #10903: New visual bug from recent bugfix
### Game and System Information

- **Version:**
1.19.19

- **OS:**
Win 10

### Description of the bug

I'm guessing that my fix: https://github.com/wesnoth/wesnoth/pull/10697 had some unintended issues. I'll investigate and make a PR later. Zoom level here is 1 step zoomed in from default.

Image

### Steps to reproduce the behavior

1.     Load a map.
2.     Scroll to the left edge.
3.     Make sure not to have grid enabled.
4.     Zoom in and out a bit while looking at the first hex column. (x=1)

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mentos987**
A rounding issue for pixel positioning.

This solves https://github.com/wesnoth/wesnoth/issues/10903 .

The last bug was very similar to this but it does not show up in the same circumstances. And I did not look around hard enough for new bugs when confirming that the old fix was good. Sorry.

This time I tested with grid on/off and with several resolutions and with pixel scale on 1 and 2. No new issues seen.

### CODE REVIEW

**Comment by soliton-** [comment]
`std::round` rounds away from zero. I suppose if positive and negative values are in play it's bad for graphics consistency to sometimes round up and sometimes down.

File: src/display.cpp [hunk 1]
```diff
@@ -668,9 +668,9 @@ bool display::fogged(const map_location& loc) const
 point display::get_location(const map_location& loc) const
 {
 	return {
-		// Round hex multiplication to ensure consistent spacing at fractional zoom levels.
-		map_area().x - viewport_origin_.x + static_cast<int>(std::round((loc.x + theme_.border().size) * hex_width())),
-		map_area().y - viewport_origin_.y + static_cast<int>(std::round((loc.y + theme_.border().size) * zoom_ + (is_odd(loc.x) ? zoom_ / 2.0 : 0)))
+		// Floor hex multiplication to ensure consistent spacing at fractional zoom levels.
```
Comment (soliton-) [inline src/display.cpp]: Since this is still rounding I think the previous text is fine but it would help to clarify that to get the mentioned consistency we need to always round in the same direction (down in the case of floor).

Comment (mentos987) [reply src/display.cpp]: Sure.

**Comment by mentos987** [comment]
I'll see if I can get a better grasp of the situation first. I tested myself towards this fix and am unclear on the exact math that causes the issue.

**Comment by mentos987** [comment]
Narrowed the issue down a bit and added comment about the exact bug cause.

**Comment by soliton-** [comment]
Can't say the new code makes it any clearer for me. If you want to narrow it down then check exactly what input causes different/wrong output.

**Comment by mentos987** [comment]
zoom_ is the pixel size of the tile at the current zoom level. (I didn't name it)

When zoom_ was fractional we could get off-by-one-pixel issues in the hex placements. Like:
```

Hex 0: round(0 * 54.75) = 0
Hex 1: round(1 * 54.75) = 55
Hex 2: round(2 * 54.75) = 110
Hex 3: round(3 * 54.75) = 164

spacing: 55, 55, 54
```

We now effectively round 54.75 to 55 causing consistent spacing.

**Comment by mentos987** [comment]
Failing test seems irrelevant.

**Comment by Wedge009** [comment]
If it was the macOS check, it was probably another case of #10805.

**Comment by soliton-** [comment]
It was the unit test run failing because the runner script is not handling timeouts properly. Not really related to this PR anyway.

**Comment by soliton-** [comment]
I'm still confused by this because `zoom_` is an integer.
https://github.com/wesnoth/wesnoth/blob/5f44b98af4854d34e0f4ff48acd07154a48ba35f/src/display.hpp#L729

**Comment by mentos987** [comment]
huh, you are right, I thought it was a double, but it seems "theme_.border().size" was the double that needed rounding then... will investigate more.

**Comment by mentos987** [comment]
zoom_ was not the culprit, but I do not know what was. The rest of the code changes somehow fixed the issue.

I give up on finding the exact cause. The rest of the changes to the code works to solve the bug.

**Comment by Wedge009** [comment]
I recall when I worked on something related to zoom a long time ago that, yes, the variable names are not great, `zoom_` being one example of this. I vaguely recall everything being related to the size of a hex, with '100% zoom' being 72 or something like that.

**Comment by soliton-** [comment]
Without reproduction steps in the issue and no explanation in this PR this looks impossible to verify.

**Comment by mentos987** [comment]
"Without reproduction steps in the issue and no explanation in this PR this looks impossible to verify." --

1. Load a map.
2. Scroll to the left edge.
3. Make sure not to have grid enabled.
4. Zoom in and out a bit while looking at the first hex column. (x=1)
5. If you see no issues then the bug is fixed.

**Comment by soliton-** [comment]
It looks like every variable in that calculation is carefully selected to only result in integers except the border size which is 0.5 and thus causes zoom levels 36, 52 and 100 to result in .5 values for the x coordinate. (So a border size of 0 for example also fixes the issue.)

This seems like a weird choice...

Anyway for the mentioned zoom levels std::round currently converts the 0.5 into a 1 and the proposed change to truncate converts to a 0. This all sounds good but then we're pretty much back to before #10697 which means the grid flickering is back.

**Comment by mentos987** [comment]
"which means the grid flickering is back" -- I tested it and no, the flickering is not back. Something else about the change caused the flickering to go away.

**Comment by soliton-** [comment]
It is back for me. I have no idea how it can not be back for you.

**Comment by mentos987** [comment]
I'll do a rebuild and test

**Comment by mentos987** [comment]
You are right, there is a new flicker issue with the current code. 

It is different from the original flicker in that it only happens on the first column x=1, where as the original flicker could happen at any column as long as it was in the left side of the screen.

I will look at it again with this in mind.

**Comment by mentos987** [comment]
Doing ceil before the int cast seems to work. I have checked for the 3 glitches on several resolutions and on pixel scales set to 1 and 2.

I see no issues. But they can be very hard to spot.

File: src/display.cpp [hunk 2]
```diff
@@ -667,10 +667,11 @@ bool display::fogged(const map_location& loc) const
 
 point display::get_location(const map_location& loc) const
 {
+	// There are 2 bugs that happens quite often if you change this code.
+	// See #10908 (faulty hex offset) and #10676 (Grid overlay flickering)
```
Comment (soliton-) [inline src/display.cpp]:
```suggestion
	// Two possible regressions to be aware of when changing this code:
	// https://github.com/wesnoth/wesnoth/issues/10903 (faulty hex offset) and
	// https://github.com/wesnoth/wesnoth/issues/10676 (Grid overlay flickering)
```

**Review by soliton- — APPROVED** [review]
