### PR TITLE
Editor enhancements

### LINKED ISSUE #9298: BUG: saved Map folders are erased on BfW client relaunching
### Game and System Information

- **Version:** 1.19.3+dev
- **OS:** Windows (Msys2 compiler)

### Description of the bug

I had some folder locations saved/bookmarked in the left sidebar of load/open map UI for easy access.
Now, I find that the locations are reset everything the editor is relaunched.
This. is. Frustrating.

### Steps to reproduce the behavior

1. Open editor
2. bookmark a custom folder in the addons
3. quit client
4. relaunch client and open editor again
5. enter load map UI

### Expected behavior

- I see my saved/bookmarked map folders (see screenshot 2)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by babaissarkar**
1. Item tool: Right click now removes items from the map (https://forums.wesnoth.org/viewtopic.php?t=54905)

Screenshot from 2024-08-30 11-59-01

2. If an addon is selected using Select active Add-on option, the Unit menu now becomes active and the Unit Type Editor can be accessed.

3. New validation check for filenames with whitespaces.
Screenshot from 2024-09-02 08-21-31

4. Using comboboxes for Attack range and types that show icons. (Partial custom type/range support)
Screenshot from 2024-09-02 14-54-03

5. Icons are also shown for race and alignments.
Screenshot from 2024-09-02 14-35-17

6. Fixes a bug that disabled the Save button when a filename was selected from list instead of typed manually.

7. Unit type editor: Add a quit confirmation to cancel button so the user doesn't lose data.

8. File Dialog: Fix a bug that stopped the user bookmarks from getting saved. (Resolves #9298)

### CODE REVIEW

**Comment by soliton-** [comment]
> 3\. Option to surround generated unit type by `#ifdef EDITOR...#endif`

Sounds like "Show **only** in Scenario Editor".

**Comment by Vultraz** [comment]
Why `Shift+` for clear? Other tools use right click for clear.

File: src/gui/dialogs/editor/edit_unit.cpp [hunk 1]
```diff
@@ -701,6 +700,7 @@ void editor_edit_unit::update_attacks() {
 		find_widget<toggle_button>(get_window(), "range_melee", false).set_value(true);
 		find_widget<toggle_button>(get_window(), "range_ranged", false).set_value(false);
 	}
+
 	if (attack["range"] == "ranged") {
 		find_widget<toggle_button>(get_window(), "range_melee", false).set_value(false);
 		find_widget<toggle_button>(get_window(), "range_ranged", false).set_value(true);
```
Comment (Vultraz) [inline src/gui/dialogs/editor/edit_unit.cpp:706]: If the group is a class member now, you can use its API to set the active value.

File: src/gui/dialogs/file_dialog.cpp [hunk 2]
```diff
@@ -196,12 +196,20 @@ void file_dialog::check_filename() {
...
 		if (wrong_ext) {
-			validation_msg.set_label("<span color='red' face='DejaVuSans'>✘</span><span color='red' size='small'>wrong extension, use " + utils::join(extensions_, ", ") + "</span>");
+			i18n_strings["extensions"] = utils::join(extensions_, ", ");
+			validation_msg.set_label(VGETTEXT("$red_x_mark <span color='red' size='small'>wrong extension, use $extensions</span>", i18n_strings));
 			save_btn.set_active(false);
 		} else {
-			validation_msg.set_label("");
-			save_btn.set_active(true);
+			if (filename.find(' ') != std::string::npos) {
+				validation_msg.set_label(VGETTEXT("$red_x_mark <span color='red' size='small'>whitespace is not allowed</span>", i18n_strings));
```
Comment (Vultraz) [inline src/gui/dialogs/file_dialog.cpp:207]: What about just keeping the label static in the CFG and hiding/showing it as needed instead of setting the label here?

File: src/gui/dialogs/file_dialog.cpp [hunk 3]
```diff
@@ -196,12 +196,20 @@ void file_dialog::check_filename() {
...
+		i18n_strings["red_x_mark"] = "<span color='red' face='DejaVuSans'>✘</span>";
 		if (wrong_ext) {
-			validation_msg.set_label("<span color='red' face='DejaVuSans'>✘</span><span color='red' size='small'>wrong extension, use " + utils::join(extensions_, ", ") + "</span>");
+			i18n_strings["extensions"] = utils::join(extensions_, ", ");
+			validation_msg.set_label(VGETTEXT("$red_x_mark <span color='red' size='small'>wrong extension, use $extensions</span>", i18n_strings));
 			save_btn.set_active(false);
 		} else {
-			validation_msg.set_label("");
-			save_btn.set_active(true);
+			if (filename.find(' ') != std::string::npos) {
```
Comment (Vultraz) [inline src/gui/dialogs/file_dialog.cpp:206]: Do an `else if` block.

Comment (babaissarkar) [reply src/gui/dialogs/file_dialog.cpp]: updated.

File: src/gui/dialogs/editor/edit_unit.cpp [hunk 4]
```diff
@@ -99,9 +99,13 @@ void editor_edit_unit::pre_show(window& win) {
...
 	menu_button& races = find_widget<menu_button>(&win, "race_list", false);
-	for(const race_map::value_type &i : unit_types.races()) {
+	for(const race_map::value_type& i : unit_types.races()) {
 		const std::string& race_name = i.second.id();
-		race_list_.emplace_back("label", race_name, "icon", "icons/unit-groups/race_" + race_name + "_30.png");
+		std::string race_icon = "icons/unit-groups/race_" + race_name + "_30.png";
+		if (!filesystem::file_exists(game_config::path + "/images/" + race_icon)) {
+			race_icon = "icons/unit-groups/race_custom_30.png";
+		}
+		race_list_.emplace_back("label", race_name, "icon", race_icon);
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/gui/dialogs/editor/edit_unit.cpp]: updated.

File: src/editor/controller/editor_controller.cpp [hunk 5]
```diff
@@ -877,6 +877,10 @@ bool editor_controller::do_execute_command(const hotkey::ui_command& cmd, bool p
 		{
 			initialize_addon_if_empty();
 
+			if (current_addon_id_.empty()) {
```
Comment (soliton-) [inline src/editor/controller/editor_controller.cpp:880]: Probably rather for a follow-up refactoring but it seems like the logic for "init was done or not" better belongs inside `initialize_addon_if_empty`. It should return bool IMO.

Comment (babaissarkar) [reply src/editor/controller/editor_controller.cpp]: @soliton- Implemented, please see if https://github.com/wesnoth/wesnoth/pull/9273/commits/c858bd1c7fbe8546c8a6809d528f39488c6c9cd2 is fine?

File: src/gui/dialogs/file_dialog.cpp [hunk 6]
```diff
@@ -196,8 +196,14 @@ void file_dialog::check_filename() {
...
 
+		utils::string_map i18n_strings;
+		i18n_strings["red_x_mark"] = "<span color='red' face='DejaVuSans'>✘</span>";
 		if (wrong_ext) {
-			validation_msg.set_label("<span color='red' face='DejaVuSans'>✘</span><span color='red' size='small'>wrong extension, use " + utils::join(extensions_, ", ") + "</span>");
+			i18n_strings["extensions"] = utils::join(extensions_, ", ");
+			validation_msg.set_label(VGETTEXT("$red_x_mark <span color='red' size='small'>wrong extension, use $extensions</span>", i18n_strings));
+			save_btn.set_active(false);
+		} else if (filename.find(' ') != std::string::npos) {
+			validation_msg.set_label(VGETTEXT("$red_x_mark <span color='red' size='small'>whitespace is not allowed</span>", i18n_strings));
```
Comment (soliton-) [inline src/gui/dialogs/file_dialog.cpp:206]: This only checks for space but whitespace sounds like it also checks for tab etc.

Is it clear to the user that this is about the file name containing a space?

Do we disallow spaces in any file name? Savegames definitely do contain spaces for example. Not sure if this dialog is used for savegames though.

Comment (babaissarkar) [reply src/gui/dialogs/file_dialog.cpp]: updated check and message, see https://github.com/wesnoth/wesnoth/pull/9273/commits/0b4de723d64b3f923a1d8a420ca451623552a7b7.
The file dialog doesn't seem to be used outside of the editor.

Comment (soliton-) [reply src/gui/dialogs/file_dialog.cpp]: Alright, good enough for me.

**Review by Vultraz — APPROVED** [review]

File: src/gui/dialogs/file_dialog.cpp (hunk 6 above)
Comment (CelticMinstrel) [reply src/gui/dialogs/file_dialog.cpp]: > The file dialog doesn't seem to be used outside of the editor.

It's definitely used outside of the editor. I'm not aware of any other place where it's used for _saving_, but at minimum it's used to select a wesnothd executable if the game can't find one in normal locations. If there are any other uses outside the editor, they're about as niche as that one.

**Comment by CelticMinstrel** [comment]
I think this looks good to merge, as long as the file dialog a) doesn't block _loading_ files with spaces in the name and b) doesn't block saving just because there's a space somewhere in the path (for example, "Programs (x86)").

**Comment by babaissarkar** [comment]
> I think this looks good to merge, as long as the file dialog a) doesn't block _loading_ files with spaces in the name and b) doesn't block saving just because there's a space somewhere in the path (for example, "Programs (x86)").

Satisfies both conditions.
