### PR TITLE
[1.16] Backport #8137: Fix horizontal scrolling regression (fixes #7404)

### LINKED ISSUE #7404: With touchpad horizontal scrolling is inverted
When I use the touchpad, scrolling upwards scrolls upward, downward scrolls downwards. But scrolling right scrolls to left.

1.16 and c9eae7c affected.
When using the OS' settings to activate `natural scrolling`, all four directions are inverted, so the bug remains.

Using Linux with KDE on top of X11 with libinput.
Other programs are not affected by this problem.
Scrolling by moving the mouse pointer via the touchpad to a side or corner of the screen works correct as well.

### PR DESCRIPTION
**Pull request by pehjota**
The old issue #2218 was actually a bug in SDL, fixed on X11 in version 2.0.18 and on Wayland in version 2.0.20.  The hardcoded workaround in pull #2481 (commit 4bc4373) caused a regression in fixed SDL versions.

This fix is similar to the workaround in widelands/widelands#5394 committed as widelands/widelands@67db32a.

Also make mouse handler use same coordinate signs as map and fix mouse_wheel_*() virtual method calls, which have been wrong in the X axis since commit dfe2f33 (and unused since commit c912f7e).

Tested with SDL 2.0.14 and 2.28.5.

Cherry picked from commit ab4001d (pull #8137) in the master branch (1.17).

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Thanks! I'll leave this open for a few days in case there are any comments, otherwise I'll go ahead and merge it.

**Comment by pehjota** [comment]
Sounds good, thanks.  I referenced this in the issue and original PR in the hopes of soliciting any such comments.

**Comment by pehjota** [comment]
It occurred to me that I should add a changelog entry, so I added one to the commit here (no other changes) and opened a new PR to add one for the original PR in master.

File: src/controller_base.cpp [hunk 1]
```diff
@@ -230,11 +230,33 @@ void controller_base::handle_event(const SDL_Event& event)
...
+		//     https://github.com/libsdl-org/SDL/pull/4700
+		//     https://github.com/libsdl-org/SDL/commit/515b7e9
+		// and on Wayland in SDL < 2.0.20:
+		//     https://github.com/libsdl-org/SDL/commit/3e1b3bc
+		// Fixes issue #7404, which is a regression caused by pull #2481
+		// that fixed issue #2218.
+		{
+			int xmul = 1;
+#if !defined(_WIN32) && !defined(__APPLE__)
+			const char* video_driver = SDL_GetCurrentVideoDriver();
```
Comment (vgaming) [inline src/controller_base.cpp:247]: This this cheap enough to execute on any SDL_MOUSEWHEEL event? Probably "yes", but worth checking. You've probably ran it locally and didn't observe any noticeable slowdown, @pehjota ?

Comment (vgaming) [reply src/controller_base.cpp:247]: UPD: yes, it's cheap enough. I've tested on 1.17 now and I'm not able to notice any slow-down. Thanks!

Comment (pehjota) [reply src/controller_base.cpp:247]: Right, as mentioned in the commit message, I ran this locally with SDL 2.0.14 and 2.28.5.  No noticeable slowdown even on my 2.40-GHz Intel Core 2 Duo (GMA 4500MHD) laptop.

It's only two to four cheap function calls and a handful of assignments and comparisons on each SDL_MouseWheelEvent.  But it can be improved slightly by caching the version/driver checks result in a static variable.  Done, in PRs #8185 and #8186.

Thanks again!
