### PR TITLE
disable dismiss in recall dialog for viewing side in planning mode

### LINKED ISSUE #10792: Players can dismiss units off-turn in planning mode resulting in crash
reported in the forum in https://forums.wesnoth.org/viewtopic.php?t=60343

Since the recall unit dialog was refactored in 1.19 this probably needs different fixes in 1.19 and 1.18

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #10792

### CODE REVIEW

**Comment by babaissarkar** [comment]
This needs testing, or alternatively I need a way to reliable reproduce the issue.

**Comment by Wedge009** [comment]
@gfgtdf You seemed to know more about #10792 than I did.

File: src/menu_events.cpp [hunk 1]
```diff
@@ -419,6 +419,8 @@ void menu_handler::recall(int side_num, const map_location& last_hex)
 
 	const auto& dlg = units_dialog::build_recall_dialog(recall_list_team, current_team);
 
+	dlg->set_show_dismiss(!(board().is_observer() && pc_.get_whiteboard()));
```
Comment (soliton-) [inline src/menu_events.cpp]: So disable dismissing if you're an observer or the whiteboard manager exists? Does an observer even get here? This logic does not align with the PR title.

This should make sure that you can only dismiss as the currently playing side. Planning mode is not really relevant besides that you probably can't even get here without planning mode.

**Comment by gfgtdf** [comment]
For testing ithink you could wither do what the orignal testing forum thread suggested: disable as combat animations & skip ai turn in prefernces and try to open the recall dialog during the ais turn. Just opening the recall dialog 
during another players turn in mp shoudl also work.



from looking at the code i don't see how it does anything thought, it only seems to effect _observers_? The original issue is not about observers

I also don't think `pc_.get_whiteboard()` can be used to check whether whitebaord is active, it shodul just returna  manager object that always exists regardless whether its active or not.

File: src/menu_events.cpp (hunk 1 above)
Comment (babaissarkar) [reply src/menu_events.cpp]: Fixed.

**Comment by babaissarkar** [comment]
Found a way to test:
Changed temporarily https://github.com/wesnoth/wesnoth/blob/edc06d287af1d242a17ad232241dde34cd7bd7aa/src/hotkey/hotkey_handler_sp.cpp#L233-L234 to `true`, then tried dismissing. Crashed. With this PR, the button is invisible, so crash is avoided.

**Comment by Wedge009** [comment]
Was the dialogue consolidation applied to 1.18, though? Or is the crash independent of that?

**Comment by soliton-** [comment]
The GUI is not relevant the issue comes from dismissing.
