### PR TITLE
Rich Label: utf8 chopoff fix

### LINKED ISSUE #10288: New help Failed to convert a string from utf8 to UCS4
### Game and System Information

- **Version:** 1.19.13
- **OS:** windows

### Description of the bug

When opening EoC Hell Guardian in help, log has errors and help page is missing data.

Image

```
20250622 18:32:37 error gui/layout: pango_text::set_text text '€‹ï¿¼
Advances from:Â Doom Guard
Race:Â Humans
Traits (2):Â strong, quick, intelligent, resilient
Abilities:Â steadfast

HP:Â 68  Moves:Â 4  Cost:Â 63  Alignment:Â chaotic  RequiredÂ XP:Â 105
This unit is from the Era of Chaos. Its coding and art were done by the various people who created the Era of Chaos.

Only the toughest of armorers are worthy of the most effective armors and weapons, forged by the best demonic blacksmiths, and blessed by unlawful magic. It is said that they could stand against an avalanche with ease, if they were commanded to do so.
Special Notes
â€¢ The steadiness of this unit reduces damage from some attacks, but only while defending.
â€¢ This unit is able to slow its enemies, halving their movement speed and attack damage until they end a turn.

Attacks' contains invalid utf-8, trimmed the invalid parts.
```

### Steps to reproduce the behavior

Install 1.18 ageless and run 1.19.13 with ./wesnoth.exe --userdata-dir "~/Wesnoth1.18"
Open help
Navigate to second Hell Guardian

First Hell Guardian is EE version which does not have same error.

Unit type as preprocessed with 1.19 in 2024 december
```
	[unit_type]
		advances_to="null"
		alignment="chaotic"
		cost=63
#textdomain wesnoth-Ageless_Era
		description=_"This unit is from the Era of Chaos. Its coding and art were done by the various people who created the Era of Chaos.

" +
			"Only the toughest of armorers are worthy of the most effective armors and weapons, forged by the best demonic blacksmiths, and blessed by unlawful magic. It is said that they could stand against an avalanche with ease, if they were commanded to do so."
		die_sound="human-die-[1~3].ogg"
		experience=150
		hitpoints=68
		id="AE_chs_chaos_empire_Hell_Guardian"
		image="units/human-chaos/hell-guardian.png"
		level=3
		movement=4
		movement_type="AE_chs_armorerfoot"
		name=_"Hell Guardian"
		profile="portraits/chaos/hell-guardian.png~RC(magenta>black)"
		race="human"
		usage="fighter"
		[abilities]
			[resistance]
				active_on="defense"
				affect_self=yes
#textdomain wesnoth-help
				description=_"This unit’s resistances are doubled, up to a maximum of 50%, when defending. Vulnerabilities are not affected."
				female_name=_"female^steadfast"
				id="steadfast"
				max_value=50
				multiply=2
				name=_"steadfast"
				special_note=_"The steadiness of this unit reduces damage from some attacks, but only while defending."
				[filter_base_value]
					greater_than=0
					less_than=50
				[/filter_base_value]
			[/resistance]
		[/abilities]
		[advancement]
			description=_"Max HP bonus +3, Max XP +20%"
			id="amla_default"
			image="icons/amla-default.png"
			max_times=100
			strict_amla=yes
			[effect]
				apply_to="hitpoints"
				heal_full=yes
				increase_total=3
			[/effect]
			[effect]
				apply_to="max_experience"
				increase="20%"
			[/effect]
			[effect]
				apply_to="status"
				remove="poisoned"
			[/effect]
			[effect]
				apply_to="status"
				remove="slowed"
			[/effect]
		[/advancement]
		[defend]
			start_time=-126
			[frame]
				image="units/human-chaos/hell-guardian.png:1,units/human-chaos/hell-guardian.png:250,units/human-chaos/hell-guardian.png:1"
			[/frame]
			[if]
				hit_sound_start_time=-25
				hits="hit"
				[hit_sound_frame]
					sound="human-hit-[1~5].ogg"
				[/hit_sound_frame]
			[/if]
		[/defend]
		[resistance]
			arcane=85
			impact=85
		[/resistance]
		[attack]
			damage=9
#textdomain wesnoth-units
			description=_"sword"
			icon="attacks/sword-orcish.png"
			name="sword"
			number=4
			range="melee"
			type="blade"
		[/attack]
		[attack]
			damage=20
			defense_weight=2.1
			description=_"shield bash"
			icon="attacks/rectangular-shield.png"
			name="shield"
			number=1
			range="melee"
			type="impact"
			[specials]
				[slow]
#textdomain wesnoth-help
					description=_"This attack slows the target until it ends a turn. Slow halves the damage caused by attacks and the movement cost for a slowed unit is doubled. A unit that is slowed will feature a snail icon in its sidebar information when it is selected."
					id="slow"
					name=_"slows"
					special_note=_"This unit is able to slow its enemies, halving their movement speed and attack damage until they end a turn."
				[/slow]
			[/specials]
		[/attack]
		[attack_anim]
			attack_sound_start_time=-100
			start_time=-175
			[filter_attack]
				name="sword"
			[/filter_attack]
			[frame]
				image="units/human-chaos/hell-guardian.png:350"
			[/frame]
			[if]
				hits=yes
				[attack_sound_frame]
					sound="sword-1.ogg"
				[/attack_sound_frame]
			[/if]
			[else]
				hits=no
				[attack_sound_frame]
					sound="miss-[1~3].ogg"
				[/attack_sound_frame]
			[/else]
		[/attack_anim]
		[attack_anim]
			attack_sound_start_time=-75
			start_time=-175
			[filter_attack]
				name="shield"
			[/filter_attack]
			[frame]
				image="units/human-chaos/hell-guardian.png:350"
			[/frame]
			[if]
				hits=yes
				[attack_sound_frame]
					sound="mace.wav"
				[/attack_sound_frame]
			[/if]
			[else]
				hits=no
				[attack_sound_frame]
					sound="miss-[1~3].ogg"
				[/attack_sound_frame]
			[/else]
		[/attack_anim]
	[/unit_type]
```

### Expected behavior

Help opens without errors and missing content, as is with 1.18.4.

### Additional context

May be related to #8929

### PR DESCRIPTION
**Pull request by babaissarkar**
Fixes #10288

Credits to @soliton- for finding out the reason, see https://github.com/wesnoth/wesnoth/issues/10288#issuecomment-3824741641.

### CODE REVIEW

File: src/gui/widgets/rich_label.cpp [hunk 1]
```diff
@@ -656,14 +656,18 @@ std::pair<config, point> rich_label::get_parsed_text(
 					DBG_GUI_RL << "wrap start";
 
 					std::size_t len = get_split_location((*curr_item)["text"].str(), point(init_width - float_size.x, float_size.y * video::get_pixel_scale()));
+
 					DBG_GUI_RL << "wrap around area: " << float_size;
 
-					std::string removed_part = (*curr_item)["text"].str().substr(len+1);
+					std::string removed_part = len > 0 ? (*curr_item)["text"].str().substr(len+1) : "";
```
Comment (soliton-) [inline src/gui/widgets/rich_label.cpp]: Might as well move this to the if down below? Should only get used there.

File: src/gui/widgets/rich_label.cpp [hunk 2]
```diff
@@ -656,14 +656,18 @@ std::pair<config, point> rich_label::get_parsed_text(
...
 
 					// first part of the text
 					// get_split_location always splits at word bounds.
 					// substr(len) will include a space, so we skip that.
```
Comment (soliton-) [inline src/gui/widgets/rich_label.cpp]: This comment should be moved to the code it comments.

Comment (babaissarkar) [reply src/gui/widgets/rich_label.cpp]: Moved.

File: src/gui/widgets/rich_label.cpp (hunk 1 above)
Comment (babaissarkar) [reply src/gui/widgets/rich_label.cpp]: Updated. Is the current version fine?

File: src/gui/widgets/rich_label.cpp [hunk 3]
```diff
@@ -655,15 +655,19 @@ std::pair<config, point> rich_label::get_parsed_text(
...
+
+					std::size_t len = get_split_location(full_text, point(init_width - float_size.x, float_size.y * video::get_pixel_scale()));
+
 					DBG_GUI_RL << "wrap around area: " << float_size;
 
-					std::string removed_part = (*curr_item)["text"].str().substr(len+1);
+					if(len > 0) {
+						// first part of the text
+						// get_split_location always splits at word bounds.
+						// substr(len) will include a space, so we skip that.
```
Comment (soliton-) [inline src/gui/widgets/rich_label.cpp]: substr(len+1) is done in the next if as far as I can tell.

File: src/gui/widgets/rich_label.cpp (hunk 1 above)
Comment (soliton-) [reply src/gui/widgets/rich_label.cpp]: Looks fine apart of the comment still being at a confusing place. Also looks like the android icon stuff got mixed in.

Comment (babaissarkar) [reply src/gui/widgets/rich_label.cpp]: removed the android icon commit and move the last two lines of the comment below.

File: src/gui/widgets/rich_label.cpp (hunk 3 above)
Comment (babaissarkar) [reply src/gui/widgets/rich_label.cpp]: moved last two lines of the comment.
