### PR TITLE
[World Conquest] Last 2 deprecation code usage fixes.

### LINKED ISSUE #5650: WC: Error flood after being made playable after recent commits. (Feedback report)
### Game and System Information
 - What version of the game are you running?
 - Battle for Wesnoth v1.15.11+dev (1af920669c6-Modified) x86_64

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
Msys2   v1.15.11+dev (1af920669c6-Modified) x86_64
 - What OS are you running?
 Windows 10

### Describe the bug
After recent commits, World Conquest was made playable again, so I gave it a test run. I got a lot of deprecated Lua and WML messages most of the time and sometimes a few bugs popped up.
Additionally, when progressing from the first scenario, you are shown the faction/side/team selection interface (the one where you pick factions, color, team, gold and income, etc). This allows you to edit the gold and income, as well as the team of the enemy AI sides...and is...a mega cheat itself. I got through most scenarios just by setting the enemy gold and income to 0 and -2 respectively, and also putting them against each other for a FFA.

### Expected behavior
No "Invalid WML found" or "Lua Error" should be appearing

### Screenshots
Screenshot 2021-03-31 203619
Screenshot 2021-03-31 223055

### Additional context
```lua
20210331 21:50:38 info deprecation: wesnoth.extract_unit has been deprecated indefinitely.
   (Note: You should use wesnoth.units.extract instead in new code)
Invalid WML found:    (Note: You should use wesnoth.units.extract instead in new code)
Invalid WML found: wesnoth.extract_unit has been deprecated indefinitely.
libpng warning: iCCP: known incorrect sRGB profile
20210331 22:03:30 info deprecation: map:get_tiles_radius has been deprecated indefinitely.
  The filter is now the last parameter, instead of the radius (Note: You should use map:find_in_radius instead in new code)
20210331 22:03:30 info deprecation: map:get_locations has been deprecated indefinitely.
   (Note: You should use map:find instead in new code)
20210331 22:03:30 info deprecation: wml.parsed has been deprecated indefinitely.
  Since vconfigs are not supported outside of the game kernel, this function is redundant and will be removed from plugin and map generation contexts. It will continue to work in the game kernel. (Note: You should use (no replacement) instead in new code)
20210331 22:08:18 info deprecation: wesnoth.add_modification has been deprecated indefinitely.
   (Note: You should use wesnoth.units.add_modification instead in new code)
Invalid WML found:    (Note: You should use map:find instead in new code)
Invalid WML found:    (Note: You should use wesnoth.units.add_modification instead in new code)
Invalid WML found:   Since vconfigs are not supported outside of the game kernel, this function is redundant and will be removed from plugin and map generation contexts. It will continue to work in the game kernel. (Note: You should use (no replacement) instead in new code)
Invalid WML found:   The filter is now the last parameter, instead of the radius (Note: You should use map:find_in_radius instead in new code)
Invalid WML found: map:get_locations has been deprecated indefinitely.
Invalid WML found: map:get_tiles_radius has been deprecated indefinitely.
Invalid WML found: wesnoth.add_modification has been deprecated indefinitely.
Invalid WML found: wml.parsed has been deprecated indefinitely.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
20210331 22:10:33 info deprecation: helper.child_range has been deprecated indefinitely.
   (Note: You should use wml.child_range instead in new code)
Invalid WML found:    (Note: You should use wml.child_range instead in new code)
Invalid WML found: helper.child_range has been deprecated indefinitely.
campaigns/World_Conquest/lua/map/main.lua:43: bad argument #-1 to 'dofile' (file not found)	stack traceback:
	[string ""]:7: in function <[string ""]:7>
	[C]: in field 'dofile'
	campaigns/World_Conquest/lua/map/main.lua:43: in function '.wc_ii_generate_scenario'
	(...tail calls...)
	[C]: in function '.xpcall'
	[string ""]:7: in main chunk
nil
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
20210331 22:30:37 error general: Map generator error: Error when running lua_map_generator create_scenario.
The generator was: World Conquest 1p
bad return value:
  expected a config (table), found a nil
```

### PR DESCRIPTION
**Pull request by knyghtmare**
The Summary of this PR:
1. Fixed an un-added entry in the changelog
2. fixed the last 2 deprecation messages
3. removed instances of `wml.parsed` as it is no longer required.

Fixes #5650

Note: In regards to the last remaining error report, I want to open a fresh issue for it. So the existing one can be closed.

How do I request a review from CelticMinstrel and Soliton?

### CODE REVIEW

File: data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua [hunk 1]
```diff
@@ -76,7 +76,7 @@ function set_terrain_impl(data)
 end
 
 function set_terrain_simul(cfg)
-	cfg = wml.parsed(cfg)
+	cfg = cfg
```
Comment (soliton-) [inline data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua:79]: Surely the line can be removed now.

Comment (knyghtmare) [reply data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua:79]: This can indeed be removed. I shall wait for any more requested changes and then make them all in one single commit.

File: data/campaigns/World_Conquest/lua/game_mechanics/effects.lua [hunk 2]
```diff
@@ -66,12 +66,12 @@ end
 -- Like apply_to=resistance with replace=true, but never decreases resistances.
 function wesnoth.effects.wc2_min_resistance(u, cfg)
 	local resistance_new = {}
-	local resistance_old = wml.parsed(wml.get_child(cfg, "resistance"))
+	local resistance_old = wml.get_child(cfg, "resistance")
```
Comment (CelticMinstrel) [inline data/campaigns/World_Conquest/lua/game_mechanics/effects.lua:69]: I think the `wml.parsed` should be left in here, as this is an `[effect]`.

File: data/campaigns/World_Conquest/lua/game_mechanics/effects.lua [hunk 3]
```diff
@@ -91,7 +91,7 @@ end
 -- Like apply_to=defense with replace=true, but never decreases defense.
 function wesnoth.effects.wc2_min_defense(u, cfg)
 	local defense_new = {}
-	local defense_old = wml.parsed(wml.get_child(cfg, "defense"))
+	local defense_old = wml.get_child(cfg, "defense")
```
Comment (CelticMinstrel) [inline data/campaigns/World_Conquest/lua/game_mechanics/effects.lua:94]: Here too I think the `wml.parsed` should be left in, for the same reason.

File: data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua (hunk 1 above)
Comment (CelticMinstrel) [reply data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua:79]: It looks like this line was incorrect to begin with - the `cfg` isn't even a config at all. So, simply removing it should be the correct answer.

Even if it stilll worked _with_ this line, it was just a fluke; this isn't a supported use of `wml.parsed`. Maybe we should add a warning in case it's misused like this elsewhere.

File: data/campaigns/World_Conquest/lua/game_mechanics/effects.lua [hunk 4]
```diff
@@ -66,12 +66,12 @@ end
...
 function wesnoth.effects.wc2_min_resistance(u, cfg)
 	local resistance_new = {}
-	local resistance_old = wml.parsed(wml.get_child(cfg, "resistance"))
+	local resistance_old = wml.get_child(cfg, "resistance")
 	local unit_resistance_cfg = nil
 	for k,v in pairs(resistance_old) do
 		if type(k) == "string" and type(v) == "number" then
 			if not unit_resistance_cfg then
-				unit_resistance_cfg = wml.parsed(wml.get_child(u.__cfg, "resistance"))
+				unit_resistance_cfg = wml.get_child(u.__cfg, "resistance")
```
Comment (CelticMinstrel) [inline data/campaigns/World_Conquest/lua/game_mechanics/effects.lua:74]: Oh, this one too should be left as it is.

**Review by CelticMinstrel — CHANGES_REQUESTED** [review]
In summary: The radius changes are fine, but the parsed changes are mostly incorrect.

**Comment by knyghtmare** [comment]
@CelticMinstrel 
I re-added those 3 instances of `wml.parsed()` back but, it triggered an error:
```
20210424 17:18:53 error scripting/lua: campaigns/World_Conquest/lua/campaign/enemy_themed.lua:74: bad argument #1 to 'unit' (WML table expected, got table)
stack traceback:
	[C]: in field 'unit'
	campaigns/World_Conquest/lua/campaign/enemy_themed.lua:74: in upvalue 'wct_map_enemy_themed'
	campaigns/World_Conquest/lua/campaign/enemy_themed.lua:97: in local 'cmd'
	lua/wml-utils.lua:144: in field 'handle_event_commands'
	lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
```

File: data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua (hunk 1 above)
Comment (knyghtmare) [reply data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua]: This change has been done in the second commit.

File: data/campaigns/World_Conquest/lua/game_mechanics/effects.lua (hunk 3 above)
Comment (knyghtmare) [reply data/campaigns/World_Conquest/lua/game_mechanics/effects.lua]: I have restored the `wml.parsed` here, in the second commit.

File: data/campaigns/World_Conquest/lua/game_mechanics/effects.lua (hunk 2 above)
Comment (knyghtmare) [reply data/campaigns/World_Conquest/lua/game_mechanics/effects.lua]: I have restored this instance of `wml.parsed` as well.

File: data/campaigns/World_Conquest/lua/game_mechanics/effects.lua (hunk 4 above)
Comment (knyghtmare) [reply data/campaigns/World_Conquest/lua/game_mechanics/effects.lua:74]: Since this is the one that is causing an error, when `wml.parsed()` is restored, I did not re-add it. Now, WC map generation works fine without errors.

Comment (CelticMinstrel) [reply data/campaigns/World_Conquest/lua/game_mechanics/effects.lua:74]: Hmm, come to think of it, this is reading from `u.__cfg` so it's pointless to use `wml.parsed` anyway.

**Review by CelticMinstrel — APPROVED** [review]

**Comment by Pentarctagon** [comment]
Can this be merged then?

**Comment by knyghtmare** [comment]
> Can this be merged then?

Yes. I shall open another issue for the last remaining bugs. There should be one or two left.
