### PR TITLE
Redirect using C output instead of C++ output

### LINKED ISSUE #8108: C output streams not redirected to logfile
as said in the title it seems like std_print is not redirected to the logfile, when i run wesnoth without a console attached those outputs are missing in the logfile. If i remember  correctly this behaviour was different on windows, but not fulyl sure.

When a run wesnoth with a console it shows normally. 

- **Version:* 1.17.23+dev
- **Downloaded from:* self biult
- **Build info:**
- **OS:* ubuntu linux.

### LINKED ISSUE #8255: Assertion when logging large essages on windows
Version: 1.17.23
OS: windows

It was observed here https://forums.wesnoth.org/viewtopic.php?p=685869#p685869 that an assertion inside  boost/iostreams/tee.hpp can fail under specific circumstances 
image

Since the only code that uses iostreams/tee.hpp is the logging code and since  i got a very long error message when trying it, i i'm pretty sure that that is is cause. 

It would be nice if someone using windows could try to reproduce (just dump a big wml object into the logger)

### PR DESCRIPTION
**Pull request by Pentarctagon**
Apparently redirecting stdout/stderr also results in std::cout/std::cerr being redirected, but not the reverse. This is not compatible with using boost's tee.

Fixes #8108
Fixes #8255

---

The uncommented code in log.cpp results in the following being logged to file:
```
0
1
2
3
4
wesnoth: src/wesnoth.cpp:1131: int main(int, char**): Assertion `false && "5"' failed.
```

The commented code in log.cpp results in the following being logged to file (stdout/std::cout is missing):
```
0
1
3
wesnoth: src/wesnoth.cpp:1131: int main(int, char**): Assertion `false && "5"' failed.
```
The commented code is based on the 1.16 code from log_windows, so I'm not sure why stdout doesn't get redirected correctly (it's neither in the log file nor present on the terminal - I've no idea where it's getting sent to):
https://github.com/wesnoth/wesnoth/blob/165d2ba37f2c95257a33ab916ca254594890278d/src/log_windows.cpp#L382

---

@Wedge009 would you be able to test if this works the same on Windows 10 1903 or later where the path to the log file contains non-ascii characters?

### CODE REVIEW

File: src/log.cpp [hunk 1]
```diff
@@ -187,13 +190,48 @@ void set_log_to_file()
...
-		//static std::ostream cout_stream{std::cout.rdbuf()};
-		auto cerr_tee { boost::iostreams::tee(*logfile, cerr_stream) };
-		output_file_.reset(new boost::iostreams::stream<decltype(cerr_tee)>{cerr_tee, 4096, 0});
-		std::cerr.rdbuf(output_file_.get()->rdbuf());
-		std::cout.rdbuf(output_file_.get()->rdbuf());
+
+		// redirect to a file
+		// IMPORTANT: apparently redirecting stderr/stdout will also redirect std::cerr/std::cout, but the reverse is not true
+		//            redirecting std::cerr/std::cout will *not* redirect stderr/stdout
+		if(setvbuf(stdout, NULL, _IONBF, 2) == -1) {
```
Comment (CelticMinstrel) [inline src/log.cpp:197]: Why do you want to set stdout to be unbuffered?

File: src/log.cpp [hunk 2]
```diff
@@ -187,13 +190,48 @@ void set_log_to_file()
...
+				std::cerr << "Failed to redirect stdout";
+			}
+			if(dup2(fd, STDERR_FILENO) == -1) {
+				std::cerr << "Failed to redirect stderr";
+			}
+		} else {
+			std::cerr << "Failed to create log file: " << output_file_path_;
+		}
+
+		// std::fflush(stderr);
```
Comment (CelticMinstrel) [inline src/log.cpp:223]: Comments should be deleted.

Comment (Pentarctagon) [reply src/log.cpp:223]: That's the plan - it's there for information. Also I forgot to set this as a draft.

File: src/log.cpp [hunk 3]
```diff
@@ -187,13 +190,48 @@ void set_log_to_file()
...
-		static std::ostream cerr_stream{std::cerr.rdbuf()};
-		//static std::ostream cout_stream{std::cout.rdbuf()};
-		auto cerr_tee { boost::iostreams::tee(*logfile, cerr_stream) };
-		output_file_.reset(new boost::iostreams::stream<decltype(cerr_tee)>{cerr_tee, 4096, 0});
-		std::cerr.rdbuf(output_file_.get()->rdbuf());
-		std::cout.rdbuf(output_file_.get()->rdbuf());
+
+		// redirect to a file
+		// IMPORTANT: apparently redirecting stderr/stdout will also redirect std::cerr/std::cout, but the reverse is not true
+		//            redirecting std::cerr/std::cout will *not* redirect stderr/stdout
```
Comment (CelticMinstrel) [inline src/log.cpp:196]: I guess this is technically true, but… the way it's stated is maybe a tad misleading.

Redirecting std::cerr/std::cout is in the iostream, replacing their stream buffer with something else. Redirecting stderr/stdout is done at a lower level, essentially making both streams be the same stream.

I'm not sure what's a better way to put this…

File: src/log.cpp (hunk 1 above)
Comment (Pentarctagon) [reply src/log.cpp:197]: Otherwise the stdout/std::cout output doesn't make it to the log file, at least for the example in wesnoth.cpp where it almost immediately terminates with an assert.

Comment (CelticMinstrel) [reply src/log.cpp:197]: Hmm… std::cout and/or the C FILE API might have a software buffer on top of that, so maybe it's fine…

**Comment by Wedge009** [comment]
> would you be able to test if this works the same on Windows 10 1903 or later where the path to the log file contains non-ascii characters?

Looks like this is still being worked on?

**Comment by Pentarctagon** [comment]
It should at least build now. The unit tests won't run since the assert is there in wesnoth.cpp, but that's fine for now.

**Comment by Wedge009** [comment]
I'm not sure what I'm supposed to test. I haven't tried non-ASCII path because I get the assertion failure in Win10 with VS 2022. On Win7 with VS 2019 I don't even get that far - nothing opens, nothing displays.

**Comment by Wedge009** [comment]
Sorry I missed that detail. Without even considering the complication of non-ASCII log paths, I don't seem to get anything recorded in the log file. Just an empty log file is created and that's all. Your code is tested as-is in Win10 with VS2022 compilation, I haven't made any modifications.

**Comment by Pentarctagon** [comment]
Weird. How are you running it?

**Comment by Wedge009** [comment]
Same as usual, from the VS IDE. Same result when running from the command-line. The only argument used is specifying the `data-dir`.

**Comment by Pentarctagon** [comment]
Is there anything printed on the command line?

**Comment by Wedge009** [comment]
No, because everything should be redirected to the log by default. If I set `--no-log-to-file` then I see the numbers 0-4 inclusive printed, but no assertion message (it shows as an assertion failed dialogue instead - and yes, it's release-mode compilation).

**Comment by Pentarctagon** [comment]
If you comment out lines 198-228, and then uncomment lines 230-240, does it work?

**Comment by Wedge009** [comment]
0, 1, and 3 are printed in the log file, followed by the normal log. Assertion is not printed - again, it's shown as a dialogue.

I didn't try moving my user directory to a path with non-ASCII characters. Is there an easy way to tell Wesnoth to use a specific directory for the log file?

**Comment by CelticMinstrel** [comment]
It sounds to me that the assertion not being printed is intentional – Windows is trying to be smart and show it to the user in a more direct way.

**Comment by Wedge009** [comment]
Looks like it's just how the VC++ library wants to implement it:
image

**Comment by Pentarctagon** [comment]
The assert in wesnoth.cpp on line 1131 can just be removed then - no point in testing it on Windows. The logs directory is just the "logs" folder inside the userdata folder, so setting a custom userdata folder will move the logs too.

Out of curiosity, are you able to build 1.16 as well? I'm wondering if the stdout redirecting ever worked, since the lines 230-240 should be essentially what the Windows logging to file was doing for 1.16.

**Comment by Pentarctagon** [comment]
Looks like Windows making the distinction between console vs gui applications is being a pain again - Windows GUI apps make `_fileno(stderr)` and `_fileno(stdout)` return -2 instead of the actual value. I've pushed a commit that hardcodes them as 1 and 2 instead, so please test again with that as well when you can.

**Comment by Wedge009** [comment]
I pulled your changes, reverting to a clean build, no modifications.

No more assertion dialogue. Still zero-byte log file generated. Running with `--no-log-to-file`, I see 0-4 inclusive printed out before the normal log text. No mention of any assertion in the log output.

I'm afraid I'm not able to keep testing ad-hoc changes but I'll try to help with testing as I'm able.

**Comment by Pentarctagon** [comment]
Pushed another attempt - if the previous code didn't work then I'm guessing this won't either, probably for the same reason. But maybe we'll get lucky and it's at least a lot simpler.

**Comment by Wedge009** [comment]
Well... using your branch unmodified, I get 2 and 4 printed in the log file... and nothing else.

**Comment by Pentarctagon** [comment]
Well, that's... different, at least. Pushed another attempt - ideally you should see 2 and 4 in the ".out.log" file and everything else in the regular ".log" file.

**Comment by Wedge009** [comment]
Yes, 2 and 4 are in .out.log.

0, 1, 3, followed by normal log text are in .log.

**Comment by Pentarctagon** [comment]
Alright, that's what I'm going to go with then, unless someone knows a way to get `_dup2()` to work with stdout/stderr for Windows GUI apps.

**Comment by Wedge009** [comment]
There weren't any assertion messages after your changes. No dialogue, no printing in the log. I assume that's okay/expected?  I haven't tried this at all on Linux.

**Comment by Wedge009** [comment]
Oh, I just remembered your request to test non-ASCII characters. I ran `wesnoth --userdata-dir=tést` and the directory was created... but the logs directory remains empty. But then I tried `wesnoth --userdata-dir=test` and the logs directory there was also empty. So I don't know what's going on.

**Comment by Wedge009** [comment]
I repeated the `wesnoth --userdata-dir=test` operation with the official Windows release for 1.17.24 and there are no logs generated either. So maybe not specific to your work here... in which case, should this be reported as an issue?

**Comment by Pentarctagon** [comment]
What does the build info dialog report the logs directory as being?

**Comment by Wedge009** [comment]
I checked that as well - it's reporting the logs directory corresponding with the `userdata-dir` input, just nothing gets written there. As I said, it's a currently-existing problem in 1.17. Testing 1.16.11 release, the log file gets written (in Windows at least, default log file writing wasn't in place for Linux).

**Comment by Pentarctagon** [comment]
Looks like the issue is that the log file setup happens before the command line options are parsed. Not sure if it makes sense to move that earlier or not though.

**Comment by Wedge009** [comment]
1.16 writes the log file in the correct location, though? Is the current set-up for 1.17 that much different? (I know you did a lot of work on the log redirection previously.)

**Comment by Pentarctagon** [comment]
For 1.16 it would initially write the log file to the Windows temp directory, then move it to the logs directory after the userdata folder is setup, wherever that ends up being.

**Comment by Pentarctagon** [comment]
Alright, the log file not using a userdata folder provided via the command line option should be fixed.

**Comment by CelticMinstrel** [comment]
I hate that there's a separate .out.log file…

**Comment by Pentarctagon** [comment]
Yeah, it's dumb. Unfortunately, Windows makes it the only option I know of to work correctly.

**Comment by CelticMinstrel** [comment]
If it's only needed on Windows, why do the other OSes need to suffer too?

**Comment by Pentarctagon** [comment]
It's only being done for Windows. Other OSes will just use `dup2(STDERR_FILENO, STDOUT_FILENO)` to have both go to the same file.

**Comment by Wedge009** [comment]
Specification of `userdata-dir` works, including log file output, now. Including non-ASCII characters in the specified directory. Only tested on Win10.

**Comment by Pentarctagon** [comment]
Nice, glad that worked on the first attempt. Thanks for testing all this out!

**Comment by CelticMinstrel** [comment]
> It's only being done for Windows. Other OSes will just use `dup2(STDERR_FILENO, STDOUT_FILENO)` to have both go to the same file.

Okay… still bad, but less bad at least. I guess we can leave that as something to work out at some unspecified time in the future…

File: src/log.hpp [hunk 4]
```diff
@@ -62,14 +62,21 @@
...
+const std::string out_log_file_suffix = ".out.log";
 
 // Maximum number of older log files to keep intact. Other files are deleted.
 // Note that this count does not include the current log file!
+// double for Windows due to the separate .log and .out.log files
+#ifdef _WIN32
+const unsigned max_logs = 16;
+#else
 const unsigned max_logs = 8;
+#endif
```
Comment (CelticMinstrel) [inline src/log.hpp:79]: I think it might be slightly better if this were arranged in a way that doesn't require editing two places. For example, like below. There may be even better possibilities as well.
```suggestion
const unsigned max_logs = 8
// double for Windows due to the separate .log and .out.log files
#ifdef _WIN32
  * 2;
#endif
```

**Comment by CelticMinstrel** [comment]
I'm wondering about the choice of name for .out.log. What actually goes in there, anyway?

**Comment by Pentarctagon** [comment]
any output to stdout/std::cout would end up in the .out.log file.

File: src/log.hpp (hunk 4 above)
Comment (Pentarctagon) [reply src/log.hpp:79]: Wouldn't that fail to compile due to missing the semi-colon on non-Windows?

**Comment by Wedge009** [comment]
Tested on Win7 - logs working, redirecting to directory with non-ASCII characters also works. As a bonus, presumably because boost tee is no longer used, #8024 is fixed by this too.

**Comment by Pentarctagon** [comment]
Nice - I'll merge this tomorrow if nothing else comes up then.
