### PR TITLE
Turbo slider

### LINKED ISSUE #2741: Speed preferences are weird
In the preferences dialog, the speed setting is not saved if the accelerated speed checkbox is unchecked when you close the dialog. This means that checking it, setting the speed, and unchecking it again does not work.

Furthermore, it does not make sense for the slider to be disabled when accelerated speed is. The accelerated speed has a quick-toggle hotkey, so the speed setting is relevant even if accelerated speed is not currently enabled.

This presumably affects both master and 1.14.

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #2741.

### CODE REVIEW

**Comment by Wedge009** [comment]
Seems reasonable to me. Thanks.

File: src/gui/dialogs/preferences_dialog.cpp [hunk 1]
```diff
@@ -360,7 +360,7 @@ void preferences_dialog::post_build(window& window)
 
 	/* ACCELERATED SPEED */
 	register_bool("turbo_toggle", true, turbo, set_turbo,
-		[&](widget& w) { disable_widget_on_toggle<slider>(window, w, "turbo_slider"); }, true);
+		[](widget&) { }, true);
```
Comment (Vultraz) [inline src/gui/dialogs/preferences_dialog.cpp]: If you're disabling the callback, use the 4-argument version of `register_bool` and remove these last two argument completely.

File: data/gui/window/preferences/01_general.cfg [hunk 2]
```diff
@@ -80,12 +80,12 @@
 			horizontal_grow = true
 			{_GUI_PREFERENCES_CHECKBOX_ALIGN_BORDER}
 			{_GUI_PREFERENCES_MAIN_COMPOSITE_SLIDER
-				( _ "Speed:")
+				( _ "Acceleration factor:")
```
Comment (Vultraz) [inline data/gui/window/preferences/01_general.cfg]: I think just "Factor:" would work.

File: data/gui/window/preferences/01_general.cfg [hunk 3]
```diff
@@ -80,12 +80,12 @@
...
 				turbo_slider (
 					# Starts at 0 since the slider values are used for vector index access.
 					minimum_value,maximum_value=0,11
 					step_size=1
-					tooltip= _ "Units move and fight speed"
+					tooltip= _ "How much faster do motion and fight animations play when 'Accelerated speed' is enabled"
```
Comment (Vultraz) [inline data/gui/window/preferences/01_general.cfg]: Suggest:
> Speed at which unit moves and animations play when 'Accelerated speed' is enabled.

File: src/gui/dialogs/preferences_dialog.cpp (hunk 1 above)
Comment (jostephd) [reply src/gui/dialogs/preferences_dialog.cpp]: I don't see how I can use the other overload of `register_bool` since I don't have a `bool` variable to pass for its third argument, but I'll remove the last two arguments.

File: data/gui/window/preferences/01_general.cfg (hunk 3 above)
Comment (jostephd) [reply data/gui/window/preferences/01_general.cfg]: Done

File: src/gui/dialogs/preferences_dialog.cpp (hunk 1 above)
Comment (Vultraz) [reply src/gui/dialogs/preferences_dialog.cpp]: Ah, yes. Sorry. You can't use the 4-argument version, but you should still drop the last two arguments.

File: data/gui/window/preferences/01_general.cfg (hunk 2 above)
Comment (jostephd) [reply data/gui/window/preferences/01_general.cfg]: I think "Factor:" alone could be confusing to first timers; without reading the tooltip it's not obvious that the slider is related to the checkbox.

Comment (Vultraz) [reply data/gui/window/preferences/01_general.cfg]: That's why it's indented, actually, to indicate that. Hm...

**Comment by jostephd** [comment]
Rebased to address @Vultraz 's comments

File: data/gui/window/preferences/01_general.cfg (hunk 2 above)
Comment (jostephd) [reply data/gui/window/preferences/01_general.cfg]: It's indented relative to the left edge of the checkbox but not relative to the left edge of the checkbox's text. Indent it more?

File: src/gui/dialogs/preferences_dialog.cpp (hunk 1 above)
Comment (jostephd) [reply src/gui/dialogs/preferences_dialog.cpp]: Done and pushed

File: data/gui/window/preferences/01_general.cfg (hunk 2 above)
Comment (Vultraz) [reply data/gui/window/preferences/01_general.cfg]: Uh.....what? No? It aligns with the checkbox text.

Comment (jostephd) [reply data/gui/window/preferences/01_general.cfg]: Yes, the checkbox's text ("Accelerated speed") and the slider's label ("Speed:" in master, "Factor:" or "Acceleration factor:" with this PR) are aligned. I'm proposing that the latter be shifted a bit to the right, so the word "Factor" would start under the 'l' of "Accelerated speed".

Comment (Vultraz) [reply data/gui/window/preferences/01_general.cfg]: No, that would be impossible to get right without magic numbers, nor would it look good. Not a good change.

Comment (jostephd) [reply data/gui/window/preferences/01_general.cfg]: I didn't mean _precisely_ under the 'l', that was just an example to clarify the idea.

Comment (Wedge009) [reply data/gui/window/preferences/01_general.cfg]: Don't forget the alignment would likely be different with translations.

Comment (jostephd) [reply data/gui/window/preferences/01_general.cfg]: If we wanted to do more indentation we'd just indent the start of the line by some constant amount. The amount wouldn't change if the text in the line above changed.

Anyway, let me know if I should change it to "Factor:".

Comment (CelticMinstrel) [reply data/gui/window/preferences/01_general.cfg]: I think it's fine as-is, personally.

**Comment by Wedge009** [comment]
Is there still a string freeze in place? Is that why we can't merge this (yet)?

**Comment by Vultraz** [comment]
No there isn't. Merge it.

**Comment by Wedge009** [comment]
Can this go to master as well?

**Comment by Vultraz** [comment]
Already done.
