### PR TITLE
Unified units dialog

### LINKED ISSUE #8829: Expose unit pick dialog to Lua as a simple API call
This refers to the recruit, recall, and debug unit create dialogs – I believe it would make sense to merge them into single dialog that supports various options to tweak it into being identical to any of the current dialogs. If it turns out I'm wrong, however, the main thing would be to expose the recruit dialog, so that SotA can handle its corpse recruits in a more reasonable manner (and automatically get all the features of the recruit dialog, like filtering).

### PR DESCRIPTION
**Pull request by babaissarkar**
Unifies the codebases of existing `unit_recruit`, `unit_recall`, `unit_create` and `unit_list` dialogs into a single `units_dialog` with various customizable options.

The frontend UI visible to the players remains the same (so far)

**Tasks:**
- [x] Check all column sorters
- [x] Code simplification and reorganization (builder pattern)
- [x] Check recalllable is correctly used or not
- - [x] Add recallable tooltip
- [x] Add lua function to access this dialog (Resolves #8829)
- - [x] `gui.show_recruit_dialog` (docs added)
- - [x] `gui.show_recall_dialog` (docs added)

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
> with four modes

This isn't quite right. It shouldn't have "four modes". It should have a set of configuration variables that mainline uses in four ways, but could potentially be used in other ways.

I haven't looked at the code yet, so maybe you already did that and this is just an imprecise statement of it.

**Comment by babaissarkar** [comment]
>  It should have a set of configuration variables that mainline uses in four ways, but could potentially be used in other ways.
Definitely, and would appreciate advice on the same.
Would something like a builder pattern be good for construction of this dialog?

**Comment by CelticMinstrel** [comment]
The builder pattern is definitely one viable way to do this in C++. (In Lua you'd have an options table.) I don't remember how the WML message dialog handles it, but this is kinda similar to that in the sense that it has a lot of options.

**Comment by Vultraz** [comment]
I agree with celmin. This should be configurable generally, not just for specific pre-defined modes.

**Comment by babaissarkar** [comment]
@CelticMinstrel @Vultraz : this is WIP, but are the changes in b401e87238d99d167607c34dafc2391a341193a8 going in the correct direction?

File: src/gui/dialogs/units_dialog.hpp [hunk 1]
```diff
@@ -0,0 +1,232 @@
...
+#include <string>
+#include <vector>
+
+class team;
+
+namespace gui2
+{
+
+
+namespace dialogs
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:38]: Please use nested namespaces (`namespace gui2::dialogs`)

File: src/gui/dialogs/units_dialog.hpp [hunk 2]
```diff
@@ -0,0 +1,232 @@
...
+	std::string topic_id_;
+	bool show_variation_grid_;
+	bool show_gender_grid_;
+	bool show_dismiss_;
+	bool show_rename_;
+
+	bool show_image_;
+
+	boost::dynamic_bitset<> visible_headers_;
+	std::map< std::string, std::function<std::string(const int)> > column_generators_;
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:200]: Formatting - excess spaces.

File: src/gui/widgets/listbox.cpp [hunk 3]
```diff
@@ -713,6 +713,7 @@ listbox_definition::resolution::resolution(const config& cfg)
 
 namespace implementation
 {
+
```
Comment (Vultraz) [inline src/gui/widgets/listbox.cpp:716]: Random extra space.

**Review by Vultraz — CHANGES_REQUESTED** [review]

File: data/gui/themes/default/window/units_dialog.cfg [hunk 4]
```diff
@@ -181,34 +173,89 @@
...
+									vertical_alignment = "center"
+
 									[label]
 										id = "unit_experience"
 										definition = "default_small"
 										linked_group = "experience"
 									[/label]
 								[/column]
-
+
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply data/gui/themes/default/window/units_dialog.cfg]: removed.

File: src/units/helper.hpp [hunk 5]
```diff
@@ -49,4 +50,11 @@ std::string unit_level_tooltip(const unit &u);
  * advance to.
  */
 std::string unit_level_tooltip(const unit_type &u);
+
+const std::string maybe_inactive(const std::string& str, bool active);
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/units/helper.hpp]: removed.

File: src/units/helper.hpp [hunk 6]
```diff
@@ -49,4 +50,11 @@ std::string unit_level_tooltip(const unit &u);
...
+std::string format_cost_string(int unit_recall_cost, const int team_recall_cost);
+std::string format_cost_string(int unit_cost);
+std::string format_name_string(const std::string& str, const bool can_recruit);
+std::string format_level_string(const int level, bool recallable);
+std::string format_movement_string(const int moves_left, const int moves_max);
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/units/helper.hpp:103]: Added docs.

File: src/gui/widgets/listbox.cpp (hunk 3 above)
Comment (babaissarkar) [reply src/gui/widgets/listbox.cpp]: removed.

File: src/gui/dialogs/units_dialog.hpp (hunk 2 above)
Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp]: removed extra space after < and before >.

File: src/gui/dialogs/units_dialog.hpp [hunk 7]
```diff
@@ -0,0 +1,232 @@
...
+	{
+		return selected_index_;
+	}
+
+	bool is_selected() const
+	{
+		return selected_index_ != -1;
+	}
+
+	std::optional<unit_const_ptr> get_unit() const
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp]: moved to utils::optional.

File: src/gui/dialogs/units_dialog.cpp [hunk 8]
```diff
@@ -0,0 +1,507 @@
...
+	find_widget<label>("title").set_label(title_);
+	find_widget<button>("ok").set_label(ok_label_);
+	find_widget<button>("dismiss").set_visible(
+		show_dismiss_ ? widget::visibility::visible : widget::visibility::invisible);
+	find_widget<button>("rename").set_visible(
+		show_rename_ ? widget::visibility::visible : widget::visibility::invisible);
+	find_widget<grid>("variation_gender_grid").set_visible(
+		show_gender_grid_ ? widget::visibility::visible : widget::visibility::invisible);
+
+	for (int i = 0; i <= 7; i++) {
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.cpp:191]: Aren't there 8 columns?

File: src/gui/dialogs/units_dialog.cpp [hunk 9]
```diff
@@ -0,0 +1,507 @@
...
+	}
+}
+
+units_dialog& units_dialog::set_column_generator(std::string id, std::function<std::string(const int)> generator)
+{
+	column_generators_.try_emplace(id, generator);
+	return *this;
+}
+
+void units_dialog::show_help()
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.cpp:340]: Function should be const.

File: src/gui/dialogs/units_dialog.hpp [hunk 10]
```diff
@@ -0,0 +1,241 @@
...
+#include "gui/widgets/listbox.hpp"
+#include "gui/widgets/toggle_button.hpp"
+#include "gui/widgets/unit_preview_pane.hpp"
+#include "team.hpp"
+#include "units/ptr.hpp"
+#include "units/types.hpp"
+#include "utils/optional_fwd.hpp"
+
+#include <boost/dynamic_bitset/dynamic_bitset.hpp>
+#include <optional>
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:29]: Remove the include for <optional> (it's pulled in through `utils/optional_fwd`)

File: src/gui/dialogs/units_dialog.cpp [hunk 11]
```diff
@@ -0,0 +1,507 @@
...
+#include "synced_context.hpp"
+#include "team.hpp"
+#include "units/helper.hpp"
+#include "units/unit.hpp"
+#include "units/ptr.hpp"
+#include "units/types.hpp"
+#include "whiteboard/manager.hpp"
+
+#include <functional>
+#include <optional>
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.cpp:49]: Remove the include for <optional>.

File: src/gui/dialogs/units_dialog.cpp (hunk 8 above)
Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.cpp:191]: the condition is `<=7`, but i'd get it from `visible_headers_`

File: src/gui/dialogs/units_dialog.hpp [hunk 12]
```diff
@@ -0,0 +1,241 @@
...
+
+	bool is_selected() const
+	{
+		return selected_index_ != -1;
+	}
+
+	utils::optional<unit_const_ptr> get_unit() const
+	{
+		if(is_selected() || !recall_list_.empty()) {
+			return utils::optional{recall_list_[get_selected_index()]};
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:56]: You don't need to wrap these in `utils::optional{}`. Just do `return recall_list_[get_selected_index()];`. Sorry for not catching this before. The only time the return types need to be the same is if you're using a ternary operator.

File: src/editor/controller/editor_controller.cpp [hunk 13]
```diff
@@ -1343,7 +1343,28 @@ void editor_controller::rename_unit()
...
+	for(unit_map::const_iterator i = units.begin(); i != units.end(); ++i) {
+		if(i->side() != gui().viewing_team().side()) {
+			continue;
+		}
+		unit_list.push_back(i.get_shared_ptr());
+	}
+
+	gui2::dialogs::units_dialog unit_dlg;
+	unit_dlg.set_title(_("Unit List"))
+			.set_ok_label(_("Scroll To"))
```
Comment (Vultraz) [inline src/editor/controller/editor_controller.cpp:1358]: Excessive indent.

File: src/menu_events.cpp [hunk 14]
```diff
@@ -390,43 +499,128 @@ void menu_handler::recall(int side_num, const map_location& last_hex)
...
 
-	gui2::dialogs::unit_recall dlg(recall_list_team, current_team);
+	gui2::dialogs::units_dialog dlg;
+	dlg.set_title(_("Recall Unit"))
+		.set_ok_label(_("Recall"))
+		.set_help_topic("recruit_and_recall")
+		.set_units(recall_list_team)
+		.set_team(&current_team)
+		.set_column_generator("unit_image", [&](const int i) {
+				unit_const_ptr unit = recall_list_team[i];
```
Comment (Vultraz) [inline src/menu_events.cpp:515]: Excess indent in lambdas.

File: src/menu_events.cpp [hunk 15]
```diff
@@ -692,24 +886,49 @@ typedef std::tuple<const unit_type*, unit_race::GENDER, std::string> type_gender
...
+	};
+
+	const auto& race_gen = [&](const int i) {
+		return types_list[i]->race()->plural_name();
+	};
+
+	create_dlg.set_title(_("Create Unit"))
+	          .set_ok_label(_("Create"))
+	          .set_help_topic("..units")
+			  .show_gender(true)
```
Comment (Vultraz) [inline src/menu_events.cpp:907]: Excessive indent for most of this list.

File: src/units/helper.hpp [hunk 16]
```diff
@@ -49,4 +50,55 @@ std::string unit_level_tooltip(const unit &u);
...
+
+/**
+ * @return If active, do nothing. If inactive, surround with pango tag that
+ * changes font color to grey.
+ */
+std::string maybe_inactive(const std::string& str, bool active);
+
+/**
+ * @return If unit recall cost is greater than team's recall cost,
+ * return a help markup string that shows the unit recall cost
```
Comment (Vultraz) [inline src/units/helper.hpp:62]: Is there a distinction between "help markup string" and "pango tag"?

File: src/units/helper.cpp [hunk 17]
```diff
@@ -88,4 +89,70 @@ std::string unit_level_tooltip(const unit_type &type)
...
+}
+
+std::string format_cost_string(int unit_cost)
+{
+	return formatter() << markup::img("themes/gold.png") << unit_cost;
+}
+
+std::string format_name_string(const std::string& str, const bool can_recruit)
+{
+	return can_recruit ? markup::span_color("#cdad00", str) : str;
```
Comment (Vultraz) [inline src/units/helper.cpp:123]: IMO this should be conditional for the caller (ie, markup if can recruit).

File: src/units/helper.hpp (hunk 16 above)
Comment (babaissarkar) [reply src/units/helper.hpp:62]: there is, since the `` tag is involved. It is one of the tags that is supported by rich label/help markup but not by pango.

File: src/units/helper.cpp (hunk 17 above)
Comment (babaissarkar) [reply src/units/helper.cpp:123]: you mean the conditonal check should be moved to the caller?

Comment (babaissarkar) [reply src/units/helper.cpp:123]: and obviously delete this.

File: src/units/helper.cpp [hunk 18]
```diff
@@ -88,4 +89,70 @@ std::string unit_level_tooltip(const unit_type &type)
...
+	} else if(level == 3) {
+		return markup::span_color("#e2b776", markup::bold(level));
+	} else {
+		return markup::span_color("#dd6600", markup::bold(level));
+	}
+}
+
+std::string format_movement_string(const int moves_left, const int moves_max)
+{
+	std::string color = "#00ff00";
```
Comment (Vultraz) [inline src/units/helper.cpp:147]: Please use `color_t`. We should probably make sure all uses of `markup::span_color` use the color_t overload and remove the string overload if possible.

File: src/menu_events.cpp [hunk 19]
```diff
@@ -270,32 +354,44 @@ void menu_handler::recruit(int side_num, const map_location& last_hex)
 		return;
 	}
 
-	gui2::dialogs::unit_recruit dlg(sample_units, board().get_team(side_num));
+	gui2::dialogs::units_dialog dlg;
+	dlg.set_title(_("Recruit Unit"))
+	   .set_ok_label(_("Recruit"))
```
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/menu_events.cpp:359]: i think my IDE indentation settings got messed up, will check.

File: src/units/helper.cpp (hunk 18 above)
Comment (babaissarkar) [reply src/units/helper.cpp:147]: good point

File: src/units/helper.cpp (hunk 17 above)
Comment (babaissarkar) [reply src/units/helper.cpp:123]: removed, wasn't being used.

File: src/units/helper.cpp (hunk 18 above)
Comment (babaissarkar) [reply src/units/helper.cpp]: all hex strings in `helper.cpp` replace with `color_t` objects.

File: src/menu_events.cpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (babaissarkar) [reply src/menu_events.cpp]: indents fixed, following lines indented by one tab (choosing not to align dots).

File: src/gui/dialogs/units_dialog.cpp (hunk 9 above)
Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.cpp]: added `const`.

File: src/gui/dialogs/units_dialog.cpp (hunk 8 above)
Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.cpp]: updated to use `visible_headers_.size()`

File: src/gui/dialogs/units_dialog.hpp [hunk 20]
```diff
@@ -0,0 +1,240 @@
...
+		return *this;
+	}
+
+	units_dialog& set_types(std::vector<const unit_type*> types)
+	{
+		recruit_list_ = types;
+		return *this;
+	}
+
+	units_dialog& set_units(std::vector<unit_const_ptr> units)
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:154]: Can this take an rvalue-reference? Either way, should assign recall_list with std::move.

File: src/gui/dialogs/units_dialog.hpp [hunk 21]
```diff
@@ -0,0 +1,240 @@
...
+		return *this;
+	}
+
+	/**
+	 * Corresponding to each widget in the row with id 'id', there is a lambda that generates
+	 * the corresponding label to set to that widget. This method sets those generator functions.
+	 * The 'id's must be the same as those defined for the various widgets
+	 * in the [list_definition] in the WML file.
+	 */
+	units_dialog& set_column_generator(std::string id, const std::function<std::string(const int)> generator);
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:166]: These should take args by reference (also could probably implement in the header like the other functions).

File: src/gui/dialogs/units_dialog.hpp (hunk 20 above)
Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp:154]: could probably be dropped, i don't think i'm using team anywhere, see the builders in menu_events.cpp, team is coming via ref capture in lambdas.

File: src/gui/dialogs/units_dialog.hpp [hunk 22]
```diff
@@ -0,0 +1,240 @@
...
+	std::vector<std::string> last_words_;
+	group<unit_race::GENDER> gender_toggle_;
+
+	/** Callbacks */
+	void list_item_clicked();
+	void filter_text_changed();
+	void rename_unit();
+	void dismiss_unit();
+
+	t_string can_recruit(const std::string& name, int side_num, team& team, map_location& loc, map_location& recruited_from);
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:225]: Orphaned declaration.

File: src/gui/dialogs/units_dialog.hpp (hunk 20 above)
Comment (Vultraz) [reply src/gui/dialogs/units_dialog.hpp:154]: Even better!

Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp:154]: apparent team is being used so set_team can't be dropped, but changed to rvalue refs and std::move.

Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp]: Please check, seems like I have to use `std::move` twice now, seems a bit suspicious.

Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp]: also renamed to `recruit_list_` and `recall_list_` to `unit_type_list_` and `unit_list_`.

**Comment by Vultraz** [comment]
After talking with @CelticMinstrel on Discord, we have an idea for improving the column generator interface. Something like:
```cpp
template<typename Value>
units_dialog& set_column_generator(const std::string& id,
	const std::vector<Value*>& container,
	const std::function<std::string(const Value&)>& generator)
{
	column_generators_.try_emplace(id, [&container, func](std::size_t index) { return func(*container[index]); });
	return *this;
}
```
(Note that as written, this would require you to work with lists of raw pointers for `unit` and `unit_type`, but it could easily be adapted.) Then it would be used like so:
```cpp
.set_column_generator("unit_hp", unit_list, [](const unit& u) {
	return markup::span_color(u.hp_color(), u.hitpoints(), "/", u.max_hitpoints());
})
```
You can use the same "wrapping" paradigm for the other helper functions, as needed.

Also, I realized that I was mistaken last night when I suggested `std::move`-ing the lists into the class, since that also means we can't access them in the lambdas in the invoking scope. And besides, optimally, we do not want to store the lists in the class at all. 

To that end, some suggestions:
* In `show_list`, since you just need the number of items, you should add a new `set_num_items` function to the class.
* No objections if you add a new `set_displayed` method (or rename the existing ones) to `unit_preview_pane` with two overloads, one taking `const unit&` and the other `const unit_type&`. That would remove the need for the check for which-list-has-values in `list_item_clicked`.

Still need to figure out how to handle other cases where the list is directly accessed in-class, but this is a start.

**Comment by Vultraz** [comment]
Is it possible to split the listbox cleanup into a separate PR? That can be merged as-is.

File: src/gui/dialogs/units_dialog.hpp [hunk 23]
```diff
@@ -0,0 +1,247 @@
...
+
+	template<typename Func>
+	units_dialog& set_sorter(int col, const Func& sorter)
+	{
+		find_widget<gui2::listbox>("recall_list").register_sorting_option(col, sorter);
+		return *this;
+	}
+
+	template<typename Value, typename Generator = std::function<std::string(const Value&)>>
+	units_dialog& set_translatable_sorter(
```
Comment (Vultraz) [inline src/gui/dialogs/units_dialog.hpp:187]: This doesn't need to be its own function now that the API has been unified. You can just rely on `set_column_generator`.

Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp:187]: So just `set_column_generator(...., true)` right?

Comment (babaissarkar) [reply src/gui/dialogs/units_dialog.hpp]: removed.

File: src/scripting/lua_gui2.cpp [hunk 24]
```diff
@@ -280,20 +285,88 @@ int intf_add_widget_definition(lua_State* L)
...
+		{ "show_narration",         &show_message_dialog },
+		{ "show_popup",             &show_popup_dialog },
+		{ "show_story",             &show_story },
+		{ "show_prompt",            &show_message_box },
+		{ "show_help",              &show_help   },
+		{ "switch_theme",           &switch_theme },
+		{ "add_widget_definition",  &intf_add_widget_definition },
+		{ "show_dialog",            &intf_show_dialog },
+		{ "show_recruit_dialog",    &intf_show_recruit_dialog },
+		{ "show_recall_dialog",     &intf_show_recall_dialog },
```
Comment (gfgtdf) [inline src/scripting/lua_gui2.cpp:369]: If these functions are only be meant to be used ingame it would be better if they'd be defined in game_lua_kernel.cpp, like gui.show_inspector, see https://github.com/wesnoth/wesnoth/blob/ebf9a2949a49d1cfaf5715bc1ec674faab6ccb4e/src/scripting/game_lua_kernel.cpp#L5257

Comment (babaissarkar) [reply src/scripting/lua_gui2.cpp:369]: sure, will look into it.

Comment (babaissarkar) [reply src/scripting/lua_gui2.cpp]: Moved to game_lua_kernel in https://github.com/wesnoth/wesnoth/pull/9499/commits/548e73b7471a3ae70d7e061f02c028fb715dc410.

**Review by Vultraz — APPROVED** [review]
Looks to be in good shape. Any further cleanup can be done after it's merged. Thanks for all your work and being patient with all the feedback!

**Review by knyghtmare — APPROVED** [review]
