### PR TITLE
Editor Adjustments

### LINKED ISSUE #9956: Can't save a map as a scenario anymore
### Game and System Information

- **Version:** 1.19.9
- **OS:** Manjaro Linux

### Description of the bug

I'm not able to save a map as a scenario anymore to get access to the scenario mode exclusive features such as areas. F1 help tells me to use Save Scenario As... but the option isn't present in the menu anymore. I've tried manually save the map as a .cfg file, but it warns that only .map and .mask are supported and the scenario mode doesn't turn on anyway.

### Steps to reproduce the behavior

1. Open the Map Editor
2. Open any existing map
3. Select File

### Expected behavior

There is some way to save the map as a scenario.

### Additional context

The help should also get amended to reflect the changes.

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #9956.

A new "Convert to Scenario" option added to "File" menu to allow converting the currently active map to a scenario has been added.

(Can be squash-merged)

### CODE REVIEW

**Comment by Pentarctagon** [comment]
What about just swapping it around to "Save as map"/"Save as scenario"?

**Comment by soliton-** [comment]
Do we specifically need this? IMO it makes more sense to have a "convert to scenario" function that is unrelated to saving. Once used then you can "save as scenario" as usual.

That would also make testing scenario stuff easier. Though that's really a secondary concern. Most important is that a user that may not be familiar with what exactly a map and a scenario mean (and what extension belongs to what) can understand this.

**Comment by babaissarkar** [comment]
> Do we specifically need this? IMO it makes more sense to have a "convert to scenario" function that is unrelated to saving. Once used then you can "save as scenario" as usual.

1. Exactly what are you objecting to? the Save As renaming? or the Save Map As Scenario option? or Both?
2. I can make the "Convert to Scenario" work probably, but note that both map and scenario are more or less same in code, and most distinction happens during write time IIRC.

**Comment by soliton-** [comment]
I'm asking if we need to have a "save as scenario" entry when there is no scenario. I'm suggesting to simply be able to turn on scenario mode. Clearly there is a distinction in the UI between map and scenario mode. #9956 is specifically asking to get access to scenario mode.

File: src/editor/map/context_manager.cpp [hunk 1]
```diff
@@ -1002,30 +1002,38 @@ void context_manager::revert_map()
...
+	init_context(width, height, fill, new_context, false);
 
-	if(new_context) {
-		int new_id = add_map_context(m, false, *default_schedule, current_addon_);
-		switch_context(new_id);
-	} else {
-		replace_map_context(m, false, *default_schedule, current_addon_);
-	}
+	// Give the new scenario an initial side.
+	get_map_context().new_side();
```
Comment (soliton-) [inline src/editor/map/context_manager.cpp:1027]: Maybe it's easy to add as many sides as there are starting points in the map?

Comment (soliton-) [reply src/editor/map/context_manager.cpp:1027]: Or as many as the highest starting position since I guess there can be gaps.

**Review by soliton- — COMMENTED** [review]
I don't have time to check in-depth but looks good to me.

File: src/editor/map/context_manager.cpp (hunk 1 above)
Comment (babaissarkar) [reply src/editor/map/context_manager.cpp:1027]: > Or as many as the highest starting position since I guess there can be gaps.
Done

**Review by Vultraz — APPROVED** [review]
