### PR TITLE
[world conquest] [1.16] [lua] Check for wc2_scenario value before executing wc2_start_units function 

### LINKED ISSUE #5900: [world conquest] [BUG] faction recruit list gets appended by recruits of another faction of the same era and Leader unit inherits heroic trait for each scenario and it stacks
### Game and System Information
 - What version of the game are you running?
 - Battle for Wesnoth v1.15.14+dev (8679f0573f8-Modified) x86_64
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - Msys2
 - What OS are you running?
 - Windows 10

### Describe the bug
After each successive scenario, the recruit list is appended with the recruits of another faction of the same era. Additionally, the leader unit inherits "trait heroic" for every scenario, and the effects stack.

### Expected behavior
Recruit list stays the same. 

### Screenshots
Screenshot 1: My recruit list is of the Drakes faction from Default Era.
SS1
Screenshot 2: My recruit list is now Loyalists and Drakes.
Screenshot 2021-06-27 202228
Screenshot 3: My recruit list has now Drakes, Northerners and Loyalists.
SS3
Screenshot 4: My recruit list has all factions except Knalgan Alliance.
SS4
Screenshot 5: Leader unit inherits "heroic" trait for each scenario. It can be clearly seen how many times it has stacked.
image

### PR DESCRIPTION
**Pull request by knyghtmare**
What this does is just checks the value of wc2_scenario before executing the function, and executes it for the first scenario only as intended.
Same as #6052, Fixes #5900 for 1.16

### CODE REVIEW

File: data/campaigns/World_Conquest/lua/campaign/scenario.lua [hunk 1]
```diff
@@ -66,9 +66,11 @@ end)
...
 on_event("wc2_start", function(cx)
 	for side_num = 1, wml.variables.wc2_player_count do
-		wesnoth.wml_actions.wc2_start_units {
-			side = side_num
-		}
+		if wml.variables.wc2_scenario == 1 then
+			wesnoth.wml_actions.wc2_start_units {
+				side = side_num
+			}
+		end
```
Comment (stevecotton) [inline data/campaigns/World_Conquest/lua/campaign/scenario.lua:73]: Either way works and there's no practical problem here, but I think doing `if ... then; for ... do` would be better style than `for ... do; if ... then`, because the condition being checked is the same each time through the loop.

**Comment by knyghtmare** [comment]
Why did one check fail? Kind of confused

**Comment by Pentarctagon** [comment]
Every once in a while the CI just decides it doesn't feel like running one of the macOS jobs and instead just marks it as failed.  Like in this case if you click on the Details link, you can see that when it got to the third step of actually building Wesnoth, it just failed without actually doing anything.

**Comment by Pentarctagon** [comment]
In any case, is this good to merge?

**Comment by knyghtmare** [comment]
Yes, it is.
