### PR TITLE
Status table team name fix

### LINKED ISSUE #9407: status table and team/user_team name
### Describe the desired feature

I don't know how this SHOULD work, but they way it looks to the player is pretty confusing and I was asked to open a ticket.

Start a MP game, and adjust the sides.

Here's the original settings untouched:
mp-orig

And here's my changes.  Note the player has changed teams and I've set it for 3x1:
mp-modified

And here's the status table, which shows all the original values:
statustbl

If I open :inspect, I see that all my changes are reflected in team_name, but user_team_name (which seems to be what status table uses) reflects the original settings.

I've exploited this oddness between team_name and user_team_name to do things like making NPCs not be attackable by any side (or something like that), so I think there's some value in the way it works.  But in this case, when I specifically set up the same such that, for example, the player was on side East and he shows up in the game as on side West, well that's just weird.

### PR DESCRIPTION
**Pull request by SomeName42**
Resolves #9407 where status dialog team names are not changed, when changed at game start.

### CODE REVIEW

**Comment by gfgtdf** [comment]
i'm wondering whetehr it would be easier to compare it to the old team_name insted of using a new variable to keep track of it, like 
`if(res["user_team_name"].empty() || res["team_name"] != parent_.team_data_[team_].team_name) {` (which would then go before the `res["team_name"] = parent_.team_data_[team_].team_name;` line)

File: src/game_initialization/connect_engine.cpp [hunk 1]
```diff
@@ -1066,43 +1066,10 @@ config side_engine::new_config() const
 			(*leader)["gender"] = "null";
 		}
 
-		res["team_name"] = parent_.team_data_[team_].team_name;
+		std::string& new_team_name = parent_.team_data_[team_].team_name;
```
Comment (soliton-) [inline src/game_initialization/connect_engine.cpp:1069]: Is there a reason this is not a const reference?

Comment (SomeName42) [reply src/game_initialization/connect_engine.cpp]: fixed
