### PR TITLE
Markup: add Help to Pango markup conversion function

### LINKED ISSUE #4874: Unit description preview shows invalid pango markup
### Game and System Information
 - 1.14.11 steam

### Describe the bug
In unit description preview https://i.vgy.me/CILzoU.png there is #3989, while in unit description markup is evaluated correctly https://i.vgy.me/Tw0WPg.png

### To Reproduce
https://github.com/ProditorMagnus/Ageless-for-1-14/blob/e7134328e678a91327abdc726e2bda2457e82d42/units/EoMa_units/Sky_Kingdom/Um.cfg#L22

### Expected behavior
Broken for both views, or working for both views.

### Screenshots
image
image

### PR DESCRIPTION
**Pull request by babaissarkar**
Resolves #4874

Also contains some whitespace changes and renaming of one `markup::tag` overload because of compiler error. (Kept choosing the wrong overload.)

### CODE REVIEW

**Comment by stevecotton** [comment]
I'm not too worried about this merging after string/feature freeze, as I believe it only affects units with `<` or `>` in their unit name. However, Soliton said in 10620 said that he'll be AFK for a few days.

File: src/serialization/markup.cpp [hunk 1]
```diff
@@ -464,4 +465,77 @@ config parse_text(const std::string& text)
...
+		attrs.emplace_back("color", "white");
+		attrs.emplace_back("size", "large");
+	}
+
+	// Nested tags
+	for(const auto& [tagname, cfg] : cfg.all_children_view()) {
+		text << config_to_pango_markup(tagname, cfg);
+	}
+
+	return markup::tag_attr(tagname, attrs, text.str());
```
Comment (soliton-) [inline src/serialization/markup.cpp:520]: Without any escaping here or above I don't see how this can work correctly.

Comment (babaissarkar) [reply src/serialization/markup.cpp:520]: Updated in 53906b9eeedc8f7ef6ace75f0f59484af4a1bb11, did I miss anything?

Comment (soliton-) [reply src/serialization/markup.cpp:520]: Looks good to me.
